Fix DOMException on empty key in $response data
yiisoft/yii2 pull request #10346
Opened 2015-12-07 16:09 UTC by sasha-ch

If my output data to serialize contains empty key:
yii\web\Response Object
(
    [format] => xml
...
[data] => Array        (
                    [] => 438
                    [1] => 748
                    [2] => 19
        )
)

I see:
<response>
    <name>Exception</name>
    <message>Invalid Character Error</message>
    <code>5</code>
    <type>DOMException</type>
    <file>/var/www/dev2_polexpert/backend/vendor/yiisoft/yii2/web/XmlResponseFormatter.php</file>
    <line>96</line>
    <stack-trace>
        <item>#0 /var/www/dev2_polexpert/backend/vendor/yiisoft/yii2/web/XmlResponseFormatter.php(96): DOMElement->__construct('')</item>
        <item>#1 /var/www/dev2_polexpert/backend/vendor/yiisoft/yii2/web/XmlResponseFormatter.php(94): yii\web\XmlResponseFormatter->buildXml(Object(DOMElement), Array)</item>
        <item>#2 /var/www/dev2_polexpert/backend/vendor/yiisoft/yii2/web/XmlResponseFormatter.php(64): yii\web\XmlResponseFormatter->buildXml(Object(DOMElement), Array)</item>
        <item>#3 /var/www/dev2_polexpert/backend/vendor/yiisoft/yii2/web/Response.php(939): yii\web\XmlResponseFormatter->format(Object(yii\web\Response))</item>
    </stack-trace>
</response>

To fix problem we may replace empty key with <item> tag, like numeric keys.

PS: json formatter works ok.

2017-01-26 13:03 UTC, sasha-ch commented
Tests in progress...

2017-01-26 14:28 UTC, sasha-ch commented
Ready.

2017-02-19 10:24 UTC, dynasource requested changes

2017-02-19 10:24 UTC, dynasource commented on framework/web/XmlResponseFormatter.php
> +    protected function getElementName($name)
the method name could be made more precise regarding the contents of the method.

2017-02-19 10:24 UTC, dynasource commented on framework/web/XmlResponseFormatter.php
> +        return (empty($name) || is_int($name) || !$this->isValidXmlName($name)) ? $this->itemTag : $name;
this condition can be made more readable by assigning it to a variable with verbose naming.

2017-02-19 10:24 UTC, dynasource commented on tests/framework/web/XmlResponseFormatterTest.php
> +            [[
thanks for adding the test. Would be nice to add a comment for understanding that this test is about your usecase

2017-02-19 14:42 UTC, samdark requested changes

2017-02-19 14:42 UTC, samdark commented on framework/web/XmlResponseFormatter.php
> +     * @param mixed $name
Need `@since` tag. Need proper phpdoc description.

2017-02-19 14:42 UTC, samdark commented on framework/web/XmlResponseFormatter.php
> +        return (empty($name) || is_int($name) || !$this->isValidXmlName($name)) ? $this->itemTag : $name;
Agree, that's rather lengthy. Any name suggestion?

2017-02-19 14:42 UTC, samdark commented on framework/web/XmlResponseFormatter.php
> +     * @param mixed $name
Need `@since` and proper description.

2017-04-25 23:07 UTC, closed without merging

2017-04-25 23:07 UTC, samdark commented
Merged. Sorry it took so long.