Docs: Combining Update, Create and Delete on one page
yiisoft/yii2 pull request #11271
Opened 2016-04-05 01:43 UTC by mdmunir

Documentation for tabular input. Sorry i am not good in english :grin:

2016-04-05 02:45 UTC, mdmunir commented
https://github.com/mdmsoft/yii2-widgets

2016-04-05 02:49 UTC, cebe commented
still would be good to have at least some words around the code :)
Does not need to be perfect english, it's important that there is description of what is going on and how the code works. You can write a draft, we can polish the english afterwards.

2016-04-05 03:54 UTC, mdmunir commented
I hope i am doing right :grinning:

2016-04-05 04:11 UTC, cebe commented
its a good start, thank you. I will review it later, if you want you can add even more explaination.

2016-04-20 08:15 UTC, Faryshta commented on docs/guide/input-tabular-input.md
> +You can use other name like `actionCreateOrUpdate()` or anyting else.
shouldn't it be naked `actionSave()` ?

2016-10-04 12:06 UTC, SilverFire requested changes

2016-10-04 12:06 UTC, SilverFire commented on docs/guide/input-tabular-input.md
> +    $settings = $origins = Setting::findAll();
Bad example. `User::findAll()` over 100k table is not the best option

2019-09-17 11:12 UTC, samdark commented
Closing since can't be merged as is and wasn't finished.

2019-09-17 11:12 UTC, closed without merging