add functions for filtering
yiisoft/yii2 pull request #11697
Opened 2016-06-05 17:00 UTC by nicdnepr

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2016-06-06 16:13 UTC, samdark commented on framework/db/Query.php
> +    public function andFilterHaving(array $condition)
Need `@since` and phpdoc.

2016-06-06 16:14 UTC, samdark commented on framework/db/Query.php
> +    public function orFilterHaving(array $condition)
Need `@since` and phpdoc.

2016-06-09 11:43 UTC, cebe commented
@nicdnepr could you explain a use case for these methods?

2016-06-10 18:22 UTC, nicdnepr commented
It's the same as function andFilterWhere, but only for having. I had a task to add GridView filtering for having results, and was surprised that there is no analog of function andFilterWhere. So I decided to add this code

2016-09-15 20:24 UTC, samdark requested changes
It looks good to me except `@since` and CHANGELOG.

2016-09-16 08:53 UTC, SilverFire requested changes
Tests are required

2016-10-11 21:09 UTC, samdark commented
Not sure if it should be in QueryInterface...

2016-12-01 21:35 UTC, samdark commented
> Not sure if it should be in QueryInterface...

No, it should not. It's in correct class.

2016-12-01 21:35 UTC, samdark commented
@nicdnepr do you want to work on it further?

2016-12-02 08:41 UTC, nicdnepr commented
@samdark Hi, I don't have much time at this moment

2016-12-14 21:00 UTC, samdark commented
Closed in favor of https://github.com/yiisoft/yii2/pull/13210

2016-12-14 21:00 UTC, closed without merging