Enhance `yii\behaviors\AttributeBehavior`
yiisoft/yii2 pull request #11969
Opened 2016-07-17 09:44 UTC by Kolyunya

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #11923 

`AttributeBehavior` can preserve current attribute values now.

2016-07-17 18:46 UTC, samdark commented
Hmm... this makes https://github.com/yiisoft/yii2/blob/master/framework/behaviors/SluggableBehavior.php#L88 pointless so either `immutable` should be moved into base `AttributeBehavior` or `immutable` should be deprecated.

@Kolyunya what do you think would be the best?

2016-07-18 08:33 UTC, Kolyunya commented
@samdark I'm not sure but I think it is important to maintain backward compatibility. If it is, we should choose the first option.

2016-07-18 08:44 UTC, samdark commented
Both my suggestions are backwards compatible, aren't they?

2016-07-18 09:08 UTC, Kolyunya commented
@samdark yes, they are. I just thought that deprecated properties and methods are subject for removal.

2016-07-18 09:49 UTC, samdark commented
In 2.1 — yes.

2016-07-18 10:48 UTC, samdark commented
Thinking about it more, condition for not touching a field could be anything: only certain existing value, value of another field etc.

2016-07-18 10:51 UTC, samdark commented
Since closures are supported for values and we have dirty attributes support, we can achieve it using existing code:

```php
'value' => function($event) {
    if (empty($this->create_time)) {
        return time();
    }

    return $this->create_time;
}
```

2016-07-18 10:51 UTC, samdark commented
So I'd decline this pull request and document ↑

2016-07-18 11:45 UTC, Kolyunya commented
@samdark I'm sorry but we can't achieve this using existing code in a general scenario when we are populating *multiple* attributes.

Use-case: Page entity has three attributes: meta_title, meta_description, meta_keywords. We need to copy title to each of the attributes only if they are empty. This will allow users to set some of them manually and to let the behavior fill the others.

The only workaround is to add three behaviors for each attribute with custom value which will check if the corresponding attribute is empty or not which is quite inelegant.

2016-07-18 12:53 UTC, samdark commented
`$skipUpdateOnFilled` is per-behavior switch. Code above is the same.

2016-07-18 13:02 UTC, samdark commented
Right, it's not convenient, at least...

2016-07-28 08:29 UTC, DrDeath72 commented
just want to write about it, i want use BlameableBehavior with beforeValidate without rewrite filled user_id

2016-09-08 04:14 UTC, Faryshta commented
how about a `$when` callable that can return `false` if you don't want the attribute to update?

2017-02-12 19:28 UTC, Kolyunya commented
@samdark @cebe what is the status of this PR? Is it under discussion or does it need some modifications?

2017-02-14 22:59 UTC, samdark requested changes
Changelog line needed.

2017-02-14 22:59 UTC, samdark commented on framework/behaviors/AttributeBehavior.php
> +     * @since 2.0.10
2.0.12

2017-02-15 15:01 UTC, Kolyunya commented
@samdark I wasn't able to push to this PR (since I already deleted that branch and repo) and I made a [new one](https://github.com/yiisoft/yii2/pull/13586).

2017-02-15 15:01 UTC, closed without merging