Revamps PageCache to store data in one entry (#10506)
yiisoft/yii2 pull request #12145
Opened 2016-08-12 12:15 UTC by sergeymakinen

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes (but N/A at the moment)
| Fixed issues  | #10506

This updated `PageCache` combines together `PageCache` and `FragmentCache` to provide caching in one entry.

### Features

- fully backwards compatible
- easy to be extended
- able to store/retrieve an additional data in `beforeCacheResponse` and `afterRestoreResponse` (*for example: I store Last-Modified in data and then retrieve it later in `HttpCache`*)
- all data is stored in one cache entry
- able to cancel caching by returning `false` in `beforeCacheResponse`

2016-08-15 22:20 UTC, samdark commented on framework/filters/PageCache.php
> +    public $dynamicPlaceholders;
Should it be public?

2016-08-15 22:23 UTC, samdark commented
@yiisoft/core-developers need additional review.

2016-08-15 22:25 UTC, samdark commented
@cebe, @drscre, @kidol

2016-08-15 22:36 UTC, sergeymakinen commented on framework/filters/PageCache.php
> +    public $dynamicPlaceholders;
Yes, `View` uses it.

2016-08-15 22:55 UTC, samdark commented on framework/filters/PageCache.php
> +    public $dynamicPlaceholders;
Is there a way to avoid exposing it?

2016-08-16 00:17 UTC, sergeymakinen commented on framework/filters/PageCache.php
> +    public $dynamicPlaceholders;
Not sure… I guess it would require changes in 'View' and any other classes implementing a dynamic content.

2016-09-14 19:59 UTC, samdark approved these changes
It looks good to me but I need more reviews from other team members.

2016-09-15 04:23 UTC, SilverFire commented on framework/filters/PageCache.php
> +     * @since 2.0.11
Add `@internal`

2016-09-15 04:27 UTC, SilverFire commented on framework/filters/PageCache.php
> +     * This method is invoked right after restoring a response is finished (but before the response is sent).
Isn't it better to change spelling like this:

`This method is invoked right after the response restoring is finished`

2016-09-15 04:29 UTC, SilverFire commented on framework/filters/PageCache.php
> +        $beforeResult = $this->beforeCacheResponse();
Maybe `beforeResponse`?

2016-09-15 04:35 UTC, SilverFire commented on framework/filters/PageCache.php
> +                        if ($name === 'headers') {
Looks like a crutch

2016-09-15 04:36 UTC, SilverFire commented on framework/filters/PageCache.php
> +                        if (isset($all[$subName])) {
Conditional nesting is too deep and it makes hard to understand what's going on here.
Could be split to a separate private method with self-documenting name.

2016-09-15 04:37 UTC, SilverFire commented on framework/filters/PageCache.php
> +        $response = Yii::$app->response;
The entire `cacheResponse` method does not fit on one screen.
Should be split for a smaller ones.

2016-09-15 04:37 UTC, SilverFire requested changes

2016-10-09 18:59 UTC, sergeymakinen commented
@SilverFire Well, thanks for the review, I'm back and I slightly changed some parts according to your review.

And em… As 2.0.10 gets delayed more and more, may be we can get this into the 2.0.10 milestone, what do you think? :)

2016-10-10 09:47 UTC, SilverFire commented
2.0.10 is delayed because we still have issues to resolve. Moving new issues back to 2.0.10 will delay it even more

2016-12-01 22:50 UTC, samdark requested changes

2016-12-01 22:50 UTC, samdark commented on framework/CHANGELOG.md
> +- Enh: Added `beforeCacheResponse` and `afterRestoreResponse` to `yii\filters\PageCache` to be more easily extendable (sergeymakinen)
Something is very wrong with changelog...

2016-12-01 22:54 UTC, sergeymakinen commented on framework/CHANGELOG.md
> +- Enh: Added `beforeCacheResponse` and `afterRestoreResponse` to `yii\filters\PageCache` to be more easily extendable (sergeymakinen)
I will figure it out as soon as I get tests up & running. I hope it happens soon.

2016-12-02 12:57 UTC, cebe commented on framework/CHANGELOG.md
> +- Enh: Added `beforeCacheResponse` and `afterRestoreResponse` to `yii\filters\PageCache` to be more easily extendable (sergeymakinen)
best way to fix it would be to rebase against master.

2016-12-02 16:15 UTC, cebe commented
I have stared to work on a test case for this class: #13124 that should be added before applying your changes to reduce the risk of unspotted breaks.

2016-12-08 22:31 UTC, sergeymakinen commented
Yahoo! Travis is green now. The PR is ready to roll.

2016-12-09 14:08 UTC, samdark approved these changes

2016-12-10 20:08 UTC, SilverFire approved these changes

2016-12-13 10:44 UTC, dynasource requested changes

2016-12-13 10:44 UTC, dynasource commented on framework/filters/PageCache.php
> +     */
this naming is a bit confusing as it look like the placeholders are dynamic. I'd prefer something like "dynamicContentPlaceholders"

2016-12-13 10:44 UTC, dynasource commented on framework/filters/PageCache.php
> +     * @internal
a public $variable which we don't want to modify? Shouldnt we use a setter than?

2016-12-13 23:57 UTC, sergeymakinen commented on framework/filters/PageCache.php
> +     * @internal
It's a [convention](https://github.com/yiisoft/yii2/blob/master/framework/base/View.php#L363) I have to follow.

2016-12-14 00:06 UTC, sergeymakinen commented on framework/filters/PageCache.php
> +     */
Me too. But it's how [it works](#r92295170)…

I can improve it later with a getter/setter, some `DynamicContentInterface` with this stuff (`getDynamicPlacholders`, `setDynamicPlacholders`), a type hinting in appropriate `View` methods and a some documentation for other developers.
Of course if it's welcome. ;)

2016-12-14 11:40 UTC, dynasource approved these changes

2016-12-14 11:59 UTC, merged

2016-12-14 11:59 UTC, samdark commented
Merged. Thank you!