Capability to hide root tag and model tag in xml responser
yiisoft/yii2 pull request #12419
Opened 2016-09-01 00:13 UTC by mhthnz

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### Usage:
```php
        Yii::$app->response->formatters['xml'] = [
            'class' => \yii\web\XmlResponseFormatter::className(),
            'rootTag' => null,
            'modelTag' => false,
        ];        
        Yii::$app->response->format = \yii\web\Response::FORMAT_XML;
```
Very helpful for working with strict xml api.

2016-09-01 09:52 UTC, samdark commented
Overall it makes sense but I have no idea what "strict xml api" is. Could you elaborate?

2016-09-01 10:16 UTC, mhthnz commented
When working with XML API external service, API requires strict format answer. But forced insertion root tag, and model tag slightly hampered for this. And we have to use in controller:
```php
return $this->renderPartial('xml_response', ['model' => $model]);
```
Not more convenient than working with properties of model across Model:toArray()

2016-09-01 17:41 UTC, samdark commented on framework/web/XmlResponseFormatter.php
> +    public $modelTag = true;
Should be renamed to `objectTags` since objects aren't necessary models in this case.

2016-12-01 22:47 UTC, samdark requested changes

2016-12-01 22:47 UTC, samdark commented on framework/web/XmlResponseFormatter.php
> +     *  @var boolean mandatory addition of the tag of object name
Need `@since 2.0.11`.

2016-12-15 21:29 UTC, samdark commented
Closed in favor of #13214

2016-12-15 21:29 UTC, closed without merging