Added example from prompt method.
yiisoft/yii2 pull request #12579
Opened 2016-09-21 08:52 UTC by nadar

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | none

2016-09-21 10:55 UTC, cebe commented on framework/console/Controller.php
> +     *         $error = 'The Pin must be at least 4 chars!';
`at least 4 chars` means 4 chars or more, but the check is whether it is equal to 4. should be changed.

2016-09-21 10:55 UTC, cebe requested changes
good addition except the one comment!

2016-09-21 12:51 UTC, samdark approved these changes

2016-09-27 10:19 UTC, merged

2016-09-27 10:19 UTC, cebe commented
Thanks you!