enhance performance by ignoring rules that are never used #12592
yiisoft/yii2 pull request #12607
Opened 2016-09-26 16:42 UTC by dynasource

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | not likely
| Tests pass?   | yes
| Fixed issues  | #12592

2016-09-26 18:27 UTC, SilverFire commented on framework/filters/AccessControl.php
> +                $rule = Yii::createObject(array_merge($this->ruleConfig, $rule));
`$rule` object must be set to `$this->rules` property to be reused in future

2016-09-26 18:27 UTC, SilverFire requested changes

2016-09-26 18:27 UTC, SilverFire commented
Could you add a CHANGELOG line?

2016-09-26 18:45 UTC, SilverFire approved these changes
Add CHANGELOG and fine to go :)

2016-09-26 18:47 UTC, SilverFire approved these changes

2016-09-26 18:49 UTC, dynasource commented
I repackaged it into 1 commit. Thx!

2016-09-26 18:51 UTC, SilverFire approved these changes

2016-09-27 10:46 UTC, samdark approved these changes

2016-09-27 17:24 UTC, cebe commented
As this could break BC for people overriding init() method and it is a critical part for website security I'd prefer to move this PR to 2.1.

2016-09-27 19:18 UTC, dynasource commented
agreed

2016-09-27 19:35 UTC, cebe commented
@dynasource can you make the same changes based on the 2.1 branch and send the PR to that branch?

2016-09-28 12:10 UTC, cebe approved these changes

2016-09-28 13:02 UTC, SilverFire commented
@dynasource Could you update UPGRADE.md and mention this change as a potential BC break?

2016-09-28 14:52 UTC, merged

2016-09-28 14:52 UTC, SilverFire commented
:+1: