Allow omit optional params on URL creation
yiisoft/yii2 pull request #12610
Opened 2016-09-26 17:55 UTC by rob006

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #10970

2016-09-27 10:44 UTC, samdark approved these changes

2016-09-27 12:53 UTC, SilverFire approved these changes

2016-09-27 12:58 UTC, cronfy requested changes
I do not think this PR has to be merged.
1. It does not fix #10970 
2. It probably breaks BC.

Please see my comments in #10970

2016-09-28 12:02 UTC, rob006 commented
I've made some changes. Right now this behavior affects only empty default params. It still fix example from #10970 but should keep BC.

2016-10-24 19:01 UTC, rob006 commented
This is ready to merge IMO.

2016-10-24 22:50 UTC, samdark commented on framework/web/UrlRule.php
> +                if (in_array($name, $this->placeholders) && strcmp($value, '') === 0) {
Isn't it better to do `$value === ''` instead of `strcmp($value, '') === 0`?

2016-10-24 22:50 UTC, samdark commented on framework/web/UrlRule.php
> +                if (in_array($name, $this->placeholders) && strcmp($value, '') === 0) {
Or empty() is you've meant it to work w/ conversion.

2016-10-25 13:11 UTC, rob006 commented on framework/web/UrlRule.php
> +                if (in_array($name, $this->placeholders) && strcmp($value, '') === 0) {
`$value` could be `0`. `empty()` will treat `0` the same as `''` (empty string) which is incorrect, and `===` will return fail when comparing `0` (integer) and `"0"` (string), which is impractical - finally all params are converted to string, so type is irrelevant. String comparison is the best option here.

2016-10-26 12:34 UTC, samdark approved these changes

2016-11-03 16:02 UTC, liongen commented on framework/web/UrlRule.php
> +                if (in_array($name, $this->placeholders) && strcmp($value, '') === 0) {
if my default params is empty it works well, but when I tried with non empty default value, it doesn't work

2016-11-03 16:22 UTC, samdark commented on framework/web/UrlRule.php
> +                if (in_array($name, $this->placeholders) && strcmp($value, '') === 0) {
@liongen could you elaborate? How it doesn't work? Errors? What's the error?

2016-11-03 16:37 UTC, rob006 commented on framework/web/UrlRule.php
> +                if (in_array($name, $this->placeholders) && strcmp($value, '') === 0) {
@liongen It is by design, see https://github.com/yiisoft/yii2/issues/10970#issuecomment-250121267

2016-11-05 00:08 UTC, liongen commented on framework/web/UrlRule.php
> +                if (in_array($name, $this->placeholders) && strcmp($value, '') === 0) {
@rob006 I get some puzzled, I'll try to explain what I want to do:

I have rules, let's say like this
`
[
           'pattern' => '<lang>/page/<id:\d+>',
           'route' => 'site/view',
           'host' => 'http://yii2.app',
           'defaults' => ['lang' => '']
]
`

First, when I tried to make url with `Url::to(['site/view', 'id' => 123]);`
the output was /site/view?id=123, when I applied your patch (from here), the url was like `http://yii2.app/page/123` and that's ok, but when I set some data to lang (let's say `'lang' => 'en'`) in defaults, my url returned to /site/view?id=123 type, but I expected something like http://yii2.dev/en/page/123

The fact is that value in defaults is global and can be set based on some conditions (`'defaults' => ['lang' => $someValue]`), and I don't want to set this value in all my urls when generate them

2016-11-05 09:11 UTC, rob006 commented on framework/web/UrlRule.php
> +                if (in_array($name, $this->placeholders) && strcmp($value, '') === 0) {
@liongen If you want add default language in this way, you should override default `UrlManager::createUrl()` and inject default language into params before URL creation. Magic injecting the default parameters when creating URLs will create unexpected restults and probably will break BC.

2016-11-05 20:14 UTC, SilverFire approved these changes

2016-11-05 20:16 UTC, SilverFire commented
Ready to merge IMO

2016-11-05 22:54 UTC, samdark commented
@cebe ?

2016-11-24 11:05 UTC, rob006 commented
@cebe Are there any problems with this PR?

2016-11-25 09:10 UTC, cebe commented
I had no time to check it yet, sorry. If someone else wants to do it. Feel free to work on it.

2016-11-28 16:00 UTC, dynasource commented on tests/framework/web/UrlRuleTest.php
> +                if (empty($expected)) {
why are these checks done with empty? I dont see any occurrence in the test execution in which an empty array is checked here? Only `false` or a filled `array`

2016-11-28 16:11 UTC, rob006 commented on tests/framework/web/UrlRuleTest.php
> +                if (empty($expected)) {
This check is for empty strings. Empty string and `false` means completely different thing in this case. See https://github.com/yiisoft/yii2/pull/12610/files#diff-96fb0ef29c09f20871090c41bf5b3839R527

2016-11-28 16:24 UTC, dynasource commented on tests/framework/web/UrlRuleTest.php
> +                if (empty($expected)) {
I dont see any empty strings going through that $expected variable

2016-11-28 16:30 UTC, rob006 commented on tests/framework/web/UrlRuleTest.php
> +                if (empty($expected)) {
![b47fffb8](https://cloud.githubusercontent.com/assets/5972388/20676503/2d8fd1fc-b590-11e6-9e05-4e3ed834cb6c.png)

2016-11-28 16:48 UTC, rob006 commented on tests/framework/web/UrlRuleTest.php
> +                if (empty($expected)) {
Ah, you're right, this should be done only for `createUrl()` tests. I will revert this.

2017-01-22 20:05 UTC, SilverFire approved these changes
Good to merge

2017-01-22 20:20 UTC, SilverFire commented
Squashed and merged: 97cad130f38766e1eb0a1945d51701091b0ab157

Thank you very much!

2017-01-22 20:20 UTC, closed without merging