12638 events priorities
yiisoft/yii2 pull request #12639
Opened 2016-09-30 09:39 UTC by ibekiaris

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   |  #yes

2016-09-30 10:10 UTC, cebe requested changes

2016-09-30 10:10 UTC, cebe commented on .gitignore
> +composer.lock
composer.lock should not be removed because it is needed for scrutinizer to work properly.

2016-09-30 10:39 UTC, SilverFire requested changes
Need some work on PR to make it acceptable.

Reindent code with spaces instead of tabs

2016-09-30 10:39 UTC, SilverFire commented on framework/base/Component.php
>      public function on($name, $handler, $data = null, $append = true)
PHPDocs for `$append` must be adjusted.

2016-09-30 10:39 UTC, SilverFire commented on framework/base/Component.php
> +			$this->_events[$name] = new EventPriorityQueue();
I'd prefer `Yii::createObject` here

2016-09-30 10:39 UTC, SilverFire commented on framework/base/EventPriorityQueue.php
> + * a) By default it does not work as a Queue
`a)` -> `-`

2016-09-30 10:39 UTC, SilverFire commented on framework/base/EventPriorityQueue.php
> + * b) You can't iterate this more than one Times
`one Times` -> `once`

2016-09-30 10:39 UTC, SilverFire commented on framework/base/EventPriorityQueue.php
> +	 * @var int
Could you add PHPDoc on what does this property mean

2016-09-30 10:39 UTC, SilverFire commented on framework/base/EventPriorityQueue.php
> +	 * Insert data into queue with given priority
`with given` -> `with the given`

2016-09-30 10:39 UTC, SilverFire commented on framework/base/EventPriorityQueue.php
> +	 * Remove item from queue by given
add `the` before `item`, `queue`, `given`

2016-09-30 10:39 UTC, SilverFire commented on framework/base/EventPriorityQueue.php
> +	 * @param array $data
Should be explained. `$data[0]` in the method looks like implicit magic

2016-09-30 10:39 UTC, SilverFire commented on tests/framework/base/EventPriorityQueueTest.php
> +		$this->eventPriorityQueue = new EventPriorityQueue();
No need to expose the Queue. It should be created for each test.

Create method like `getQueue()` and call it in every test to get a clear instance of `EventPriorityQueue`

2016-09-30 10:39 UTC, SilverFire commented on tests/framework/base/EventPriorityQueueTest.php
> +		foreach ($this->eventPriorityQueue as $item) {
The whole test should be redone like this:

```php
$items = [
    ['foo', null],
    ['bar', null],
    ['baz', null]
];

foreach ($items as $item) {
    $queue->insert($item);
}

foreach ($queue as $item) {
    $restoredItems[] = $item;
}

$this->assertEquals($items, $restoredItems);                                                                                                                                                                                                   

```

2016-09-30 10:39 UTC, SilverFire commented on tests/framework/base/EventPriorityQueueTest.php
> +		$data = ['foo', null];
Same here

2016-09-30 10:39 UTC, SilverFire commented on tests/framework/base/EventPriorityQueueTest.php
> +		$data = ['foo', 'fooData'];
Same here

2016-09-30 10:39 UTC, SilverFire commented on tests/framework/base/EventPriorityQueueTest.php
> +		$data = ['foo', null];
same here

2016-09-30 11:11 UTC, ibekiaris commented on framework/base/Component.php
>      public function on($name, $handler, $data = null, $append = true)
I think that we have to leave this as it is until we define priorities in the App events. Then we can totally replace append + prepend with priority variable as an integer or array

2016-09-30 11:57 UTC, ibekiaris commented on framework/base/Component.php
> +			$this->_events[$name] = new EventPriorityQueue();
I am of the opinion that is not very safe for this "Queue" but I can understand this is a Yii2 approach. I ll commit that.

2016-09-30 12:02 UTC, ibekiaris commented on framework/base/Component.php
> +			$this->_events[$name] = new EventPriorityQueue();
I ve just commited Yii::createObject you want me to revert to plain implementation?

2016-09-30 13:13 UTC, ibekiaris commented
I have committed changes requested

2016-10-04 09:00 UTC, samdark requested changes

2016-10-04 09:00 UTC, samdark commented on .gitignore
> +/extensions
This file should not be in the commit.

2016-10-04 09:00 UTC, samdark commented on framework/base/Component.php
> +            $priority = $this->_events[$name]->getMaxPriority() + 5;
What's `5`? Why exactly `5`? Is it constant? If so, move it into constant or at least add a comment describing the purpose.

2016-10-04 09:00 UTC, samdark commented on framework/base/Component.php
> +            // TODO Change self::hasEventHandlers to avoid that calculation
Should be addressed before merge.

2016-10-04 09:00 UTC, samdark commented on framework/base/EventPriorityQueue.php
> + * @author Ioannis Bekiaris <info@ibekiaris.me>
Need `@since` tag.

2016-10-04 09:00 UTC, samdark commented on framework/base/EventPriorityQueue.php
> +    protected $priorityCounter = PHP_INT_MAX;
Does defining defaults as constants work with PHP 5.4?

2016-10-04 09:00 UTC, samdark commented on framework/base/EventPriorityQueue.php
> +     * @var int
Description needed.

2016-10-04 09:00 UTC, samdark commented on framework/base/EventPriorityQueue.php
> +    protected $innerQueue;
Description needed.

2016-10-04 09:00 UTC, samdark commented on framework/base/EventPriorityQueue.php
> +     * @var array
Description needed.

2016-10-04 09:00 UTC, samdark commented on framework/base/EventPriorityQueue.php
> +                // TODO We can avoid this calculation. Check removed item calculation.
Should be addressed before merge.

2016-10-04 09:00 UTC, samdark commented on tests/framework/base/EventPriorityQueueTest.php
> +    protected function setUp()
Could be removed.

2016-10-04 09:05 UTC, ibekiaris commented on framework/base/Component.php
> +            $priority = $this->_events[$name]->getMaxPriority() + 5;
5 is used until is deprecated because of the current append prepend functionality. When priorities in core flow defined we 'll just remove that 5.

2016-10-04 09:07 UTC, ibekiaris commented on framework/base/EventPriorityQueue.php
> +    protected $priorityCounter = PHP_INT_MAX;
You are right. Available since PHP 5.0.5

2016-10-04 09:30 UTC, samdark commented on framework/base/Component.php
> +            $priority = $this->_events[$name]->getMaxPriority() + 5;
Need a comment in the code explaining that else it would be too cryptic in a month.

2016-10-04 09:39 UTC, ibekiaris commented on framework/base/Component.php
> +            $priority = $this->_events[$name]->getMaxPriority() + 5;
I agree. You are  definitely right!

2016-10-10 14:52 UTC, ibekiaris commented on .gitignore
> +/extensions
It is not.. Do I understand something wrong?

2016-10-10 18:41 UTC, samdark commented on .gitignore
> +/extensions
It is if it's displayed here. Same about `composer.lock`.

2016-10-10 22:21 UTC, samdark commented on .gitignore
> +/extensions
OK. Don't worry, we'll make sure nothing wrong is in when merging...

2016-12-15 23:08 UTC, samdark commented
https://github.com/yiisoft/yii2/pull/12639/commits/ffa688c5d56ed3237c00157adb86e648260dcfa3 seems to be not visible in the PR diff. That's very weird. @ibekiaris would you please re-submit a pull request?

2017-03-14 11:28 UTC, SamMousa commented
This seems to need a lot more work before it's ready for merge, docs seem to be missing as well.
@ibekiaris Any idea on when / if you'll be able to work on this again? 
Could it be bumped to 2.0.13?

2017-12-02 12:16 UTC, SilverFire commented
As for me, event handling should not guarantee handlers execution order. 
In case the handlers list is Not prioritized, developer should simply remember, that handlers just follow the event, not other handlers.
Handlers can be attached on class creation, during class runtime, even during another handler execution. Keeping original execution order will become a mess in this case.
In case you really need to react on event in a special order, then handlers should be tied and executed in procedural manner.

The PR seems to be abandoned, I'm closing it.

2017-12-02 12:16 UTC, closed without merging