Add checkAjax support in Controller::redirect
yiisoft/yii2 pull request #12650
Opened 2016-10-02 14:21 UTC by ivanovyordan

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #11058

2016-10-02 20:38 UTC, SilverFire requested changes
CHANGELOG and UPGRADE.md should be updated

2016-10-02 20:38 UTC, SilverFire commented on framework/web/Controller.php
> +     * to redirect to the given URL. If this is false, a `Location` header will be sent, which when received as
`false` -> <code>\`false\`</code>

2016-10-03 05:44 UTC, ivanovyordan commented on framework/web/Controller.php
> +     * to redirect to the given URL. If this is false, a `Location` header will be sent, which when received as
Setting default value to `false` would break BC right?

2016-10-03 06:52 UTC, SilverFire commented on framework/web/Controller.php
> +     * to redirect to the given URL. If this is false, a `Location` header will be sent, which when received as
Yeah

2016-10-03 08:40 UTC, rob006 commented
This breaks BC anyway, since it changes method signature.

2016-10-04 09:43 UTC, samdark commented
Agree. It's a BC break.

2016-10-04 12:06 UTC, ivanovyordan commented on framework/web/Controller.php
> +     * to redirect to the given URL. If this is false, a `Location` header will be sent, which when received as
@SilverFire I made the changes.

Thanks for the feedback guys.

2016-10-04 12:11 UTC, SilverFire commented
I'm fine with merging into 2.1 right now

2016-10-04 12:25 UTC, closed without merging

2016-10-04 12:26 UTC, samdark commented
Merged into 2.1: https://github.com/yiisoft/yii2/commit/0d72e37f3ce759a7286423eb32f19814bc2e0392