Added `\yii\i18n\Formatter::asDurationTime()`
yiisoft/yii2 pull request #12660
Opened 2016-10-04 06:35 UTC by githubjeka

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  |  #12022 fixed by the PR

2016-10-04 07:15 UTC, SilverFire commented on framework/i18n/Formatter.php
> +        if (!isset($options['implodeString'])) {
H

2016-10-04 07:31 UTC, SilverFire requested changes
And we still have no way to configure years, months and days

2016-10-04 07:31 UTC, SilverFire commented on framework/i18n/Formatter.php
> +        if (!isset($options['implodeString'])) {
How about

```php
$implodeString = ArrayHelper::get($options, 'implodeString', ', ');
```

2016-10-04 07:31 UTC, SilverFire commented on framework/i18n/Formatter.php
> +            $parts[] = Yii::t('yii', '{delta, plural, =1{1 year} other{# years}}', ['delta' => $interval->y],
Splitting for two lines does not look reasonable here

2016-10-04 07:37 UTC, SilverFire commented
Maybe, we should agree three different options for every part:

- `null` (default) - display part only when it's not zero
- `true` - always display a part, even it's zero
- `false` - never display a part

2016-10-04 07:37 UTC, samdark requested changes

2016-10-04 07:37 UTC, samdark commented on framework/i18n/Formatter.php
> +     * @deprecated Since version in 2.0.10. The signature will be changed in 2.1 to [[Formatter::asDurationTime()]]
`in` isn't needed here. Just `Since version 2.0.10`

2016-10-04 07:41 UTC, githubjeka commented
is label `2.0.11` ?

2016-10-04 07:44 UTC, SilverFire commented
The PR does not look ready to be merged right now, so I've assigned it to the next milestone.
If you can continue work on this PR, we can accept it in 2.0.10 once it's ready

2016-10-04 09:16 UTC, githubjeka commented on framework/i18n/Formatter.php
> +     * @deprecated Since version in 2.0.10. The signature will be changed in 2.1 to [[Formatter::asDurationTime()]]
fixed thanks

2016-10-04 09:16 UTC, githubjeka commented on framework/i18n/Formatter.php
> +            $parts[] = Yii::t('yii', '{delta, plural, =1{1 year} other{# years}}', ['delta' => $interval->y],
Fixed

2016-10-04 09:17 UTC, githubjeka commented
Corrected

2016-10-04 09:26 UTC, samdark requested changes

2016-10-04 09:26 UTC, samdark commented on framework/i18n/Formatter.php
> +        if ($showYears || (is_null($showYears) &&$interval->y > 0)) {
Formatting! `&&$inteval`. Same in more lines ↓

2016-10-04 09:26 UTC, samdark commented on framework/i18n/Formatter.php
> +        if ($showYears || (is_null($showYears) &&$interval->y > 0)) {
`=== null` should be used instead of `is_null`

2016-10-04 09:26 UTC, samdark commented on framework/i18n/Formatter.php
> +        if (is_null($value)) {
`=== null` should be used instead of `is_null`

2016-10-04 09:33 UTC, githubjeka commented on framework/i18n/Formatter.php
> +        if (is_null($value)) {
Why? Is requirement to yii2 code?

2016-10-04 09:37 UTC, samdark commented on framework/i18n/Formatter.php
> +        if (is_null($value)) {
It's overall better to use simple checks instead of function calls where possible. More explicit, less opcodes.

2016-10-04 09:45 UTC, SilverFire commented
Btw, the implementation is not very smart.

Take a look at implementation in `moment.js` https://github.com/moment/moment/blob/develop/src/lib/duration/humanize.js

2016-10-04 09:57 UTC, githubjeka commented
@SilverFire I think about. But it will pull the more changes. And so, I added a few lines :) May be better create new issue...

2016-10-04 10:09 UTC, SilverFire commented
It's fine to do it in this pull request.

2016-10-04 10:16 UTC, SilverFire commented
Considering that we implement completely different behavior, I suggest to leave `asDuration()` almost changes and implement `asRoudedDuration()` that will create `DateInterval` object and round it so only required parameters are left

2016-10-04 10:23 UTC, githubjeka commented
It will called DecoratorDateInterval class, formatter should use it.... #эко_меня_понесло

2016-10-05 16:29 UTC, githubjeka commented
>Does it make any sense to show something like 1 year 11 months 3 seconds ago?

Yes you can - via `\yii\i18n\Formatter::asRelativeTime`. It isn't about this issue.

I added more tests. Now, I suggest leave as is or please explain what do you want to exactly?

2016-12-08 20:38 UTC, cebe commented
Sorry for the late reply. It seems that the requirements for this method are not very clear so before putting more work into this we should agree on what the different methods should do. Also the interface for specifying which part of the duration to show is not simple. It ususally does not make sense to display e.g. only year and seconds so you display `1 year, 16 seconds` for a timestamp that was actually a year, a month and some hours + 16 seconds. What should instead applied is a parameter that defines the precision. There are also multiple options on how to handle that:

- precision is `year`:
  - we could display `0 years` if duration <= 1 year, `1 year` if <= 2 year etc.
  - alternative: display `x sec` if duration <= 1 min, `x min` if duration <= 1 h, and switch to above display if we reached year
- precision is `month`:
  - `1 year, 2 month` if > duration is over a year or just display the months if it is not.
  - same couting as above could be applied. (or not)

There are a lot of options here that should be discussed to define a method interface (or multiple methods).
See also 
- http://www.icu-project.org/apiref/icu4j/com/ibm/icu/text/MeasureFormat.html
- http://www.icu-project.org/apiref/icu4j/com/ibm/icu/text/RelativeDateTimeFormatter.html
guess intl has something we could use here. Need to find it.

2016-12-09 05:02 UTC, closed without merging