Show alternative when command not found
yiisoft/yii2 pull request #12661
Opened 2016-10-04 06:53 UTC by mdmunir

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #12659

2016-10-04 07:14 UTC, SilverFire commented
Console application class looks overcomplicated now.

Maybe it's better to create c separate class `AlternativesFinder` and instantiate it in the `catch` block?

2016-10-04 07:24 UTC, mdmunir commented
The most complicated code are get list of command. The same code also use in `HelpController`. Much better if we separated it to another class.

2016-10-04 08:22 UTC, samdark requested changes

2016-10-04 08:22 UTC, samdark commented on framework/CHANGELOG.md
> +- Enh #12659: Show alternative when command not found (mdmunir)
Suggest alternatives when console command typed was not found

2016-10-04 08:22 UTC, samdark commented on framework/console/Application.php
> +            if($alternatives = $this->findAlternatives($route)){
Formatting!

2016-10-04 08:22 UTC, samdark commented on framework/console/Application.php
> +                $message .= count($alternatives) > 1 ?  "\nDid you mean one of these?" : "\nDid you mean this?";
In case of only one alternative it could be outputted right away as `Did you mean %s?`

2016-10-04 08:22 UTC, samdark commented on framework/console/Application.php
> +        $threshold = 1e3;
What's `1e3`?

2016-10-04 08:22 UTC, samdark commented on framework/console/Application.php
> +        $threshold = 1e3;
Need a comment explaining why exactly this value is used.

2016-10-04 08:22 UTC, samdark commented on framework/console/Application.php
> +            return $lev < 2 * $threshold;
What's `2`?

2016-10-04 08:23 UTC, samdark commented
I agree that it could be a good idea to move logic into different class.

2016-10-04 08:36 UTC, SilverFire commented
Suggest to create `ModuleReflection` class which will know all about modules reflection.

And something like `ActionAlternativesFinder`, which will be responsible for alternatives search:

```php
$alternatives = (new ActionAltertativesFinder([
     'allActions' => (new ModuleReflection($this->module))->getActions(),
]))->findFor($action);
```

2016-10-04 08:46 UTC, mdmunir commented on framework/console/Application.php
> +            return $lev < 2 * $threshold;
Copied from Sympony https://github.com/symfony/console/blob/master/Application.php#L971.
I am also not understand what actually is :grin:

2016-10-04 14:57 UTC, samdark reviewed
Overall it's much better but I'm not sure @SilverFire meant a static helper when he suggested a separate class...

2016-10-04 14:57 UTC, samdark commented on framework/console/Application.php
> +
Looks suspicious...

2016-10-04 14:57 UTC, samdark commented on framework/console/controllers/HelpController.php
> +
Same here. Looks suspicious. Do we need to ignore exceptions here?

2016-10-05 06:36 UTC, SilverFire commented
No, I didn't mean helper in this case

2016-10-05 07:12 UTC, SilverFire commented
## Separate non-static classes

### Pros:

 - Can create class-scope constants to explain Levenshtein magic numbers
 - Low coupling
 - Easier to test - the class has no dependencies
 - Easier to re-use
 - (Generally it's about SOLID)

### Cons:

 - Not so convenient to call as Helpers

## Helper class

### Pros:

 - Easy to call - good for top-level public API

### Cons:

 - Mixed responsibility
 - Higher coupling (`Yii::$app` calls)
 - Harder to test
 - Just a bunch of function, grouped in some namespace. Functional programming masked behind OOP-style

___

Considering it will not be a frequently used API, I don't see profits from making it as a helper.

2016-10-05 07:32 UTC, samdark commented
Added link to the summary to https://github.com/yiisoft/yii2/blob/master/docs/internals/design-decisions.md

2016-10-05 09:57 UTC, cebe commented
imo it is much easier to implement this by introducing an exception class that handles the case and cover the display in the ErrorHandler. See #12675 for a draft implementation.

2016-10-05 10:27 UTC, samdark commented
Agree. Exception solution looks cleaner.

2016-10-05 10:28 UTC, samdark commented
@mdmunir what do you think about @cebe proposal?

2016-11-26 22:47 UTC, cebe commented
I am closing this PR in favor of  #12675, which is now complete. Thank you for your contribution @mdmunir!

2016-11-26 22:47 UTC, closed without merging