DetailView captionOptions & contentOptions attributes
yiisoft/yii2 pull request #12665
Opened 2016-10-04 13:56 UTC by githubjeka

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #11844 fixed by the PR

Later I will update phpDoc & changeLog...

2016-10-04 14:54 UTC, samdark requested changes
Looks OK. Need CHANGELOG and phpdoc.

2016-10-04 16:18 UTC, githubjeka commented
Check in

2016-10-04 20:18 UTC, samdark requested changes

2016-10-04 20:18 UTC, samdark commented on framework/CHANGELOG.md
> +- Enh #11835: Fixed NTEXT in `\yii\db\mssql\QueryBuilder::$typeMap` that is being deprecated in MSSQL (githubjeka)
Why this line is added?

2016-10-04 20:18 UTC, samdark commented on framework/CHANGELOG.md
> +- Enh #11844: Added the ability to customize html attributes of label and value tags in `\yii\widgets\DetailView` (githubjeka)
html → HTML

2016-10-05 04:36 UTC, githubjeka commented on framework/CHANGELOG.md
> +- Enh #11835: Fixed NTEXT in `\yii\db\mssql\QueryBuilder::$typeMap` that is being deprecated in MSSQL (githubjeka)
Strange. After merge ....

2016-10-05 04:48 UTC, githubjeka commented on framework/CHANGELOG.md
> +- Enh #11835: Fixed NTEXT in `\yii\db\mssql\QueryBuilder::$typeMap` that is being deprecated in MSSQL (githubjeka)
Fixed

2016-10-05 04:48 UTC, githubjeka commented on framework/CHANGELOG.md
> +- Enh #11844: Added the ability to customize html attributes of label and value tags in `\yii\widgets\DetailView` (githubjeka)
Fixed

2016-10-05 08:47 UTC, SilverFire commented
Merged https://github.com/yiisoft/yii2/commit/987c302883a9dc3fcfa5011df6559a6f99b8ea91

2016-10-05 08:47 UTC, closed without merging

2016-10-05 08:49 UTC, githubjeka commented
Bad merged!

2016-10-05 08:51 UTC, SilverFire commented
It's git :)

2016-10-05 08:53 UTC, githubjeka commented
No wonder it is so called.

2016-10-05 08:53 UTC, SilverFire commented
Resolved by 5b7a70c

2016-10-05 08:58 UTC, githubjeka commented
Again it's bad

2016-10-05 09:02 UTC, SilverFire commented
Thank you, done af32a48