Added Method yii\web\Request::getDomain()
yiisoft/yii2 pull request #12670
Opened 2016-10-04 20:24 UTC by ivanovyordan

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #11309 

Also modified `yii\web\Request::getHostInfo()` to use the new method.
P.S. Not sure what kind of unit test I need to write to cover the new methods.

2016-10-04 20:56 UTC, rob006 commented
```php
Yii::$app->getRequest()->hostInfo = 'http://example.com';
echo Yii::$app->getRequest()->domain;
```

You will expect that `Request::getDomain()` will return `example.com`, but you will get completely different result.

2016-10-04 21:28 UTC, tunecino commented
please check those:
http://stackoverflow.com/questions/288810/get-the-subdomain-from-a-url
http://stackoverflow.com/questions/399932/can-i-improve-this-regex-check-for-valid-domain-names
https://github.com/yiisoft/yii2/issues/11309#issuecomment-207453311

2016-10-04 21:51 UTC, rob006 commented
@tunecino This is irrelevant in this context. If `Request::hostInfo` is `http://myapp.example.com` I expect that `Request::getDomain()` will return `myapp.example.com` instead of `example.com`.

2016-10-04 22:46 UTC, tunecino commented
mmm I see. you mean like what `parse_url($url)['host']` would return. I guess I did misunderstood this from the beginning.

2016-10-06 09:18 UTC, samdark requested changes

2016-10-06 09:18 UTC, samdark commented on framework/web/Request.php
> +     * @see setDomain()
Need `@since` tag.

2016-10-06 09:18 UTC, samdark commented on framework/web/Request.php
> +                if(strpos($this->_domain, ':') !== false) {
Formatting. Need space before `(`.

2016-10-06 09:18 UTC, samdark commented on framework/web/Request.php
> +     * @param string $value the host part of the application URL.
Need `@since` tag.

2016-10-06 09:18 UTC, samdark commented on framework/web/Request.php
> +            if($domain !== null) {
Need space after `if`

2016-10-06 09:18 UTC, samdark commented on framework/web/Request.php
> +                $this->_hostInfo = $http . '://' . $domain . ':' . $port;
I think it changes behavior i.e. `:80` and `:433` will be added while previously it was not.

2016-10-06 10:32 UTC, rob006 commented
Alternative: #12686

2016-10-06 10:34 UTC, samdark commented
@ivanovyordan what do you think about @rob006 solution?

2016-10-06 22:00 UTC, closed without merging

2016-10-06 22:01 UTC, samdark commented
https://github.com/yiisoft/yii2/pull/12686 merged. Thanks for contributing a possible solution.