Add `beforeRow` and `afterRow`
yiisoft/yii2 pull request #12710
Opened 2016-10-10 14:18 UTC by mdmunir

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | 
| Fixed issues  | 

# Usage
```php
ListView::widget([
    'dataProvider' => $dataProvider,
    'itemOptions' => ['class' => 'col-md-4'],
    'beforeRow' => function($model, $key, $index) {
        if ($index % 3 === 0) {
            return '<div class="row">';
        }
    },
   'afterRow' => function($model, $key, $index) use($dataProvider) {
        if ($index % 3 === 2 || $index === $dataProvider->count - 1) {
            return '</div>';
        }
    },
]);
```

2016-10-10 14:23 UTC, samdark commented
I have no objections merging it. @yiisoft/core-developers opinions?

2016-10-10 14:24 UTC, mdmunir commented
https://github.com/yiisoft/yii2/blob/master/framework/grid/GridView.php#L113-L119

2016-10-10 14:26 UTC, klimov-paul requested changes

2016-10-10 14:26 UTC, klimov-paul commented on framework/widgets/ListView.php
> +    public $beforeRow;
Should be `beforeItem`.

2016-10-10 14:26 UTC, klimov-paul commented on framework/widgets/ListView.php
> +    public $afterRow;
Should be `afterItem`

2016-10-10 14:26 UTC, klimov-paul commented on framework/widgets/ListView.php
> +    public $beforeRow;
Missing `since` tag

2016-10-10 14:26 UTC, klimov-paul commented on framework/widgets/ListView.php
> +    public $afterRow;
Missing `since` tag

2016-10-10 14:26 UTC, klimov-paul commented on framework/widgets/ListView.php
> +                if (!empty($row)) {
Should be check for `null` or `false`.
Empty string added to the items set may be a desiarable behavior.

2016-10-11 12:36 UTC, cebe commented
Looks good to me, need a CHANELOG entry.

2016-10-11 23:16 UTC, samdark approved these changes

2016-10-12 08:36 UTC, klimov-paul approved these changes

2016-10-12 08:57 UTC, samdark commented
@yiisoft/core-developers 2.0.10 or 2.0.11?

2016-10-12 09:26 UTC, klimov-paul commented
I am for `2.0.11`.
`ListView` is not covered by unit tests. It is better to move this fix to the beginning of bew milestone.

2016-10-12 09:34 UTC, dynasource commented
> ListView is not covered by unit tests
Im willing to fix that

2016-12-18 08:53 UTC, SilverFire commented
Merged with some adjustments: https://github.com/yiisoft/yii2/commit/0148325426ea495cbfcc7170ed8c45a0bccfbb1e

2016-12-18 08:53 UTC, SilverFire commented
Thank you!

2016-12-18 09:00 UTC, closed without merging