clear cached filemtime call, fix #12713OD
yiisoft/yii2 pull request #12717
Opened 2016-10-11 08:27 UTC by SG5

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes/no
| Fixed issues  | #12713

2016-10-11 08:42 UTC, samdark commented
Have you verified it helps?

2016-10-11 08:50 UTC, SG5 commented
yes, i've got 3 time `Invalid Cache!` message

2016-10-11 20:36 UTC, Coksnuss commented
I can confirm that it works as well (as stated in my issue).
If the proposed fix is accepted, maybe the ticket can be moved to the 2.0.10 milestone?

2016-10-11 20:50 UTC, cebe requested changes

2016-10-11 20:50 UTC, cebe commented on framework/caching/FileDependency.php
>          return @filemtime(Yii::getAlias($this->fileName));
getAlias() should be called once and the result be stored in a variable.

2016-10-12 08:39 UTC, samdark approved these changes

2016-12-16 01:49 UTC, cebe approved these changes

2016-12-16 20:31 UTC, dynasource approved these changes

2016-12-16 20:35 UTC, merged

2016-12-16 20:35 UTC, samdark commented
Thanks!