Add is_dir() validation for BaseFileHelper::findFiles()
yiisoft/yii2 pull request #12732
Opened 2016-10-13 07:08 UTC by zalatov

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

Add is_dir() validation for BaseFileHelper::findFiles().
Sometimes it throws exception when file/directory is deleted or moved while executing script.

2016-10-13 08:06 UTC, SilverFire requested changes
It will be good to have a test of this case.

CHANGELOG is required

2016-10-13 11:30 UTC, samdark commented on framework/helpers/BaseFileHelper.php
> +                } elseif (is_dir($path) && (!isset($options['recursive']) || $options['recursive'])) {
Need to make sure it works well with symlinks.

2016-10-13 11:30 UTC, samdark commented on framework/helpers/BaseFileHelper.php
> +                } elseif (is_dir($path) && (!isset($options['recursive']) || $options['recursive'])) {
On Windows as well...

2016-10-13 22:37 UTC, zalatov commented
@SilverFire,
I don't know how test it.
We catch this error when two concurrent requests.
While first request already deleting files in dir, second request only start find files.

@samdark,
From the documentation:
`is_dir() Note that this functions follows symbolic links. It will return true if the file is actually a symlink that points to a directory.`

2016-10-26 23:55 UTC, zalatov commented
Added row to CHANGELOG

2016-10-27 07:14 UTC, cebe commented
> But... in CHANGELOG last version is 2.08, therefore this pull request is 2.0.11.

can you rebase your branch on master?

2016-10-27 23:44 UTC, zalatov commented
Pulled last changes from master

2016-12-15 21:21 UTC, SilverFire commented
Merged, thank you!

2016-12-15 21:22 UTC, SilverFire commented
https://github.com/yiisoft/yii2/commit/50953c2960549a727a9650d0db36cf21f0c542e9

2016-12-15 21:22 UTC, closed without merging