RBAC migration: Changed `data` column type from `text` to `blob`
yiisoft/yii2 pull request #12755
Opened 2016-10-17 07:45 UTC by SilverFire

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12681 

Changed `data` column type from `text` to `blob` to handle null-byte (`\0`) in serialized RBAC rule properly

Closes #12681

2016-10-17 09:22 UTC, samdark approved these changes

2016-11-11 10:48 UTC, dynasource requested changes
it would be nice to have this data variable in a test to prevent changing in the future.

2016-11-12 13:44 UTC, SilverFire commented
Done!

2016-11-12 13:49 UTC, SilverFire commented
Merged https://github.com/yiisoft/yii2/commit/23790272dc561aacf2070cbbda396f49e44cbb7d

2016-11-12 13:49 UTC, closed without merging