Issue #12748 fix
yiisoft/yii2 pull request #12770
Opened 2016-10-18 13:30 UTC by MKiselev

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12748

2016-10-18 14:57 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +            $this->db = Instance::ensure($this->db, Connection::className());
I'd leave it as is here and duplicate the call in `create` action so it won't trigger errors if it doesn't need database.

2016-10-18 14:57 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +                $relatedTableSchema = $this->db->getTableSchema($relatedTable);
You need DB here so call `$this->db = Instance::ensure($this->db, Connection::className());`.

2016-10-18 14:57 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +                        $this->stdout("Related table for field {$column} already exist, but primary key is a composite. Default name will be used for related field\n", Console::FG_YELLOW);
```php
"Related table for field \"{$column}\" exists, but primary key is composite. Default name \"id\" will be generated for related field\n"
```

2016-10-18 14:57 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +                        $this->stdout("Related table for field {$column} already exist, but do not have primary key. Default name will be used for related field.\n", Console::FG_YELLOW);
```php
"Related table for field \"{$column}\" exists, but does not have a primary key. Default name \"id\" will be used for related field.\n"
```

2016-10-18 14:57 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +                    preg_match('/foreignKey\((\w*)\s?(\w*)\)/', $chunk, $matches);
Why the regexp change?

2016-10-20 22:01 UTC, MKiselev commented on framework/console/controllers/MigrateController.php
> +                $relatedTableSchema = $this->db->getTableSchema($relatedTable);
How to check that the component DB may be initialized here?

Я имею в виду, что если в конфигурации приложения db не задан, то DI не может разрешить эту зависимость и получаю исключение.

2016-10-20 22:05 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +                $relatedTableSchema = $this->db->getTableSchema($relatedTable);
https://github.com/yiisoft/yii2/pull/12770#discussion_r83872685

You can probably try-catch exception and fall back to default generation scenario...

2016-10-20 22:13 UTC, MKiselev commented on framework/console/controllers/MigrateController.php
> +                    preg_match('/foreignKey\((\w*)\s?(\w*)\)/', $chunk, $matches);
Regular expression changed for support setting field name for reference key by using whitespace like this: ```foreignKey(table_name reference_key)```

Now FK may by defined in three ways:
```table_id:foreignKey(table_name reference_key)```
```table_id:foreignKey(table_name)```
```table_id:foreignKey```

2016-10-20 23:30 UTC, MKiselev commented
Видимо не так CHANGELOG.md надо править, я стянул с мастера и поправил...
Ещё и имя с битбакета в гите настроено.

2016-10-22 17:39 UTC, MKiselev commented
@samdark have any comments for last commit?

2016-10-23 08:58 UTC, samdark requested changes

2016-10-23 08:58 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +            $foreignKeys[$firstTable . '_id']['column'] = '';
I'd still fall back to just `id`.

2016-10-23 08:58 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +                        } else {
This is the most common variant so I'd check for `=== 1` first.

2016-10-23 08:58 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +                        } elseif ($primaryKeyCount < 1) {
It's better to write it as `=== 0` since it can't be negative anyway.

2016-10-23 12:58 UTC, MKiselev commented on framework/console/controllers/MigrateController.php
> +            $foreignKeys[$firstTable . '_id']['column'] = '';
@samdark  if here use just ```id```, then here https://github.com/MKiselev/yii2/blob/4126e46c3889373a54d59a22fe49c5b485d370c1/framework/console/controllers/MigrateController.php#L320 check will be false.

2016-10-23 13:12 UTC, MKiselev commented
@samdark update code.

2016-10-23 13:16 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +            $foreignKeys[$firstTable . '_id']['column'] = '';
Ah. OK then.

2016-10-23 13:19 UTC, samdark requested changes
Looks much better now. Added a bit more inline comments. Also need a changelog.

2016-10-23 13:19 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +            $foreignKeys[$firstTable . '_id']['column'] = '';
Maybe it should be set to `null` and then the check could be ` === null`?

2016-10-23 13:19 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +                    preg_match('/foreignKey\((\w*)\s?(\w*)\)/', $chunk, $matches);
Docs should be updated accordingly.

2016-10-23 17:04 UTC, MKiselev commented
@samdark code was updated. My english is not very good, please check docs. RU docs I will update after accept PR.

2016-10-23 17:04 UTC, MKiselev commented on framework/console/controllers/MigrateController.php
> +                    preg_match('/foreignKey\((\w*)\s?(\w*)\)/', $chunk, $matches);
Was updated.

2016-10-23 18:06 UTC, samdark approved these changes
Everything's OK except wording.

2016-10-23 20:22 UTC, MKiselev commented
@samdark What exactly is wrong?
I added RU docs.

2016-10-27 13:20 UTC, samdark commented
Some wording in English. I can handle that...

2016-10-31 23:02 UTC, closed without merging

2016-10-31 23:03 UTC, samdark commented
Merged with some adjustments: https://github.com/yiisoft/yii2/commit/4f89265fff54723b6a2fa624a2f89429cd482d54. Thanks!