refs #12771 \yii\web\User::can() and guest
yiisoft/yii2 pull request #12785
Opened 2016-10-19 15:10 UTC by Ni-san

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12771 

Skip \yii\rbac\PhpManager::checkAccessRecursive and \yii\rbac\DbManager::checkAccessRecursive if role assignments are empty.
I checked code of `\yii\rbac\PhpManager::checkAccessRecursive` and `\yii\rbac\DbManager::checkAccessRecursive`, and I'm sure that result always will be "false" if `$assignments` is empty array and `\yii\rbac\BaseManager::$defaultRoles` is empty array too.
On the other hand, I'm not sure it matters.

2016-11-13 16:34 UTC, SilverFire requested changes

2016-11-13 16:34 UTC, SilverFire commented on framework/CHANGELOG.md
> +- Enh #12499: When AJAX validation in enabled, `yii.activeForm.js` will run it forcefully on form submit to display all possible errors (silverfire)
This line should be removed

2016-11-13 16:34 UTC, SilverFire commented on framework/rbac/BaseManager.php
> +    protected function emptyRoles(array $assignments)
We prefix this kind of methods with `has` or `is` to make it easier to understand, what does the method do.

Maybe, `hasNoAssignments()`?

2016-11-13 16:34 UTC, SilverFire commented on framework/rbac/BaseManager.php
> +     * Check that there no any roles in user's role assignments and in default roles
Method checks, whether $assignments array is empty and [[defaultRoles]] are empty as well.

2016-11-13 16:34 UTC, SilverFire commented on framework/rbac/BaseManager.php
> +     * @param Assignment[] $assignments list of user's role assignments
`@param Assignment[] $assignments array of user's assignments`

2016-11-13 16:34 UTC, SilverFire commented on framework/rbac/BaseManager.php
> +     * @return bool true if empty
`@return bool whether $assignments array is empty and [[defaultRoles]] are empty as well`

2016-11-13 16:34 UTC, SilverFire commented on framework/rbac/BaseManager.php
> +        return count($assignments) === 0 && count($this->defaultRoles) === 0;
Could be simplified to 

```php
return empty($assignments) && empty($this->defaultRoles);
```

2016-11-13 16:34 UTC, SilverFire commented on framework/rbac/DbManager.php
> +        // nothing to check, user has no any rights
Could be removed

2016-11-13 16:34 UTC, SilverFire commented on framework/rbac/PhpManager.php
> +        // nothing to check, user has no any rights
Could be removed

2016-11-15 05:42 UTC, Ni-san commented on framework/CHANGELOG.md
> +- Enh #12499: When AJAX validation in enabled, `yii.activeForm.js` will run it forcefully on form submit to display all possible errors (silverfire)
done

2016-11-15 05:42 UTC, Ni-san commented on framework/rbac/BaseManager.php
> +     * Check that there no any roles in user's role assignments and in default roles
done

2016-11-15 05:42 UTC, Ni-san commented on framework/rbac/BaseManager.php
> +     * @param Assignment[] $assignments list of user's role assignments
done

2016-11-15 05:42 UTC, Ni-san commented on framework/rbac/BaseManager.php
> +     * @return bool true if empty
done

2016-11-15 05:42 UTC, Ni-san commented on framework/rbac/BaseManager.php
> +    protected function emptyRoles(array $assignments)
done

2016-11-15 05:45 UTC, Ni-san commented on framework/rbac/DbManager.php
> +        // nothing to check, user has no any rights
done

2016-11-15 08:42 UTC, SilverFire approved these changes
Looks good to me

2016-11-15 08:59 UTC, dynasource requested changes
Thanks for putting effort in improving Yii2.

A few things:
- there is duplication of logic in DbManager & PhpManager which should be prevented. I would expect a new function like 'getActiveAssignements' or something like that.
- inverse logic is applied in the method name 'hasNoAssignments'. This should be formulated positively like 'hasAssignments'
- I a still missing a clear explanation in the method docs why the added method is useful. It states what it does, but not why its useful.
- new methods should  get a @since tag

2016-12-17 10:26 UTC, closed without merging

2016-12-17 10:26 UTC, SilverFire commented
Sorry for this mess, it looks like a GitHub bug :(

2016-12-17 10:44 UTC, SilverFire commented
A few words what happen to this PR: 

1. I've synchronized it with master and pushed changes to the branch in @Ni-san's fork. GitHub got crazy and showed a diff for this PR containing hundreds of commits.
2. I've removed all this mess and force-pushed clear branch
3. No changes suggested by @Ni-san survived in his branch after this force-push. Sorry.

2016-12-17 10:45 UTC, SilverFire commented
Restored changes from `git reflog`, pushed to the master branch: https://github.com/yiisoft/yii2/commit/5795b3937eab3764a79e180f259dbabd6f655dad

2016-12-17 10:45 UTC, SilverFire commented
The PR is merged. Thank yoou