Fix #12791
yiisoft/yii2 pull request #12792
Opened 2016-10-20 15:32 UTC by rmrevin

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12791

2016-10-20 18:25 UTC, cebe requested changes

2016-10-20 18:25 UTC, cebe commented on framework/behaviors/AttributeTypecastBehavior.php
> +    public function reinitAutoDetectedAttributeTypes()
I don't think there is the need to create a public method for this.

2016-10-21 07:14 UTC, cebe commented on framework/behaviors/AttributeTypecastBehavior.php
> +    public function reinitAutoDetectedAttributeTypes()
as far as I see, you can call attach() in the test directly.

2016-10-21 08:13 UTC, rmrevin commented on framework/behaviors/AttributeTypecastBehavior.php
> +    public function reinitAutoDetectedAttributeTypes()
@cebe fixed

2016-10-21 09:53 UTC, klimov-paul commented
Resolved by commit d4df72a2a4d83ce2f4ae4fef4ca252834d6a319b

2016-10-21 09:53 UTC, closed without merging