Remove copy-paste
yiisoft/yii2 pull request #12826
Opened 2016-10-24 14:06 UTC by SG5

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | -

2016-10-24 14:31 UTC, SG5 commented
Does somebody have idea how to get class name resolution in php 5.4?

2016-10-24 14:52 UTC, samdark requested changes

2016-10-24 14:52 UTC, samdark commented on framework/widgets/ActiveField.php
> +            throw new InvalidParamException(Html::class . " doesn't have method $type()");
Won't work with PHP 5.4.

2016-10-24 14:52 UTC, samdark commented on framework/widgets/ActiveField.php
> +        if (!method_exists(Html::class, $type)) {
Won't work with PHP 5.4.

2016-10-24 14:54 UTC, samdark commented on framework/widgets/ActiveField.php
> +        if (!method_exists(Html::class, $type)) {
I'd avoid such check... it's possible to create explicit whitelist here.

2016-10-25 10:06 UTC, dynasource requested changes

2016-10-25 18:26 UTC, samdark requested changes

2016-10-25 18:26 UTC, samdark commented on framework/helpers/BaseFormatConverter.php
> +     * @param $pattern
phpdoc should be properly done.

2016-10-25 18:26 UTC, samdark commented on framework/caching/Cache.php
> +     * @param array $items the items to be cached, as key-value pairs.
Need method description.

2016-10-25 18:26 UTC, samdark commented on framework/caching/Cache.php
> +     * @param Dependency $dependency dependency of the cached items. If the dependency changes,
`If the dependency changes,` then what?

2016-11-13 15:31 UTC, SilverFire commented
@SG5 Would you like to continue work on this PR?

2016-11-25 21:53 UTC, samdark requested changes

2016-11-25 21:53 UTC, samdark commented on framework/caching/Cache.php
> +     * @return array
Need `@since` tag because it's part of API (protected method).

2016-11-25 21:53 UTC, samdark commented on framework/helpers/BaseFormatConverter.php
> +     * @return bool|string
Need `@since` tag.

2016-11-25 21:53 UTC, samdark commented on framework/helpers/BaseFormatConverter.php
> +     * Get patter for ICU date converter
patter → pattern

2016-11-25 21:53 UTC, samdark commented on framework/helpers/BaseFormatConverter.php
> +     * @param $pattern
Need descriptions for parameters

2016-11-25 21:53 UTC, samdark commented on framework/widgets/ActiveField.php
> +     * @return array
Need `@since` tag and description for parameters and return.

2016-11-26 08:58 UTC, dynasource commented
IMO this PR must be split in multiple pull requests. It's covering too many area's. I would like to see 1 fix at a time (so its easy to revert) and to be sure that tests are covering it.

2016-11-26 09:13 UTC, SilverFire commented
Generally the changes are good, but I agree with @dynasource that this PR is complex enough to review

2016-11-28 07:33 UTC, closed without merging