Added ContentRangeHttpException that uses when the requested range is not satisfiable
yiisoft/yii2 pull request #12854
Opened 2016-10-26 23:52 UTC by zalatov

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

It's need to catch this error.
For example, we can't need to log this error.
Now we can do ```try...catch``` or add it to exclude category.

2016-10-27 07:12 UTC, cebe requested changes

2016-10-27 07:12 UTC, cebe commented on framework/web/ContentRangeHttpException.php
> +    public function __construct($status = 416, $message = 'Requested range not satisfiable', $code = 0, \Exception $previous = null)
code should be hardcoded as it is the case with other Http exceptions: https://github.com/yiisoft/yii2/blob/af0119a910b9d6edd81d55d0b9395f27192edb2f/framework/web/NotFoundHttpException.php#L24

2016-10-27 07:12 UTC, cebe commented on framework/web/ContentRangeHttpException.php
> +    public function __construct($status = 416, $message = 'Requested range not satisfiable', $code = 0, \Exception $previous = null)
message should be `null` by default, default message is set by response if not present.

2016-10-27 07:12 UTC, cebe commented on framework/web/ContentRangeHttpException.php
> + */
`@since 2.0.11`

2016-10-27 09:52 UTC, samdark requested changes

2016-10-27 09:52 UTC, samdark commented on framework/CHANGELOG.md
> +- New: Added ContentRangeHttpException that uses when the requested range is not satisfiable (zalatov)
Need `#12854` here.

2016-10-27 09:52 UTC, samdark commented on framework/web/ContentRangeHttpException.php
> +class ContentRangeHttpException extends HttpException
How about renaming it to `InvalidContentRangeException`?

2016-10-27 23:28 UTC, zalatov commented on framework/web/ContentRangeHttpException.php
> +    public function __construct($status = 416, $message = 'Requested range not satisfiable', $code = 0, \Exception $previous = null)
fixed

2016-10-27 23:28 UTC, zalatov commented on framework/web/ContentRangeHttpException.php
> + */
fixed

2016-10-27 23:29 UTC, zalatov commented on framework/CHANGELOG.md
> +- New: Added ContentRangeHttpException that uses when the requested range is not satisfiable (zalatov)
added

I'm add a new section - 2.0.11

2016-10-29 19:01 UTC, samdark requested changes

2016-10-29 19:01 UTC, samdark commented on framework/CHANGELOG.md
> +- Enh #12854: Added `InvalidContentRangeHttpException` that uses when the requested range is not satisfiable (zalatov)
The class name here in changelog and in the actual code is different.

2016-10-31 02:57 UTC, zalatov commented
fixed

2016-10-31 08:45 UTC, dynasource commented
where is the unit test? Can you please add it?

2016-10-31 10:00 UTC, rob006 requested changes

2016-10-31 10:00 UTC, rob006 commented on framework/web/ContentRangeHttpException.php
> +class ContentRangeHttpException extends HttpException
Exception name is inconsistent - all other HttpExceptions uses [status code name](https://github.com/yiisoft/yii2/blob/master/framework/web/Response.php#L163) as exception name, so to this should be named `RangeNotSatisfiableHttpException`.

2016-10-31 10:42 UTC, samdark commented on framework/web/ContentRangeHttpException.php
> +class ContentRangeHttpException extends HttpException
Agree. Thanks for noticing that. @zalatov could you rename it?

2016-11-28 00:08 UTC, zalatov commented
Sorry for so delay...

Fixed - renamed to RangeNotSatisfiableHttpException.

2016-11-28 08:05 UTC, samdark approved these changes

2016-11-28 08:17 UTC, dynasource requested changes

2016-11-28 08:17 UTC, dynasource commented on framework/CHANGELOG.md
> +- Enh #12854: Added `RangeNotSatisfiableHttpException` that uses when the requested range is not satisfiable (zalatov)
->  Added `RangeNotSatisfiableHttpException` to cover 416 file request exceptions

2016-11-28 08:17 UTC, dynasource commented on framework/web/RangeNotSatisfiableHttpException.php
> + * This exception uses when the requested range is not satisfiable.
Please be more clarifying about this error. Its unclear that this is about files. Wikipedia states:
'The client has asked for a portion of the file (byte serving), but the server cannot supply that portion. For example, if the client asked for a part of the file that lies beyond the end of the file.'

2016-11-28 08:17 UTC, dynasource commented on framework/web/Response.php
> +     * @throws RangeNotSatisfiableHttpException if the requested range cannot be satisfied.
please make this line consistent with the other method at line 485

2016-12-01 21:52 UTC, closed without merging

2016-12-01 21:53 UTC, samdark commented
Merged with adjustments suggested. Test is modified to check that correct exception is thrown. Thanks for contribution.