Added braces check for initDefaultButton
yiisoft/yii2 pull request #12863
Opened 2016-10-27 19:50 UTC by edgardmessias

Prevents init default button when the template contains similar names

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12859, #9796

2016-10-27 19:56 UTC, samdark requested changes

2016-10-27 19:56 UTC, samdark commented on tests/framework/grid/ActionColumnTest.php
> +        $column = new ActionColumn(['template' => '{view-itens} {update-itens} {delete-itens}']);
itens → items

2016-10-27 19:56 UTC, samdark commented on tests/framework/grid/ActionColumnTest.php
> +        $column = new ActionColumn(['template' => '{view} {view-itens}']);
itens → items

2016-10-27 20:00 UTC, edgardmessias commented
Fixed

2016-10-27 21:22 UTC, merged

2016-10-27 21:22 UTC, samdark commented
Thanks!

2016-10-28 07:56 UTC, arogachev commented
Good addition :+1: