Fix #12878 refactoring exposing active query get query table name
yiisoft/yii2 pull request #12893
Opened 2016-11-01 20:11 UTC by dynasource

see the descriptions of the different commits.
I also fixed consistency for some other unit tests

2016-11-02 10:43 UTC, samdark approved these changes

2016-11-02 11:15 UTC, klimov-paul requested changes

2016-11-02 11:15 UTC, klimov-paul commented on tests/framework/db/ActiveQueryTest.php
> +    public function testGetQueryTableName_from_not_set()
Why methods are named not in 'camelCase' ?

2016-11-02 11:16 UTC, samdark commented on tests/framework/db/ActiveQueryTest.php
> +    public function testGetQueryTableName_from_not_set()
Yes, should be renamed.

2016-11-02 11:20 UTC, klimov-paul commented
Actually the entire change does not feels right. In the scope of `ActiveQuery` method `getQueryTableName()` seems to be ambiguous: the table name, which query is acciciated to is already covered by `Query::from`.
Originally method `getQueryTableName()` was an internal helper for the query bulding process and thus its presence was OK. But this PR changes it purpose creating a twisted public interface.

If you wish `ActiveQuery` to be able to return a related table name you should convert `from` into a virtual property with getter, which can prefill it by `ActiveRecord::tableName()` if its value is empty.

2016-11-02 11:25 UTC, dynasource commented on tests/framework/db/ActiveQueryTest.php
> +    public function testGetQueryTableName_from_not_set()
for the simple reason that multiple tests for the same method can be easily distinguished

2016-11-02 11:27 UTC, dynasource commented on tests/framework/db/ActiveQueryTest.php
> +    public function testGetQueryTableName_from_not_set()
an alternative could be testGetQueryTableName_fromNotSet(), its a matter of taste and the depth in which you are testing. If you have 20 different test methods with similarities, the underscores help significantly with an easy comparison

2016-11-02 11:27 UTC, klimov-paul commented on tests/framework/db/ActiveQueryTest.php
> +    public function testGetQueryTableName_from_not_set()
Does not sound convincing to me

2016-11-02 11:29 UTC, dynasource commented
I totally disagree. The current implementation shows zero reason for having $query as an argument.

2016-11-02 11:31 UTC, klimov-paul commented
???
So do you think the argument should be removed entirely then?
What about these places:

https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQuery.php#L606
https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQuery.php#L607

2016-11-02 11:31 UTC, samdark commented
Hmm... what @klimov-paul says makes sense. At least problem part of it.

2016-11-02 11:34 UTC, dynasource commented
I dont see a $this inside getQueryTableName(), then it makes no sense to have $query as an argument. Its confusing.

2016-11-02 11:37 UTC, samdark commented
@dynasource see lines @klimov-paul linked to.

2016-11-02 11:37 UTC, samdark requested changes
Seems it won't work this way.

2016-11-02 11:42 UTC, samdark approved these changes
No, that's OK :)

2016-11-02 11:43 UTC, samdark commented
Re-checked. Changes looks OK to me.

2016-11-02 11:43 UTC, dynasource commented on tests/framework/db/ActiveQueryTest.php
> +    public function testGetQueryTableName_from_not_set()
have you every created 20 test methods to test 1 PHP function?

2016-11-02 11:43 UTC, samdark commented
@klimov-paul the places you've referred to are covered.

2016-11-02 11:45 UTC, klimov-paul commented
I will not accept this change unless @cebe agreed on it.

2016-11-02 12:06 UTC, samdark commented
#12878

2016-11-02 12:17 UTC, dynasource commented on tests/framework/db/ActiveQueryTest.php
> +    public function testGetQueryTableName_from_not_set()
for normal framework code, yes. camelCase will do. 
But not if you are testing:
* 1 method:
* on multiple criteria
* in multiple test methods (to keep the smallest contained environment + to have an instant understanding if a test fails)

2016-11-02 12:55 UTC, dynasource commented on tests/framework/db/ActiveQueryTest.php
> +    public function testGetQueryTableName_from_not_set()
https://books.google.nl/books?id=K5dYi2HfAOYC&pg=PA82&lpg=PA82&dq=phpunit+methods+underscore+distinguish&source=bl&ots=L_aiHseLUp&sig=qk_bWtDkN7yk17oDjgeZC_hZ6KU&hl=nl&sa=X&ved=0ahUKEwiModPdjorQAhXKCywKHReLAwoQ6AEIUDAG#v=onepage&q=phpunit%20methods%20underscore%20distinguish&f=false

2016-11-02 13:55 UTC, cebe requested changes
we may turn it into a protected method as it was discussed in #12878 but it should not be public. Public method will add something to the interface that does not belong here. All other methods are for constucting/modifying the Query object. Only this one would be a getter, this creates inconsistency in the interface.

2016-11-02 14:01 UTC, dynasource commented
the function name should also be altered. The current PR still shows the old name 'getQueryTableName' and without $query as an argument, it should at least be named getTableName(). But, regarding all of our conversations, this name is also not preferable. @klimov-paul stated that this method is meant for internal processing. It should get a name that clarifies that.

2016-11-02 14:02 UTC, samdark commented
Agree.

2016-11-02 14:09 UTC, cebe commented
I have reviewed the method now in more detail and I think it should not be added to the public interface, not even protected.

- Its original implementation was to determine table names from `from` part in certain circumstances. This works as expected for the code where it is used now and appropriate checks are made, e.g. in `alias()` ,method. It may not work as expected, when `from` contains multiple tables.
- If we want to provide a new method for retrieving an alias or table name, we get to the same discussion we already have/had in #9326 and #7263.
- there should be a `getAlias()` and/or `getTableName()` method whos implementation may be based on this internal method, but that should be discussed in the issues and addressed separately from the refactoring made here.

additionally to `from`, which is already there

2016-11-02 14:15 UTC, dynasource commented
I agree. Do you have a suggestion for the private method to be newly called?

2016-11-03 17:18 UTC, samdark commented
`getTableNameAndAlias()`?

2016-11-04 08:05 UTC, dynasource commented
'getTableNameAndAlias' is the most logical with respect to the objective of the method. But we should also take the 'temporary processing' aspect into account. Couldnt we add add the '@internal' tag to this method? Based on the PHPdoc specs https://phpdoc.org/docs/latest/references/phpdoc/tags/internal.html, this tag:
* The @internal tag can be used as counterpart of the @api tag, indicating that the associated Structural Elements are used purely for the internal workings of this piece of software.

This would saves us from confusion in the future

2016-11-08 16:15 UTC, cebe commented
a private method is "internal" anyway so there is no need for such a label.

2016-11-08 16:33 UTC, dynasource commented
of course, but it helps emphasizing that it should only be used internally and never be made public. It would have prevented this whole discussion and the issue at https://github.com/yiisoft/yii2/issues/12878

2016-11-08 20:46 UTC, samdark commented
Name should be changed in the rest of the code, it seems...

2016-11-08 21:00 UTC, dynasource commented
good to see my added tests in action ;)

2016-12-08 20:21 UTC, cebe approved these changes

2016-12-08 20:22 UTC, merged

2016-12-08 20:22 UTC, cebe commented
Thank you!