Profile cache time for performance purpose
yiisoft/yii2 pull request #12891
Opened 2016-11-01 18:09 UTC by vitalyzhakov

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12775

2016-11-02 19:01 UTC, vitalyzhakov commented
```* @param mixed $key a key identifying the cached value. This can be a simple string or
     * a complex data structure consisting of factors representing the key.```
@samdark , this function really using mixed argument or strings only?

2016-11-02 22:59 UTC, samdark commented
Yes, mixed is correct. See `buildKey()`.

2016-11-02 23:04 UTC, samdark requested changes

2016-11-02 23:04 UTC, samdark commented on framework/caching/Cache.php
> +        \Yii::beginProfile($key);
`__METHOD__` should be used as a second argument.

2016-11-02 23:04 UTC, samdark commented on framework/caching/Cache.php
> +        \Yii::beginProfile($key);
Need to check how these calls affect production performance. If much, add a check for `YII_DEBUG`.

2016-11-03 16:33 UTC, vitalyzhakov commented
I have changed code and create new PR #12911

2016-11-03 16:33 UTC, closed without merging