fix #4790
yiisoft/yii2 pull request #12898
Opened 2016-11-03 00:16 UTC by Faryshta

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #4790

2016-11-03 14:48 UTC, cebe requested changes
In general, please address only one issue per pull request. It is hard to review general refactoring together with adding a feature. Small changes are okay, but you did a lot of unrelated things here that makes it hard to accept the PR.

2016-11-03 14:48 UTC, cebe commented on framework/data/Sort.php
> +    public $pageParam = 'page';
could be `null` by default, and if set it will be used. this way we can introduce it backwards compatible.

2016-11-03 14:48 UTC, cebe commented on framework/data/Sort.php
> +        return ArrayHelper::getValue($this->getAttributeOrders(), $attribute);
this adds too much overhead, it does not make sense to replace a simple isset() with the complex implementation that `ArrayHelper::getValue()` has.

2016-11-03 14:48 UTC, cebe commented on framework/data/Sort.php
> +            );
:+1:

2016-11-03 14:48 UTC, cebe commented on framework/data/Sort.php
> +        );
I'd prefer original code. it is more readable than nested ternary operators.

2016-11-03 14:48 UTC, cebe commented on framework/data/Sort.php
> +            );
same as above, `ArrayHelper::getValue` is overkill.

2016-11-03 14:48 UTC, cebe commented on framework/data/Sort.php
> +        return ArrayHelper::getValue($this->getAttributeOrders(), $attribute);
It also can break code that uses related attributes, `author.name` will evaluate differently in new and old code.

2016-11-03 16:04 UTC, cebe commented on framework/data/Sort.php
> +    public $pageParam = 'page';
yes, if it is added with default value null, this can go into 2.0.x

2017-04-09 07:26 UTC, Faryshta commented on framework/data/Sort.php
> +    public $pageParam = 'page';
on #4790 this is considered a bug so yes this changes previous behavior because it fixes a bu

2019-04-18 23:27 UTC, closed without merging