Extract default help header of console commands into a separate method.
yiisoft/yii2 pull request #12901
Opened 2016-11-03 04:51 UTC by diezztsk

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | no

I would like to overite  default help header but copy of all source code of getDefaultHelp method is wrong way.

2016-11-03 09:36 UTC, samdark requested changes
Makes sense overall but fixes I've mentioned should be done. Additionally we need a CHANGELOG update.

2016-11-03 09:36 UTC, samdark commented on framework/console/controllers/HelpController.php
> +     * @return string default help header.
Need `@since 2.0.11` here.

2016-11-03 09:36 UTC, samdark commented on framework/console/controllers/HelpController.php
> +     * Display a default help header.
It's not displaying, it's returning.

2016-11-07 03:39 UTC, diezztsk commented on framework/console/controllers/HelpController.php
> +     * @return string default help header.
Fixed.

2016-11-07 09:21 UTC, dynasource approved these changes

2016-11-07 09:57 UTC, samdark approved these changes

2016-11-07 10:26 UTC, merged

2016-11-07 10:26 UTC, samdark commented
Merged. Thank you!