moved & updated test 'testFindScalar' from trait to ActiveRecordTest.…
yiisoft/yii2 pull request #12909
Opened 2016-11-03 14:37 UTC by dynasource

fixes #12897

2016-11-03 15:55 UTC, samdark approved these changes

2016-11-07 13:43 UTC, cebe requested changes

2016-11-07 13:43 UTC, cebe commented on tests/framework/ar/ActiveRecordTestTrait.php
> -
this is not correct, they may be used in non-db AR.

2016-11-07 13:57 UTC, dynasource commented on tests/framework/ar/ActiveRecordTestTrait.php
> -
according to @cebe, 'when the framework and extensions where in one repo that trait was shared between DB AR implementation and other, like Elasticsearch, redis and mongo. When we split the repos out, that was the workaround' more info https://github.com/yiisoft/yii2-redis/blob/master/tests/bootstrap.php#L17-L26

2016-11-08 09:30 UTC, dynasource commented
see https://github.com/yiisoft/yii2/pull/12909#discussion_r86779365

2016-11-08 09:30 UTC, closed without merging