fixes #12905
yiisoft/yii2 pull request #12906
Opened 2016-11-03 12:45 UTC by muayyad-alsadi

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 12905

2016-11-03 12:54 UTC, dynasource commented on framework/web/UrlManager.php
> -    protected $cacheKey = __CLASS__;
this will cause a BC

2016-11-03 12:58 UTC, MysteryDragon commented on framework/web/UrlManager.php
> +        return __CLASS__.'.'. Yii::getAlias('@app');
White spaces missing

2016-11-03 15:16 UTC, muayyad-alsadi commented on framework/web/UrlManager.php
> -    protected $cacheKey = __CLASS__;
@dynasource  first this is protected, second I implemented a getter with same name

2016-11-03 15:30 UTC, samdark requested changes
See comments. Also formatting should be fixed and phpdoc should be in order.

2016-11-03 15:30 UTC, samdark commented on framework/web/UrlManager.php
> -    protected $cacheKey = __CLASS__;
A setter should be there as well.

2016-11-03 15:30 UTC, samdark commented on framework/web/UrlManager.php
> -    protected $cacheKey = __CLASS__;
The property should become private. Getter should return default value as you've proposed if property it's not set explicitly.

2016-11-03 15:46 UTC, muayyad-alsadi commented
@samdark  one of the suggestions is to have a public cacheKeyPrefix that defaults to `__CLASS__` and  no need for any getter as we append `@app` to it. This might not seem backward compatible but it's because it was private/protected.

What do you think?

2016-11-03 15:52 UTC, samdark commented
Not being able to remove `@app` from it sounds bad to me.

2016-11-03 19:52 UTC, muayyad-alsadi commented
is there a way to distinct different routes in different apps other than `@app`.

with current Yii code it's the key is a protected property that you can't change. In the new approach I allow you to change the prefix.

Another approach is to append `$hash` to the prefix, the downside when one changes the route, a redundant stall key will remain.

so `$hash` and `@app` I can't think of any other thing.

Btw I don't like having a setter because the cache is get/set at the initializing of yii app (loading routes) setting it later have no meaningful purpose.

If someone want to change it, he should extend the class.

2016-11-03 19:56 UTC, samdark commented
Yes. A manually set prefix, for example. It's a common case when in backend you're using another instance of URLManager with the frontend rules to link to frontend.

2016-11-03 20:24 UTC, muayyad-alsadi commented
here is the use case that you are talking about,

https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/topic-link-backend-frontend.md

I need to know the `@app` (or whatever that identifies it) of the app for which the url rules belong to.
If we are able to do this, then providing custom prefix is meaning less.

Let me read more to see how to do that.

2016-11-03 20:34 UTC, muayyad-alsadi commented
```
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => require 'urls.php',
        ],
        'urlManagerApp2' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => require 'urls2.php',
            'cachePrefix'=>'app2-urls'
        ],
```

I'm trying to eliminate the need of passing cachePrefix (principle of least astonishment)
I think there is there a way to get the name of the component (`urlManagerApp2`)
So we are left with stressing that cachePrefix should be customized.

2016-11-03 20:41 UTC, samdark commented
Name of the component will be different for frontend app and backend app in this case. Rules will be the same.

2016-11-03 21:43 UTC, muayyad-alsadi commented
in that case I prefer using the hash, but we should have ttl (public configrable ttl) to avoid stall  cache of unused hashes

2016-11-03 22:34 UTC, samdark commented
How about https://github.com/yiisoft/yii2/issues/12905#issuecomment-258259468?

2016-11-05 09:30 UTC, muayyad-alsadi commented
I've replaced this with the suggested approach,

* make cacheKey public
* make it expand using `getAlias`
 
https://github.com/yiisoft/yii2/pull/12926

2016-11-05 19:42 UTC, SilverFire requested changes

2016-11-05 19:42 UTC, SilverFire commented on framework/web/UrlManager.php
> +    protected function getCacheKey() {
`{` should be move to the new line

2016-11-05 19:42 UTC, SilverFire commented on framework/web/UrlManager.php
> +        return __CLASS__.'.'.Yii::getAlias('@app');
`return __CLASS__ . '.' . Yii::getAlias('@app');`

2016-11-05 19:42 UTC, SilverFire commented on framework/web/UrlManager.php
> +
Redundant line

2016-11-05 19:42 UTC, SilverFire commented on framework/web/UrlManager.php
> +     * return class name suffixed with
PHPDoc should be corrected

2016-11-05 19:50 UTC, muayyad-alsadi commented on framework/web/UrlManager.php
> +        return __CLASS__.'.'.Yii::getAlias('@app');
Check my other pr with different approach. There is no need for getters nor setters

2016-11-05 22:50 UTC, samdark commented
This approach isn't good in its inflexibility. Since there's better alternative in for of https://github.com/yiisoft/yii2/pull/12926, I'm closing this one.

2016-11-05 22:50 UTC, closed without merging

2016-11-06 07:07 UTC, SilverFire commented
Agreed. Didn't see #12926 when commented this PR