fxing doc for #7214
yiisoft/yii2 pull request #12922
Opened 2016-11-04 16:19 UTC by dynasource

fixes 7214

2016-11-04 19:40 UTC, samdark requested changes

2016-11-04 19:40 UTC, samdark commented on docs/guide/input-forms.md
> +#### Wrapping with begin() and end()
Should be `###` since it's level 3 header.

2016-11-04 19:40 UTC, samdark commented on docs/guide/input-forms.md
> +#### ActiveField
Should be `###` since it's level 3 header.

2016-11-04 19:40 UTC, samdark commented on docs/guide/input-forms.md
> +We can use ActiveField [dropDownList()](http://www.yiiframework.com/doc-2.0/yii-widgets-activefield.html#dropDownList()-detail)
It's referenced differently. Should be `[[\yii\widgets\ActiveField::dropDownList()]]`.

2016-11-04 19:40 UTC, samdark commented on docs/guide/input-forms.md
> +We can use ActiveField [radioList()](http://www.yiiframework.com/doc-2.0/yii-widgets-activefield.html#radioList()-detail)
It's referenced differently. Should be `[[\yii\widgets\ActiveField::radioList()]]`.

2016-11-04 19:40 UTC, samdark commented on docs/guide/input-forms.md
> +#### Creating a radio list <span id="creating-activeform-dropdownlist"></span>
id is wrong.

2016-11-04 19:40 UTC, samdark commented on docs/guide/input-forms.md
> +#### ActiveField
id missing. Should be `<span id="activefield"></span>`.

2016-11-04 19:40 UTC, samdark commented on docs/guide/input-forms.md
> +#### Wrapping with begin() and end()
ID missing. Should be `<span id="wrapping-with-begin-and-end"></span>`.

2016-11-04 19:40 UTC, samdark commented on docs/guide/input-forms.md
> +#### Creating a checkbox List <span id="creating-activeform-dropdownlist"></span>
ID is wrong.

2016-11-04 19:40 UTC, samdark commented on docs/guide/input-forms.md
> +We can use ActiveField [checkboxList()](http://www.yiiframework.com/doc-2.0/yii-widgets-activefield.html#checkboxList()-detail)
It's referenced differently. Should be `[[\yii\widgets\ActiveField::checkboxList()]]`.

2016-11-05 19:41 UTC, SilverFire requested changes

2016-11-05 19:41 UTC, SilverFire commented on docs/guide/input-forms.md
> +### Wrapping with begin() and end() <span id="wrapping-with-begin-and-end"></span>
`begin()` -> <code>\`begin()\`</code>
`end()` -> <code>\`end()\`</code>

2016-11-05 19:41 UTC, SilverFire commented on docs/guide/input-forms.md
> +Creating Lists <span id="creating-activeform-dropdownlist"></span>
Maybe, id should be changed as well?

2016-11-05 19:41 UTC, SilverFire commented on docs/guide/input-forms.md
> +These $items have to be processed by the different list widgets.
`$items` -> <code>\`$items\`</code>

2016-11-05 19:41 UTC, SilverFire commented on docs/guide/input-forms.md
> +by the current value of the $model's attribute.
`$model's` -> <code>\`$model\`'s</code>

2016-11-05 19:41 UTC, SilverFire commented on docs/guide/input-forms.md
> +#### Creating a drop-down list <span id="creating-activeform-dropdownlist"></span>
Id must be unique

2016-11-05 19:50 UTC, rob006 commented on docs/guide/input-forms.md
> +Creating Lists <span id="creating-activeform-dropdownlist"></span>
Change ID will break all URLs which point to this section.

2016-11-09 09:03 UTC, merged