Primary key for column schema builder
yiisoft/yii2 pull request #12925
Opened 2016-11-05 04:11 UTC by mdmunir

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | -
| Fixed issues  | #11638 #10889

* Introduce more relevant name for auto increment column
```php
[
    'id' => $this->serial(), // instead of $this->primaryKey()
]
```
* Add `primaryKey()` to `ColumnSchemaBuilder`
```php
        $this->createTable($cache->cacheTable, [
            'id' => $this->string(128)->primaryKey(),
            'expire' => $this->integer(),
            'data' => $this->binary(),
        ], $tableOptions);
```

2016-11-05 09:12 UTC, dynasource commented
to add to the conversion:
https://dev.mysql.com/doc/refman/5.5/en/numeric-type-overview.html
'SERIAL is an alias for BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE.'

2016-11-05 09:17 UTC, dynasource requested changes
I am missing some tests for other DBs like postgresql & mssql. Is there a specific reason no to include?

2016-11-05 09:17 UTC, dynasource commented on framework/db/ColumnSchemaBuilder.php
> +        return $this->isPrimary ? ' PRIMARY KEY' : ($this->isUnique ? ' UNIQUE' : '');
could be improved on readability. Switch statement on true.

2016-11-05 09:17 UTC, dynasource commented on framework/db/SchemaBuilderTrait.php
>          return $this->getDb()->getSchema()->createColumnSchemaBuilder(Schema::TYPE_PK, $length);
if you look at mysqls definition for SERIAL (SERIAL is an alias for BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE.), this is a bit confusing and perhabs error prone, using the Schema::TYPE_PK.

2016-11-05 10:27 UTC, mdmunir commented on framework/db/ColumnSchemaBuilder.php
> +        return $this->isPrimary ? ' PRIMARY KEY' : ($this->isUnique ? ' UNIQUE' : '');
ya.. you are right.

2016-11-05 10:27 UTC, mdmunir commented on framework/db/SchemaBuilderTrait.php
>          return $this->getDb()->getSchema()->createColumnSchemaBuilder(Schema::TYPE_PK, $length);
only mysql right? IMO, `serial()` still more make sense than `primaryKey()`.

2016-11-05 11:30 UTC, dynasource commented on framework/db/SchemaBuilderTrait.php
>          return $this->getDb()->getSchema()->createColumnSchemaBuilder(Schema::TYPE_PK, $length);
please elaborate

2016-11-05 17:17 UTC, rob006 commented on framework/db/SchemaBuilderTrait.php
>          return $this->getDb()->getSchema()->createColumnSchemaBuilder(Schema::TYPE_PK, $length);
Why not `autoIncrement()`?

2016-11-05 19:55 UTC, SilverFire requested changes

2016-11-05 19:55 UTC, SilverFire commented on framework/db/ColumnSchemaBuilder.php
> +     * @return $this
`@since`

2016-11-05 19:55 UTC, SilverFire commented on framework/db/SchemaBuilderTrait.php
> +     * @see [[serial()]]
`@since 2.0.6`

2016-11-05 19:55 UTC, SilverFire commented on framework/db/SchemaBuilderTrait.php
> +     * @see [[bigSerial()]]
`@since 2.0.6`

2016-11-05 19:59 UTC, SilverFire commented
I don't like `serial()` much. This name is not self-explanatory and does not reference to the appropriate DBMS concept.

2016-11-05 23:29 UTC, mdmunir commented
> I don't like serial() much

postgre use `serial` as type.

2016-11-12 15:12 UTC, SilverFire commented on framework/db/ColumnSchemaBuilder.php
> +     * @return $this
Resolved

2016-11-12 15:14 UTC, SilverFire requested changes
DOCS update is required

2016-11-12 15:14 UTC, SilverFire commented on framework/db/SchemaBuilderTrait.php
> +     * @deprecated since version 2.0.11
Deprecation does not mean that the method description should be dropped. Could you restore it?

2019-04-24 11:49 UTC, samdark commented
Won't make it into 2.0.

2019-04-24 11:49 UTC, closed without merging