Issue #12938 Add $params to View::renderDynamic()
yiisoft/yii2 pull request #12955
Opened 2016-11-09 11:47 UTC by mikehaertl

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | 
| Fixed issues  | #12938

2016-11-09 11:54 UTC, dynasource requested changes
good addon to the framework. Don't forget the unit tests of course. We want your solution to be perfect now and in the future.

2016-11-09 11:54 UTC, dynasource commented on framework/CHANGELOG.md
> +- Enh #12938: Allow to pass additional parameters to `yii\base\View::renderDynamic()`
please add your name (mikehaertl)

2016-11-09 11:54 UTC, dynasource commented on framework/base/View.php
> +     * @param array $params the parameters (name-value pairs) that will be extracted and made
can you add one of your clear examples in the method doc above?

2016-11-09 11:54 UTC, dynasource commented on framework/base/View.php
> +     * @param array $params the parameters (name-value pairs) that will be extracted and made
shouldnt this be:
* 'and be made'
* 'and be reused'

2016-11-09 11:54 UTC, dynasource commented on framework/base/View.php
> +     * reused each time $statement is executed. You should make sure, that they are safely serializable.
they = these

2016-11-09 12:15 UTC, samdark approved these changes
Overall all is good.

2016-11-09 12:15 UTC, samdark commented on framework/base/View.php
> +            $statements = 'extract(unserialize(\'' . serialize($params) . '\'));'.$statements;
Need spaces around `.` when concatenating.

2016-11-09 12:26 UTC, mikehaertl commented on framework/base/View.php
> +     * @param array $params the parameters (name-value pairs) that will be extracted and made
@dynasource I've copied the sentence from the other `$params`, e.g. from `render()`. There's no `be` there either.

2016-11-09 12:30 UTC, samdark commented
How about a unit test so it's set in stone and never broken?

2016-11-09 12:33 UTC, mikehaertl commented
Regarding the unit tests: There are no tests for `renderDynamic()` yet, at least I couldn't find any. I'm not a real expert on writing framework tests, so I will not find time to write a new test from scratch. Even more as this is a non-trivial task here that involves a complex setup including cache etc.

2016-11-09 12:36 UTC, dynasource commented
no problem. Ill add these later.

2016-11-09 12:37 UTC, dynasource approved these changes

2016-11-09 13:28 UTC, rob006 commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
Why not typehint `$params` as array?

2016-11-09 13:32 UTC, mikehaertl commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
I found it easier to check `$params === null` than `count($params) === 0`. But I don't really mind to change this. We should also use `@param array|null ...` in the comment block if we keep `null`.

2016-11-09 13:36 UTC, rob006 commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
With

```php 
public function renderDynamic($statements, array $params = null)
```

you could use `$params !== []` or just `!empty($params)`.

2016-11-09 13:44 UTC, mikehaertl commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
@dynasource Any preferences? Should I change it?

2016-11-09 13:46 UTC, rob006 commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
I fixed my example.

2016-11-09 13:50 UTC, dynasource commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
Im working on the tests now (encountering some problems with testing eval()). Will include the array hinting, so you're allowed to take a break ;)

2016-11-09 15:04 UTC, samdark approved these changes

2016-11-09 15:09 UTC, rob006 requested changes
This change should be noted in `UPGRADE.md`.

2016-11-09 15:28 UTC, merged

2016-11-09 15:29 UTC, dynasource commented
thanks to you all!

2016-11-09 22:05 UTC, samdark commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
@mikehaertl `$array !== []` with array type hinting is preferred.

2016-11-09 22:19 UTC, rob006 commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
@samdark Why? `empty()` is faster than `=== []` and IMO more readable.

2016-11-09 22:21 UTC, dynasource commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
although the performance differences are minor, empty is indeed more readable

2016-11-09 22:38 UTC, samdark commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
@rob006 is it faster?

2016-11-09 22:42 UTC, samdark commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
Indeed it is. Let's use it then.

2016-11-10 07:16 UTC, mikehaertl commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
@rob006 @samdark Any references? And is this only for empty arrays? For many years now we've seen `===` as the fastest way to compare e.g. for `null` or empty strings. It's still used in many places all over the framework. Did this change?

2016-11-10 08:26 UTC, samdark commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
I've made a test for `empty($array)` and `$array !== []` for both empty and non-empty arrays at https://3v4l.org/.

2016-11-10 08:31 UTC, dynasource commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
yeah, did the same for `isset()` vs `===` a week ago. Therefore I prefer isset() from now. Faster and more readable

2016-11-10 08:39 UTC, mikehaertl commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
@samdark @dynasource Hmm, I'd vote against that. Unless there's a reliable "official" source that `isset` and `empty` are really always faster, why suddenly change what was considered best practice over all the years? It's like a convention in the Yii framework to always use `===` whenever applicable.

I also don't agree that `isset()` is more readable than `===null`. It's not even the same thing. `isset()` also works for undefined variables. Something you don't always want.

So before changing this convention lightheartedly we should really ask, if this is really neccessary. "If it ain't broken - don't fix it!".

2016-11-10 08:50 UTC, dynasource commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
* https://3v4l.org/ can show you the prove. You can try it yourself. @samdark, where your full url :).
* isset() is more readable. You read from left to right. Isset() shows immediately whats going on, compared to `===` which can be a equation to anything
* 'It's not even the same thing': agree, which shows you, you have to use it when it is appropiate

2016-11-10 09:15 UTC, samdark commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
@mikehaertl it's not suddenly. Actually [it's in our code style](https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md#--vs-empty) for quite a while...

2016-11-10 09:21 UTC, mikehaertl commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
@samdark If it's only about arrays I'm fine. It wasn't me who brought up the `isset()` topic ;).

Still the `===null` vs `isset()` convention should also be part of the coding style guide.

2016-11-10 09:21 UTC, dynasource commented on framework/base/View.php
> +    public function renderDynamic($statements, $params = null)
:)

2019-05-14 15:03 UTC, srnden commented
I would like to see this change in 2.0.*

2019-05-14 15:07 UTC, samdark commented
It won't be merged since 2.0.x doesn't accept features from last year.