Added bash completion file for ./yii commands
yiisoft/yii2 pull request #12959
Opened 2016-11-09 21:35 UTC by cebe

| Q             | A
| ------------- | ---
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | none included
| Fixed issues  | #475

This allows to auto-complete commands available by the `./yii`
executable on the bash by expanding the first argument with the TAB key.
E.g. Typing `./yii [TAB]` will list all commands. `./yii mig[TAB]` will
auto-complete to `./yii migrate` and tab after that will list all
migration sub-commands(actions).

fixes #475

2016-11-10 15:35 UTC, SilverFire requested changes

2016-11-10 15:35 UTC, SilverFire commented on framework/yii.bash-completion
> +# This file implements bash completion for the ./yii command file.
`#!/bin/bash`

2016-11-10 15:35 UTC, SilverFire commented on framework/yii.bash-completion
> +# Temporarily you can source this file in you bash by typing: . yii.bash-completion
I'd prefer `source yii.bash-completion` instead of `. yii.bash-completion` as it is more readable and less confusing.

2016-11-10 15:35 UTC, SilverFire commented on framework/yii.bash-completion
> +# For permanent availability, copy or link this file to /etc/bash_completion.d/
Maybe it's better to put it to `/usr/share/bash-completion/completions`?

2016-11-10 15:35 UTC, SilverFire commented on docs/guide/tutorial-console.md
> +    . yii.bash-completion
I'd prefer source yii.bash-completion instead of . yii.bash-completion as it is more readable and less confusing.

2016-11-10 15:35 UTC, SilverFire commented on docs/guide/tutorial-console.md
> +Note the dot on the beginning of that line. It means you want to include the definitions give in the `yii.bash-completion` file in
And then this line could be removed

2016-11-10 15:35 UTC, SilverFire commented
Will try to do the same for ZSH

2016-11-10 19:48 UTC, cebe commented on framework/yii.bash-completion
> +# This file implements bash completion for the ./yii command file.
no, this file should not be executed as a script but only be sourced.

2016-11-10 19:49 UTC, cebe commented on framework/yii.bash-completion
> +# For permanent availability, copy or link this file to /etc/bash_completion.d/
`/usr/` is for software installed by the package mangager. `/etc/` is the place for custom files like this one.

2016-11-10 21:30 UTC, SilverFire commented on framework/yii.bash-completion
> +# This file implements bash completion for the ./yii command file.
Ok

2016-11-10 21:31 UTC, SilverFire commented on framework/yii.bash-completion
> +# For permanent availability, copy or link this file to /etc/bash_completion.d/
Right.

2016-11-26 22:14 UTC, dynasource approved these changes

2016-11-27 08:47 UTC, SilverFire requested changes
I don't like that completion file is located in the `/framework` directory because it is not a part of framework. I suggest to put in somewhere in `/contrib` or similar

2016-11-27 11:10 UTC, dynasource commented
> I don't like that completion file is located in the /framework directory because it is not a part of framework. I suggest to put in somewhere in /contrib or similar

sharply noticed. I would expect a separate folder indeed.

2016-11-27 11:29 UTC, cebe commented
Well, it belongs to `./yii` so I but it next to it. and it should be inside of the framework to ship with it. How about putting it into /console folder?

2016-11-27 13:13 UTC, SilverFire commented
Take a look how docker-compose solved this task: https://docs.docker.com/compose/completion/

2016-11-27 15:57 UTC, cebe commented
You mean to put it somewhere in yiisoft/yii2 repo and use curl in the docs to fetch it?

2016-11-28 09:46 UTC, SilverFire commented
@cebe exactly

2016-11-28 14:17 UTC, SilverFire commented
![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/4499203/20671495/37c9d730-b586-11e6-80b1-ccf8d3154ae5.gif)

2016-11-28 14:20 UTC, SilverFire approved these changes

2016-11-28 14:24 UTC, cebe reviewed
let me add the options to bash too.

2016-11-28 14:24 UTC, cebe commented on framework/CHANGELOG.md
> +- Enh #475: Added basic bash completion support for the `./yii` command (cebe)
@SilverFire add your name here and add zsh ;)

2016-11-28 15:04 UTC, samdark commented
It behaves a bit weird to me when there's no `./yii` in current dir and I'm typing `./yii` and then `TAB`. It prints out ` ./yii bash: ./yii: No such file or directory`, then waits for `ENTER` to be pressed, then prints `bash: ./yii: No such file or directory`.

2016-11-28 15:06 UTC, samdark commented
Doesn't seem to be working under MINGW64 bash. Script properly calls `help/list` command but then I'm getting nothing back after delay.

2016-11-28 20:21 UTC, cebe commented
> It behaves a bit weird to me when there's no ./yii in current dir

good catch, will fix that.

2016-12-02 23:42 UTC, cebe commented
added argument completion to bash. also fixed the issue with `./yii` not existing. This PR is ready to review and merge.

2016-12-03 00:25 UTC, merged