Migrations order fix
yiisoft/yii2 pull request #12975
Opened 2016-11-11 22:13 UTC by evgen-d

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12974

2016-11-12 07:50 UTC, TerraSkye commented
Wouldnt a uksort be better? Instead of creating a temp array?

2016-11-12 11:48 UTC, SilverFire requested changes
Good in general. Some change should be applied before the merge though.

2016-11-12 11:48 UTC, SilverFire commented on framework/console/controllers/MigrateController.php
>          unset($history[self::BASE_MIGRATION]);
`$history[self::BASE_MIGRATION]` is no longer a valid key. See [this](https://github.com/yiisoft/yii2/pull/12975/files#diff-952bc7045bade5b9e9c44621c5f93c19R210)

2016-11-12 11:48 UTC, SilverFire commented on framework/console/controllers/MigrateController.php
> +            if (preg_match('/m?(\d{6}_?\d{6})(\D.*)?$/is', $row['version'], $matches)) {
Add here

```php
if ($row['version'] === self::BASE_MIGRATION) {
    continue;
}
```

2016-11-12 11:48 UTC, SilverFire commented on framework/console/controllers/MigrateController.php
> +            if ($a == $b) {
`===` should be used

2016-11-12 11:48 UTC, SilverFire commented on framework/console/controllers/MigrateController.php
> +                return ($a > $b) ? -1 : 1;
use http://php.net/manual/ru/function.strcasecmp.php instead

2016-11-12 11:48 UTC, SilverFire commented on framework/console/controllers/MigrateController.php
> +       if ($this->db->schema->getTableSchema($this->migrationTable, true) === null) {
Gimme back that space! :hocho:

2016-11-12 12:06 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +       if ($this->db->schema->getTableSchema($this->migrationTable, true) === null) {
?

2016-11-12 12:33 UTC, evgen-d commented
@SilverFire all done

2016-11-12 14:17 UTC, samdark commented
@evgen-d tests are failing: https://travis-ci.org/yiisoft/yii2/jobs/175302999

2016-11-12 14:41 UTC, SilverFire requested changes

2016-11-12 14:41 UTC, SilverFire commented on framework/console/controllers/MigrateController.php
> +            } elseif (preg_match('/m?(\d{6}_?\d{6})(\D.*)?$/is', $row['version'], $matches)) {
`elseif` does not make sense. If previous condition is true, `continue` will go to next iteration of `foreach`

2016-11-12 15:24 UTC, evgen-d commented
This PR fix some problem with `migrate/down all`, but i think that `version` and `namespase` must be on different columns of DB table.
This order `orderBy('apply_time DESC, version DESC')` is wrong, and may return wrong history when you call `migrate/down [N]`

2016-11-12 16:18 UTC, merged

2016-11-12 16:18 UTC, SilverFire commented
Thank you

2016-11-14 11:12 UTC, klimov-paul commented
General note to the @yiisoft/core-developers : please use 'squash and merge' button instead of simple 'merge' whlie merging PR. This prevents GIT log to hold redundant commits.