Disable serialization by default for ArrayCache for increased performance
yiisoft/yii2 pull request #12984
Opened 2016-11-12 22:34 UTC by rhertogh

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | -

I would expect the ArrayCache to be optimized for speed since it's only used during a single requests, but the serialization is turned on by default which has a major performance impact (see test below).
Turning the serialization off might brake backwards compatibilty due to the check in the yii/caching/Cache class: ```if ($dependency !== null && $this->serializer !== false) {```

Test results:
unserialized: 9.3 ms
serialized: 3391.6 ms

Test data: two dimensional array (100x100)

Test run: 100 x 1 write, 10 reads

Test:

```
$data = array_fill(0, 100, array_fill(0, 100, rand(0, 10000)));

Yii::$app->arrayCache->serializer = false;
Yii::beginProfile('cacheTest-unserialized');
for ($i = 1; $i <= 100; $i++) {
    Yii::$app->arrayCache->set("cacheTest-unserialized-$i", $data);
    for ($j = 1; $j <= 10; $j++) {
        Yii::$app->arrayCache->get("cacheTest-unserialized-$i");
    }
}
Yii::endProfile('cacheTest-unserialized');

Yii::$app->arrayCache->serializer = null;
Yii::beginProfile('cacheTest-serialized');
for ($i = 1; $i <= 100; $i++) {
    Yii::$app->arrayCache->set("cacheTest-serialized-$i", $data);
    for ($j = 1; $j <= 10; $j++) {
        Yii::$app->arrayCache->get("cacheTest-serialized-$i");
    }
}
Yii::endProfile('cacheTest-serialized');
```

2016-11-13 08:11 UTC, SilverFire commented
Makes sense. Voting for.

2016-11-13 08:13 UTC, SilverFire requested changes
Change should be mentioned in `CHANGELOG.md` and `UPGRADE.md`

2016-11-13 08:13 UTC, SilverFire commented on framework/caching/ArrayCache.php
> +     * Serialization is disabled by default for ArrayCache for increased performance
`ArrayCache` -> `[[ArrayCache]]`

2016-11-13 08:13 UTC, SilverFire commented on framework/caching/ArrayCache.php
> +     * @var null|array|false The functions used to serialize and unserialize cached data.
This line should be replaced with `@inheritdoc`

2016-11-13 08:13 UTC, SilverFire commented on framework/caching/ArrayCache.php
> +     * @see Cache::serializer
Line could be removed

2016-11-13 10:29 UTC, dynasource commented
agree. Optimal performance should be the default.

2016-11-13 20:16 UTC, samdark commented on framework/UPGRADE.md
> +* The `serializer` property for `yii\caching\ArrayCache` has been changed form `null` to `false`, this disables serialization
Sounds like total backwards compatibility break to me...

2016-11-13 20:18 UTC, SilverFire commented on framework/UPGRADE.md
> +* The `serializer` property for `yii\caching\ArrayCache` has been changed form `null` to `false`, this disables serialization
It's only for ArrayCache. All other types of caches will not be affected

2016-11-13 20:20 UTC, samdark commented on framework/UPGRADE.md
> +* The `serializer` property for `yii\caching\ArrayCache` has been changed form `null` to `false`, this disables serialization
Yes but still ArrayCache won't work in many cases anymore.

2016-11-13 21:47 UTC, cebe commented
No need to break anything here. This can be added as a note in the class PHPdoc and can be enabled if needed. ArrayCache has very rare use cases anyway.

2016-12-15 22:56 UTC, samdark commented
I'm against merging this change. It makes default behavior very inconsistent. Instead, I'd mention it in either performance guide or the ArrayCache class itself.

2016-12-15 23:26 UTC, closed without merging

2016-12-15 23:27 UTC, cebe commented
I have added a note to the class docs. performance improvement is not an acceptable reason for BC breaks. Thanks for your contribution, @rhertogh!