Adds ability for the user to choose if they want to double encode entities within textareas or not when using ActiveForm. Applies enhancement from #12988.
yiisoft/yii2 pull request #12994
Opened 2016-11-14 09:00 UTC by cyphix333

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12988

2016-11-14 09:30 UTC, samdark requested changes
Need a changelog and a unit test.

2016-11-14 16:59 UTC, SilverFire requested changes

2016-11-14 16:59 UTC, SilverFire commented on framework/helpers/BaseHtml.php
> +        $doubleEncode = (isset($options['doubleEncode'])) ? $options['doubleEncode'] : true;
All these lines could be replaced with one:

```php
ArrayHelper::remove($options, 'doubleEncode', true);
```

2016-11-14 17:54 UTC, cyphix333 commented on framework/helpers/BaseHtml.php
> +        $doubleEncode = (isset($options['doubleEncode'])) ? $options['doubleEncode'] : true;
Ahh nice, haven't used `ArrayHelper` enough to know you could do that. I have made the changes locally.

2016-11-14 18:40 UTC, rob006 commented on framework/helpers/BaseHtml.php
> +     * - `doubleEncode`: whether to encode HTML entities in `$value`. If false, HTML entities in `$value` will not
`false` should be wrapped by `` ` ``

2016-11-18 14:36 UTC, cyphix333 commented
Sorry for the delay in getting the revised version up but I am having some problems getting phpunit working, will finalize this as soon as I solve the issues.

2016-11-20 11:47 UTC, cyphix333 commented
Ran a unit test on the `helpers` group and there was a failure that was unrelated to the changes I did, line `958` of `helpers/HtmlTest.php`.

2016-11-20 12:08 UTC, dynasource requested changes
need unit tests

2016-11-20 12:08 UTC, dynasource commented on framework/helpers/BaseHtml.php
> +        // Get value of `doubleEncode` option and then remove it from the array as it is not
can this be done in 1 line to make it less obtrusive?

2016-11-20 12:08 UTC, dynasource commented on framework/helpers/BaseHtml.php
> +     * - `doubleEncode`: whether to encode HTML entities in `$value`. If `false`, HTML entities in `$value` will not
the naming `doubleEncode` does not align with the definition.

2016-11-20 13:22 UTC, cyphix333 commented on framework/helpers/BaseHtml.php
> +     * - `doubleEncode`: whether to encode HTML entities in `$value`. If `false`, HTML entities in `$value` will not
How so? It's actually a copy straight from the `encode` method and seems to say what it does perfectly.

2016-11-20 13:24 UTC, cyphix333 commented on framework/helpers/BaseHtml.php
> +        // Get value of `doubleEncode` option and then remove it from the array as it is not
If you're referencing the comment then I think more _readable_ code/comments is far better than something slightly obtrusive.

2016-11-20 13:43 UTC, dynasource commented on framework/helpers/BaseHtml.php
> +     * - `doubleEncode`: whether to encode HTML entities in `$value`. If `false`, HTML entities in `$value` will not
the word 'double' is not explained

2016-11-20 13:45 UTC, dynasource commented on framework/helpers/BaseHtml.php
> +        // Get value of `doubleEncode` option and then remove it from the array as it is not
if you can't explain it in 1 line, you don't understand it well enough.

2016-11-20 13:52 UTC, cyphix333 commented on framework/helpers/BaseHtml.php
> +     * - `doubleEncode`: whether to encode HTML entities in `$value`. If `false`, HTML entities in `$value` will not
Does it need to be as it references `HTML entities` which means they are already encoded.

2016-11-20 13:54 UTC, cyphix333 commented on framework/helpers/BaseHtml.php
> +        // Get value of `doubleEncode` option and then remove it from the array as it is not
Well feel free to re-word it as you like, but I understand it fine :)

2016-11-20 13:56 UTC, dynasource commented on framework/helpers/BaseHtml.php
> +     * - `doubleEncode`: whether to encode HTML entities in `$value`. If `false`, HTML entities in `$value` will not
of course. You are using the word 'double' so people are looking for that word in the definition. Why is it `doubleEncode` and not just named `encode`

2016-11-20 14:05 UTC, dynasource commented on framework/helpers/BaseHtml.php
> +        // Get value of `doubleEncode` option and then remove it from the array as it is not
could be more declarative instead of imperative

2016-11-20 14:10 UTC, dynasource commented on framework/helpers/BaseHtml.php
> +     * - `doubleEncode`: whether to encode HTML entities in `$value`. If `false`, HTML entities in `$value` will not
you don't have to answer that to me ;) It's what developers are questioning if they see the parameter 'doubleEncode'

2016-11-20 14:19 UTC, cyphix333 commented on framework/helpers/BaseHtml.php
> +        // Get value of `doubleEncode` option and then remove it from the array as it is not
Updated - hopefully this is to your liking better.

2016-11-20 14:20 UTC, cyphix333 commented on framework/helpers/BaseHtml.php
> +     * - `doubleEncode`: whether to encode HTML entities in `$value`. If `false`, HTML entities in `$value` will not
I was just following the standard way it is done. :)

2016-11-20 15:00 UTC, dynasource approved these changes

2016-11-22 09:26 UTC, dynasource requested changes
don't forget about the unit tests

2016-11-22 10:17 UTC, cyphix333 commented
@dynasource I have already done unit tests, please see my [previous post](https://github.com/yiisoft/yii2/pull/12994#issuecomment-261773453).

2016-11-22 10:19 UTC, dynasource commented
you have to add them to cover your usecase (so we don't loose you solution in future commits)

2016-11-22 10:28 UTC, cyphix333 commented
@dynasource Sorry I haven't used phpunit before and was unsure what you wanted. I have attached the output of the test.

[unit-test.txt](https://github.com/yiisoft/yii2/files/606065/unit-test.txt)

2016-11-26 16:31 UTC, cyphix333 commented
@dynasource Did you need anything else from me?

2016-11-26 16:56 UTC, dynasource commented
@cyphix333, Brett, we have to have unit tests (like https://github.com/yiisoft/yii2/pull/13079/files#diff-e4de87b687b5c876d6209e73ed20863eR97) in order for PR's to accept (and to stay stable in the future)

2016-11-27 00:24 UTC, cebe approved these changes

2016-11-27 00:24 UTC, cebe commented on framework/helpers/BaseHtml.php
> +     * be further encoded.
Please add `This option is available since version 2.0.11.`

2016-11-28 22:08 UTC, SilverFire commented
Merged with minor adjustments: 7f46ab33
Thank you

2016-11-28 22:08 UTC, closed without merging