Allow resetting dependency registered as singleton
yiisoft/yii2 pull request #13002
Opened 2016-11-14 21:44 UTC by dmitrivereshchagin

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

If `null` passed to `yii\di\Container::setSingleton()` as dependency definition, next call to `yii\di\Container::get()` will generate new instance of dependency.

2016-11-14 21:56 UTC, dynasource commented
can you elaborate on your usecase?

2016-11-14 22:14 UTC, dmitrivereshchagin commented
I simply want to implement `Doctrine\Common\Persistence\ManagerRegistry` interface using `yii\di\Container` to store DBAL connections and entity managers. These changes might be useful to implement `Doctrine\Common\Persistence\ManagerRegistry::resetManager()` for example.

2016-11-14 22:18 UTC, cebe commented on framework/di/Container.php
> +            $this->_singletons[$class] = null;
as far as I see there is no need for the elseif and `$this->_singletons[$class] = null;` can be performed in any case.

2016-11-14 22:23 UTC, dmitrivereshchagin commented on framework/di/Container.php
> +            $this->_singletons[$class] = null;
I think there is no need to create `$class` key when there is no dependency registered.

2016-11-15 08:41 UTC, SilverFire commented
Could you add a unit test for this PR?

2016-11-15 09:04 UTC, dynasource commented
I see that you've replaced a lot of tests. Could you move these improments in a separate PR please.

2016-12-17 08:18 UTC, dmitrivereshchagin commented
@SilverFire test for proposed behavior is already here 🙂

2016-12-17 08:21 UTC, dmitrivereshchagin commented
@dynasource unnecessary changes in assertions removed.

2016-12-17 09:36 UTC, dynasource requested changes

2016-12-17 09:36 UTC, dynasource commented on tests/framework/di/ContainerTest.php
> +    public function testSingleton()
should be testSetSingleton

2016-12-17 09:36 UTC, dynasource commented on tests/framework/di/ContainerTest.php
> +        $qux2 = $container->get($QuxInterface);
please separate groups of assertions with line breaks.

2016-12-17 09:36 UTC, dynasource commented on framework/di/Container.php
> +        } elseif (isset($this->_singletons[$class])) {
this should be combined with the previous comparison to make it more readable. Are you sure this change of logic is not a BC break?

2016-12-17 09:52 UTC, dmitrivereshchagin commented on tests/framework/di/ContainerTest.php
> +    public function testSingleton()
Fixed

2016-12-17 09:52 UTC, dmitrivereshchagin commented on tests/framework/di/ContainerTest.php
> +        $qux2 = $container->get($QuxInterface);
Fixed

2016-12-17 10:12 UTC, dmitrivereshchagin commented on framework/di/Container.php
> +        } elseif (isset($this->_singletons[$class])) {
Please see my reply to @cebe. There is no BC break. I have added some checks for `hasSingleton()` to be sure.

2016-12-17 10:20 UTC, dynasource commented on framework/di/Container.php
> +        } elseif (isset($this->_singletons[$class])) {
can you combine the comparisons?

2016-12-17 10:34 UTC, dmitrivereshchagin commented on framework/di/Container.php
> +        } elseif (isset($this->_singletons[$class])) {
No. Null assignment should take place only in two cases:

* normal singleton configuration
* resetting singleton (singleton is configured *and* `null` passed as an argument)

2016-12-17 10:38 UTC, dynasource commented on framework/di/Container.php
> +        } elseif (isset($this->_singletons[$class])) {
so this is not correct?:

```php
if($definition === null && isset($this->_singletons[$class]){

}else{

}

```

2016-12-17 10:44 UTC, dmitrivereshchagin commented on framework/di/Container.php
> +        } elseif (isset($this->_singletons[$class])) {
It will set a key in `$this->_singletons` in any case and break `hasSingleton()`.

2016-12-17 12:30 UTC, dmitrivereshchagin commented
It may be better to implement proposed behavior as a separate method. We can call it `resetSingleton()` and put in container class.
```php
public function resetSingleton($class)
{
    if (!array_key_exists($class, $this->_singletons) {
        throw new InvalidConfigException();
    }

    $this->_singletons[$class] = null;

    return $this;
}
```
Besides of that such method can be implemented (slightly less efficiently) in subclass.
```php
public function resetSingleton($class)
{
    if (!$this->hasSingleton($class)) {
        throw new InvalidConfigurationException();
    }

    $definitionitions = $this->getDefinitions();
    $this->setSingleton($class, $definitions[$class]);

    return $this;
}
```

2016-12-17 12:43 UTC, dynasource commented
separate method is better. What's the use of the exception? Can you just reset the value if it exists.

2016-12-17 12:57 UTC, dmitrivereshchagin commented
It could point out an error in application configuration or usage of obsolete service.

2016-12-17 14:53 UTC, dmitrivereshchagin commented
There is no way to introduce this feature without breaking BC. In the case when dependency and its definition are the same object singleton cannot be reset in reliable way.

2016-12-17 14:53 UTC, closed without merging