Closes #11163: Added separate method for client-side validation options in `yii\validators\Validator`
yiisoft/yii2 pull request #13014
Opened 2016-11-16 07:43 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #11163

2016-11-16 11:15 UTC, samdark approved these changes

2016-11-29 07:56 UTC, arogachev commented
Should I add something else?

2016-11-29 08:08 UTC, SilverFire requested changes

2016-11-29 08:08 UTC, SilverFire commented on framework/validators/Validator.php
> +     * @param \yii\base\Model $model the model being validated
I suggest to add the following lines:

```
This method is usually called from [[clientValidateAttribute()]].
You may override this method to modify options that will be passed to the client-side validation.
```

2016-11-29 08:08 UTC, SilverFire commented
Maybe we should PHPDoc for `clientValidateAttribute` as well? For example (spelling could be enhanced):

```
Calls [[getClientOptions()]] to generate options array for client-side validation.
...
@see getClientOptions()
```

2016-11-29 08:24 UTC, arogachev commented
@SilverFire Yes, I thought about that. Will update it soon.

2016-12-02 11:57 UTC, arogachev commented
Updated PHPDoc, please check.

2016-12-02 20:15 UTC, SilverFire approved these changes

2016-12-02 20:35 UTC, dynasource requested changes
is there a reason to have getClientOptions() to be public? From what I've seen in the code and read in the descriptions, it seems more logical to make it protected.  

For the rest this PR looks OK.

2016-12-02 20:39 UTC, SilverFire commented
Makes sence

2016-12-04 08:15 UTC, arogachev commented
@dynasource Yes, you are right. Fixed it.

2016-12-05 07:55 UTC, dynasource approved these changes

2016-12-05 20:32 UTC, SilverFire approved these changes

2016-12-05 20:34 UTC, SilverFire commented
https://github.com/yiisoft/yii2/commit/cdaf5c86efe5a92159aabc44e36f42251d1c0d4c

2016-12-05 20:35 UTC, SilverFire commented
Merged. Thank you for a great PR

2016-12-05 20:35 UTC, closed without merging

2016-12-05 20:49 UTC, nkovacs commented
Why is `getClientOptions()` protected?

It should be public so that a custom implementation of `ActiveField` can bypass `clientValidateAttribute` completely. That was the point of #11163.

(Side note: I was subscribed to #11163, but I didn't receive a notification of this pull request, because you only referenced the issue. I only got an email when the commit closed the issue, after the merge. Please comment on the issue next time, so that people watching it get a notification email.)

2016-12-05 21:45 UTC, cebe commented
@nkovacs I have reopened #11163, lets discuss the details there.