Provide options for the span element.
yiisoft/yii2 pull request #13020
Opened 2016-11-16 16:32 UTC by nadar

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no

It should be possibile to provide optional classes for the disable state list item. 

(As we are currently building all widgets for bootstrap 4, the pagination element looks different, there for we need more options to configure)

2016-11-17 08:22 UTC, SilverFire requested changes
Could you add a line to Changelog and update unit tests?

2016-11-17 08:22 UTC, SilverFire commented on framework/widgets/LinkPager.php
> +    public $disabledSpanOptions = [];
Maybe it's better to rename this property to `disabledPaseElementOptions` to be consistent with `disabledPageCssClass` and `activePageCssClass` property?

2016-11-17 08:22 UTC, SilverFire commented on framework/widgets/LinkPager.php
> +            return Html::tag('li', Html::tag('span', $label, $this->disabledSpanOptions), $options);
It makes sense to make tag name customizable as it's done [here](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L1225), for example

2016-11-17 09:21 UTC, SilverFire requested changes

2016-11-17 09:21 UTC, SilverFire commented on framework/widgets/LinkPager.php
> +     * @var array An array with options to pass to the disabled tag which is generated inside the disabled list element.
Special option `tag` must be mentioned

2016-11-17 09:21 UTC, SilverFire commented on framework/widgets/LinkPager.php
> +            return Html::tag('li', Html::tag($tag, $label, $this->disabledPageElementOptions), $options);
Empty line before the `return` statement is required according to code style agreement

2016-11-17 09:21 UTC, SilverFire commented on tests/framework/widgets/LinkPagerTest.php
> +    	$pagination = new Pagination();
Code align in tests should be fixed

2016-11-17 10:34 UTC, SilverFire approved these changes

2016-11-17 10:44 UTC, samdark requested changes

2016-11-17 10:44 UTC, samdark commented on framework/widgets/LinkPager.php
> +    public $disabledPageElementOptions = [];
Need `@since` tag.

2016-11-17 12:29 UTC, samdark approved these changes

2016-11-17 12:43 UTC, dynasource requested changes

2016-11-17 12:43 UTC, dynasource commented on framework/widgets/LinkPager.php
> +     * @var array An array with options to pass to the disabled tag which is generated inside the disabled list element.
More consistent:
 @var array An array with  ...->  @var array the options for the disabled tag to be generated inside ...

2016-11-17 12:43 UTC, dynasource commented on framework/widgets/LinkPager.php
> +     * In order to to customize the tag name itself use the array key `tag` and value for its tag name value.
In order to to customize the tag name itself use the array key `tag` and value for its tag name value.
->
In order to customize the html tag, please use the `tag` key.

2016-11-17 12:43 UTC, dynasource commented on framework/widgets/LinkPager.php
> +    public $disabledPageElementOptions = [];
pageElement....isn't this rather vague? I have a hard time imagining what a 'disabledPageElement' is...

2016-11-17 12:43 UTC, dynasource commented on tests/framework/widgets/LinkPagerTest.php
> +        $pagination->setPage(0);
it it possible to remove these methods and to pass these as an options array?

2016-11-17 12:48 UTC, nadar commented on framework/widgets/LinkPager.php
> +    public $disabledPageElementOptions = [];
It was suggested by @SilverFire. But its also hard to imagine what the other properties stand for.

2016-11-17 12:49 UTC, nadar commented on tests/framework/widgets/LinkPagerTest.php
> +        $pagination->setPage(0);
I just copied from the previous existing test.

2016-11-17 13:00 UTC, dynasource approved these changes

2016-11-17 13:01 UTC, dynasource commented on tests/framework/widgets/LinkPagerTest.php
> +        $pagination->setPage(0);
alright, consistent then.

2016-11-17 13:03 UTC, dynasource requested changes
I still don't like this $property name:
$disabledPageElementOptions 

It should properly inform me about what it is. Now I'm still wondering.

2016-11-17 14:44 UTC, nadar commented
@dynasource Well, do you have a better idea?

2016-11-17 14:48 UTC, samdark commented
`$disabledPageButtonOptions`?

2016-11-17 15:12 UTC, dynasource commented
> @dynasource Well, do you have a better idea?

Well, lets start by looking at your own intro text:
"It should be possibile to provide optional classes for the disable state list item."

This is understandable.

So I would expect something like a $disabledListItemOptions or $disabledListItemSpanOptions

2016-11-17 15:16 UTC, nadar commented
Sounds good to. Infact its not the list element, its the element inside the list element. And if the tag name can be changed it should not contain the name "Span" (as i mentioned first as well).

2016-11-17 15:20 UTC, dynasource commented
`$disabledListItemSubTagOptions`

2016-11-17 15:21 UTC, dynasource commented
of course this is long and should be prevented, but it is always better than a tag name that nobody understands

2016-11-18 08:26 UTC, SilverFire commented
> `$disabledPageButtonOptions`?

No, it's not button options.

> Infact its not the list element, its the element inside the list element. And if the tag name can be changed it should not contain the name "Span" (as i mentioned first as well).

Right.

> `$disabledListItemSubTagOptions`

Looks complex enough

2016-11-22 08:58 UTC, nadar commented
So `$disabledListItemSubTagOptions` is suitable for everyone? Then i am going to change it.

2016-11-22 09:06 UTC, samdark commented
Yes, it's better than the current name. Not ideal but certainly better.

2016-11-22 11:14 UTC, dynasource approved these changes

2016-11-22 16:15 UTC, dynasource commented
merged in https://github.com/yiisoft/yii2/commit/aba42fce4dcfdd7c3b9dd97f4d3c9eed9101bdf4, thanks!

2016-11-22 16:15 UTC, closed without merging