Sluggablebehavior: use ArrayHelper::getValue for slugParts[]
yiisoft/yii2 pull request #13035
Opened 2016-11-17 14:08 UTC by thyseus

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

Use yii\helpers\ArrayHelper::getValue() to determine the slugParts[] in the SluggableBehavior. This allows to use:

```php
[
    'class' => SluggableBehavior::className(),
    'attribute' => 'offer.title',
]
```

instead of/in addition to:

```php
 public function behaviors()
    {
        return [
                [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
                ]
        ];
}

public function getTitle()
{
    return $this->offer->title;
}
```

2016-11-17 14:18 UTC, samdark requested changes
Overall makes sense but some adjustments required. Additionally, unit tests are needed.

2016-11-17 14:18 UTC, samdark commented on framework/CHANGELOG.md
> +- Enh: Use ArrayHelper::getValue in SluggableBehavior (thyseus)
Need issue `#` here. If there's no issue existing for it, use pull request number i.e. `Enh #13035`.

2016-11-17 14:18 UTC, samdark commented on framework/behaviors/SluggableBehavior.php
> +     * @var boolean whether to generate a new slug if it has already been generated before.
This is wrong change. Should be `bool` because `boolean` can't be used as return type in PHP 7+.

2016-11-17 14:18 UTC, samdark commented on framework/behaviors/SluggableBehavior.php
> +     * @var boolean whether to ensure generated slug value to be unique among owner class records.
This is wrong change. Should be `bool` because `boolean` can't be used as return type in PHP 7+.

2016-11-17 14:18 UTC, samdark commented on framework/behaviors/SluggableBehavior.php
> +     * @return boolean
This is wrong change. Should be `bool` because `boolean` can't be used as return type in PHP 7+.

2016-11-17 14:18 UTC, samdark commented on framework/behaviors/SluggableBehavior.php
> +     * @return boolean whether slug is unique.
This is wrong change. Should be `bool` because `boolean` can't be used as return type in PHP 7+.

2016-11-17 14:18 UTC, samdark commented on framework/behaviors/SluggableBehavior.php
> +     * @param integer $iteration iteration number
This is wrong change. Should be `int` because `integer` can't be used as return type in PHP 7+.

2016-11-17 17:03 UTC, thyseus commented on framework/behaviors/SluggableBehavior.php
> +     * @param integer $iteration iteration number
Thanks! These comment adjustments have been made automatically by Phpstorm when using the autoformatter. Will revert them and add unit tests tomorrow.

2016-11-17 17:04 UTC, thyseus commented
Thanks! These comment adjustments have been made automatically by Phpstorm when using the autoformatter. Will revert them and add unit tests tomorrow.

2016-11-18 10:07 UTC, thyseus commented
@samdark commit is cleaned up and unit test is added. Please re-evaluate if this PR can be merged, thank you.

2016-11-18 10:59 UTC, dynasource approved these changes

2016-11-18 10:59 UTC, dynasource commented on framework/CHANGELOG.md
> +- Enh #13035: Use ArrayHelper::getValue() in SluggableBehavior::getValue() (thyseus)
this could be more descriptive with an explanation for this enhancement

2016-11-18 10:59 UTC, dynasource commented on tests/framework/behaviors/SluggableBehaviorTest.php
> +    public function testSlugRelatedAttribute()
well done

2016-11-22 09:12 UTC, samdark approved these changes

2016-11-22 10:07 UTC, cebe approved these changes

2016-11-22 10:20 UTC, merged

2016-11-22 10:20 UTC, samdark commented
Thanks!