Add support for creating protocol-relative URLs
yiisoft/yii2 pull request #13067
Opened 2016-11-24 13:31 UTC by rob006

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12738

2016-11-24 13:36 UTC, samdark commented
What do you think about using `//` instead of empty string?

2016-11-24 13:43 UTC, rob006 commented
I think that empty string is more intuitive. `https` means that schema is `https`, empty string means that there is no schema.

2016-11-24 14:51 UTC, samdark approved these changes
Looks good to me except parameter empty value. I have no better proposals than `//` so won't object on having empty string.

2016-11-28 14:53 UTC, SilverFire approved these changes

2016-11-28 21:58 UTC, cebe requested changes
good changes! only some minor improvements needed.

2016-11-28 21:58 UTC, cebe commented on framework/helpers/BaseUrl.php
> +     * - string: generating an absolute URL with the specified scheme (either `http`, `https` or empty string).
maybe add a hint `or empty string, for protocol relative URL`? it is not directly obvious why one would pass an empty string here, also searching for "yii protocol relative url" would find this text better than now.

2016-11-28 21:58 UTC, cebe commented on framework/helpers/BaseUrl.php
> +            } elseif (is_string($scheme)) {
is_string check is not needed here, it is already checked in line 245

2016-11-28 21:58 UTC, cebe commented on framework/helpers/BaseUrl.php
> +     * - string: returning an absolute URL with the specified scheme (either `http`, `https` or empty string).
same here.

2016-11-28 21:58 UTC, cebe commented on framework/helpers/BaseUrl.php
> +     * - string: generating an absolute URL with the specified scheme (either `http`, `https` or empty string).
and here :)

2016-11-28 21:58 UTC, cebe commented on framework/web/UrlManager.php
> +     * @param string|null $scheme the scheme to use for the URL (either `http`, `https` or empty string).
and here :)

2016-11-28 21:58 UTC, cebe commented
I like using empty string for no scheme.

2016-11-28 23:07 UTC, cebe approved these changes

2016-11-29 07:55 UTC, closed without merging