Fixes #13071: Help option for commands was not working in modules
yiisoft/yii2 pull request #13079
Opened 2016-11-26 12:21 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13071

2016-11-26 15:37 UTC, arogachev commented
@dynasource There were no tests for #12028. Added unit tests to cover both #12028 and #13079 issues.

2016-11-26 18:43 UTC, samdark requested changes
The change itself is correct. I'd like to ask to extract 2nd class in the test to its own file. Otherwise, it's good.

2016-11-26 18:43 UTC, samdark commented on tests/framework/console/ControllerTest.php
> +class FakeHelpController extends HelpController
It's better to extract this class into separate file...

2016-11-26 19:10 UTC, arogachev commented on tests/framework/console/ControllerTest.php
> +class FakeHelpController extends HelpController
OK. I'll do this tomorrow.

2016-11-26 20:46 UTC, cebe approved these changes

2016-11-26 21:28 UTC, dynasource requested changes
thumbs up for the unit tests!

2016-11-26 21:28 UTC, dynasource commented on tests/framework/console/ControllerTest.php
> +        $controller = new FakeController('posts', Yii::$app);
here you are starting a new 'test' setting. To have it perfectly self contained, you should add this to a separate test method. The test will also easier to understand.

2016-11-26 21:28 UTC, dynasource commented on tests/framework/console/ControllerTest.php
> +        $controller = new FakeController('posts', new Module('news'));
same here. New test method with a nice name stating what is being tested.

2016-11-27 11:08 UTC, dynasource approved these changes
well done

2016-11-27 11:31 UTC, cebe approved these changes

2016-11-27 12:57 UTC, dynasource commented on tests/framework/console/ControllerTest.php
> +        $controller = new FakeController('posts', Yii::$app);
'crucial'....it depends on which hat you put on. From the consistency & readability & stability perspective, it is a better practice.

2016-11-27 13:13 UTC, samdark approved these changes

2016-11-27 13:14 UTC, merged

2016-11-27 13:14 UTC, samdark commented
Merged. Thank you!