Update examples for events using interfaces
yiisoft/yii2 pull request #13070
Opened 2016-11-25 08:00 UTC by sizeg

Where was a mistake in example for events using interfaces. As events has no method [[className()]] and when called [[Event::trigger()]] we should pass first argument class name implemented this interface, not the interface itself.

2016-11-25 09:20 UTC, cebe requested changes

2016-11-25 09:20 UTC, cebe commented on docs/guide/concept-events.md
> +Event::on(DanceEventInterface::class, DanceEventInterface::EVENT_DANCE, function ($event) {
`::class` does not work on php 5.4 so it should not be used in 2.0.x docs.

2016-11-25 10:28 UTC, samdark commented
It should pass interface name, I think. W/o using `::className()`, of course.

2016-11-25 10:40 UTC, sizeg commented
> It should pass interface name

@samdark then it will conflict with the next paragrath
```php
// DOES NOT WORK
Event::trigger('DanceEventInterface', DanceEventInterface::EVENT_DANCE); // error
```

2016-11-25 10:43 UTC, sizeg commented
We should pass to [[Event::trigger()]] a fully qualified class name implemented our event interface. By the way I'm using it this way.

According to the previouse examples from doc, were two new objects created from Component, we can use [[className()]] I think.

2016-11-25 21:50 UTC, samdark commented
@cebe need your assistance in this one...

2016-11-26 09:15 UTC, dynasource approved these changes
these updates are correct

2016-11-26 10:20 UTC, SilverFire commented
Resolved by f1f357b

2016-11-26 10:20 UTC, closed without merging

2016-11-26 10:20 UTC, SilverFire commented
@sizeg thank you for noticing