Select only primary keys in UniqueValidator (#10896)
yiisoft/yii2 pull request #13098
Opened 2016-11-30 18:07 UTC by developeruz

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #10896

Select only primary key when counting records.
Selected results are used only in these lines
```php 
$n = count($models);
...
reset($models)->getPrimaryKey()
```

2016-11-30 18:44 UTC, samdark requested changes
Looks good to me. Need changelog for 2.0.11.

2016-11-30 18:44 UTC, samdark commented
@dynasource it's already covered by existing tests.

2016-11-30 18:46 UTC, dynasource commented
if that was the case, this PR wouldnt be necessary?

2016-11-30 18:58 UTC, samdark commented
Yes. It is about performance optimization only. It is not changing behavior and not fixing any issues.

2016-11-30 19:24 UTC, dynasource commented
My fault. Had to expand the code to see it.

2016-12-01 04:04 UTC, developeruz commented
Changelog was added. 
Btw, a current version of the validateAttribute function is too long to be fully covered with unit test. May I refactor it and push as other PR with additional tests? Or should I do it in this PR, because of the code climate?

2016-12-01 08:20 UTC, samdark commented
Separate PR would be much better. This one is good as is.

2016-12-01 08:22 UTC, samdark requested changes

2016-12-01 08:22 UTC, samdark commented on framework/CHANGELOG.md
> +- Enh: #10896 Select only primary key when counting records in UniqueValidator
Usually we write github handles right after i.e.:

```
Enh #10896: Select only primary key when counting records in `yii\validators\UniqueValidator` (developeruz)
```

2016-12-01 08:40 UTC, cebe approved these changes

2016-12-01 08:40 UTC, cebe commented on framework/CHANGELOG.md
> +- Enh: #10896 Select only primary key when counting records in UniqueValidator
your name is missing at the end of the line :) Also it would be good to order items in changelog by issue number. This avoids merge problems.

2016-12-01 08:43 UTC, cebe commented on framework/CHANGELOG.md
> +- Enh: #10896 Select only primary key when counting records in UniqueValidator
somehow this github review thing is buggy, did not see alex comment before writing this :-/

2016-12-01 09:11 UTC, samdark approved these changes

2016-12-01 09:17 UTC, dynasource approved these changes

2016-12-01 09:45 UTC, merged

2016-12-01 09:46 UTC, cebe commented
Thank you!

2017-01-27 22:17 UTC, samdark commented
Had to revert it: https://github.com/yiisoft/yii2/commit/bede9feba5b39169381d7af3c48ae89753fbe9e5