Organizes frontpage
yiisoft/yii2 pull request #13115
Opened 2016-12-01 21:55 UTC by dynasource

Containes frontpage improvements:
- before it was a bit unorganized
- it lacked installation instructions
- the important badges are now placed in the title
- links are structured in tables
- uninformative / unnecessary parts are removed

2016-12-01 22:14 UTC, samdark requested changes

2016-12-01 22:14 UTC, samdark commented on README.md
> +We strive to embrace all the best practices applied in modern Web application development.
I'd remove "all" because it's not true :) We're skipping some for the sake of API...

2016-12-01 22:14 UTC, samdark commented on README.md
> +**Composer**
Bold should not be used for headers.

2016-12-01 22:14 UTC, samdark commented on README.md
> +With [Composer](https://getcomposer.org/) installed, you can install Yii by running the following commands under a Web-accessible folder:
"If you have Composer, you can install" because of "installed ... install" sounds repetitive.

2016-12-01 22:14 UTC, samdark commented on README.md
> +With [Composer](https://getcomposer.org/) installed, you can install Yii by running the following commands under a Web-accessible folder:
There's no need to run it under web accessible folder. In contrary, doing that would result in application files right under webroot which is not what we should encourage.

2016-12-01 22:14 UTC, samdark commented on README.md
> +Your participation to Yii 2 development is very welcome! There are many area's in which you can help us
"participation in"?

2016-12-01 22:14 UTC, samdark commented on README.md
> +Your participation to Yii 2 development is very welcome! There are many area's in which you can help us
"area's" → "areas"

2016-12-01 22:14 UTC, samdark commented on README.md
> +improve our framework:
our framework → the framework?

2016-12-01 22:14 UTC, samdark commented on README.md
> +| Type  | Resource |
Should it be a table? It looks like a list to me. Header and type aren't really helpful.

2016-12-01 22:14 UTC, samdark commented on README.md
> +| Type  | Online | PDF |
Should it be a table? List looks more suitable here.

2016-12-01 22:29 UTC, cebe requested changes

2016-12-01 22:29 UTC, cebe commented on README.md
> +Yii2 requires `PHP 5.4`.
I would also add something like "Yii2 requires at least PHP version 5.4. I also runs fine on newer version like 7.x."
State the minimum requirement but don't sound old/outdated.

2016-12-01 22:29 UTC, cebe commented on README.md
> +| Guide |  http://www.yiiframework.com/doc-2.0/guide-index.html | http://stuff.cebe.cc/yii2-guide.en.pdf |
~~the guide has a mirror too.~~

2016-12-01 22:29 UTC, cebe commented on README.md
> +| Guide |  http://www.yiiframework.com/doc-2.0/guide-index.html | http://stuff.cebe.cc/yii2-guide.en.pdf |
actually there is no point in mentioning the mirror anymore. It should go down as soon as the new site is there and yiiframework.com is updated once a day anyway.

2016-12-01 22:29 UTC, cebe commented on README.md
> +| Type  | Resource |
yeah, a two column table does not really make sense. list is better.

2016-12-01 22:33 UTC, cebe commented on README.md
> +| Guide |  http://www.yiiframework.com/doc-2.0/guide-index.html | http://stuff.cebe.cc/yii2-guide.en.pdf |
Also for the PDF it is better to link to <http://yiiframework.domain-na.me/doc/download/yii-guide-2.0-en.pdf> which is part of the new website and regenerated more frequently.
We could also link to the translated versions:

- es: http://yiiframework.domain-na.me/doc/download/yii-guide-2.0-es.pdf
- fr: http://yiiframework.domain-na.me/doc/download/yii-guide-2.0-fr.pdf
- pl: http://yiiframework.domain-na.me/doc/download/yii-guide-2.0-pl.pdf
- pt-BR: http://yiiframework.domain-na.me/doc/download/yii-guide-2.0-pt-br.pdf
- ru: http://yiiframework.domain-na.me/doc/download/yii-guide-2.0-ru.pdf

2016-12-02 20:06 UTC, samdark commented on README.md
> +With [Composer](https://getcomposer.org/) installed, you can install Yii by running the following commands under a Web-accessible folder:
Then it's wrong there as well.

2017-07-29 12:10 UTC, samdark commented
These suggestions were already applied to readme.

2017-07-29 12:10 UTC, closed without merging