Simplified code branching, named variable better
yiisoft/yii2 pull request #13113
Opened 2016-12-01 15:45 UTC by samdark

Mainly to test Codeclimate but it makes code a bit more readable as well.

2016-12-01 20:31 UTC, cebe approved these changes
For easier review: https://github.com/yiisoft/yii2/pull/13113/files?w=0 (ignoring whitespace changes)

2016-12-02 07:04 UTC, SilverFire commented on framework/base/Component.php
> -                }
This change looks wrong. `return` statement is missing in this condition

2016-12-02 07:05 UTC, SilverFire commented on framework/base/Component.php
>          if ($handler === null) {
We leave empty line before return statement or not?

2016-12-02 07:06 UTC, SilverFire commented on framework/BaseYii.php
> -        } else {
We leave empty line before return statement or not?

2016-12-02 07:08 UTC, SilverFire requested changes

2016-12-02 07:08 UTC, SilverFire commented on framework/BaseYii.php
> +        return false;
We leave empty line before return statement or not?

2016-12-02 07:08 UTC, SilverFire commented on framework/base/Controller.php
> +        return Yii::$app->runAction(ltrim($route, '/'), $params);
We leave empty line before return statement or not?

2016-12-02 07:08 UTC, SilverFire commented on framework/base/Event.php
> +        return $removed;
We leave empty line before return statement or not?

2016-12-02 09:58 UTC, samdark commented on framework/BaseYii.php
> +        return false;
We don't have agreement on that as far as I remember. In these cases it depends on if it's a separate logical return block or not.

2016-12-02 10:57 UTC, dynasource commented on framework/base/Event.php
> +        return $removed;
rather not. Don't see the use of it as there is already an empty line because of the bracket

2016-12-02 12:22 UTC, SilverFire approved these changes

2016-12-02 16:20 UTC, cebe commented on framework/BaseYii.php
> +        return false;
we did not do that but at the point where PSR2 was changing from tabs to spaces, these lines were introduced for some reason. In most cases I do not think adding a blank line makes sense.

2016-12-02 20:49 UTC, dynasource approved these changes
the changes look OK. The line breaks are inconsistent though.

2016-12-02 21:15 UTC, merged