#13128: Fixed incorrect position of {pos} string in ColumnSchemaBuilder __toString
yiisoft/yii2 pull request #13129
Opened 2016-12-03 21:07 UTC by df2

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | unknown
| Fixed issues  | #13128

2016-12-08 14:56 UTC, df2 commented
Can this please be merged into master?

2016-12-08 15:38 UTC, dynasource commented
if the append string is not inserted at last, its not really an append string anymore right ;)

2016-12-08 22:20 UTC, cebe commented
Yeah but still it makes sense to change it because DBMS syntax is this way. It may be useful to point that out in the docs though.

2016-12-09 08:06 UTC, dynasource commented
does this "append" typology match any mysql typology or is it chosen by us. Tried to find a clarifying reference.

2016-12-09 11:52 UTC, df2 commented
Basically `append` is used to append to the column definition. The position indicator should always be last in the SQL statement.

MySql: http://dev.mysql.com/doc/refman/5.7/en/alter-table.html

```
| CHANGE [COLUMN] old_col_name new_col_name column_definition
      [FIRST|AFTER col_name]
```

Cubrid: http://www.cubrid.org/manual/91/en/sql/schema/table.html#change-modify-clauses

```
    CHANGE [COLUMN | CLASS ATTRIBUTE ] old_col_name new_col_name column_definition
             [FIRST | AFTER col_name]
  | MODIFY [COLUMN | CLASS ATTRIBUTE] col_name column_definition
             [FIRST | AFTER col_name]
```

Oracle: It seems it was a mistake to allow the position option. I have removed it from the oci `__toString`.

2016-12-09 12:06 UTC, df2 commented
Not sure why these tests are failing... help much appreciated.

2016-12-09 13:57 UTC, samdark commented
Tests are not failing, it's codeclimate, not travis.

2016-12-09 14:00 UTC, samdark requested changes

2016-12-09 14:00 UTC, samdark commented on tests/framework/db/QueryBuilderTest.php
> +                Schema::TYPE_PK . " FIRST",
Should it be special for Oracle which doesn't support it?

2016-12-09 15:04 UTC, df2 commented on tests/framework/db/QueryBuilderTest.php
> +                Schema::TYPE_PK . " FIRST",
Hmm, I think then with Oracle, adding a position modifier will have no effect, and thus the tests are correct. It is the same as Postgres in that respect.

2016-12-09 15:06 UTC, samdark commented on tests/framework/db/QueryBuilderTest.php
> +                Schema::TYPE_PK . " FIRST",
OK.

2016-12-09 15:07 UTC, samdark approved these changes

2016-12-10 20:07 UTC, SilverFire approved these changes

2016-12-11 13:55 UTC, cebe approved these changes

2016-12-11 20:36 UTC, merged

2016-12-11 20:36 UTC, samdark commented
Merged. Thank you!