Fix docs about table prefixes
yiisoft/yii2 pull request #13127
Opened 2016-12-03 11:35 UTC by dynasource

fixes #8354 by adding docs about prefixes to the mentioned areas

2016-12-03 11:42 UTC, samdark approved these changes

2016-12-03 11:50 UTC, SilverFire requested changes

2016-12-03 11:50 UTC, SilverFire commented on docs/guide/db-active-record.md
> +By default each Active Record class is associated with it's database table,
`it's` -> `its`

2016-12-03 11:50 UTC, SilverFire commented on docs/guide/db-active-record.md
> +[[yii\db\ActiveRecord::tableName()|tableName()]] returns the class name as the table name by calling [[Inflector::camel2id()]].
`[[yii\db\ActiveRecord::tableName()|tableName()]] returns` -> `[[yii\db\ActiveRecord::tableName()|tableName()]] method returns`

2016-12-03 11:50 UTC, SilverFire commented on docs/guide/db-active-record.md
> +[[yii\db\ActiveRecord::tableName()|tableName()]] returns the class name as the table name by calling [[Inflector::camel2id()]].
Namespace for `[[Inflector]]` is missing

2016-12-03 12:09 UTC, SilverFire approved these changes

2016-12-03 17:07 UTC, cebe commented on docs/guide/db-query-builder.md
> +For example, `{{%post}}` becomes `{{tbl_post}}`.
This is already covered in `db-dao.md`. http://www.yiiframework.com/doc-2.0/guide-db-dao.html#quoting-table-and-column-names

2016-12-03 17:08 UTC, cebe commented
I have added a commit with some improvements. Also table prefix in query guide seems duplicate, it should link to http://www.yiiframework.com/doc-2.0/guide-db-dao.html#quoting-table-and-column-names instead.

2016-12-05 11:51 UTC, cebe approved these changes

2016-12-05 12:57 UTC, merged