Logging url rules
yiisoft/yii2 pull request #13134
Opened 2016-12-04 19:09 UTC by bashkarev

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | https://github.com/yiisoft/yii2-debug/issues/173

2016-12-05 11:38 UTC, cebe commented on framework/web/UrlManager.php
> +                    ], Logger::LEVEL_PROFILE, __METHOD__);
why `LEVEL_PROFILE` and not `LEVEL_TRACE`?

2016-12-05 11:42 UTC, bashkarev commented on framework/web/UrlManager.php
> +                    ], Logger::LEVEL_PROFILE, __METHOD__);
to exclude in Log panel

2016-12-05 15:15 UTC, samdark requested changes

2016-12-05 15:15 UTC, samdark commented on framework/web/UrlManager.php
> +                    ], Logger::LEVEL_PROFILE, __METHOD__);
Can't we exclude it by class/method name?

2016-12-05 16:48 UTC, bashkarev commented on framework/web/UrlManager.php
> +                    ], Logger::LEVEL_PROFILE, __METHOD__);
fixed

2016-12-05 16:50 UTC, samdark approved these changes
Except of missing issue number in changelog it looks fine to me.

2016-12-05 16:50 UTC, samdark commented on framework/CHANGELOG.md
> +- Enh: Added Logging url rules (bashkarev)
Need `#13134` here

2016-12-05 18:15 UTC, cebe commented
The good looks good so far but I wonder whether we might want to log the whole route object (or a serialization of it) to be able to display all relevant configurations in the debug panel. E.g. RestUrlRules or GroupUrlRule contain a lot more information that could be relevant in debug panel.

2016-12-05 18:15 UTC, cebe commented on framework/web/UrlRule.php
> +     */
`@since 2.0.11`

2016-12-05 18:16 UTC, cebe commented
Form a progress point of view it would also be good to develop the debug panel in the framework changes together to make adjustments here when new aspects show up on toolbar side and merge them both after everything is finished.

2016-12-05 20:38 UTC, SilverFire approved these changes
Except minor comments by @cebe

2016-12-05 21:15 UTC, bashkarev commented
![2016-12-06_00-13-52](https://cloud.githubusercontent.com/assets/3738201/20902626/f55d4d00-bb48-11e6-983a-9ba47bc4193f.png)
![2016-12-05_23-59-12](https://cloud.githubusercontent.com/assets/3738201/20902625/f5559592-bb48-11e6-8f09-5556824c4699.png)
??

2017-01-22 20:27 UTC, SilverFire commented
> The good looks good so far but I wonder whether we might want to log the whole route object

The idea is good, but, probably, this amount of data could be too much for the debug file.

I think the PR should be accepted as is. Any objection @yiisoft/core-developers?

2017-01-22 20:37 UTC, samdark commented
No objections from me.

2017-01-27 16:03 UTC, merged

2017-01-27 16:03 UTC, samdark commented
Merged. Thanks!