Fix protocol-relative URLs in `Url::to()` (#13156)
yiisoft/yii2 pull request #13157
Opened 2016-12-07 19:15 UTC by rob006

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13156

Fix #13156.

2016-12-07 19:17 UTC, rob006 commented on framework/helpers/BaseUrl.php
> +        ) {
Any idea why we're not using `static::isRelative()` here?

2016-12-10 18:54 UTC, SilverFire requested changes

2016-12-10 18:54 UTC, SilverFire commented on framework/helpers/BaseUrl.php
> +        ) {
Because `isRelative()` method was added after this line. You can use it

2016-12-10 20:30 UTC, samdark requested changes
Please add changelog.

2016-12-10 21:34 UTC, rob006 commented on framework/helpers/BaseUrl.php
> +        ) {
Done.

2016-12-10 21:36 UTC, rob006 commented
@samdark This bug is not released, it is related to #13067.

2016-12-10 22:45 UTC, samdark approved these changes

2016-12-11 14:14 UTC, cebe approved these changes

2016-12-11 18:39 UTC, SilverFire approved these changes

2016-12-11 18:39 UTC, merged

2016-12-11 18:39 UTC, SilverFire commented
Thank you!~