Load MySQL comments into TableSchema
yiisoft/yii2 pull request #13162
Opened 2016-12-08 09:57 UTC by michaelarnauts

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13154

2016-12-09 10:59 UTC, samdark requested changes

2016-12-09 10:59 UTC, samdark commented on framework/db/TableSchema.php
> +     * @var string the comment that has been assigned to this table.
Need `@since 2.0.12`.

2016-12-09 10:59 UTC, samdark commented on framework/db/mysql/Schema.php
> +     * @param TableSchema $table the table metadata object
Need `@since 2.0.12`.

2016-12-09 10:59 UTC, samdark commented on framework/db/mysql/Schema.php
> +     * @param TableSchema $table the table metadata object
How about other database engines?

2016-12-09 21:32 UTC, michaelarnauts commented
I've added the `@since 2.0.12` to the phpdoc.

2016-12-09 21:35 UTC, samdark commented
Great. We can't really release it for MySQL only so will see if we'll have enough time to implement all other DB engines support before 2.0.12...

2016-12-09 21:46 UTC, michaelarnauts commented
* `mssql` uses a strange way to store comments, by using "extended properties", not sure if this is considered a standard practice to do so (http://stackoverflow.com/questions/378700/is-it-possible-to-add-a-description-comment-to-a-table-in-microsoft-sql-2000)
* `postgres` seems to provide a decent way to do this (http://stackoverflow.com/questions/5664094/getting-list-of-table-comments-in-postgresql)

I'm not sure about other databases.

2016-12-09 22:57 UTC, samdark commented
Oracle: http://stackoverflow.com/questions/16567129/how-to-get-table-comments-via-sql-in-oracle

2016-12-09 22:58 UTC, samdark commented
SQLite seems not to support comments at all.

2019-04-23 21:21 UTC, samdark commented
Won't make it into 2.0.

2019-04-23 21:21 UTC, closed without merging

2019-04-23 21:21 UTC, samdark commented
https://github.com/yiisoft/yii2/pull/13162