saveAs with alias
yiisoft/yii2 pull request #13176
Opened 2016-12-09 08:38 UTC by DrDeath72

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

2016-12-09 09:48 UTC, dynasource requested changes
looks useful
- please add a test for it

2018-01-13 15:11 UTC, developeruz commented
@dynasource, we don't have a test for `saveAs` method because it is quite difficult to test uploaded files in a unit test without real request. Test for this PR already exists because all you need is to test that `Yii::getAlias()` works as expected.

2018-01-13 17:28 UTC, samdark approved these changes

2018-01-27 17:45 UTC, rob006 commented
This was already rejected: https://github.com/yiisoft/yii2/issues/7462#issuecomment-76290267

I don't think we should merge this. If someone needs to use alias, he could just pass `Yii::getAlias()` result to `saveAs()`.

See also https://github.com/yiisoft/yii2/blob/master/docs/internals/design-decisions.md

2018-01-27 17:45 UTC, closed without merging