Refactor validateAttribute method in UniqueValidator
yiisoft/yii2 pull request #13202
Opened 2016-12-13 18:32 UTC by developeruz

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

Extract prepareParams and prepareQuery from validateAttribute, so they can be tested separately.

2016-12-13 18:59 UTC, dynasource requested changes
looks good. Well done. Few requests.

2016-12-13 18:59 UTC, dynasource commented on framework/validators/UniqueValidator.php
> +    private function exists($targetClass, $params, $model)
could be useful to have a naming more unique to prevent collisions in the ancestor tree. A private method "Exists" is risky in general.

2016-12-13 18:59 UTC, dynasource commented on framework/validators/UniqueValidator.php
> +     * @since 2.0.11
this method is not new correct? Doesnt need @since?

2016-12-13 18:59 UTC, dynasource commented on framework/validators/UniqueValidator.php
> +     */
does need since

2016-12-13 18:59 UTC, dynasource commented on framework/validators/UniqueValidator.php
> +     */
@since?

2016-12-13 18:59 UTC, dynasource commented on framework/validators/UniqueValidator.php
> +     * Apply filters and prepare a query
Other way around to be more consistent with the method naming: "Prepares a query by applying filters"

2016-12-13 18:59 UTC, dynasource commented on framework/validators/UniqueValidator.php
> +     * Prepare params according to various syntax
"according to various syntax" is a bit vague ;). Can be more specific.

2016-12-13 21:45 UTC, samdark submitted a review, later dismissed

2016-12-14 21:47 UTC, dynasource submitted a review, later dismissed

2016-12-15 06:55 UTC, mdomba approved these changes

2016-12-15 08:47 UTC, SilverFire requested changes
PHPDocs should be adjusted. Working on this right now, do not merge

2016-12-15 09:39 UTC, SilverFire approved these changes

2016-12-15 11:15 UTC, dynasource approved these changes

2016-12-15 11:23 UTC, merged

2016-12-15 11:23 UTC, dynasource commented
thanks!