Xml formatter root and object tags
yiisoft/yii2 pull request #13214
Opened 2016-12-15 21:28 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12419

2016-12-15 23:16 UTC, cebe requested changes

2016-12-15 23:16 UTC, cebe commented on framework/web/XmlResponseFormatter.php
> +     * @var string the name of the root element or null if no root tag should be added.
in Html helper we use false for no tag. In general we could also allow it to be empty(). as `<>` would not be a valid xml tag anyway.

2016-12-15 23:16 UTC, cebe commented on framework/web/XmlResponseFormatter.php
> +     * @since 2.0.10
2.0.11.

2016-12-15 23:42 UTC, cebe approved these changes

2016-12-18 10:48 UTC, SilverFire approved these changes

2016-12-26 15:28 UTC, merged

2016-12-26 15:31 UTC, klimov-paul commented on framework/web/XmlResponseFormatter.php
> +    public $objectTags = true;
`objectTags` does not sound appropriate for a boolean field.
Possible names could be:
- `createObjectTags`
- `useObjectTags`
- `addObjectTags`

2016-12-26 15:35 UTC, samdark commented on framework/web/XmlResponseFormatter.php
> +    public $objectTags = true;
Yes. `useObjectTags` sounds better...