Query filter having
yiisoft/yii2 pull request #13210
Opened 2016-12-14 20:59 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #11697

2016-12-14 21:08 UTC, SilverFire approved these changes

2016-12-14 21:17 UTC, cebe approved these changes

2016-12-14 21:40 UTC, dynasource requested changes

2016-12-14 21:40 UTC, dynasource commented on tests/framework/db/QueryTest.php
> +        $query->andFilterHaving(['not in', 'id', []]);
this one is the same as the previous. If thats on purpose, please add a comment description

2016-12-14 21:40 UTC, dynasource commented on tests/framework/db/QueryTest.php
> +        // should work with operator format
this seems the start of a new test scenario? How should one interpretate this in the future?

2016-12-14 22:38 UTC, samdark commented on tests/framework/db/QueryTest.php
> +        // should work with operator format
It's copy-pasted from `filterWhere` tests. Could be refactored separately.

2016-12-15 15:05 UTC, klimov-paul approved these changes

2016-12-15 15:10 UTC, merged