Catch `\Throwable` in critical places
yiisoft/yii2 pull request #13217
Opened 2016-12-16 01:23 UTC by cebe

Added catch `\Throwable` to be compatible with PHP7.
Added it in cases where object state needs to be kept consistent.

Mainly on transactions but also some other places where some values are
reset before exiting.

Most of them could probably be refactored by using `finally` in 2.1, as
that requires PHP 5.5.

fixes #12619

2016-12-16 09:44 UTC, samdark approved these changes

2016-12-16 11:26 UTC, klimov-paul requested changes

2016-12-16 11:26 UTC, klimov-paul commented on docs/guide/db-dao.md
> +} catch(\Exception $e) { // replace \Exception with \Throwable when you are using PHP 7
Shouldn't this contain example with extra `catch (\Throwable $e) {` in addition to `\Exception` as it is done inside the core code?

```php
} catch (\Exception $e) { // can be ommited when you are using PHP 7
    ...
} catch (\Throwable $e) {
   ...
}
```

2016-12-16 11:46 UTC, samdark commented on docs/guide/db-dao.md
> +} catch(\Exception $e) { // replace \Exception with \Throwable when you are using PHP 7
No. If your project is PHP 7 only, there's no point in catching `\Exception`.

2016-12-16 11:46 UTC, samdark commented on docs/guide/db-dao.md
> +} catch(\Exception $e) { // replace \Exception with \Throwable when you are using PHP 7
Probably yes. For portability reasons.

2016-12-16 23:44 UTC, cebe commented on docs/guide/db-dao.md
> +} catch(\Exception $e) { // replace \Exception with \Throwable when you are using PHP 7
done.

2016-12-17 10:24 UTC, klimov-paul approved these changes

2016-12-18 17:52 UTC, SilverFire approved these changes

2016-12-18 17:53 UTC, merged