Fix #13108: Negative integer parameter causes "Unknown alias" error w…
yiisoft/yii2 pull request #13220
Opened 2016-12-16 08:33 UTC by pana1990

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  |  #13109, #13108

Fix #13108: Negative integer parameter causes "Unknown alias" error when you execute command console

2016-12-16 09:57 UTC, samdark approved these changes

2016-12-16 23:51 UTC, cebe approved these changes

2016-12-17 13:48 UTC, dynasource requested changes

2016-12-17 13:48 UTC, dynasource commented on framework/console/Request.php
> +                if (is_numeric($name) === false) {
is_numeric already returns a boolean http://php.net/manual/en/function.is-numeric.php. No need for a comparison here

2016-12-17 13:48 UTC, dynasource commented on tests/framework/console/RequestTest.php
> +    public function testResolve()
the use of dataProvider would cleanup your test and provide consistency throughout the test environment

2016-12-17 14:46 UTC, samdark commented on framework/console/Request.php
> +                if (is_numeric($name) === false) {
`if (!is_numeric`

2016-12-17 16:16 UTC, pana1990 commented on framework/console/Request.php
> +                if (is_numeric($name) === false) {
done!

2016-12-17 16:16 UTC, pana1990 commented on tests/framework/console/RequestTest.php
> +    public function testResolve()
done!

2016-12-17 19:30 UTC, SilverFire approved these changes

2016-12-17 19:30 UTC, merged

2016-12-17 19:30 UTC, SilverFire commented
Thank you!