Implement #13219: Ability to not shuffle masters connections
yiisoft/yii2 pull request #13241
Opened 2016-12-18 20:29 UTC by Vovan-VE

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes?
| Tests pass?   | (no tests)
| Fixed issues  | #13219

2016-12-19 01:18 UTC, Vovan-VE commented
Cannot check which master was selected. `Connection::getSlave()` returns another `Connection`, so I can check its `$dsn`. But `open()` only gets `$pdo` from selected master.

2016-12-19 09:52 UTC, Vovan-VE commented
Should I add `private $_master` to `Connection` in the same manner as `private $_slave`? Shoul I do it in this PR or in separate?

2016-12-19 13:06 UTC, samdark commented
This PR.

2016-12-19 22:55 UTC, Vovan-VE commented on framework/db/Connection.php
> + * @property Connection $master The currently active master connection. Null is returned if there is no master
Is it possible to add `@since 2.0.12` to such property?

2016-12-19 23:04 UTC, cebe commented on framework/db/Connection.php
> + * @property Connection $master The currently active master connection. Null is returned if there is no master
no, the annotation should be on the getter. it will be shown in the apidocs correctly.

2016-12-21 00:53 UTC, Vovan-VE commented
Can this PR be merged into 2.0.11? If so, I will update `@since`s and CHANGELOG.

2016-12-24 09:01 UTC, SilverFire approved these changes
Yes, I think we can accept this PR for 2.0.11 release.

CHANGELOG must be updated

2016-12-26 15:32 UTC, samdark requested changes

2016-12-26 15:32 UTC, samdark commented on framework/db/Connection.php
> +    protected function openFromPoolSequentally(array $pool, array $sharedConfig)
Sequentally → Sequentially

2016-12-26 15:32 UTC, samdark commented on framework/db/Connection.php
> +     * Connections will be tried in sequental order.
Sequental → Sequential

2016-12-27 11:28 UTC, samdark approved these changes

2016-12-27 11:28 UTC, samdark commented on framework/db/Connection.php
> +    public $randomizeMasters = true;
How about renaming it to `shuffleMasters`?

2016-12-31 13:16 UTC, dynasource requested changes

2016-12-31 13:16 UTC, dynasource commented on tests/framework/db/sqlite/ConnectionTest.php
> +    public function testMasterSlaveRandomization()
this test looks to complex and will be hard  to maintain in the future. Cant you refactor it to less code?

2017-01-02 01:14 UTC, cebe approved these changes

2017-01-02 01:15 UTC, merged

2017-01-02 01:15 UTC, cebe commented
Merged, Thank you!