More control over ActiveForm widget
yiisoft/yii2 pull request #13240
Opened 2016-12-18 16:27 UTC by uaoleg

If part of a form is rendered separately (e.g. in ajax request), it's not easy to apply JS validation to it.
By moving JS registration to a separate method this problem could be solved much more easier.

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

2016-12-18 17:07 UTC, SilverFire requested changes
CHANGELOG line is required
Unit tests are required

2016-12-18 17:07 UTC, SilverFire commented on framework/widgets/ActiveForm.php
> +     * This registers the necessary JavaScript code.
```
This method registers the necessary JavaScript code
@since 2.0.11
```

2016-12-31 13:37 UTC, dynasource commented on framework/widgets/ActiveForm.php
> +    public function registerJs()
it would also be more consistent with $enableClientScript

2017-04-27 19:28 UTC, SilverFire commented
Merged https://github.com/yiisoft/yii2/commit/a480d7087546c085866e3076fdda59f91349b964 with minor enhancements https://github.com/yiisoft/yii2/commit/fce20a30204188282ec46d2b132928aacf52ed3b

Thank you

2017-04-27 19:28 UTC, closed without merging