Add support \yii\db\Expression attribute to \yii\data\Sort
yiisoft/yii2 pull request #13260
Opened 2016-12-20 22:43 UTC by LAV45

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

If you want to sort the data in an unusual way we usually use the class `\yii\db\Expression` as the wrapper of our expression.
```php
Product::find()
    ->orderBy(new Expression("[[price]] ASC NULLS LAST"))
   ->all();
```

But this option cannot be used when sorting settings `\yii\data\ActiveDataProvider`

I propose to extend the functionality of the class `\yii\data\Sort` to preserve the possibility to sort by an arbitrary expression.
```php
$dataProvider = new ActiveDataProvider([
    'query' => Product::find(),
]);
$dataProvider->sort->attributes['price'] = [
        'asc' => [new Expression("[[price]] ASC NULLS LAST")],
        'desc' => [new Expression("[[price]] DESC NULLS LAST")],
];
```

2016-12-21 09:50 UTC, SilverFire commented
I don't think that `yii\data\Sort` class should know something about DB-related things, such as `yii\db\Expression`. Otherwise we will encourage developers to write plain SQL in views :)

Maybe it makes sense to introduce a mapping method in `yii\db\ActiveQuery`, such as:

```php
public function mapOrders()
{
    return [
        'active_with_value' => new Expression('[[is_active]] = TRUE AND [[value]] IS NOT NULL'),
    ];
}
```

2016-12-21 12:35 UTC, LAV45 commented
I immediately thought the same thing. 
I would not want to add another addiction to the \yii\data\Sort , but I decided to follow the example of [\yii\helpers\BaseJson::processData()](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseJson.php#L145)

```php
class BaseJson
{
    protected static function processData($data, &$expressions, $expPrefix)
    {
// ...
            if ($data instanceof JsExpression) {
                $token = "!{[$expPrefix=" . count($expressions) . ']}!';
                $expressions['"' . $token . '"'] = $data->expression;
                return $token;
            } elseif ($data instanceof \JsonSerializable) {
                return static::processData($data->jsonSerialize(), $expressions, $expPrefix);
            } elseif ($data instanceof Arrayable) {
                $data = $data->toArray();
            } elseif ($data instanceof \SimpleXMLElement) {
                $data = (array) $data;
            } else {
// ...
    }
}
```

In my opinion there is nothing wrong with handling different data types.

2016-12-21 16:29 UTC, LAV45 commented
@SilverFire , I would suggest to use this option
```php
public function mapOrders()
{
    return [
        'is_active' => [
            SORT_ASC => new Expression('[[is_active]] = TRUE AND [[value]] IS NOT NULL'),
            SORT_DESC => new Expression('[[is_active]] = FALSE OR [[value]] IS NULL'),
        ]
    ];
}
```
then it can be used
```php
Product::find()
    ->orderBy(['is_active' => SORT_DESC])
```

In this case, if the key is the same as the attribute in the table then it will use the version of `yii\db\ActiveQuery::mapOrders()`

2016-12-22 07:01 UTC, SilverFire commented
Looks good for me. Let's wait for more opinions from @yiisoft/core-developers

2016-12-22 09:34 UTC, klimov-paul commented
I can't see any issue here. `Sort` already supports SQL expressions as an attribute.
Here is a working example:

```
$nameSortExpression = 'CASE ([[title]] IS NULL) WHEN true THEN [[name]] ELSE [[title]] END';
$dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => [
                'attributes' => [
                    'name' => [
                        'asc' => [
                            $nameSortExpression => SORT_ASC
                        ],
                        'desc' => [
                            $nameSortExpression => SORT_ASC,
                        ],
                    ],
                ],
                'defaultOrder' => [
                    'name' => SORT_ASC,
                ],
            ],
        ]);
```

2016-12-22 11:44 UTC, LAV45 commented
@klimov-paul ,
If we follow your example then builds the query
```sql
... ORDER BY "manufacturer"."data"->'nntdays_units' DESC NULLS LAST DESC LIMIT 20
```
At the end of the query is added `DESC`

2016-12-22 11:57 UTC, klimov-paul commented
So, it is a matter of skipping automatic `ASC`/`DESC` addition, not `Expression` support.

2016-12-22 19:58 UTC, LAV45 commented
What do you think about the last change?

2016-12-22 20:15 UTC, klimov-paul commented
Makes sense.

2016-12-26 10:44 UTC, klimov-paul requested changes
CHANGELOG line is missing

2016-12-26 10:44 UTC, klimov-paul commented on framework/data/Sort.php
> + *                 'desc' => ['first_name' => SORT_DESC, '[[last_name]] DESC'],
Original examples should be preserved.
Direct full sort specification should be added as extra line.

2016-12-26 10:44 UTC, klimov-paul commented on framework/data/Sort.php
> + *                 'desc' => ['first_name' => SORT_DESC, '[[last_name]] DESC'],
Also it is better to mention PostgreSQL specific example with `NULLS FIRST` involved to make it more clear when it may be needed.

2016-12-26 10:44 UTC, klimov-paul commented on tests/framework/data/SortTest.php
> +    }
I would simplify this test: all waht is necessary is check if expression can be passed as sort attribute value.
There is no need to check multisort here as it is already covered.

2016-12-26 16:24 UTC, samdark approved these changes

2016-12-29 21:52 UTC, SilverFire approved these changes

2016-12-31 12:37 UTC, dynasource requested changes

2016-12-31 12:37 UTC, dynasource commented on framework/data/Sort.php
> +                if (is_int($name)) {
this deserves a description so it's objective can be easily understood in the future

2017-01-02 16:59 UTC, LAV45 commented on framework/data/Sort.php
> +     * This syntax can be described using the following example:
@dynasource, and nothing fits this description

2017-05-09 14:27 UTC, klimov-paul commented
Resolved by commit 473598ac8ccbc3f0782e41d0ad2a01abd4b55fb2

2017-05-09 14:27 UTC, closed without merging