Fixes #13277: Invalid parsing of `--` in CLI
yiisoft/yii2 pull request #13293
Opened 2016-12-29 21:43 UTC by rugabarbo

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13277

2016-12-30 09:08 UTC, samdark requested changes

2016-12-30 09:08 UTC, samdark commented on framework/console/Request.php
> +            if ($route == '--') {
`===` can be safely used.

2016-12-30 09:08 UTC, samdark commented on framework/console/Request.php
> +            } elseif ($param == '--') {
`===` could be safely used.

2016-12-30 17:53 UTC, samdark approved these changes

2016-12-30 18:52 UTC, SilverFire approved these changes
Vote for merging in 2.0.11

2016-12-31 12:55 UTC, dynasource approved these changes

2016-12-31 14:31 UTC, SilverFire commented
Merged b4acf4606127315e2843e07547b849557705aeec
Thank you! :christmas_tree:

2016-12-31 14:32 UTC, closed without merging