Add test case for deadlock in MySQL
yiisoft/yii2 pull request #13346
Opened 2017-01-08 02:21 UTC by Vovan-VE

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | should yes
| Fixed issues  | not fixed here, should to confirm #12715

At first here goes test case which do deadlock and catch it as successful result. Don't merge.

2017-01-08 03:14 UTC, Vovan-VE commented
Then here comes just one nested transaction to actually fail the test case.

2017-01-08 03:27 UTC, Vovan-VE commented
> There was 1 failure:
> 1) yiiunit\framework\db\mysql\ConnectionTest::testDeadlockException
> child exited with error status. Shared children log:
> [2017-01-08 03:16:29.325] child 2: wait signal from child 1
> [2017-01-08 03:16:29.326] child 1: connect
> [2017-01-08 03:16:29.327] child 1: delete
> [2017-01-08 03:16:29.328] child 1: insert
> [2017-01-08 03:16:29.333] child 1: transaction
> [2017-01-08 03:16:29.335] child 1: select
> [2017-01-08 03:16:29.336] child 1: send signal to child 2
> [2017-01-08 03:16:29.336] child 2: connect
> [2017-01-08 03:16:29.337] child 2: transaction
> [2017-01-08 03:16:29.340] child 2: update
> [2017-01-08 03:16:31.336] child 1: update
> [2017-01-08 03:16:31.337] child 1: commit
> [2017-01-08 03:16:31.338] child 2: exit
> [2017-01-08 03:16:31.339] child 2: ! sql error 42000: 1305: SAVEPOINT LEVEL1 does not exist

I hope the issue can be confirmed with this without merging this test case.

2017-02-21 18:41 UTC, dynasource approved these changes
thanks for taking time to dive into this issue. The approach with several committing steps is helpful to indicate your solution to be working. 

The test can be made easier to understand though, by dedicating it into pieces in a separate class.

2017-02-22 13:51 UTC, samdark approved these changes

2017-02-22 13:52 UTC, samdark requested changes

2017-02-22 13:52 UTC, samdark commented on framework/db/Connection.php
> +                } catch (\Exception $e_rollback) {
`$e_rollback` could be named `$rollbackException`.

2017-02-22 23:30 UTC, samdark requested changes

2017-02-22 23:30 UTC, samdark commented on framework/db/Connection.php
>              if ($transaction->isActive && $transaction->level === $level) {
These two blocks are exactly the same. Is it possible to extract these into a method?

2017-02-23 00:56 UTC, Vovan-VE commented on framework/db/Connection.php
>              if ($transaction->isActive && $transaction->level === $level) {
Should it be a method in `Connection` with arguments `($transaction, $level)` or method in `Transaction` with arguments `($level)`. Also these two blocks will become one when minimum PHP version will be required 7.

2017-02-23 08:52 UTC, SilverFire approved these changes
One of the most complex tests in Yii :)

2017-02-23 12:16 UTC, samdark commented on framework/db/Connection.php
>              if ($transaction->isActive && $transaction->level === $level) {
Connection. And it should not be public.

2017-02-23 17:54 UTC, samdark approved these changes

2017-02-23 17:55 UTC, samdark commented
Looks good to me. Please add changelog and we'll merge it.

2017-02-23 22:10 UTC, Vovan-VE commented
IMHO, this PR should not be merged. Provided test case is not stable (PHP 5.6 segfailt) and platform specific (fork and signals). It's too complex and too ugly.
#13347 contains fix only and should be merged instead.

2017-02-23 22:27 UTC, samdark commented
I don't like to have code for such complicated case not covered by a unit test. In the test method we can probably check for pcntl absence or PHP 5.6 and skip them.

2017-02-25 10:39 UTC, dynasource commented
agree with @samdark . Lets keep it and see how the unit test performs. We can always remove / simplify later on.

2017-02-25 10:56 UTC, Vovan-VE commented
Last too commits shows that SEGFAULT is unstable at least for PHP 5: https://travis-ci.org/yiisoft/yii2/builds/204767330 - all passed; https://travis-ci.org/yiisoft/yii2/builds/204767391 - all 5.* segfault.
How to locate the reason? I need to do some refactoring anyway. Where should I extract some classes? `tests/framework/db/mysql/?/*.php`

2017-02-25 11:03 UTC, dynasource commented
That's a pity indeed. Thanks for looking into it. A new separate class dedicated to this issue would be nice like i.e. /tests/framework/db/mysql/connection/DeadLockTest.php

2017-03-07 19:58 UTC, merged

2017-03-07 19:58 UTC, samdark commented
Merged. Thank you very much.

2017-03-10 01:25 UTC, cebe commented on framework/db/Connection.php
> +     */
`@since 2.0.12` missing.

2017-03-10 01:27 UTC, cebe commented
Great job with the unit test!

2017-03-10 01:30 UTC, cebe commented on framework/db/Connection.php
> +     */
I think this could even be made private. if there is a need to customize this one can override transaction().

2017-03-10 01:31 UTC, cebe commented on framework/db/Connection.php
> +     */
fixed: 7d4b33a

2017-03-10 01:42 UTC, Vovan-VE commented
Thanks. But it seems to me that I did add one more place for segfaulting at least PHP 5.4 on tests.

2017-03-10 14:54 UTC, cebe commented
PHP segfauling means there is a bug in PHP as PHP code itself should not be able to segfault.

2017-03-10 15:56 UTC, Vovan-VE commented
Yes, but from now whole build will be treated as failed.
Previously before last refactoring segfault was inconsistent for PHP 5.*. Now it became looks consistent for 5.4.

2017-03-10 18:36 UTC, samdark commented
Would be a good idea to either fix it or skip it for 5.4...

2017-03-10 23:24 UTC, cebe commented
we need to redo our travis setup anyway in some kind as the mysql errors are still occuring.

2017-03-14 10:25 UTC, Vovan-VE commented
5.4 did not segfault here https://travis-ci.org/yiisoft/yii2/builds/210844774

2017-03-14 10:33 UTC, samdark commented
I've restarted build. Let's see how it goes.

2017-03-14 11:07 UTC, samdark commented
Hmm... works :)