asTime fixed for time-only values
yiisoft/yii2 pull request #13348
Opened 2017-01-08 11:33 UTC by bizley

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13343

2017-02-14 18:24 UTC, SilverFire approved these changes

2017-02-15 00:12 UTC, cebe commented on framework/i18n/Formatter.php
> +     * Since version 2.0.12 the array has third boolean element indicating whether the timestamp has date information.
A note in the `UPGRADE` file is needed.

2017-02-15 00:12 UTC, cebe commented on tests/framework/i18n/FormatterDateTest.php
> +        $this->assertSame('9am', $this->formatter->asTime('9am', 'Ha'));
a test including seconds would be nice.

2017-02-15 07:33 UTC, bizley commented on framework/i18n/Formatter.php
> +     * Since version 2.0.12 the array has third boolean element indicating whether the timestamp has date information.
`UPGRADE` draft added.

2017-02-15 07:33 UTC, bizley commented on tests/framework/i18n/FormatterDateTest.php
> +        $this->assertSame('9am', $this->formatter->asTime('9am', 'Ha'));
Done.

2017-02-15 21:58 UTC, SilverFire approved these changes

2017-02-16 08:00 UTC, dynasource requested changes
could this PR be completed with a unit test which matches the clear use case of https://github.com/yiisoft/yii2/issues/13343#issuecomment-271119689 (including a reference?)

2017-02-16 09:29 UTC, SilverFire commented
https://github.com/yiisoft/yii2/pull/13348/files#diff-f1eb247f183bf542c55a57d24506a469R698
Isn't this enough?

2017-02-16 09:31 UTC, bizley commented
It's ok, I've just finished the exact use case test, commit in few seconds.

2017-02-16 10:07 UTC, dynasource approved these changes
thanks!

2017-02-16 15:12 UTC, cebe approved these changes

2017-02-16 15:13 UTC, closed without merging

2017-02-16 15:13 UTC, cebe commented
Merged, thank you!