Disabled link at current page
yiisoft/yii2 pull request #13369
Opened 2017-01-11 09:02 UTC by aquy

linkpager disabled link at current page

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | no

2017-01-11 10:13 UTC, samdark commented
Why?

2017-01-11 10:24 UTC, aquy commented
link page to itself on the site bad for SEO and the user is already on this page

2017-01-11 10:35 UTC, samdark commented
OK. Makes sense.

2017-01-11 17:27 UTC, bashkarev commented
Google and others, remove the current link.
Maybe replace `a` to `span`?
And to make it optional.

2017-01-11 17:33 UTC, samdark commented
Yes. That is a good idea.

2017-01-12 07:34 UTC, aquy commented
I've added the option to replace `a` to `span` - `disabledCurrentPageLink`

2017-01-12 11:19 UTC, samdark requested changes

2017-01-12 11:19 UTC, samdark commented on framework/widgets/LinkPager.php
> +    public $disabledCurrentPageLink = false;
`disabledCurrentPageLink` → `disableCurrentPageLink`.

2017-01-12 22:18 UTC, samdark approved these changes

2017-01-14 13:50 UTC, SilverFire requested changes
Could you update [tests](https://github.com/yiisoft/yii2/blob/master/tests/framework/widgets/LinkPagerTest.php) to reflect the changes?

2017-01-16 08:51 UTC, aquy commented
Yes, tests have been updated

2017-01-16 14:57 UTC, thyseus commented
How about making this to be true by default?

2017-01-16 15:03 UTC, samdark commented
I think it's OK to make it true by default.

2017-01-16 16:09 UTC, bashkarev commented
This can break the page layout

2017-01-16 16:11 UTC, samdark commented
How?

2017-01-16 16:20 UTC, bashkarev commented
if not use bootstrap
```html
<ul>
    <li><a href="/?page=1">url</a></li>
    <li><span>current</span></li>
</ul>
```
```css
ul > li > a {
    float: left;
    display: block; // etc
}
```

2017-01-16 16:22 UTC, samdark commented
Right. Then it's not a good idea :)

2017-01-21 09:25 UTC, SilverFire approved these changes

2017-04-01 21:54 UTC, closed without merging

2017-04-01 21:56 UTC, samdark commented
Merged. Thanks!