Fix russian translation
yiisoft/yii2 pull request #13372
Opened 2017-01-11 14:50 UTC by jetexe

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13287

2017-01-11 17:51 UTC, samdark requested changes

2017-01-11 17:51 UTC, samdark commented on framework/helpers/BaseInflector.php
> +        if (is_null($twoWordsConnector)) {
Better to use `$twoWordsConnector === null`.

2017-01-12 04:15 UTC, cebe approved these changes

2017-01-12 06:23 UTC, jetexe commented on framework/helpers/BaseInflector.php
> +        if (is_null($twoWordsConnector)) {
fixed

2017-01-12 07:12 UTC, jetexe commented
condition fixed

2017-01-12 11:07 UTC, samdark approved these changes

2017-01-13 23:38 UTC, cebe approved these changes
needs a changelog line.

2017-01-14 12:27 UTC, SilverFire requested changes

2017-01-14 12:27 UTC, SilverFire commented on framework/helpers/BaseInflector.php
> +            $twoWordsConnector = ' ' . Yii::t('yii', 'and') . ' ';
I'd rather put spaces inside the translation to allow changing using dictionary.

```php
$twoWordsConnector = Yii::t('yii', ' and ');
```

2017-01-14 16:40 UTC, samdark commented on framework/helpers/BaseInflector.php
> +            $twoWordsConnector = ' ' . Yii::t('yii', 'and') . ' ';
Yes, I think it is a very good idea.

2017-01-15 19:09 UTC, closed without merging

2017-01-15 19:10 UTC, samdark commented
Merged with adjustment proposed by @SilverFire: https://github.com/yiisoft/yii2/commit/3a1cd7f3aa5cafdb7abc3901a36c81d507dab46f