Fix #13278: `DbQueryDependency` created
yiisoft/yii2 pull request #13384
Opened 2017-01-13 10:57 UTC by klimov-paul

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13278

Fixes #13278 adding new `DbQueryDependency` cache dependency

2017-01-13 13:51 UTC, samdark approved these changes

2017-01-13 13:51 UTC, samdark commented on framework/caching/DbQueryDependency.php
> +            throw new InvalidConfigException('`' . get_class($this) . '::$query` should be an instance of `yii\db\QueryInterface`.');
Since errors aren't outputted with markdown processing it's better to use regular " instead of `.

2017-01-14 13:40 UTC, SilverFire requested changes
Good in general. CHANGELOG line should be added before merge

2017-01-14 13:40 UTC, SilverFire commented on tests/framework/caching/DbQueryDependencyTest.php
> +    }
It will be good to add the following tests:
 - `method` set to `string` and `callback`
 - `query` that is not instance of `yii\db\QueryInterface`

2017-01-21 10:20 UTC, SilverFire approved these changes

2017-02-09 10:30 UTC, merged