Fixed #13212 - DbSession failure when trying to regenerate session id
yiisoft/yii2 pull request #13404
Opened 2017-01-18 14:45 UTC by andrewnester

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13212

2017-01-18 15:31 UTC, samdark approved these changes

2017-01-21 09:52 UTC, SilverFire requested changes

2017-01-21 09:52 UTC, SilverFire commented on framework/web/DbSession.php
> +            return;
How about tracing `Yii::warning`?

2017-01-22 08:40 UTC, samdark commented on framework/web/DbSession.php
> +            return;
Yes, good idea.

2017-01-22 11:23 UTC, andrewnester commented
@SilverFire @samdark guys, I've just added `Yii::warning` call

2017-01-22 13:41 UTC, SilverFire approved these changes

2017-01-22 13:42 UTC, SilverFire commented
Good to merge in 2.0.11

2017-01-22 17:15 UTC, merged

2017-01-22 17:15 UTC, samdark commented
Thanks!