Populating missing languages
yiisoft/yii2 pull request #13446
Opened 2017-01-25 23:47 UTC by bizley

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #11502

- `MessageController` now properly populates missing languages in case of extraction with "_db_" format and no new messages.  
  Previously with no new messages to extract missing languages were ignored.
- Unit tests for extracting messages with "_db_" format added.
- Test checking case #11502 added in `BaseMessageControllerTest`.
- `testMarkObsoleteMessages()` had to be overridden because in case of DB messages source message is wrapped in `@@` and not translation.

Additionally I've made few slight modifications in `MessageController`:
- Excessive `else` has been removed in explicit cases.
- Failure to create language directory throws exception now in case of "_php_" and "_po_" formats.
- Db component is verified with `Instance::ensure()` to allow tests configuration.
- Single-character variable `$m` renamed to keep Code Climate happier.
- Console output "_Nothing new...skipped_" replaced with "_Nothing to save_" to make it compatible with other message saving methods and `BaseMessageControllerTest`.

`DbMessageControllerTest` is based on SilverFire's code for `DbMessageSourceTest`.

2017-01-26 08:55 UTC, samdark requested changes

2017-01-26 08:55 UTC, samdark commented on framework/console/controllers/MessageController.php
> +                if (!is_dir($dir) && !mkdir($dir)) {
`@` should not be removed since `mkdir` not only fails but triggers warnings.

2017-01-26 08:55 UTC, samdark commented on framework/console/controllers/MessageController.php
> +        foreach ($query->each(100, $db) as $row) {
Does that help to improve performance or memory usage?

2017-01-26 09:10 UTC, bizley commented on framework/console/controllers/MessageController.php
> +        foreach ($query->each(100, $db) as $row) {
Right, probably not in here. Old AR habit.

2017-01-26 09:17 UTC, samdark commented on framework/console/controllers/MessageController.php
> +        foreach ($query->each(100, $db) as $row) {
I guess that in this case it can actually decrease performance...

2017-01-26 09:31 UTC, bizley commented
Should I modify CHANGELOG to 2.0.12 as well?

2017-01-26 09:41 UTC, samdark commented
Yes, I think so. No more issues are going to me solved in 2.0.11 except the ones assigned to milestone else we won't release it ever :)

2017-01-26 09:57 UTC, samdark approved these changes

2017-01-26 13:42 UTC, andrewnester commented on framework/console/controllers/MessageController.php
> +class MessageController extends \yii\console\Controller
maybe it's better to add `use yii\console\Controller` statement?

2017-01-26 13:44 UTC, bizley commented on framework/console/controllers/MessageController.php
> +class MessageController extends \yii\console\Controller
It's used only once so I made it like with other similar Yii 2 classes cases.

2017-02-01 23:51 UTC, closed without merging

2017-02-01 23:51 UTC, samdark commented
Merged https://github.com/yiisoft/yii2/commit/1749c46c5d7a14a2c45fbad5f723edbbca37db34 Thank you!