Fixed #13378 - Added skipOnEmpty option to SluggableBehaviour
yiisoft/yii2 pull request #13449
Opened 2017-01-26 13:22 UTC by andrewnester

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13378

2017-02-19 10:31 UTC, dynasource requested changes

2017-02-19 10:31 UTC, dynasource commented on tests/framework/behaviors/SluggableBehaviorTest.php
> +{
the naming should have ActiveRecord at the end (ActiveRecordSluggable actually too IMO). So a better name is `SkipOnEmptySluggableActiveRecord'. Perhabs you can change that too.

2017-04-04 13:52 UTC, andrewnester commented
@dynasource thanks! I've just updated my PR.

2017-04-04 21:30 UTC, samdark requested changes

2017-04-04 21:30 UTC, samdark commented on framework/behaviors/SluggableBehavior.php
>                      $slugParts[] = ArrayHelper::getValue($this->owner, $attribute);
Empty check and return could be done right here so there's no need to iterate array one more time.

2017-04-04 21:30 UTC, samdark commented on framework/behaviors/SluggableBehavior.php
>                      $slugParts[] = ArrayHelper::getValue($this->owner, $attribute);
```php
$part = ArrayHelper::getValue($this->owner, $attribute);
if ($part === null || $part === '') {
    return $this->owner->{$this->slugAttribute};
}
$slugParts[] = $part;
```

2017-04-05 14:32 UTC, andrewnester commented on framework/behaviors/SluggableBehavior.php
>                      $slugParts[] = ArrayHelper::getValue($this->owner, $attribute);
@samdark thanks! looks like it would be good change for performance. done!

2017-04-05 15:01 UTC, samdark approved these changes
Looks good. Please add a changelog entry.

2017-04-10 08:17 UTC, klimov-paul commented on framework/behaviors/SluggableBehavior.php
> +                        return $this->owner->{$this->slugAttribute};
I am unsure if this logic is correct:
- if there is no slug (e.g. for new record) and its source is empty - the slug will be empty.
- if slug is set (existing record) and its source is empty (but changed!) - the slug remains unchanged, which seems odd

2017-04-10 21:59 UTC, samdark commented on framework/behaviors/SluggableBehavior.php
> +                        return $this->owner->{$this->slugAttribute};
I'd expect that. Your first point is how it behaves now. Usually if you're using a field to generate a slug the field is required.  Second point is what this property was introduced for.

2017-07-03 17:41 UTC, dynasource approved these changes

2017-07-04 17:47 UTC, merged

2017-07-04 17:47 UTC, samdark commented
Merged. Thank you!

2017-07-09 19:43 UTC, rob006 commented
Test are broken: https://travis-ci.org/yiisoft/yii2/builds/249564948