Removes redunant code and allows override query relation in descendan…
yiisoft/yii2 pull request #13441
Opened 2017-01-24 16:46 UTC by leandrogehlen

| Q             | A
| ------------- | ---
| Is bugfix?    |  no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

Sometimes it's necessary to change default behavior for relation queries.

Example:

I have created a `MultiTenantRecord` where `ActiveRecord::find()` must be overrided, like:

```php

public static function find()
{
    $identity = Yii::$app->user->identity;
    if ($identity instanceof TenantInterface) {
        return parent::find()->where([static::tableName().'.tenant_id' => $identity->getTenantId()]);
    } else {
        throw new NotSupportedException("Identity does not implements TenantInteface");
    }
}
```
but this should be occurs only "master" record not for relation.
Then this allows customize query for relation

2017-02-19 11:24 UTC, dynasource requested changes
this is useful for further customizing relations within ActiveRecords

2017-02-19 11:24 UTC, dynasource commented on framework/db/BaseActiveRecord.php
> +    protected function newRelationQuery($class, $link, $multiple)
this should be called `createRelationQuery` and if we want to be consistent even `createLinkQuery`

2017-02-19 11:33 UTC, leandrogehlen commented on framework/db/BaseActiveRecord.php
> +    protected function newRelationQuery($class, $link, $multiple)
👍 , @dynasource  i think better `createRelationQuery`

2017-02-22 20:33 UTC, SilverFire requested changes
composer.lock should not be comminted

2017-02-22 20:33 UTC, SilverFire commented on framework/db/BaseActiveRecord.php
> +     * @return ActiveQueryInterface the relational query object.
`@since 2.0.12`

2017-02-22 21:15 UTC, leandrogehlen commented
Sorry, i removed my fork accidentally, i will redo the changes in another PR

2017-02-22 23:23 UTC, closed without merging