Support HTTP_X_FORWARDED_PROTO through multiple proxy levels
yiisoft/yii2 pull request #13452
Opened 2017-01-26 18:21 UTC by bpicolo

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes/no   **depends on the behavior people are relying on?**
| Tests pass?   | yes, + new test added
| Fixed issues  | #13451

2017-01-26 18:23 UTC, bpicolo commented on framework/web/Request.php
> +            || isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strncasecmp($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https', 5) === 0;
this is magical, happy to s/5/strlen('https') if preferred

2017-01-26 20:12 UTC, samdark approved these changes

2017-01-29 10:56 UTC, SilverFire approved these changes

2017-01-29 23:06 UTC, samdark commented on framework/web/Request.php
> +            || isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strncasecmp($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https', 5) === 0;
It looks OK to me as is.

2017-02-16 07:44 UTC, dynasource requested changes
This PR intoduces new unit tests which are not covering all the state possibilities (like for ```_SERVER['HTTPS'], 'on'```). These should be added or at least be commented as 'todo' for future expansion.

Also, it is unclear why strcasecmp is only changed for the second and not for the first use of strcasecmp.

2017-02-16 11:42 UTC, bpicolo commented
@dynasource did you read the Issue? The first strcasecmp is irrelevant to the issue at hand.

As for testing, I don't agree that exhaustive testing is or should be a requirement. Especially as test coverage prior is actual 0.

2017-02-16 12:10 UTC, dynasource commented
@bpicolo, I am watching your PR from a future code review / read perspective. When someone sees these similar functions a false assumption can be made that a synchronization is forgotten. It would be helpful to understand this from the code with proper naming.

Similar applies for your tests. When somebody is looking at the tests in the future, a false assumption is made about the tests being complete. In this case, it isn't. Also here it would be helpful to easily whats covered and what not. 

We dont want us to burn time in the future to 'interpretate' while this can be prevented.

2017-02-16 13:27 UTC, bpicolo commented
I'll change it up, but imo the bar for making OSS contributions convenient here is not being applied at the right height

2017-02-16 13:41 UTC, bpicolo commented
At least partly because this was 3 weeks ago and is now much less on mind 😶

2017-02-16 13:58 UTC, bpicolo commented
@dynasource  Does that suit you better? I suspect a comment there is more appropriate than revising the former to strncasecmp, and would prefer to avoid temporary variables for naming's sake (yeah, unfortunate that PHP internals naming is poor in general ☹️  )

2017-02-16 14:19 UTC, dynasource commented
@bpicolo, thanks for putting effort in the extra work. It will suit if the comment is 1 line and explationary for the use of strncasecmp (optionally by a reference to the issue topic)

2017-02-16 14:20 UTC, bpicolo commented
@dynasource  Already put a 4-line comment in to be extra explicit. Seem good?

2017-02-16 14:26 UTC, dynasource commented
if you think you cannot shrink this comment any further without affecting interpretation, it is OK by me.

2017-02-16 14:27 UTC, bpicolo commented
Wasn't sure if the former was a question or a statement. there ya go

2017-02-16 14:29 UTC, dynasource approved these changes

2017-02-16 14:30 UTC, dynasource commented
your persistence is appreciated

2017-02-16 14:31 UTC, bpicolo commented
<3 Thanks for the CR. I understand where you're coming from, you know how it is coming back to popups from old contexts at 7AM though, hah.

2017-02-17 23:01 UTC, samdark requested changes
Reviewed again. It's not safe to rely on `HTTP_` headers if you're not behind a trusted proxy. I think we should introduce a list of trusted IPs and consider `HTTP_` headers only if requested one is one of these.

2017-02-17 23:02 UTC, samdark commented
See https://github.com/yiisoft/yii2/issues/10854

2017-02-17 23:14 UTC, bpicolo commented
@samdark seems resolveable by LB configuration no? 

IP whitelist doesn't work well in the world of auto scaling cloud groups.

2017-02-17 23:16 UTC, bpicolo commented
True that it's not necessarily a good default though. Not sure.

2017-02-17 23:19 UTC, samdark commented
@bpicolo yes, it's resolvable by proper configuration when you have a load balancer in place but isn't a safe default in case you don't have load balancer at all i.e. more than half of all cases.

2017-03-14 12:48 UTC, samdark commented
Thanks for contributing. The issue will be solved but not with this pull request. Sorry about that.

2017-03-14 12:48 UTC, closed without merging