ActiveDataProvider should avoid query data when data count is zero
yiisoft/yii2 pull request #13467
Opened 2017-01-29 14:24 UTC by kLkA

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12752

2017-01-29 21:00 UTC, Renkas commented on framework/data/ActiveDataProvider.php
> +            if (($pagination->totalCount = $this->getTotalCount()) === 0) {
why put all the logic in one line? Good practice is that every action goes to a separate line. Here you are doing assignment and then comparison on one ...

I can't see any performance optimization neither on this syntax.

2017-01-29 23:04 UTC, samdark approved these changes

2017-01-30 08:34 UTC, kLkA commented on framework/data/ActiveDataProvider.php
> +            if (($pagination->totalCount = $this->getTotalCount()) === 0) {
Hi @Renkas , I agree with you. Thank you

2017-02-14 18:05 UTC, SilverFire requested changes
The test does not check the query skipping fact. It just proves, that you will get 0 modes when count query returns 0 rows.

2017-02-14 18:07 UTC, SilverFire commented
My suggestions is to create a `ZeroCountQueryStub` class, with `count()` method that always returns 0

2017-02-17 12:42 UTC, dynasource commented
> The test does not check the query skipping fact. It just proves, that you will get 0 modes when count query returns 0 rows.

agree

2017-02-20 09:00 UTC, closed without merging