Include defaultRoles in getRolesByUser() results
yiisoft/yii2 pull request #13462
Opened 2017-01-28 14:51 UTC by developeruz

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #11230

2017-01-28 15:43 UTC, samdark requested changes

2017-01-28 15:43 UTC, samdark commented on framework/rbac/BaseManager.php
> +     * Returns defaultRoles as array of Role objects
Need `@since 2.0.12`.

2017-01-28 15:43 UTC, samdark commented on framework/rbac/BaseManager.php
> +     * Returns defaultRoles as array of Role objects
Missing `@return`

2017-01-29 04:32 UTC, developeruz commented on framework/rbac/BaseManager.php
> +     * Returns defaultRoles as array of Role objects
Added

2017-01-29 23:08 UTC, samdark approved these changes

2017-02-14 17:55 UTC, SilverFire submitted a review, later dismissed

2017-02-14 17:59 UTC, SilverFire requested changes

2017-02-14 17:59 UTC, SilverFire commented on framework/rbac/BaseManager.php
> +            $result[$roleName] = new Role(['name' => $roleName]);
We already have method `createRole()` for this purpose.
I think it is better to call it instead

```php
$result[$roleName] = $this->createRole($roleName);
```

2017-02-14 18:24 UTC, developeruz commented on framework/rbac/BaseManager.php
> +            $result[$roleName] = new Role(['name' => $roleName]);
I changed this line. Thanks.

2017-02-14 21:30 UTC, SilverFire approved these changes

2017-02-14 22:26 UTC, merged

2017-02-14 22:26 UTC, samdark commented
Merged. Thanks!

2017-02-15 05:06 UTC, hirenbhut93 commented
@samdark, @developeruz  It's work when define rule with default role? Like http://www.yiiframework.com/doc-2.0/guide-security-authorization.html#using-default-roles

2017-02-15 07:32 UTC, samdark commented
If rule is executed before the call — yes.

2017-02-15 07:50 UTC, hirenbhut93 commented
@samdark What?

2017-02-15 08:16 UTC, samdark commented
In that case it's not available at the call time so I think it won't be returned.

2017-03-10 23:45 UTC, cebe commented on framework/rbac/BaseManager.php
> +    public function getDefaultRoles()
method name conflicts with the property. This should be changed.

2017-03-11 03:28 UTC, developeruz commented on framework/rbac/BaseManager.php
> +    public function getDefaultRoles()
Should I create a new PR because this one is already merged?
Can you, please, suggest a name for this method?

2017-03-11 03:42 UTC, arogachev commented on framework/rbac/BaseManager.php
> +    public function getDefaultRoles()
@developeruz Yes, you should create new PR. Suggest your variation of naming and we can discuss from there.