Made ActionColumn Yii::t() tags static again
yiisoft/yii2 pull request #13489
Opened 2017-02-01 18:42 UTC by cebe

this was changed in 2.0.11 and cause the messages translation to not
recognize them anymore.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | n/a

2017-02-01 19:44 UTC, rob006 commented
Can't we just use:

```php
// Yii::t('yii', 'View');
// Yii::t('yii', 'Update');
// Yii::t('yii', 'Delete');
```
for messages extraction?

2017-02-01 20:28 UTC, samdark commented
That's way too hacky.

2017-02-01 20:28 UTC, samdark approved these changes

2017-02-01 20:59 UTC, rob006 commented
Why hacky? In many situation you may need only mark some text as translatable without real translating (other frameworks/tools already have methods for that, like `gettext_noop()`), using comment is the most clean and performance-wise solution for me.

2017-02-01 21:23 UTC, samdark commented
I don't think `switch` is worse than `ucfirst`.

2017-02-01 23:52 UTC, samdark requested changes
Need changelog

2017-02-02 18:31 UTC, cebe commented
@samdark done.
@rob006 for the fix I'd merge it like this now but if you think this feature is needed you can open an issue and we can discuss how to implement it. It may be useful but I am not sure it is a good idea to do it with comments.

2017-02-02 18:33 UTC, samdark approved these changes

2017-02-02 18:46 UTC, merged

2017-02-02 19:20 UTC, cebe commented
There is now a hotfix release 2.0.11.1, which includes this fix.