fix reading stream came from db
yiisoft/yii2 pull request #13507
Opened 2017-02-03 13:43 UTC by StalkAlex

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13501

2017-02-03 13:47 UTC, samdark approved these changes
Looks good. Need a line for changelog.

2017-02-03 14:00 UTC, cebe requested changes
Also a testcase would be great to cover this.

2017-02-03 14:00 UTC, cebe commented on framework/rbac/DbManager.php
> +        $result = $row['data'];
`$row` can be false, so that check must be done here.

2017-02-03 14:04 UTC, StalkAlex commented on framework/rbac/DbManager.php
> +        $result = $row['data'];
ok, I'll change it and make test.

2017-02-03 18:13 UTC, StalkAlex commented
I fixed both getRule and getRules method. Some tests were failed due to this bug, now there are all ok. Not sure what else testcase could be here, because current tests have covered this already from my point of view.

2017-02-03 19:21 UTC, samdark commented
2.0.11 was not failing: https://travis-ci.org/yiisoft/yii2/builds/197358860

2017-02-04 07:24 UTC, StalkAlex commented
I ran locally only rbac group for 2.0.11.1. Here's result:
![default](https://cloud.githubusercontent.com/assets/2943154/22616715/70583744-ead4-11e6-8a44-272a647c49a6.png)
I suppose it's correct behaviour because of bug I reported.
Here's run for fixed version:
![default](https://cloud.githubusercontent.com/assets/2943154/22616734/e46d7e32-ead4-11e6-9357-ba9b67f783ee.png)

2017-02-04 12:51 UTC, merged

2017-02-04 12:51 UTC, samdark commented
Merged. Thanks!