Enabling queryCache on a database that is also the storage for Cache caused a loop.
yiisoft/yii2 pull request #13506
Opened 2017-02-03 10:31 UTC by michaelarnauts

Enabling queryCache on a database that is also the storage for Cache caused a loop.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #11719

2017-02-03 12:43 UTC, samdark requested changes

2017-02-03 12:43 UTC, samdark commented on framework/caching/DbCache.php
> +            $this->db->createCommand()
Should `$db` be used here instead of `$this->db`?

2017-02-03 13:37 UTC, michaelarnauts commented on framework/caching/DbCache.php
> +            $this->db->createCommand()
Hmm, I guess that makes sence!

2017-02-03 13:41 UTC, michaelarnauts commented on framework/caching/DbCache.php
> +                        'data' => [$value, \PDO::PARAM_LOB],
I'm wondering now (it has been a while since I wrote this code), is `$this` or `$value` accessible from inside this callback?

2017-02-03 13:43 UTC, samdark commented on framework/caching/DbCache.php
> +                        'data' => [$value, \PDO::PARAM_LOB],
`$this` is accessible. Other variables aren't. Should be:

```php
function (Connection $db) use ($value) {
```

2017-02-03 13:44 UTC, samdark commented on framework/caching/DbCache.php
> +        $this->db->noCache(function (Connection $db) {
```php
function (Connection $db) use ($key) {
```

2017-02-03 13:44 UTC, samdark commented on framework/caching/DbCache.php
> +        $result = $this->db->noCache(function (Connection $db) {
```php
function (Connection $db) use ($key, $value, $duration) {
```

2017-02-03 13:46 UTC, samdark commented on framework/caching/DbCache.php
> +                        'data' => [$value, \PDO::PARAM_LOB],
I wonder how did that actually worked for you...

2017-02-03 14:35 UTC, michaelarnauts commented on framework/caching/DbCache.php
> +                        'data' => [$value, \PDO::PARAM_LOB],
I wonder that too, I guess it didn't but it also didn't hang my app anymore (see #11719).

2017-02-03 14:44 UTC, samdark commented on framework/caching/DbCache.php
> +                        'data' => [$value, \PDO::PARAM_LOB],
Could you test with proper code?

2017-02-14 20:19 UTC, SilverFire requested changes
Looks good in general. Could you add a changelog line and create test?

2017-04-26 00:16 UTC, closed without merging

2017-04-26 00:17 UTC, samdark commented
Verified and merged. Thank you.