[WIP] Introduced `Validator::format()`
yiisoft/yii2 pull request #13528
Opened 2017-02-06 12:49 UTC by SamMousa

Refactored all validators to use `$this->format` instead of `Yii::$app->getI18n()->format`.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes (subjective)
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | 
| Fixed issues  | #13254

2017-02-06 13:14 UTC, samdark requested changes

2017-02-06 13:14 UTC, samdark commented on framework/validators/Validator.php
> +     * @return string
Need `@since` tag.

"Same implementation as used by \Yii::t" isn't needed here.

2017-02-18 15:17 UTC, dynasource approved these changes
nice cleanup. I'd tend to prefer a method name `formatMessage` as its more descriptive

2017-02-20 19:30 UTC, SilverFire requested changes
Good PR

2017-02-20 19:30 UTC, SilverFire commented on framework/validators/Validator.php
> +     * Formats a mesage using the I18N, or simple strtr if \Yii::$app is not available.
`\Yii::$app` -> <code>\`\Yii::$app\`</code>

2017-02-20 19:30 UTC, SilverFire commented on framework/validators/Validator.php
> +     * Same implementation as used by \Yii::t
`\Yii::t` -> <code>\`\Yii::t\`</code>

2017-02-20 19:33 UTC, SamMousa commented
Will fix this tomorrow.

2017-02-20 19:37 UTC, SamMousa commented
@dynasource I chose `format` since it is used by formatters as well.
Let me know if I must change it to `formatMessage`.

2017-02-20 19:48 UTC, samdark commented
`formatMessage` looks better to me in this case since context isn't clear from just `format`.

2017-02-20 19:48 UTC, samdark approved these changes

2017-02-20 20:12 UTC, SamMousa commented
That refactor will have to wait till tomorrow so i can do it the lazy way with an IDE :)

2017-03-14 12:26 UTC, samdark approved these changes

2017-03-14 12:37 UTC, merged

2017-03-14 12:37 UTC, samdark commented
Merged. Thanks!