Issue 13551: loading fixtures in subdirectories
yiisoft/yii2 pull request #13553
Opened 2017-02-10 14:24 UTC by d1rtyf1ng3rs

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | -
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13551 

An attempt to fix #13551.
Would like hear some comments / critics first, expecially about `getFixturesConfig()` changes.

2017-02-12 09:44 UTC, samdark requested changes

2017-02-12 09:44 UTC, samdark commented on framework/console/controllers/FixtureController.php
> +            // $isNamespaced = (strpos($fixture, '\\') !== false);
I think we can check for both `/` and `\` here or normalize everything to linux paths format before the check and the problem will be solved.

2017-02-12 09:44 UTC, samdark commented on framework/console/controllers/FixtureController.php
> +            if (class_exists($className)) {
If both namespaced and non-namespaced fixtures with the same base name exist there will be conflict.

2017-02-16 15:32 UTC, d1rtyf1ng3rs commented
Added fixture's relative path normalization to linux format in `findFixtures()` method;
reverted changes to `getFixturesConfig()` to its original (so `$isNamespaced` is calculated correctly) and added slash-replace from linux-path-backslashes to namespace slashes.

2017-02-16 15:39 UTC, d1rtyf1ng3rs commented on framework/console/controllers/FixtureController.php
> +            // $isNamespaced = (strpos($fixture, '\\') !== false);
Added one more commit - issue should be solved now.
Added fixture's relative path normalization to linux format in `findFixtures()` method;
reverted changes to `getFixturesConfig()` to its original (so `$isNamespaced` is calculated correctly) and added slash-replace from linux-path-backslashes to namespace slashes.

2017-02-18 20:54 UTC, samdark requested changes

2017-02-18 20:54 UTC, samdark commented on framework/console/controllers/FixtureController.php
> +            $relativeName = str_replace("\\", "/", $relativeName);
Shouldn't it be done to `$fixture` prior to replacements right before `// strip $fixturesPath from $fixture's full path` line?

2017-02-18 20:54 UTC, samdark commented on framework/console/controllers/FixtureController.php
> +            $relativeDir = dirname($relativeName) == '.' ? '' : dirname($relativeName) . '/';
`===` can be used instead of `==`

2017-02-19 09:36 UTC, dynasource requested changes
I would like to see your usecase examples covered by unit tests

2017-02-19 09:36 UTC, dynasource commented on framework/console/controllers/FixtureController.php
> +            // strip $fixturesPath from $fixture's full path
the added logic should be ensapsulated in a private method with the comments in the description

2017-02-22 09:25 UTC, d1rtyf1ng3rs commented on framework/console/controllers/FixtureController.php
> +            $relativeName = str_replace("\\", "/", $relativeName);
Good point. Yes, there might be a problem - `$fixture` is calculated automatically, whereas `$fixturesPath` is provided or may be provided by user. So it's not guaranteed they're in the same format.
I'll provide corresponding changes soon.

2017-02-22 09:31 UTC, d1rtyf1ng3rs commented on framework/console/controllers/FixtureController.php
> +            // strip $fixturesPath from $fixture's full path
> ... unit tests

Roger that; will provide soon.

> ... should be encapsulated in a private method

Why?

2017-02-22 09:32 UTC, d1rtyf1ng3rs commented
> ... unit tests

Roger that; will provide soon.

2017-02-22 09:48 UTC, dynasource commented on framework/console/controllers/FixtureController.php
> +            // strip $fixturesPath from $fixture's full path
to see 'what' is does by reading the code instead of reading 'how' it is done

2017-03-03 11:07 UTC, d1rtyf1ng3rs commented
Welp, it wasn't much of a 'soon', but here it is.
- Unit tests added;
- getRelativeName() method extracted;
- minor path normalization changes.

I have, still, left the inline-comments in getRelativeName() method; feel free to remove them, if those are 'too much'.

2017-03-04 10:06 UTC, samdark approved these changes

2017-03-04 10:57 UTC, dynasource requested changes

2017-03-04 10:57 UTC, dynasource commented on tests/data/console/controllers/fixtures/subdir/SecondFixture.php
> +        FixtureStorage::$subdirSecondFixtureData[] = 'some data set for subdir/second fixture';
I dont see this `string` being used anywhere? Shouldnt it be used in on of the unit tests?

2017-03-04 10:57 UTC, dynasource commented on tests/data/console/controllers/fixtures/subdir/FirstFixture.php
> +        FixtureStorage::$subdirFirstFixtureData[] = 'some data set for first fixture in subdir';
I dont see this string being used anywhere? Shouldnt it be used in on of the unit tests?

2017-03-04 10:57 UTC, dynasource commented on framework/console/controllers/FixtureController.php
> +    }
it's hard to determine the quality of the logic without a dedicated unittest. It would be nice to have one for a proper understanding.

2017-03-04 10:57 UTC, dynasource commented on framework/console/controllers/FixtureController.php
> +        // $fixturesPath is normalized to unix format in getFixturesPath()
the argument naming does not match the @param doc. Currently I assume an object $fixture being passed.

2017-03-04 20:02 UTC, d1rtyf1ng3rs commented on tests/data/console/controllers/fixtures/subdir/SecondFixture.php
> +        FixtureStorage::$subdirSecondFixtureData[] = 'some data set for subdir/second fixture';
Well, the string (the value) itself *can*, but *doesn't have to* be used in unit tests.
The property, howerer, [is used in unit-tests](https://github.com/yiisoft/yii2/pull/13553/files/719f6aee4856d2e5bbd9b44100955d9e34f94573#diff-410e9261d60564f099dc41e3dd30a538).
P.s. In fact, all the added fixtures and their usage in tests are *the same* as of existing fixtures.

2017-03-04 20:10 UTC, d1rtyf1ng3rs commented on framework/console/controllers/FixtureController.php
> +        // $fixturesPath is normalized to unix format in getFixturesPath()
Negative.
`$fixture` is a string; one of the strings that `FileHelper::findFiles()` returns [here](https://github.com/yiisoft/yii2/pull/13553/files/719f6aee4856d2e5bbd9b44100955d9e34f94573#diff-96190cbb10ccc75fed657c73f25ae920L414).

2017-03-04 20:26 UTC, d1rtyf1ng3rs commented on framework/console/controllers/FixtureController.php
> +    }
The new function `getFixtureRelativeName()` is triggered on both `load`/`unload` actions, so is involved in all tests that use those actions.
Yet, I agree - its' tests are rather "not obvious" / "non-direct".

If dedicated tests for it are absolutely necessary, I would need some help in form of hints, guidelines or requirements for them. Or any description of what is the "good-enough" form for them.

2017-03-04 21:37 UTC, dynasource commented on framework/console/controllers/FixtureController.php
> +        // $fixturesPath is normalized to unix format in getFixturesPath()
The function argument should be more clear, in this case $fullFixturePath if the @param comment is correctly formulated.

2017-03-04 21:37 UTC, dynasource commented on framework/console/controllers/FixtureController.php
> +    }
Agree. It's a nice to have as you already covered it.

2017-03-04 21:37 UTC, dynasource commented on tests/data/console/controllers/fixtures/subdir/SecondFixture.php
> +        FixtureStorage::$subdirSecondFixtureData[] = 'some data set for subdir/second fixture';
if thats the case, it would be nice to have this string formulated empty or with a more understandable description `'dummy string'`

2017-03-04 22:27 UTC, rob006 requested changes

2017-03-04 22:27 UTC, rob006 commented on framework/console/controllers/FixtureController.php
> +     * @param $fixture string Full fixture path
This phpdoc is invalid - type should go before param name:
```
     * @param string $fixture Full fixture path
```

2017-03-05 16:41 UTC, d1rtyf1ng3rs commented on tests/data/console/controllers/fixtures/subdir/SecondFixture.php
> +        FixtureStorage::$subdirSecondFixtureData[] = 'some data set for subdir/second fixture';
> more understandable description 'dummy string'

Agree. But still, I can't see any way this should've been guessed from all the other fixture contents.
I mean, check out any of the `tests/data/console/controllers/fixtures/*Fixture.php` - they all have their data in format of `"some data set for <fixture-name-here> fixture"`...
Hence the question: fixture content should be replaced to `dummy string` only in *added* fixtures, or in *all* of the mentioned fixtures?

2017-03-05 17:23 UTC, d1rtyf1ng3rs commented on framework/console/controllers/FixtureController.php
> +     * @param $fixture string Full fixture path
Should be fixed now, thanks.

2017-03-05 17:24 UTC, d1rtyf1ng3rs commented on framework/console/controllers/FixtureController.php
> +        // $fixturesPath is normalized to unix format in getFixturesPath()
Agree. Should be done now.

2017-05-18 14:30 UTC, dynasource approved these changes

2017-05-18 15:20 UTC, cebe requested changes

2017-05-18 15:20 UTC, cebe commented on framework/console/controllers/FixtureController.php
> +            $foundFixtures[] = $relativeName;
no need to have a variable here, just do `$foundFixtures[] = $this->getFixtureRelativeName($fixture);`

2017-05-18 15:20 UTC, cebe commented on framework/console/controllers/FixtureController.php
> +        $fullFixturePath = str_replace("\\", "/", $fullFixturePath);
how does this deal with Windows paths like `C:\Somedir`, looks like that does not work to me.

2017-05-18 18:16 UTC, samdark commented on framework/console/controllers/FixtureController.php
> +        $fullFixturePath = str_replace("\\", "/", $fullFixturePath);
Windows doesn't really care about which type of slash is used.

2017-05-19 07:50 UTC, cebe commented on framework/console/controllers/FixtureController.php
> +        $fullFixturePath = str_replace("\\", "/", $fullFixturePath);
sure, but if the alias resolves to `C:\whatever/fixturepath` it will not match `C:/whatever/fixturepath` as far as I see.

2017-05-19 09:12 UTC, dynasource commented on framework/console/controllers/FixtureController.php
> +        $fullFixturePath = str_replace("\\", "/", $fullFixturePath);
sharp. 
We need more unit tests to make ensure this usecase

2017-05-22 12:17 UTC, samdark commented on framework/console/controllers/FixtureController.php
> +        $fullFixturePath = str_replace("\\", "/", $fullFixturePath);
@d1rtyf1ng3rs would you please cover these cases?

2017-05-30 18:28 UTC, SilverFire commented
Merged f111ab441312272250fcd5a4372875715bdd7c66 with minor adjustments in f7c9e6b8528b22d086ea1fd95e0b99f8a3d24e35

Thank you!

2017-05-30 18:28 UTC, closed without merging