修改一处小小的笔误，$this 应为 $model
yiisoft/yii2 pull request #13568
Opened 2017-02-14 08:02 UTC by agangdi

namespace app\components;

use yii\validators\Validator;

class CountryValidator extends Validator
{
    public function validateAttribute($model, $attribute)
    {
        if (!in_array($model->$attribute, ['兲朝', '墙外'])) {
            $this->addError($attribute, '国家必须为 "兲朝" 或 "墙外" 中的一个。');
        }
    }
}

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2017-02-14 08:06 UTC, samdark requested changes

2017-02-14 08:06 UTC, samdark commented on docs/guide-zh-CN/input-validation.md
> +            $model->addError($attribute, '国家必须为 "兲朝" 或 "墙外" 中的一个。');
Seems it's outdated. See original: https://github.com/yiisoft/yii2/blob/master/docs/guide/input-validation.md#standalone-validators-

2017-02-15 08:10 UTC, agangdi commented on docs/guide-zh-CN/input-validation.md
> +            $model->addError($attribute, '国家必须为 "兲朝" 或 "墙外" 中的一个。');
It's still "$this->addError", I think it should be "$model->addError"

2017-02-15 08:23 UTC, samdark commented on docs/guide-zh-CN/input-validation.md
> +            $model->addError($attribute, '国家必须为 "兲朝" 或 "墙外" 中的一个。');
No https://github.com/yiisoft/yii2/blob/master/framework/validators/Validator.php#L404

2017-02-15 08:27 UTC, agangdi commented on docs/guide-zh-CN/input-validation.md
> +            $model->addError($attribute, '国家必须为 "兲朝" 或 "墙外" 中的一个。');
Should be "$model->addError($attribute,"  or "$this->addError($model, $attribute,"

2017-02-15 08:36 UTC, samdark commented on docs/guide-zh-CN/input-validation.md
> +            $model->addError($attribute, '国家必须为 "兲朝" 或 "墙外" 中的一个。');
Well, it is in the English text. Translation is, obviously, wrong. If you can update it according to English docs it would be great.

2017-02-15 08:42 UTC, agangdi commented on docs/guide-zh-CN/input-validation.md
> +            $model->addError($attribute, '国家必须为 "兲朝" 或 "墙外" 中的一个。');
Ok, It's really not a big error.  But let me have a try.

2017-02-15 09:06 UTC, agangdi commented
I've sent a new pull request, So just close this one.

2017-02-15 09:06 UTC, closed without merging