Implemented `yii\db\mssql\QueryBuilder::resetSequence()`
yiisoft/yii2 pull request #13582
Opened 2017-02-15 08:05 UTC by boboldehampsink

Mentioned in #13577 and #13581 and compatible with SQL Server 2008+.

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13577

2017-02-16 18:46 UTC, sergeymakinen requested changes

2017-02-16 18:46 UTC, sergeymakinen commented on framework/db/mssql/QueryBuilder.php
> +                $key = reset($table->primaryKey);
I guess it would be better to quote this as well:
```php
$key = $this->db->quoteColumnName(reset($table->primaryKey));
```

2017-02-17 13:29 UTC, boboldehampsink commented on framework/db/mssql/QueryBuilder.php
> +                $key = reset($table->primaryKey);
Isn't $table->primaryKey automatically quoted?

2017-02-17 13:29 UTC, boboldehampsink commented
No unit test has been written, as none of the other resetSequence() implementations are covered by tests either.

2017-02-17 13:42 UTC, sergeymakinen commented on framework/db/mssql/QueryBuilder.php
> +                $key = reset($table->primaryKey);
No, it’s stored as is.

2017-02-17 13:44 UTC, boboldehampsink commented on framework/db/mssql/QueryBuilder.php
> +                $key = reset($table->primaryKey);
Added

2017-02-17 13:46 UTC, sergeymakinen approved these changes

2017-02-17 13:51 UTC, sergeymakinen commented on framework/db/mssql/QueryBuilder.php
> +                $value = "(SELECT COALESCE(MAX(\"{$key}\"),0) FROM {$tableName})+1";
`MAX({$key})` should be used as it will be automatically enclosed in quotes.

2017-02-17 13:53 UTC, boboldehampsink commented on framework/db/mssql/QueryBuilder.php
> +                $value = "(SELECT COALESCE(MAX(\"{$key}\"),0) FROM {$tableName})+1";
True. This implementation is based on the PGSQL implementation. Fix it there too?

2017-02-17 14:00 UTC, sergeymakinen commented on framework/db/mssql/QueryBuilder.php
> +                $value = "(SELECT COALESCE(MAX(\"{$key}\"),0) FROM {$tableName})+1";
I think it would be nice (in a separate PR). :)

2017-02-17 14:02 UTC, boboldehampsink commented on framework/db/mssql/QueryBuilder.php
> +                $value = "(SELECT COALESCE(MAX(\"{$key}\"),0) FROM {$tableName})+1";
Fixed. Will open new PR for PGSQL.

2017-02-18 21:02 UTC, samdark approved these changes

2017-02-18 21:03 UTC, samdark commented
@boboldehampsink still would be great to cover it with tests. Probably w/ general implementation.

2017-02-20 10:11 UTC, boboldehampsink commented
Ok. Maybe its better to open a new PR for the general implementation of resetSequence() tests?

2017-02-20 10:48 UTC, samdark commented
Yes.

2017-02-20 11:12 UTC, boboldehampsink commented
Ok. For now I first implemented a simple test for MSSQL.

2017-02-20 11:45 UTC, dynasource approved these changes
looks ok to me

2017-02-20 11:54 UTC, merged

2017-02-20 11:54 UTC, samdark commented
Merged. Thanks!