`yii\db\QueryBuilder::truncateTable` should work consistent over all databases
yiisoft/yii2 pull request #13580
Opened 2017-02-15 07:29 UTC by boboldehampsink

Cubrid, MSSQL, MySQL, and OCI already restart the identity by default, PGSQL doesn't. This PR makes the use of the `yii\db\QueryBuilder::truncateTable` method more consistent.

_Note: RESTART IDENTITY is available from PGSQL 8.4+_

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #13577

2017-02-15 07:37 UTC, samdark commented
The requirement of 8.4+ (2009) is OK. Would be good to mention it in docs here: http://www.yiiframework.com/doc-2.0/guide-db-dao.html

2017-02-15 07:38 UTC, samdark approved these changes

2017-02-15 07:44 UTC, boboldehampsink commented
Updated all docs

2017-02-15 21:48 UTC, SilverFire approved these changes

2017-02-16 08:38 UTC, dynasource requested changes

2017-02-16 08:38 UTC, dynasource commented on framework/db/pgsql/QueryBuilder.php
> +     * Builds a SQL statement for truncating a DB table.
can you add a description for the reason for restarting the Identity?

2017-02-16 09:22 UTC, boboldehampsink commented on framework/db/pgsql/QueryBuilder.php
> +     * Builds a SQL statement for truncating a DB table.
Sure, what about "Restarts identity to be consistent with other databases."?

2017-02-16 09:42 UTC, dynasource commented on framework/db/pgsql/QueryBuilder.php
> +     * Builds a SQL statement for truncating a DB table.
could you add an explanation about this 'consistency' and the exception for PGSQL for future reference?

2017-02-16 09:45 UTC, boboldehampsink commented on framework/db/pgsql/QueryBuilder.php
> +     * Builds a SQL statement for truncating a DB table.
"Explicitly restart identity for PGSQL to be consistent with other databases which all do this by default"

2017-02-16 09:46 UTC, dynasource commented on framework/db/pgsql/QueryBuilder.php
> +     * Builds a SQL statement for truncating a DB table.
perfect

2017-02-16 09:57 UTC, dynasource approved these changes

2017-02-20 20:38 UTC, merged

2017-02-20 20:38 UTC, samdark commented
Merged. Thanks!