Created unit tests for role based access filter
yiisoft/yii2 pull request #13597
Opened 2017-02-17 00:23 UTC by mrbig

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no - extra unit test coverage
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | none

I've noticed that there are no unit test for AccessControl filter that checks RBAC roles. I'm working on an access control enhancement, so to check the current behavior was a must.

This patch introduces a mock auth manager for the AccessRuleTest, than mimicks the auth schema from the [definitive guide](http://www.yiiframework.com/doc-2.0/guide-security-authorization.html), and also a test for role based authorization.

2017-02-18 18:56 UTC, samdark approved these changes

2017-02-18 19:10 UTC, dynasource requested changes
thanks for adding tests!

2017-02-18 19:10 UTC, dynasource commented on tests/framework/filters/AccessRuleTest.php
> +    protected function mockUser($userid = null)
I dont see an example with an empty argument in the unit tests?

2017-02-18 19:10 UTC, dynasource commented on tests/framework/filters/AccessRuleTest.php
> +    {
because of the repetition in your tests, please convert these to a PhpUnit dataProvider. This enables us to determine if all usecases are covered

2017-02-20 09:57 UTC, mrbig commented on tests/framework/filters/AccessRuleTest.php
> +    protected function mockUser($userid = null)
It is used by the already existing test cases (testMatchAction, testMatchVerb). I didn't want to break those, neither changes tests I'm not working with.
See lines: 121 and 185

2017-02-20 09:58 UTC, mrbig commented on tests/framework/filters/AccessRuleTest.php
> +    {
Current unit test for the ACF are built up like this. I doubt I'll have the time now to rewrite the whole thing now. Please take a look at the complete test:
https://github.com/yiisoft/yii2/blob/master/tests/framework/filters/AccessRuleTest.php

2017-02-23 20:06 UTC, SilverFire approved these changes

2017-02-23 20:17 UTC, cebe approved these changes

2017-02-23 20:26 UTC, dynasource approved these changes
dataprovider looks great. Thanks.
Fixed some types. 'excepted' is not the same as 'expected' ;)

2017-02-23 20:55 UTC, merged

2017-02-23 20:55 UTC, samdark commented
Thank you!