Fixes Oracle’s Schema::setTransactionIsolationLevel()
yiisoft/yii2 pull request #13592
Opened 2017-02-16 15:44 UTC by sergeymakinen

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | —

`PDO_OCI` doesn’t like a trailing semicolon (many tests are broken ATM) and Oracle only supports `READ COMMITED` and `SERIALIZABLE`.

2017-02-16 22:53 UTC, cebe requested changes

2017-02-16 22:53 UTC, cebe commented on framework/db/Schema.php
> +        $this->db->createCommand("SET TRANSACTION ISOLATION LEVEL $level")->execute();
this change should be made in the OCI subclass only.

2017-02-16 22:53 UTC, cebe commented on framework/db/oci/Schema.php
> +                throw new NotSupportedException(get_class($this) . ' only supports transaction isolation levels READ COMMITTED and SERIALIZABLE.');
isn't there an error thrown by the dbms already if you specify a different level? There should not be a need to cover this here.

2017-02-16 22:53 UTC, cebe commented on framework/db/oci/Schema.php
> +     * @since 2.0.12
`@since` is only needed if the interface changes. this method existed before 2.0.12 in the parent class so it is not new.

2017-02-16 23:46 UTC, sergeymakinen commented on framework/db/Schema.php
> +        $this->db->createCommand("SET TRANSACTION ISOLATION LEVEL $level")->execute();
There's should not be a semicolon. That's the point of PR.

2017-02-16 23:48 UTC, sergeymakinen commented on framework/db/oci/Schema.php
> +                throw new NotSupportedException(get_class($this) . ' only supports transaction isolation levels READ COMMITTED and SERIALIZABLE.');
I think you're right. In SQLite's class it handles a syntax difference but it's not needed here.

2017-02-17 03:02 UTC, dynasource requested changes

2017-02-18 20:55 UTC, samdark approved these changes

2017-02-19 07:14 UTC, dynasource approved these changes

2017-02-19 14:32 UTC, merged

2017-02-19 14:32 UTC, samdark commented
Merged. Thanks!