Closes #13243: Added support for unicode attribute names in `yii\widgets\DetailView`
yiisoft/yii2 pull request #13610
Opened 2017-02-18 10:23 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13243

2017-02-18 11:17 UTC, dynasource commented
shouldnt that ObjectMock extends from Model?

2017-02-18 11:19 UTC, arogachev commented
@dynasource Probably. That's how it initially was.

2017-02-18 11:22 UTC, dynasource commented
Im expecting that for testing the DetailView widget

2017-02-18 15:24 UTC, arogachev commented
@dynasource I changed the base class to `yii\base\Model`.

> That way we can make definition of attributes with unicode names less verbose.

But this does not make that definition less verbose. Actually PHP natively supports unicode in variable names, so why not to use it instead? Applied this change too.

2017-02-18 15:28 UTC, dynasource approved these changes

2017-02-18 19:02 UTC, samdark approved these changes

2017-02-22 14:21 UTC, SilverFire requested changes

2017-02-22 14:21 UTC, SilverFire commented on framework/widgets/DetailView.php
> +                if (!preg_match('/^([^:]+)(:(\w*))?(:(.*))?$/', $attribute, $matches)) {
The updated regular expression will allow attribute names, starting from the digit, e.g. `5nizza'. Is not allowed it PHP.

2017-02-24 16:54 UTC, arogachev commented on framework/widgets/DetailView.php
> +                if (!preg_match('/^([^:]+)(:(\w*))?(:(.*))?$/', $attribute, $matches)) {
@SilverFire As I said, I decided to use the same regex that's currently used for GridView. Seems like the same problem was fixed earlier for GridView only and DetailView's regex was not synchronized with these changes. That means earlier this regex was accepted. What you suggest to do? Fix it to not allow leading digits in both DetailView and GridView or just DetailView?

2017-02-24 17:09 UTC, SilverFire commented on framework/widgets/DetailView.php
> +                if (!preg_match('/^([^:]+)(:(\w*))?(:(.*))?$/', $attribute, $matches)) {
Ok, let it be

2017-02-24 17:09 UTC, SilverFire approved these changes

2017-02-24 21:19 UTC, merged

2017-02-24 21:19 UTC, samdark commented
Merged. Thanks!