Optimize `yii\data\ActiveDataProvider`
yiisoft/yii2 pull request #13617
Opened 2017-02-19 08:29 UTC by Kolyunya

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #12752 

Added tests to the #13467.

2017-02-19 14:43 UTC, samdark requested changes

2017-02-19 14:43 UTC, samdark commented on tests/framework/data/ActiveDataProviderTest.php
> +class UnqueryableQueryMock extends Query
Class should be in its own file.

2017-02-19 14:43 UTC, samdark commented on tests/framework/data/ActiveDataProviderTest.php
> +    public function testZeroModels()
I'd name it `testNoQueryWhenZeroModels` or something like that.

2017-02-19 15:02 UTC, Kolyunya commented on tests/framework/data/ActiveDataProviderTest.php
> +    public function testZeroModels()
What about `testDoesNotPerformQueryWhenHasNoModels`? This seems to be more like a real English sentence.

2017-02-19 15:02 UTC, Kolyunya commented on tests/framework/data/ActiveDataProviderTest.php
> +class UnqueryableQueryMock extends Query
Is `use yiiunit\framework\db\UnqueryableQueryMock`

2017-02-19 15:05 UTC, Kolyunya commented
@samdark fixed mentioned issues.

2017-02-19 15:12 UTC, dynasource commented on tests/framework/data/ActiveDataProviderTest.php
> +class UnqueryableQueryMock extends Query
I dont have a problem with keeping it in the current file as it is unlikely to be reused in other tests. Additionally it should be replaced by an anonymous class in PHP7 in the (hopefully near) future

2017-02-19 15:15 UTC, dynasource commented on tests/framework/data/ActiveDataProviderTest.php
> +    public function testZeroModels()
lets keep it close to the code. I would prefer something like: `testSkipQueryWhenZeroTotalCount()`

2017-02-19 15:16 UTC, Kolyunya commented on tests/framework/data/ActiveDataProviderTest.php
> +class UnqueryableQueryMock extends Query
@dynasource we may want to test the same thing (that a query was not performed)  if some other tests.

2017-02-19 16:29 UTC, samdark approved these changes

2017-02-20 06:55 UTC, dynasource approved these changes

2017-02-20 09:00 UTC, merged

2017-02-20 09:00 UTC, samdark commented
Merged. Thanks!