yii2-13637 Same logger in Yii and Yii::$app->log->logger
yiisoft/yii2 pull request #13641
Opened 2017-02-22 15:31 UTC by antonmarin

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13637, #12163

2017-03-02 18:29 UTC, antonmarin commented
Seems like pr is ready now :)

2017-03-02 20:39 UTC, cebe commented
This is a breaking change, so if we fix it, this should be done in 2.1.

2017-03-03 05:18 UTC, antonmarin commented
@cebe it breaks only if you try logging before application initialization. Is it possible?

2017-03-04 10:07 UTC, samdark commented
Yes. It is what's done automatically for `trace` level if `YII_DEBUG` is true. It logs all the app init sequence.

2017-03-04 10:10 UTC, antonmarin commented
@samdark isn't log components bootstapped at this time?

2017-03-04 10:11 UTC, samdark commented
It should be.

2017-03-04 10:14 UTC, antonmarin commented
@samdark so, do i understand right that it will be ok if log component should always bootstrap because it used while application initialization? What about i add log component to BaseApplication->bootstrap?

2017-03-04 10:17 UTC, samdark commented
I think so. @cebe, @SilverFire, @dynasource, @klimov-paul what do you think?

2017-03-04 11:03 UTC, dynasource commented
IMO, the Application should not bootstrap anything by default at all. It should be a slim as possible, ideally just enough to survive.

Regarding the logging. This should be refactored in the framework to be optional, like is requested is several topics throughout the issue tracker. The problem is performance and hickups during processing of large data. It is hard for people to understand why it is occurring and to eventually understand it to be happing because of a Logger (which they seemed to have disabled).

2017-03-05 08:22 UTC, antonmarin commented
@dynasource as @samdark said there is logging all the app init sequence, so is it possible to make logger optional? I think the only way is to create some DummyLogger or remove logging from app init. If you prefer first way, so my PR is actual, and the other way is to remove both logging and bootstrap logger. Have i missed something?

2017-03-10 18:27 UTC, antonmarin commented
any updates?

2017-03-10 18:41 UTC, samdark commented
Actually, I've re-checked code and I'm not so sure if we're actually logging init sequence prior to log is initialized. A good way to check it is to set logging level to trace, enable debug, run a single request and save logs. Then check if logs are the same with this pull request.

2017-03-10 18:45 UTC, antonmarin commented
`yii\base\Controller:130 Yii::trace('Route to run: ' . $action->getUniqueId(), __METHOD__);`

2017-03-10 18:47 UTC, antonmarin commented
well what direction to move? set logger optional and check existence (not so pretty)? create dummy? or leave log bootstrapping?

2017-03-10 18:50 UTC, antonmarin commented
`\yii\base\Application:322 Yii::trace('Bootstrap with ' . get_class($component), __METHOD__);`

2017-03-10 18:51 UTC, antonmarin commented
Another way is to require Logger config as basePath

2017-03-10 18:57 UTC, samdark commented
Leave log bootstrapping. Bootstrap sequence is important and needs logging.

2017-03-10 19:01 UTC, antonmarin commented
ok. so what about merge? :)

2017-03-10 19:36 UTC, SilverFire requested changes

2017-03-10 19:36 UTC, SilverFire commented on tests/framework/BaseYiiTest.php
> +        BaseYii::getLogger();
`\yii\base\InvalidConfigException` may be thrown on `Logger` initialization as well. This test should be split

2017-03-10 19:36 UTC, SilverFire commented on framework/BaseYii.php
> +        throw new InvalidConfigException('No logger without application');
I think this exception will be popular so we should explicitly explain what's going on.

How about `Logger component must be initialized before using logging actions. Add "log" component to the "bootstrap" section of the configuration on the first position.`?

2017-03-14 20:43 UTC, dynasource requested changes
I would expect to see unit tests that reflect the title & the changes in this PR

2017-03-15 04:30 UTC, antonmarin commented
@dynasource, i don't understand. Could you explain in different words?

2017-03-15 08:08 UTC, dynasource commented
the title states "Same logger in Yii and Yii::$app->log->logger" but I can not see this by looking at the new unit tests. I can only see new tests about throwing errors which does not go into depth about your actual usecase.

2017-03-15 08:23 UTC, antonmarin commented
> DispatcherTest:62 already reflects current changes
$this->assertSame(Yii::getLogger(), $dispatcher->getLogger());

So, do i understang right, that you mean, that that test should be moved to separate test method?

2017-03-15 08:34 UTC, samdark commented
I think he means that the test should assert that logger is the same in both cases.

2017-03-15 08:36 UTC, dynasource commented
correct, and otherwise the title of this issue should be changed towards the real goal of this PR

2017-03-15 08:36 UTC, antonmarin commented
> I think he means that the test should assert that logger is the same in both cases.
> $this->assertSame(Yii::getLogger(), $dispatcher->getLogger());
isn't that do it?

2017-03-15 16:46 UTC, antonmarin commented
so i change title as test already exists

2017-03-31 05:44 UTC, antonmarin commented
any update?

2017-04-01 14:14 UTC, samdark requested changes

2017-04-01 14:14 UTC, samdark commented on framework/log/Dispatcher.php
> +            $this->setLogger('yii\log\Logger');
`\yii\log\Logger::class` could be used.

2017-04-01 14:23 UTC, antonmarin commented on framework/log/Dispatcher.php
> +            $this->setLogger('yii\log\Logger');
But Yii requires php 5.4?

2017-04-01 15:13 UTC, sergeymakinen commented on framework/log/Dispatcher.php
> +            $this->setLogger('yii\log\Logger');
This PR is aimed for Yii 2.1 which requires PHP 5.5 ATM.

2017-07-18 08:51 UTC, TerraSkye commented on framework/log/Dispatcher.php
> +            $this->setLogger('yii\log\Logger');
2.1 is set for 7.1 if im not mistaken https://github.com/yiisoft/yii2/issues/11397

2017-07-18 10:09 UTC, cebe commented on framework/log/Dispatcher.php
> +            $this->setLogger('yii\log\Logger');
@TerraSkye correct, but that decision has been made after @sergeymakinen commented ;)

2017-07-18 10:50 UTC, samdark commented
I'm thinking about ditching our logger altogether and using PSR-3 compatible interface with monolog as default implementation.

2017-07-18 11:04 UTC, sergeymakinen commented
@samdark I couldn't agree more. Even though I love the Yii logger.

2017-07-18 14:06 UTC, dynasource commented
Yeah. Good idea

2017-08-02 09:01 UTC, antonmarin commented
great idea, so maybe i should close PR?

2017-08-02 11:00 UTC, samdark commented
Yes. Would be cool if you'll create another issue about using PSR-3 and reference this one. Thanks.

2019-04-23 20:58 UTC, closed without merging

2019-04-23 20:58 UTC, samdark commented
Won't be merged into 2.0.