Readme redesign
yiisoft/yii2 pull request #13682
Opened 2017-02-28 17:48 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | none

2017-02-28 18:05 UTC, dynasource requested changes
good improvements

2017-02-28 18:05 UTC, dynasource commented on README.md
> +It is fast, secure and efficient and works right out of the box using reasonable defaults.
its a bit unclear how to interpretate 'using reasonable defaults'?

2017-02-28 18:05 UTC, dynasource commented on README.md
> +You may join them and:
'them' feels less warm than 'us'

2017-02-28 18:07 UTC, samdark commented on README.md
> +It is fast, secure and efficient and works right out of the box using reasonable defaults.
Means instead of having to configure every aspect of the framework from scratch it is pre-configured for you with some default which are mostly fine.

2017-02-28 22:11 UTC, SilverFire approved these changes

2017-02-28 22:12 UTC, SilverFire requested changes

2017-02-28 22:12 UTC, SilverFire commented on README.md
> +<div align="center">
https://github.com/yiisoft/yii2/blob/17eb053341855154558e9e234039bb5f8c7b4da8/README.md

As far a I see, markdown inside HTML does not work good

2017-02-28 22:20 UTC, cebe commented on README.md
> +<div align="center">
yes, If a HTML block is started everything inside is not considered markdown. This only works in Markdown Extra, not GFM.

2017-02-28 22:25 UTC, cebe commented
edited it a bit:  	b66c5c3

2017-02-28 22:25 UTC, cebe approved these changes

2017-03-01 08:55 UTC, dynasource approved these changes

2017-03-01 09:23 UTC, SilverFire approved these changes

2017-03-01 09:27 UTC, merged