setStatusCode method of Response should return $this
yiisoft/yii2 pull request #13695
Opened 2017-03-03 17:23 UTC by kyle-mccarthy

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

The `setStatusCode` method of `yii\web\Response` should return the Response instance.  This will allow for returning a response in a controller without having issues related to returning void.

```
/**
 * @return \yii\web\Response 
 */
public function actionExample()
{
    $model = new Example();
    if ($model->load(Yii::$app->request->post() && $model->save()) {
        return $this->asJson(['message' => 'Example saved']);
    }
    return $this->asJson(['message' => 'Could not save example', 'errors' => $model->getErrors()])->setResponseCode(400);
}
```

2017-03-03 20:24 UTC, SilverFire requested changes

2017-03-03 20:24 UTC, SilverFire commented on framework/web/Response.php
> +     * @return $this
`@return $this the response object itself`

2017-03-03 20:24 UTC, SilverFire commented on framework/CHANGELOG.md
> +- Enh: `setStatusCode` in `\yii\web\Response` returns `$this` (kyle-mccarthy)
<code>Enh #13695: \`\yii\web\Response::setStatusCode()\` method now returns the Response object itself (kyle-mccarthy)</code>

2017-03-03 20:42 UTC, kyle-mccarthy commented
@SilverFire I made the requested changes and merged with master also.  Let me know if you see anything else!

2017-03-04 08:18 UTC, SilverFire approved these changes

2017-03-04 09:58 UTC, samdark approved these changes

2017-03-04 10:46 UTC, dynasource approved these changes

2017-03-04 15:53 UTC, 13065176046 commented
很不错

2017-03-04 15:55 UTC, merged

2017-03-04 15:55 UTC, samdark commented
Merged. Thanks!