Fix immutable sluggable behavior
yiisoft/yii2 pull request #13729
Opened 2017-03-08 17:18 UTC by Kolyunya

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13728

2017-03-08 20:54 UTC, samdark approved these changes

2017-03-10 18:48 UTC, SilverFire approved these changes

2017-03-14 20:25 UTC, dynasource requested changes

2017-03-14 20:25 UTC, dynasource commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
this feels a bit magical and is taking too much time to understand. Can you support this with a comment to explain why true is to be returned when attribute is null?

2017-03-14 20:39 UTC, Kolyunya commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
Wouldn't [this](https://github.com/yiisoft/yii2/pull/13747) be sufficient?

2017-03-14 20:48 UTC, Kolyunya commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
Sorry I missed the line.

2017-03-14 21:08 UTC, Kolyunya commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
Seems like we can optimize this condition for the case when `$value` is a string. We can compare it to the current slug value. Do you think it worth implementing?

For the case when `$value` is `callable` the comment would be:
> Callback-based non-immutable slugs should be recalculated each time.

2017-03-14 21:15 UTC, dynasource commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
well, the current state of SluggableBehavior is too vague IMO, so every step to make it more readable is a step in the right direction.

2017-03-14 21:28 UTC, Kolyunya commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
Should we add another condition for the case when `$value` is a string or just recalculate all value-based slugs?

2017-03-14 21:33 UTC, dynasource commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
what would be the usecase for that?

2017-03-14 21:37 UTC, Kolyunya commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
When the slug is string-based and it's value is equal to the `$value` we can return `false` and slug value won't be recalculated.

2017-03-14 21:43 UTC, dynasource commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
if this condition had to be covered by a method with a proper self declaring name, how would you call this method?

2017-03-15 07:40 UTC, Kolyunya commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
Do you think we should move this condition to a separate method?

I added a WIP comment. The problem is that it tells that `callback-based` slugs are always reevaluated but in fact all `value-based` slugs are always reevaluated at the moment.

2017-03-15 08:02 UTC, dynasource commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
Im trying to get concrete answers to my questions to get a proper understanding ;)

2017-03-15 08:17 UTC, Kolyunya commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
Could you please ask a *self-contained* concrete question please? What particularly don't you understand?

2017-03-15 08:31 UTC, dynasource commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
We want to know 'what' the software does and not 'how' he does it. 

I tried to get to this, but I could not get clear answers to my questions. Examples:

* My question "Can you support this with a comment to explain why true is to be returned when attribute is null" in https://github.com/yiisoft/yii2/pull/13729#discussion_r106017513 gets a vague implementation reaction in https://github.com/yiisoft/yii2/pull/13729#discussion_r106027562
* My question "what would be the usecase for that" gets an answer about implemantation details in https://github.com/yiisoft/yii2/pull/13729#discussion_r106033797 but not about the "why" which was my question
* My last question to understand the "why" https://github.com/yiisoft/yii2/pull/13729#discussion_r106035189 was about trying to get you to formulate the usecase into a understandable testMethod, but again I dont get an corresponding answer to my question in https://github.com/yiisoft/yii2/pull/13729#discussion_r106101040

To go back to the code. My problem is to understand the logic behind `$this->attribute === null`. What is the meaning of it. Why is it added? By purely looking at the code, I have to put effort into understand it. This goes against the best practice that code should be self-explanatory and instantly understandable. 

So again. We want to know 'what' the software does and not 'how' he does it.

2017-03-15 09:24 UTC, Kolyunya commented on framework/behaviors/SluggableBehavior.php
> +        if ($this->attribute === null) {
> Can you support this with a comment to explain why true is to be returned when attribute is null?
Yes I can. And I did it here: https://github.com/yiisoft/yii2/pull/13729/files#r106027562

> What would be the usecase for that?
String-based slugs.

> What is the meaning of it. Why is it added?
It seems to be obvious for me. It's not possible to tell if new slug is needed or not for callback-based slugs. That is why a new value is always needed for such slugs.

2017-04-20 18:30 UTC, merged

2017-04-20 18:30 UTC, samdark commented
Merged. Thank you!

2017-04-20 18:31 UTC, Kolyunya commented
Glad to help!