WIP: Add PHP_CodeSniffer to Travis CI config
yiisoft/yii2 pull request #13732
Opened 2017-03-08 23:53 UTC by Kolyunya

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

**Disclamer**: This is a WIP.

I'd like to suggest to make use of the `PHP_CodeSniffer` during `Travis CI` checks to improve the general quality of the framework code and to prevent `PSR-2` violations.

I configured `PHP_CodeSniffer` to report no(*)(**) errors or warnings at all for the framework core while having most strict checks for both errors and warnings.

Proposed fixes are just a raw draft. We can decide not to adopt some rules altogether.

I'd like to know if you think this whole idea worth working at or not.

* There are actually two errors reported but they are going to be fixed in the upcoming `PHP_CodeSniffer` release.
** No errors are reported after proposed fixes.

2017-03-09 00:16 UTC, samdark requested changes

2017-03-09 00:16 UTC, samdark commented on framework/assets/yii.gridView.js
> +    function initEventHandler($gridView, type, event, selector, callback)
I don't think it should be applied to JavaScript.

2017-03-09 00:16 UTC, samdark commented on framework/assets/yii.js
> +    function initCsrfHandler()
I don't think it should be applied to JavaScript.

2017-03-09 00:16 UTC, samdark commented on framework/assets/yii.validation.js
> +    function getUploadedFiles(attribute, messages, options)
I don't think it should be applied to JavaScript.

2017-03-09 00:16 UTC, samdark commented on framework/requirements/views/web/index.php
> +        <?php if ($summary['errors'] > 0) : ?>
Does not look correct to me.

2017-03-09 00:16 UTC, samdark commented on framework/views/_addColumns.php
> +<?php foreach ($fields as $field) : ?>
Doesn't look correct to me.

2017-03-09 00:16 UTC, samdark commented on framework/views/_addForeignKeys.php
> +<?php foreach ($foreignKeys as $column => $fkData) : ?>
Doesn't look correct to me.

2017-03-09 00:16 UTC, samdark commented on framework/views/_createTable.php
> +<?php foreach ($fields as $field) :
Doesn't look correct to me.

2017-03-09 00:16 UTC, samdark commented on framework/views/_dropColumns.php
> +foreach ($fields as $field) : ?>
Doesn't look correct to me.

2017-03-09 00:16 UTC, samdark commented on framework/views/_dropForeignKeys.php
> +<?php foreach ($foreignKeys as $column => $fkData) : ?>
Doesn't look correct to me.

2017-03-09 00:27 UTC, Kolyunya commented on framework/assets/yii.gridView.js
> +    function initEventHandler($gridView, type, event, selector, callback)
I thing JS should be validated as well. If not by the `PHPCS` then by what? Don't mind dropping `JS` validation via `PHPSC` altogether though.

2017-03-09 00:30 UTC, Kolyunya commented on framework/requirements/views/web/index.php
> +        <?php if ($summary['errors'] > 0) : ?>
This seems to be correct: https://github.com/squizlabs/PHP_CodeSniffer/issues/366#issuecomment-66937317

> I'm not sure what PSR2 actually intends in this case. They don't mention the alternate syntax anywhere. So I still need to enforce the spaces after opening parentheses error, which means you code will look like this after I fix these issues:

2017-03-09 00:30 UTC, Kolyunya commented on framework/views/_addColumns.php
> +<?php foreach ($fields as $field) : ?>
This seems to be correct: https://github.com/squizlabs/PHP_CodeSniffer/issues/366#issuecomment-66937317

> I'm not sure what PSR2 actually intends in this case. They don't mention the alternate syntax anywhere. So I still need to enforce the spaces after opening parentheses error, which means you code will look like this after I fix these issues:

2017-03-09 00:30 UTC, Kolyunya commented on framework/views/_createTable.php
> +<?php foreach ($fields as $field) :
This seems to be correct: https://github.com/squizlabs/PHP_CodeSniffer/issues/366#issuecomment-66937317

> I'm not sure what PSR2 actually intends in this case. They don't mention the alternate syntax anywhere. So I still need to enforce the spaces after opening parentheses error, which means you code will look like this after I fix these issues:

2017-03-09 00:30 UTC, Kolyunya commented on framework/views/_dropColumns.php
> +foreach ($fields as $field) : ?>
This seems to be correct: https://github.com/squizlabs/PHP_CodeSniffer/issues/366#issuecomment-66937317

> I'm not sure what PSR2 actually intends in this case. They don't mention the alternate syntax anywhere. So I still need to enforce the spaces after opening parentheses error, which means you code will look like this after I fix these issues:

2017-03-09 00:30 UTC, Kolyunya commented on framework/views/_dropForeignKeys.php
> +<?php foreach ($foreignKeys as $column => $fkData) : ?>
This seems to be correct: https://github.com/squizlabs/PHP_CodeSniffer/issues/366#issuecomment-66937317

> I'm not sure what PSR2 actually intends in this case. They don't mention the alternate syntax anywhere. So I still need to enforce the spaces after opening parentheses error, which means you code will look like this after I fix these issues:

2017-03-09 00:31 UTC, Kolyunya commented on framework/views/_addForeignKeys.php
> +<?php foreach ($foreignKeys as $column => $fkData) : ?>
This seems to be correct: https://github.com/squizlabs/PHP_CodeSniffer/issues/366#issuecomment-66937317

> I'm not sure what PSR2 actually intends in this case. They don't mention the alternate syntax anywhere. So I still need to enforce the spaces after opening parentheses error...

2017-03-09 00:33 UTC, Kolyunya commented on framework/assets/yii.js
> +    function initCsrfHandler()
https://github.com/yiisoft/yii2/pull/13732#discussion_r105060381

2017-03-09 00:33 UTC, Kolyunya commented on framework/assets/yii.validation.js
> +    function getUploadedFiles(attribute, messages, options)
https://github.com/yiisoft/yii2/pull/13732#discussion_r105060381

2017-03-09 00:33 UTC, Kolyunya commented on framework/views/_addColumns.php
> +<?php foreach ($fields as $field) : ?>
https://github.com/yiisoft/yii2/pull/13732#discussion_r105060849

2017-03-09 00:33 UTC, Kolyunya commented on framework/views/_addForeignKeys.php
> +<?php foreach ($foreignKeys as $column => $fkData) : ?>
https://github.com/yiisoft/yii2/pull/13732#discussion_r105060849

2017-03-09 00:33 UTC, Kolyunya commented on framework/views/_createTable.php
> +<?php foreach ($fields as $field) :
https://github.com/yiisoft/yii2/pull/13732#discussion_r105060849

2017-03-09 00:33 UTC, Kolyunya commented on framework/views/_dropColumns.php
> +foreach ($fields as $field) : ?>
https://github.com/yiisoft/yii2/pull/13732#discussion_r105060849

2017-03-09 00:33 UTC, Kolyunya commented on framework/views/_dropForeignKeys.php
> +<?php foreach ($foreignKeys as $column => $fkData) : ?>
https://github.com/yiisoft/yii2/pull/13732#discussion_r105060849

2017-03-09 00:42 UTC, Kolyunya commented on framework/views/errorHandler/callStackItem.php
> -<li class="<?php if ($index === 1 || !$handler->isCoreFile($file)) echo 'application'; ?> call-stack-item"
This is what `PHPCBF` thinks it should look like. Haven't reviewed this myself yet.

2017-03-09 00:42 UTC, Kolyunya commented on framework/views/errorHandler/callStackItem.php
> -                <?php if ($line !== null) echo 'at line'; ?>
This is what `PHPCBF` thinks it should look like. Haven't reviewed this myself yet.

2017-03-09 00:43 UTC, Kolyunya commented on framework/views/errorHandler/exception.php
> -        if ($exception instanceof \yii\web\HttpException) {
This is what `PHPCBF` thinks it should look like. Haven't reviewed this myself yet.

2017-03-09 00:43 UTC, Kolyunya commented on framework/views/errorHandler/exception.php
> -                if ($exception instanceof \yii\web\HttpException) {
This is what `PHPCBF` thinks it should look like. Haven't reviewed this myself yet.

2017-03-09 00:51 UTC, Kolyunya commented on framework/views/_createTable.php
> +<?php foreach ($fields as $field) :
https://github.com/yiisoft/yii2/pull/13732#discussion_r105060849

2017-03-09 06:35 UTC, samdark commented on framework/assets/yii.gridView.js
> +    function initEventHandler($gridView, type, event, selector, callback)
It's OK to be validated but the standard should not be the same as for PHP. Common placement of `{` in JavaScript is same line.

2017-03-09 06:36 UTC, samdark commented on framework/views/errorHandler/callStackItem.php
> -                <?php if ($line !== null) echo 'at line'; ?>
This fix is OK.

2017-03-09 06:43 UTC, samdark commented on framework/requirements/views/web/index.php
> +        <?php if ($summary['errors'] > 0) : ?>
No PSR mentions it including PSR-12 in the works but Yii's internal doc does: https://github.com/yiisoft/yii2/blob/master/docs/internals/view-code-style.md

Accoding to the doc it should be:

```php
<?php if ($summary['errors'] > 0): ?>
```

i.e. no space.

2017-03-09 07:31 UTC, Kolyunya commented on framework/assets/yii.gridView.js
> +    function initEventHandler($gridView, type, event, selector, callback)
Removed `*.js` files validation altogether for the time being.

2017-03-09 07:32 UTC, Kolyunya commented on framework/requirements/views/web/index.php
> +        <?php if ($summary['errors'] > 0) : ?>
Excluded that rule.

2017-03-09 08:39 UTC, rob006 commented
I think that using https://github.com/FriendsOfPHP/PHP-CS-Fixer would be much more useful and flexible.

2017-03-09 09:08 UTC, Kolyunya commented
@rob006 what are the particular issues of the current setup which could be solved the `PHP-CS-Fixer`?

2017-03-09 09:30 UTC, rob006 commented
PHP-CS-Fixer is easier to configure and extend. It has more active development and community IMO. 

I also made a quick look into fixes from this PR and many of this changes looks invalid and just dumb. I never had such problems with `PHP-CS-Fixer` before. 

I could open alternative PR with PHP-CS-Fixer integration, so we could just compare results and choose better tool for this.

2017-03-09 09:36 UTC, Kolyunya commented
> many of this changes looks invalid and just dumb.

Could you name them explicitly please (excluding `views`)?

2017-03-09 09:42 UTC, rob006 commented
```diff
diff --git a/framework/db/Query.php b/framework/db/Query.php
index b20a8b4..c95b734 100644
--- a/framework/db/Query.php
+++ b/framework/db/Query.php
@@ -408,8 +408,7 @@ protected function queryScalar($selectExpression, $db)
             return null;
         }
 
-        if (
-            !$this->distinct
+        if (!$this->distinct
             && empty($this->groupBy)
             && empty($this->having)
             && empty($this->union)
```

```diff
diff --git a/framework/mutex/OracleMutex.php b/framework/mutex/OracleMutex.php
index bf78add..b0f1d88 100644
--- a/framework/mutex/OracleMutex.php
+++ b/framework/mutex/OracleMutex.php
@@ -89,14 +89,14 @@ protected function acquireLock($name, $timeout = 0)
 
         /** inside pl/sql scopes pdo binding not working correctly :(  */
         $this->db->createCommand(
-                'DECLARE
+            'DECLARE
     handle VARCHAR2(128);
 BEGIN
     DBMS_LOCK.ALLOCATE_UNIQUE(:name, handle);
     :lockStatus := DBMS_LOCK.REQUEST(handle, DBMS_LOCK.' . $this->lockMode . ', ' . $timeout . ', ' . $releaseOnCommit . ');
 END;',
-                [':name' => $name]
-            )
+            [':name' => $name]
+        )
             ->bindParam(':lockStatus', $lockStatus, PDO::PARAM_INT, 1)
             ->execute();
```

Why "excluding /views/"? Don't you want fix views files too?

2017-03-09 09:50 UTC, Kolyunya commented
> PHP-CS-Fixer is easier to configure and extend.

@rob006  what do you mean by `easier`? Configuring each of the rules is a matter of a single (couple) lines in the config.

```php
diff --git a/framework/db/Query.php b/framework/db/Query.php
index b20a8b4..c95b734 100644
--- a/framework/db/Query.php
+++ b/framework/db/Query.php
@@ -408,8 +408,7 @@ protected function queryScalar($selectExpression, $db)
             return null;
         }
 
-        if (
-            !$this->distinct
+        if (!$this->distinct
             && empty($this->groupBy)
             && empty($this->having)
             && empty($this->union)
```
This is a matter of the convention. I like the proposed change.

```php
diff --git a/framework/mutex/OracleMutex.php b/framework/mutex/OracleMutex.php
index bf78add..b0f1d88 100644
--- a/framework/mutex/OracleMutex.php
+++ b/framework/mutex/OracleMutex.php
@@ -89,14 +89,14 @@ protected function acquireLock($name, $timeout = 0)
 
         /** inside pl/sql scopes pdo binding not working correctly :(  */
         $this->db->createCommand(
-                'DECLARE
+            'DECLARE
```
Why would you use 8 spaces for indentation instead of 4 here?

2017-03-09 10:08 UTC, Kolyunya commented
@rob006 I simplified the config to the maximum extent possible and left *only* `PSR-2` rules while removing all others. Would you mind reviewing reported issues now?

2017-03-09 10:13 UTC, Kolyunya commented
```php
diff --git a/framework/db/Query.php b/framework/db/Query.php
index b20a8b4..c95b734 100644
--- a/framework/db/Query.php
+++ b/framework/db/Query.php
@@ -408,8 +408,7 @@ protected function queryScalar($selectExpression, $db)
             return null;
         }
 
-        if (
-            !$this->distinct
+        if (!$this->distinct
             && empty($this->groupBy)
             && empty($this->having)
             && empty($this->union)
```

@rob006 this is an obvious violation of the `PSR-2`.
>Opening parentheses for control structures MUST NOT have a space after them, and closing parentheses for control structures MUST NOT have a space before.

2017-03-09 10:15 UTC, rob006 commented
> what do you mean by easier?

In PHP-CS-Fixer configuration is an object. So you could create own class with configuration and easy share between different projects. You could also easy modify this configuration by extending config class. 

We could create composer package with yii2 specific configuration and fixers - then everybody could use Yii2 CS in his own project and made some modifications by extending yii2 cs config class. With `phpcs.xml` you need copy this file and keep sync manually.

> This is a matter of the convention. I like the proposed change.

It is much less readable and consistent. With long conditions it is easy to miss that indentation block is part of condition and not `if` body.

You also don't use 

```php
if ($something) { $this->doSomethig();
    $this->doSomethingElse();
}
```
so why you want do this in `if` condition block?

> Why would you use 8 spaces for indentation instead of 4 here?

I'm referring to:

```diff
-                [':name' => $name]
-            )
+            [':name' => $name]
+        )
             ->bindParam(':lockStatus', $lockStatus, PDO::PARAM_INT, 1)
             ->execute();
```

Why closing parenthesis is not intended with `->bindParam()`?

2017-03-09 10:23 UTC, Kolyunya commented
> It is much less readable and consistent.

The original version violates the standard:

> Opening parentheses for control structures MUST NOT have a space after them...

Regarding
>Why closing parenthesis is not intended with ->bindParam()?

Why should it be? Could you provide a quote from the standard please?

2017-03-09 10:35 UTC, rob006 commented
> The original version violates the standard:
> >   Opening parentheses for control structures MUST NOT have a space after them...

To be strict, there is no space after opening parenthesis - there is only a single `LF` char.
But there is a space before closing parenthesis (from indentation) and it is not fixed. Do you think that it should? :D

> Why should it be? Could you provide a rule from the standard which is violated please?

There is no rule, you just broke nice indentation. For what?

2017-03-09 10:45 UTC, Kolyunya commented
> There is no rule, you just broke nice indentation. For what?

@rob006 would you mind defining `nice`? `->bindParam()` is indented one block to the right of the `createCommand()` and this indentation is used all over the core [e.g.](https://github.com/yiisoft/yii2/blob/master/framework/caching/DbCache.php#L106).

2017-03-09 10:51 UTC, rob006 commented
Nice:
```php
        $query
            ->select(
                ['COUNT(*)']
            )
            ->from($this->cacheTable)
            ->where('[[id]] = :id AND ([[expire]] = 0 OR [[expire]] >' . time() . ')', [':id' => $key]);
```

Not nice:
```php
        $query->select(
            ['COUNT(*)']
        )
            ->from($this->cacheTable)
            ->where('[[id]] = :id AND ([[expire]] = 0 OR [[expire]] >' . time() . ')', [':id' => $key]);
```

Whole call chain should be intended once, so you can easily see when it starts and when it ends.

2017-03-09 10:55 UTC, Kolyunya commented
@rob006 this could become a `nice` proposal to the `PSR`. I'd gonna upvote it :D

2017-03-14 06:49 UTC, samdark approved these changes

2017-03-14 20:32 UTC, dynasource commented
@Kolyunya, whats your opinion about PHP-CS-Fixer?

2017-03-14 20:38 UTC, Kolyunya commented
@dynasource at the time of posting this PR I haven't tried it yet. I tried it a couple of days ago and it seemed to me that it's not a silver bullet either and should be tweaked too.

I think that we should stick to the tool which would provide most accurate reports. I just proposed a tool I was aware of.

2017-03-14 21:20 UTC, dynasource commented
I think it is a good suggestion and that it is useful to have one. Now we have 2 different solutions proposed here, we should choose one. Would be nice to have opinions from the @community.

2017-03-23 17:40 UTC, photodude commented
If you are just applying PSR2 why not use style-ci see https://styleci.io/

PHPCS and others are more for code styles that have complex requierments beyond things like PSR2

2017-03-23 17:42 UTC, Kolyunya commented
We will probably want to enforce custom Yii2 code-style.

2017-03-23 17:49 UTC, photodude commented
Do you have an existing list for what you want to enforce?

for example
- https://developer.joomla.org/coding-standards.html
- https://codex.wordpress.org/WordPress_Coding_Standards
- https://www.drupal.org/docs/develop/standards
- http://symfony.com/doc/current/contributing/code/standards.html
- https://laravel.com/docs/5.4/contributions#coding-style
- https://www.codeigniter.com/user_guide/general/styleguide.html

2017-03-23 17:51 UTC, Kolyunya commented
[Sure](https://github.com/yiisoft/yii2/blob/master/docs/internals/view-code-style.md).

2017-03-23 17:54 UTC, photodude commented
I think you will find some of those items can't be enforced without custom enforcer scripts (for example the way the comments and docblocks are written) as there is no standard available for what your presenting.

2017-03-23 17:56 UTC, photodude commented
There is also a big difference between a written code style with examples, and just an example file that shows acceptable coding (the latter is what you presented).

2017-03-24 02:22 UTC, gsherwood commented
Hi all. I maintain PHPCS so I thought I'd drop in and clear some things up.

PHPCS is a tool for checking coding standards in your project, whatever they may be. It ships with a few standards (including the old PEAR standard and the much newer PSR-1 and PSR-2 standards) but it is designed for you to pick and choose from the included rules and design your own. You can also write your own checks and auto-fixes if none of the included checks meet your requirements. For projects that have no idea what standard to use, using a built-in one is probably the easiest thing to do, but that's not a requirement. A lot of projects customise their coding standards, even if it is a simple as PSR-2 minus a couple of things they don't like.

PHPCS ships with lots of different report types to help you integrate it into IDEs, CI systems, text editors, and custom code, but you can also define your own custom report classes if you want. One report that might be useful is the [information](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting#printing-an-information-report) report. This one is used to tell you information about your code base and is helpful when deciding on a standard. I use this report to generate my [Analysis of Coding Conventions in PHP projects](https://squizlabs.github.io/PHP_CodeSniffer/analysis/). Note that I have Yii2 in there and I've found that your code is very consistent. You can view the report of how the project's coding conventions have changed over the last 2+ years here: https://squizlabs.github.io/PHP_CodeSniffer/analysis/yiisoft/yii2/index.html

Writing your own standard for PHPCS is a matter of creating an XML file. The format is quite extensive and allows for customisiation of the checks performed, but also the severity of each message, the message content itself, regex based file exclusions for checks (some projects don't want specific checks done on specific files or folders), and overriding a complete set of config variables.

That XML format is documented here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml

Also note that you can commit your standard as a file called `phpcs.xml` (or `phpcs.xml.dist`) in your project's root directory so that developers can just run `phpcs` and the standard tells PHPCS which files and directories to process, and what checks to perform. But you don't have to. You could also just pass around the XML file and use it with PHPCS to ensure people are running the same checks over their code. Or a sub-project could create their own custom standard that imports your XML file and changes a few things.

WordPress does this with [their coding standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards). You can see they have a main WordPress Core standard, but also extensions like VIP and Extra. They do a great job with their coding standards, have a lot of custom sniffs, contribute a lot back to PHPCS, and can fix quite a lot of the found errors automatically. It's worth taking a look at that repo if you want to see PHPCS in use.

[Drupal's Coder](https://www.drupal.org/project/coder) is another example of this, but it is less extensive. I also get a lot of good contributions from the developers of this project though.

The 3.0 version is the best to use right now if you are starting fresh, and that version also allows you to make use of PHPCS directly in code. For example, if you just want to run PHPCS over a snippet of code, you could do it like this: https://gist.github.com/gsherwood/aafd2c16631a8a872f0c4a23916962ac . Or if you'd like to tokenize JS files th same way PHP files are tokenized, you can use this code: https://gist.github.com/gsherwood/f17cfc90f14a9b29eeb6b2e99e6e7f66 . It adds a bit more flexibility to what is typically just a CLI tool.

PHPCS also comes with a tool called PHPCBF (officially, the PHP Code Beautifier and Fixer, but maybe you can figure out the unofficial name) which is used to fix coding standard issues. PHPCS reports errors and PHPCBF fixes them. Quite a lot of errors that PHPCS finds are fixable, and I've spent several years tweaking the fixers (especially the one that does indents) to work with a wide range of code. 

Despite concerns here that PHPCS development and community is not very active, I can tell you that I get a lot of contributions from developers and I've seen code in bug reports that no developer should probably see. But that helps me make PHPCS more robust and able to deal with a range of issues, including graceful handling of parse errors, which is pretty important if you want developers to be constantly checking standards in their IDE.

I hope this clears up a few things about PHPCS and hopefully I haven't taken up too much of your time.

Ultimately, you should choose whichever tool you think works best for your project. But I wanted to make it clear that PHPCS has been actively developed for more than 10 years and still gets 30-40k downloads a day. It's an active project with an active user base, and I think it has a very extensive feature set that makes it flexible enough for most projects. I'd encourage you to give it a go if you haven't already. It's free :)

2017-03-30 09:01 UTC, cebe commented
@gsherwood thanks for sharing your thoughts about this!

2017-03-30 16:32 UTC, samdark commented
So overall PHPCS looks like a good match and the changes in the pull request do make sense. @cebe how about merging it?

2017-03-30 16:40 UTC, Kolyunya commented
@samdark I think we should tweak config a bit. PHP CS Fixer [reported](https://github.com/yiisoft/yii2/pull/13778/files) some issues which PHPCS didn't.

2017-03-30 16:51 UTC, samdark commented
OK. Moving to 2.0.13 then.

2017-03-31 03:32 UTC, jrfnl commented
Hiya, I've had a quick look at some of the things PHP CS Fixes found which weren't reported by PHPCS so far and would like to make the below suggestions for rules to add to your ruleset to cover these.
You may also want to review the [existing exclusions in your ruleset](https://github.com/yiisoft/yii2/pull/13732/files#diff-6b216d983cf0a62e9c648934c5687456R8-10) carefully as they are partially to blame for the issues which weren't found.

N.B.: If you'd include the below suggestions, you may need/want to tweaks them a bit to exclude extraneous error codes coming from these sniffs which you are not interested in.

```xml
<!-- Covers: https://github.com/yiisoft/yii2/pull/13778/files#diff-ef822e03c117e20fd1d786afc7c5b5e3L772 and similar -->
<rule ref="Squiz.ControlStructures.ControlSignature" />

<!-- Covers: https://github.com/yiisoft/yii2/pull/13778/files#diff-03b64c04d37c13a3118b4b8119f5ae8dL439, https://github.com/yiisoft/yii2/pull/13778/files#diff-ef822e03c117e20fd1d786afc7c5b5e3L219, https://github.com/yiisoft/yii2/pull/13778/files#diff-85a8556277e468a30afc79beb7aa25dfL660 and similar -->
<rule ref="Generic.WhiteSpace.ScopeIndent">
    <properties>
        <property name="exact" value="4" />
    </properties>
</rule>

<!-- Covers: https://github.com/yiisoft/yii2/pull/13778/files#diff-c6dd99ed2184ed7a7f316aee5fe67513L492 and similar -->
<rule ref="Squiz.Commenting.PostStatementComment" />

<!-- Covers: https://github.com/yiisoft/yii2/pull/13778/files#diff-709ff61c838c754d533b87ec33f14908L115 and similar -->
<rule ref="PSR2.ControlStructures.ElseIfDeclaration.NotAllowed">
    <type>error</type>
</rule>

<!-- Covers: https://github.com/yiisoft/yii2/pull/13778/files#diff-f000680354101249e9f60e71e6278e3bL136 and similar -->
<rule ref="Generic.Functions.OpeningFunctionBraceBsdAllman" />

<!-- If you also want to enforce braces on the next line for closures: -->
<rule ref="Generic.Functions.OpeningFunctionBraceBsdAllman">
    <properties>
        <property name="checkClosures" value="true" />
    </properties>
</rule>

<!-- Covers: https://github.com/yiisoft/yii2/pull/13778/files#diff-3f97b6f0e759a8a52920b07abe345579L69, https://github.com/yiisoft/yii2/pull/13778/files#diff-74bb1570acfdb8abc2d6d89e79b0ab54L88 and similar -->
<rule ref="Squiz.WhiteSpace.SuperfluousWhitespace" />
```

I'm pretty sure there's actually also a sniff which will catch the extraneous blank lines, but I can't think of the name of the sniff off-hand.

Hope this helps ;-)

2017-05-01 23:06 UTC, rob006 commented
see #14100

2017-05-07 19:56 UTC, samdark commented
I like @rob006 approach more. Closing this one. @Kolyunya thank you for preparing the pull request. At least it triggered the continuation @rob006 did.

2017-05-07 19:56 UTC, closed without merging

2017-05-07 19:59 UTC, Kolyunya commented
@samdark I'm just curious what do you mean by the `approach`? It's possible to extract config and custom rules to a separate repository and it's possible to enable same rules.

2017-05-07 20:22 UTC, samdark commented
PHP configs are a bit more flexible than XML IMO but that both approaches (tools) are OK. Also @rob006 covered a lot of cases without false positives so it doesn't make sense to re-do the same using different tool, I think.