fix https://github.com/yiisoft/yii2/issues/13704
yiisoft/yii2 pull request #13766
Opened 2017-03-13 17:31 UTC by vladis84

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets #13704 by the PR, if any

2017-03-13 17:42 UTC, vladis84 commented
Лучше не смог придумать

2017-03-13 18:55 UTC, samdark requested changes

2017-03-13 18:55 UTC, samdark commented on framework/validators/UniqueValidator.php
> +        return is_null($this->targetClass) ? get_class($model) : $this->targetClass;
`$this->targetClass === null` should be used instead of `is_null`.

2017-03-14 13:08 UTC, vladis84 commented on framework/validators/UniqueValidator.php
> +        return is_null($this->targetClass) ? get_class($model) : $this->targetClass;
Well I will correct

2017-03-14 13:50 UTC, vladis84 commented on framework/validators/UniqueValidator.php
> +        return is_null($this->targetClass) ? get_class($model) : $this->targetClass;
Can it is better empty($this->targetClass)?

2017-03-14 13:51 UTC, samdark commented on framework/validators/UniqueValidator.php
> +        return is_null($this->targetClass) ? get_class($model) : $this->targetClass;
No.

2017-03-14 15:34 UTC, vladis84 commented
Add tests. Fix remarks.

2017-03-14 21:07 UTC, dynasource requested changes

2017-03-14 21:07 UTC, dynasource commented on tests/framework/validators/UniqueValidatorTest.php
> +        $validator->targetClass = 'target class';
this is not a real example of a targetClass right ;). Please strive to create a unit test that is instantly understable and also stable for the future. This is likely to break when is check on a real classname.

2017-03-14 21:07 UTC, dynasource commented on tests/framework/validators/UniqueValidatorTest.php
> +        // Not filled property targetClass.
you are preparing a new test scenario here. Please move this to a dedicated test method with a corresponding test name

2017-03-14 21:37 UTC, samdark approved these changes

2017-03-15 15:08 UTC, vladis84 commented on tests/framework/validators/UniqueValidatorTest.php
> +        $validator->targetClass = 'target class';
Fixed

2017-03-15 15:08 UTC, vladis84 commented on tests/framework/validators/UniqueValidatorTest.php
> +        // Not filled property targetClass.
Fixed

2017-03-15 16:10 UTC, dynasource approved these changes
looks better. Thanks

2017-03-16 05:28 UTC, arogachev requested changes

2017-03-16 05:28 UTC, arogachev commented on framework/validators/UniqueValidator.php
> +        $conditionsWithTableName = [];
IMO `$conditionsWithTableName variable` can be named better and probably shorter.

2017-03-16 05:28 UTC, arogachev commented on framework/validators/UniqueValidator.php
> +            $columnNameWithPrefix = "{$tableName}.$columnName";
The same applies to `$columnNameWithPrefix` variable. Maybe use `$prefixedColumnName` at least or even `$prefixedColumn` instead? Current name feels pretty verbose.

2017-03-16 05:28 UTC, arogachev commented on framework/validators/UniqueValidator.php
> +        foreach ($conditions as $columnName => $columnValue) {
Maybe use just `$column => $value` instead? These are loop's internal variables, also I don't see any coincidence with other similar variables or anything that can confuse understanding of a shorter variation.

2017-03-16 05:28 UTC, arogachev commented on framework/validators/UniqueValidator.php
> +        $conditionsWithTableName = [];
Also why not modify existing `$conditions` array instead of creating new one? I don't see any conditions in `foreach` loop.

2017-03-16 12:47 UTC, samdark commented
@vladis84 was it closed by accident?

2017-03-16 12:52 UTC, vladis84 commented
Deliberately closed. 
You do not need help.

2017-03-16 13:14 UTC, samdark commented
Hm? Why? We do need help and we appreciate contributing.

2017-03-16 14:33 UTC, SilverFire requested changes

2017-03-16 14:33 UTC, SilverFire commented on framework/validators/UniqueValidator.php
> +            $columnNameWithPrefix = "{$tableName}.$columnName";
`$columnName` should be quoted with `[$coumnName]`, shouldn't it?

2017-03-16 14:43 UTC, closed without merging

2017-03-16 14:44 UTC, samdark commented
Merged with some additional adjustments https://github.com/yiisoft/yii2/commit/3c1f3e20cfa260d1484fece29b255103b3bb6f5e. Thanks for contributing and sorry if we did something wrong. All these requests from core team members are to make framework better, not to offend contributors.

2017-03-16 14:45 UTC, samdark commented
> $columnName should be quoted with [$coumnName], shouldn't it?

Nope. It's already prepared in this case.

2017-03-16 14:57 UTC, vladis84 commented on framework/validators/UniqueValidator.php
> +        $conditionsWithTableName = [];
https://habrahabr.ru/post/136835/

2017-03-16 15:00 UTC, samdark commented on framework/validators/UniqueValidator.php
> +            $columnNameWithPrefix = "{$tableName}.$columnName";
Nope. It's already prepared in this case.

2017-03-16 15:01 UTC, samdark commented on framework/validators/UniqueValidator.php
> +        $conditionsWithTableName = [];
@arogachev how? Keys are modified in this case, not value.

2017-03-17 03:43 UTC, arogachev commented on framework/validators/UniqueValidator.php
> +        $conditionsWithTableName = [];
@vladis84, @samdark - OK, I missed that. But I still think that `$conditionsWithTableName` variable can be just something like `$prefixedConditions`. In this context it's clear what it means. Also it's shorter and more readable IMO. The same applies to other related variables such as `$columnNameWithPrefix` (can be just `$prefixedColumn`). What do you think?

2017-03-17 04:00 UTC, arogachev commented
@vladis84 wrote:

> Deliberately closed.
> You do not need help.

That's a weak argument.

@samdark wrote:

> sorry if we did something wrong

We did nothing wrong.

@samdark wrote:

> All these requests from core team members are to make framework better, not to offend contributors.

Exactly. You should respect framework's rules and adequately accept criticism. PR review is an important part of workflow for pretty much every program nowadays (especially for those that are intended for wide, non-personal use). Also PR review can contain **suggestions** for discussion. This does not mean that you are wrong and must immediately fix something, but for other core members and contributors to discuss. The final goal is to make things better and easier to maintain.

Sorry if it sounds straight - but If you can't deal with it - maybe it's a better option to not create PRs at all or just create issues to designate problem for example. Also I do not see any offence (even implicit) in this PR.

2017-03-17 11:32 UTC, samdark commented
@arogachev the matter is already settled.