Store regex for attribute names in one place. Allow '+' character.
yiisoft/yii2 pull request #13765
Opened 2017-03-13 15:39 UTC by SamMousa

Partial fix. Moves the regex to one place and adds support for the `+` character.
Does not add support for other non-word characters as mentioned in #4408.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #4408

2017-03-13 16:22 UTC, SamMousa commented
I"m not sure the failed tests are caused by my code changes...

Can someone restart the tests? 
If the tests pass I think this is something that can be merged relatively quickly since it is only a few lines of code and will not break any existing projects.

It also allows for more advanced local configuration (by changing `BaseHtml::$attributeRegex`).

2017-03-13 17:11 UTC, SilverFire requested changes

2017-03-13 17:11 UTC, SilverFire commented on framework/helpers/BaseHtml.php
> +    public static $attributeRegex = '/(^|.*\])([\w\.\+]+)(\[.*|$)/';
Could you add since tag and description?

2017-03-13 18:37 UTC, kmindi commented
Pls add a unit test as well, you can use or base yours on the one I proposed in the WIP PR https://github.com/yiisoft/yii2/pull/4446/files
Also I remember there was a comment by @cebe https://github.com/yiisoft/yii2/pull/4446#issuecomment-59438335 that states:
> attributes should not be exactly the same as allowed in gridview because gridview allows relational attribute names using . so ... must not be a valid name in Html.

2017-03-13 18:54 UTC, SamMousa commented
Will do!

On 13 Mar 2017 7:40 PM, "Yii-Bot for @yiisoft repository automation" <
notifications@github.com> wrote:

> Thank you for putting effort in the improvement of the Yii framework.
> We have reviewed your pull request.
>
> In order for the framework and your solution to remain stable in the
> future, we have a unit test requirement in place. Therefore we can only
> accept your pull request if it is covered by unit tests.
>
> Could you add these please?
>
> Thanks!
>
> P.S. If you have any questions about the creation of unit tests? Don't
> hesitate to ask for support. More information about unit tests
> <http://www.yiiframework.com/doc-2.0/guide-test-unit.html>
>
> *This is an automated comment, triggered by adding the label pr:request
> for unit tests.*
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yiisoft/yii2/pull/13765#issuecomment-286203530>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAhYzYdNENMD_EOLuBWkIiTsMG4-D6Z1ks5rlY2wgaJpZM4MbbOa>
> .
>

2017-03-13 19:21 UTC, samdark requested changes

2017-03-13 19:21 UTC, samdark commented on framework/helpers/BaseHtml.php
> +    public static $attributeRegex = '/(^|.*\])([\w\.\+]+)(\[.*|$)/u';
Need phpdoc.

2017-03-14 08:32 UTC, SamMousa commented
@kmindi Have added the unit test, based on your test cases. Have added your name to the changelog as well.

One of your test cases contained a `,` which is a non-word character so I've added that to the error cases instead!

2017-03-14 09:06 UTC, SamMousa commented
@samdark As usual these fixes are part of a feature we need in production ;-), any idea when 2.0.12 will be released?

2017-03-14 09:14 UTC, samdark approved these changes

2017-03-14 09:15 UTC, samdark commented
https://github.com/yiisoft/yii2/milestones/2.0.12

2017-03-14 20:54 UTC, dynasource requested changes
good changes. Please split the unit tests towards best practice of 'single' purpose.

2017-03-14 20:54 UTC, dynasource commented on tests/framework/helpers/HtmlTest.php
> +        if (!isset($expected)) {
it is not preferable to split logic in tests as tests should be instantly clear. Can you split this in 2 tests please?

2017-03-14 21:08 UTC, SamMousa commented
Will do

On 14 Mar 2017 9:54 PM, "Boudewijn Vahrmeijer" <notifications@github.com>
wrote:

> *@dynasource* requested changes on this pull request.
>
> good changes. Please split the unit tests towards best practice of
> 'single' purpose.
> ------------------------------
>
> In tests/framework/helpers/HtmlTest.php
> <https://github.com/yiisoft/yii2/pull/13765#discussion_r106024128>:
>
> > +            ['. ..', null],
> +            ['a +b', null],
> +            ['a,b', null]
> +
> +        ];
> +    }
> +
> +    /**
> +     * @dataProvider dataProviderAttributeNames
> +     *
> +     * @param string $name
> +     * @param string|null $expected
> +     */
> +    public function testAttributeNameValidation($name, $expected)
> +    {
> +        if (!isset($expected)) {
>
> it is not preferable to split logic in tests as tests should be instantly
> clear. Can you split this in 2 tests please?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yiisoft/yii2/pull/13765#pullrequestreview-26928923>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAhYzePRl-tZ4H4MsrQ79Vu1aCoiR7Xhks5rlv6EgaJpZM4MbbOa>
> .
>

2017-03-15 08:00 UTC, SamMousa commented
This is ready for merge.

2017-03-15 08:11 UTC, dynasource requested changes
polishing required.

2017-03-15 08:11 UTC, dynasource commented on tests/framework/helpers/HtmlTest.php
> +
blank line

2017-03-15 08:11 UTC, dynasource commented on tests/framework/helpers/HtmlTest.php
> +        /**
identation

2017-03-15 08:11 UTC, dynasource commented on tests/framework/helpers/HtmlTest.php
> +     * @param string|null $expected
@param is obsolete now

2017-03-15 09:06 UTC, dynasource approved these changes

2017-03-15 11:44 UTC, samdark commented
https://travis-ci.org/yiisoft/yii2/jobs/211271201#L565

2017-03-15 13:10 UTC, SamMousa commented
Currently it fails due to some database errors. Could travis be reconfigured to scan the output and retry if those are the errors?

2017-03-15 13:12 UTC, samdark commented
Tests are fine. These DB errors are cryptic and hard to fix. It is retrying 3 times now but that doesn't really help.

2017-03-15 13:14 UTC, SamMousa commented
Ah, I'm seeing the same on gitlab-ci builds :| 
Can travis be controlled via github comments? like @travis-ci retest please or something like that?

2017-03-15 13:19 UTC, merged

2017-03-15 13:19 UTC, samdark commented
Merged. Thank you!

2017-03-15 13:19 UTC, samdark commented
@SamMousa I can restart travis manually from project page.