Improved help and added a test for it.
yiisoft/yii2 pull request #13772
Opened 2017-03-14 11:17 UTC by SamMousa

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #10372

2017-03-14 11:29 UTC, SamMousa commented
Hmm, thanks for fixing that will take it into account in the future :)

2017-03-14 11:29 UTC, samdark requested changes

2017-03-14 11:29 UTC, samdark commented on tests/framework/console/ControllerTest.php
> +    public function testHelp()
Could be named `testHelpSkipsTypehintedArguments()`. Long but name itself explains what it does.

2017-03-14 11:36 UTC, samdark approved these changes

2017-03-14 14:43 UTC, arogachev requested changes

2017-03-14 14:43 UTC, arogachev commented on tests/framework/console/ControllerTest.php
> +    public function testHelpSkipsTypehintedArguments()
Maybe ...Type**H**inted... ?

2017-03-14 14:43 UTC, arogachev commented on tests/framework/console/FakeController.php
> +    public function actionAksi7(self $typedArgument, $simpleArgument) {
Sorry, but what `aksi7` means?

2017-03-14 15:22 UTC, SamMousa commented on tests/framework/console/FakeController.php
> +    public function actionAksi7(self $typedArgument, $simpleArgument) {
It's an action in the fake controller.

2017-03-14 21:01 UTC, dynasource requested changes

2017-03-14 21:01 UTC, dynasource commented on tests/framework/console/FakeController.php
> +    public function actionAksi7(self $typedArgument, $simpleArgument) {
can you rename this action towards a name that is less magical and closer related to the actual test scenario?

2017-03-14 21:08 UTC, SamMousa commented
You mean like aksi1 through aksi6? *-)

On 14 Mar 2017 10:02 PM, "Boudewijn Vahrmeijer" <notifications@github.com>
wrote:

> *@dynasource* requested changes on this pull request.
> ------------------------------
>
> In tests/framework/console/FakeController.php
> <https://github.com/yiisoft/yii2/pull/13772#discussion_r106026067>:
>
> > @@ -84,6 +84,10 @@ public function actionAksi6()
>          return $this->testArray;
>      }
>
> +    public function actionAksi7(self $typedArgument, $simpleArgument) {
>
> can you rename this action towards a name that is less magical and closer
> related to the actual test scenario?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yiisoft/yii2/pull/13772#pullrequestreview-26930991>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAhYzb3w3qPS5Yru1KurPUQd8C3HXi81ks5rlwA-gaJpZM4Mcb8U>
> .
>

2017-03-14 21:22 UTC, dynasource commented
`actionWithDifferentArgumentHints'

2017-03-14 21:24 UTC, SamMousa commented
I understand what you mean, I'm just saying that the other 6 action follow
a different convention that I chose to follow. 8-)

On 14 Mar 2017 10:22 PM, "Boudewijn Vahrmeijer" <notifications@github.com>
wrote:

> `actionWithDifferentArgumentHints'
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yiisoft/yii2/pull/13772#issuecomment-286564975>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAhYzaVZaVZgVVyCaMk3CXyjVmm6KmA8ks5rlwUpgaJpZM4Mcb8U>
> .
>

2017-03-14 23:23 UTC, SamMousa commented on tests/framework/console/FakeController.php
> +    public function actionAksi7(self $typedArgument, $simpleArgument) {
Please have a look at the rest of `FakeController`. It contains action that are numerically named for some reason. If you don't like it you should fix the whole controller not just 1 random function.

2017-03-15 08:01 UTC, SamMousa commented
This is ready for merge.

2017-03-15 08:10 UTC, samdark commented
@dynasource fixing naming in existing non-related tests is out of scope of this pull request.

2017-03-15 08:14 UTC, samdark commented on tests/framework/console/FakeController.php
> +    public function actionAksi7(self $typedArgument, $simpleArgument) {
The controller was like that and renaming requires much more analysis. I'd say leave it as is for now.

2017-03-15 08:34 UTC, dynasource requested changes

2017-03-15 08:34 UTC, dynasource commented on tests/framework/console/FakeController.php
> +    public function actionAksi7(self $typedArgument, $simpleArgument) {
for my approval, this newly added testAction should be altered based on my argument https://github.com/yiisoft/yii2/pull/13772/files#r106026067

2017-03-15 08:35 UTC, samdark requested changes

2017-03-15 08:35 UTC, samdark commented on tests/framework/console/FakeController.php
> +    public function actionAksi7(self $typedArgument, $simpleArgument) {
Right, it's a new one. Then it makes sense to name it properly.

2017-03-15 09:06 UTC, dynasource approved these changes

2017-03-15 11:42 UTC, samdark commented on tests/framework/console/FakeController.php
> +    public function actionAksi7(self $typedArgument, $simpleArgument) {
1 function is a good start. We'll fix the rest sooner or later.

2017-03-15 11:42 UTC, samdark approved these changes

2017-03-15 11:43 UTC, samdark commented
https://travis-ci.org/yiisoft/yii2/jobs/211268219#L311

2017-03-15 12:03 UTC, SamMousa commented
GitHub IDE is not ideal. Works again now.

2017-03-15 12:47 UTC, merged

2017-03-15 12:47 UTC, samdark commented
Merged. Thank you!