Add default precision and scale for decimal column type (mssql)
yiisoft/yii2 pull request #13776
Opened 2017-03-15 00:39 UTC by arturf

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

At the moment column definition for decimal type did not work properly in some cases. For example in migrations `$this->decimal(8,4)` will generate only `decimal` part.

2017-03-15 13:05 UTC, arturf commented
@samdark I fix `QueryBuilderTest` and squash commit

2017-03-15 13:21 UTC, samdark commented
> For example in migrations $this->decimal(8,4) will generate only decimal part.

Would that be fixed with these changes?

2017-03-15 13:28 UTC, arturf commented
> Would that be fixed with these changes?

Yes

Please, see https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L738

With current typeMap definition (without default scale) in yii\db\mssql\QueryBuilder, precisions from params wil be replaced. This PR fix this.

2017-03-15 13:39 UTC, samdark commented
I see. Are tests currently checking it?

2017-03-15 14:42 UTC, arturf commented
> Are tests currently checking it?

for decimal field - yes. But test contain some incorrect expected results for other types that don't equal to typeMap. For example boolean is mapped to bit, but test expexts for tinyint. Add fix in this PR?

2017-03-16 11:18 UTC, samdark commented
Separate pull request will be better.

2017-03-16 11:19 UTC, samdark commented
For this pull request we need a changelog.

2017-03-16 12:45 UTC, arturf commented
> For this pull request we need a changelog.

done

2017-03-16 13:46 UTC, dynasource requested changes

2017-03-16 13:46 UTC, dynasource commented on framework/db/mssql/QueryBuilder.php
> +        Schema::TYPE_DECIMAL => 'decimal(18,0)',
please use decimal(10,0) for consistency troughout the different DBMSes. See for Mysql https://github.com/yiisoft/yii2/blob/master/framework/db/mysql/QueryBuilder.php#L38

2017-03-16 13:54 UTC, arturf commented on framework/db/mssql/QueryBuilder.php
> +        Schema::TYPE_DECIMAL => 'decimal(18,0)',
and setting it as (10,0) will change current behaviour

2017-03-16 14:04 UTC, markmarco16 commented on framework/db/mssql/QueryBuilder.php
> +        Schema::TYPE_DECIMAL => 'decimal(18,0)',
Maybe (5,2) is a good value, because (10,0) is similar to INT(10), don't have decimal

2017-03-16 15:05 UTC, dynasource commented on framework/db/mssql/QueryBuilder.php
> +        Schema::TYPE_DECIMAL => 'decimal(18,0)',
alright. Lets keep it non BC

2017-03-16 15:05 UTC, dynasource approved these changes

2017-03-16 16:36 UTC, samdark approved these changes

2017-03-16 16:38 UTC, merged

2017-03-16 16:38 UTC, samdark commented
Merged. Thanks!

2017-03-17 03:34 UTC, arogachev commented
Thanks! One small remark - please create dedicated branches for PRs (do not use master), please see [Point 3](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md#3-create-a-new-branch-for-your-feature-based-on-the-current-yii-master-branch) in our [Git Worklow](https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md) document.

2017-03-30 10:34 UTC, cebe commented on framework/db/mssql/QueryBuilder.php
> +        Schema::TYPE_DECIMAL => 'decimal(18,0)',
> @dynasource this change for mssql only and (18, 0) is default values for SQL Server.
> Other DBMS have own type mapping

This is correct, entries in these fields should always use the default by the dbms.

2017-03-30 14:23 UTC, samdark commented
Not using master allows you to work on multiple pull requests at the same time. Using master you can't do it.