Allow limiting the length of the sql string that will be printed
yiisoft/yii2 pull request #13787
Opened 2017-03-16 14:06 UTC by thiagotalma

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

When we run a migration with a very large view, for example, it is bad to follow the migration progress on the screen.

2017-03-16 16:40 UTC, samdark commented
Could you elaborate about use case?

2017-03-17 18:29 UTC, thiagotalma commented
I have a database view that takes up 4 pages of the screen when it is executed in a migration.
It would be very useful to be able to configure to only print the first 200 characters.

2017-03-18 19:05 UTC, samdark commented
I suggest making it a global class property instead of a method parameter.

2017-03-20 20:30 UTC, samdark approved these changes

2017-03-20 21:10 UTC, dynasource approved these changes

2017-03-20 21:10 UTC, dynasource commented on framework/db/Migration.php
> +        $sqlPrint = ($this->printSqlLength === 0 || strlen($sql) <= $this->printSqlLength) ? $sql : substr($sql, 0, $this->printSqlLength) . "[...hidden]";
difficult line to read. Deserves a multiple lines.

2017-03-21 08:41 UTC, rob006 commented on framework/db/Migration.php
> +        $sqlPrint = ($this->printSqlLength === 0 || strlen($sql) <= $this->printSqlLength) ? $sql : substr($sql, 0, $this->printSqlLength) . "[...hidden]";
You probably should use `mb_strlen()` and `mb_substr()` here.

2017-03-21 10:17 UTC, samdark requested changes
See comments.

2017-03-21 20:08 UTC, samdark requested changes

2017-03-21 20:08 UTC, samdark commented on framework/db/Migration.php
> +        if ($this->printSqlLength !== 0 && mb_strlen($sql) > $this->printSqlLength) {
`mb_strlen` should have encoding specified.

2017-03-21 20:08 UTC, samdark commented on framework/db/Migration.php
> +            $sqlPrint = mb_substr($sql, 0, $this->printSqlLength) . "[...hidden]";
Same here. Encoding should be specified.

2017-03-21 23:06 UTC, thiagotalma commented on framework/db/Migration.php
> +        if ($this->printSqlLength !== 0 && mb_strlen($sql) > $this->printSqlLength) {
Which one should I use?
I searched for a pattern in the framework and did not find it.
In fact, most cases are without encoding.

2017-03-22 08:56 UTC, samdark commented on framework/db/Migration.php
> +        if ($this->printSqlLength !== 0 && mb_strlen($sql) > $this->printSqlLength) {
mb_strlen($from, Yii::$app->charset)

2017-03-22 08:59 UTC, rob006 commented on framework/db/Migration.php
> +        if ($this->printSqlLength !== 0 && mb_strlen($sql) > $this->printSqlLength) {
`StringHelper::truncate()` may be better option in this case.

2017-03-22 09:02 UTC, samdark commented on framework/db/Migration.php
> +        if ($this->printSqlLength !== 0 && mb_strlen($sql) > $this->printSqlLength) {
Actually, yes.

2017-03-22 11:54 UTC, bashkarev commented on framework/db/Migration.php
> +    public $printSqlLength = 0;
- `-1` - show all
- `0` - not display 
?

2017-03-22 12:00 UTC, dynasource commented on framework/db/Migration.php
> +    public $printSqlLength = 0;
agree that 0 is counter intuitive

2017-03-22 12:05 UTC, rob006 commented on framework/db/Migration.php
> +    public $printSqlLength = 0;
```php
public $printSqlLengthLimit;
```

If `null`, there is no limit. If `0`, query id not displayed.

2017-04-05 09:57 UTC, arogachev requested changes

2017-04-05 09:57 UTC, arogachev commented on framework/db/Migration.php
> +    public $printSqlLength;
I suggest using `$printedSqlLength` or `$displayedSqlLength` instead.

2017-04-05 09:57 UTC, arogachev commented on framework/db/Migration.php
> +        $sqlPrint = $sql;
`$printedSql` is better, more clear and correct form IMO.

2017-04-05 09:57 UTC, arogachev commented on framework/db/Migration.php
> +            $sqlPrint = StringHelper::truncate($sql, $this->printSqlLength, '[...hidden]');
Nitpicking, but maybe add a space after dots: `[... hidden]`.

2017-04-05 14:20 UTC, thiagotalma commented
@arogachev done!

2017-04-05 14:21 UTC, thiagotalma commented on framework/db/Migration.php
> +            $sqlPrint = mb_substr($sql, 0, $this->printSqlLength) . "[...hidden]";
@samdark done!

2017-04-05 14:58 UTC, samdark approved these changes

2017-04-06 04:40 UTC, arogachev commented
@thiagotalma Thanks! 👍 Made small corrections. Now I think it's ready for merge. Others,, please check.

2017-04-06 04:40 UTC, arogachev approved these changes

2017-06-09 20:37 UTC, closed without merging

2017-06-09 20:37 UTC, samdark commented
Merged with adjustments. Thanks!