Support JSON in mysql and postgresql
yiisoft/yii2 pull request #13783
Opened 2017-03-15 16:40 UTC by undefinedor

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13019 #10436

2017-03-16 12:42 UTC, Renkas commented
JSON data type is available from MySQL 5.7.8. What happens if I use 5.6?

2017-03-16 17:04 UTC, undefinedor commented
@Renkas  throw a exception . Mysql 5.6 does't support JSON.

2017-03-16 17:04 UTC, undefinedor commented
@Renkas  throw a exception . Mysql 5.6 does't support JSON.

2017-03-16 17:17 UTC, RSalo commented
@Renkas i think Yii should support that, but checking availability this functionality fall on users shoulders

2017-03-16 21:07 UTC, samdark commented
Throwing exception sounds OK to me in this case. MySQL 5.6 is 2013.

2017-03-16 22:48 UTC, dynasource requested changes
shouldnt the added support for JSON be a little bigger than what this PR contains?

2017-03-16 22:59 UTC, samdark commented
@dynasource what's missing?

2017-03-16 23:04 UTC, sergeymakinen commented
Even basic JSON support is good but it'd be good to reflect in the title that the PR adds a JSON support to the column schema builder to not get hopes up.

2017-03-17 08:28 UTC, dynasource commented
> Even basic JSON support is good but it'd be good to reflect in the title that the PR adds a JSON support to the column schema builder to not get hopes up.

exactly

2017-03-30 10:37 UTC, cebe commented on framework/db/pgsql/Schema.php
>          'jsonb' => self::TYPE_STRING,
same should apply for jsonb, the difference is in the storage of the data, not in the data format. https://www.postgresql.org/docs/9.4/static/datatype-json.html

2017-03-30 10:39 UTC, cebe requested changes
needs a changelog, and ideally a test also.

2017-05-25 09:11 UTC, jeesus commented
Any estimate when we could see this in stable release?

2017-05-25 09:12 UTC, samdark commented
No. Without tests it won't make it to stable release.

2017-06-03 14:54 UTC, Tigrov commented on framework/db/mysql/QueryBuilder.php
> +        Schema::TYPE_JSON => 'json'
It's better to use `Schema::TYPE_JSON => 'jsonb'`
https://www.postgresql.org/docs/current/static/datatype-json.html

2017-06-03 15:13 UTC, Tigrov commented on framework/db/pgsql/QueryBuilder.php
> +        Schema::TYPE_JSON => 'json',
It's better to use `Schema::TYPE_JSON => 'jsonb'`
https://www.postgresql.org/docs/current/static/datatype-json.html

2017-09-26 08:53 UTC, acim commented
What is going on with this?

2017-09-26 09:03 UTC, samdark commented
Nothing. With tests missing there's no chance for merging it.

2017-10-06 05:52 UTC, nguyenbs commented
Hi,
I see the test is already passed, how about next plan?

2017-10-06 20:34 UTC, samdark commented
Existing tests did but there are no tests for the code added.

2018-02-04 22:03 UTC, samdark commented
Closed in favor of https://github.com/yiisoft/yii2/pull/15560

2018-02-04 22:03 UTC, closed without merging