Fix a bug in menu widget item class rendering
yiisoft/yii2 pull request #13796
Opened 2017-03-17 22:02 UTC by Kolyunya

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13770

2017-03-17 22:03 UTC, Kolyunya commented on framework/widgets/Menu.php
> -                    $options['class'] = implode(' ', $class);
`$class` is going to be imploded by `renderTagAttributes()`.

2017-03-17 22:04 UTC, Kolyunya commented on framework/widgets/Menu.php
> -                    $options['class'] .= ' ' . implode(' ', $class);
`$options['class']` is an array so it's not concatenated to `$class` but is merged with it.

2017-03-17 22:06 UTC, Kolyunya commented on tests/framework/widgets/MenuTest.php
> +                ],
A test for the case when `$class` is empty.

2017-03-17 22:21 UTC, Kolyunya commented on framework/widgets/Menu.php
> +                        $options['class'] = [$options['class']];
BC support. Probably a subject for removal.

2017-03-17 22:22 UTC, Kolyunya commented on framework/widgets/Menu.php
> +                    $options['class'] = ArrayHelper::merge($class, $options['class']);
`$options['class']` is an array so it's not concatenated to `$class` but is merged with it.

2017-03-17 22:29 UTC, Kolyunya commented on tests/framework/widgets/MenuTest.php
> +        $output = Menu::widget([
BC test.

2017-03-17 22:50 UTC, samdark commented on framework/widgets/Menu.php
> +                    if (!is_array($options['class'])) {
Could be done as `$options['class'] = (array) $options['class'];`.

2017-03-17 22:50 UTC, samdark commented on framework/widgets/Menu.php
> +                    if (!is_array($options['class'])) {
Or even `$options['class'] = ArrayHelper::merge($class, (array) $options['class']);`.

2017-03-18 08:30 UTC, Kolyunya commented on framework/widgets/Menu.php
> +                    if (!is_array($options['class'])) {
I feel like the latter is an over complication of the merge statement. I used the former approach and added a comment clarifying why this is needed. What do you think?

2017-03-18 09:51 UTC, samdark requested changes
Code itself looks good. I'd break test method into three separate ones named after what they're testing.

2017-03-18 10:32 UTC, Kolyunya commented
Refactored tests.

2017-03-18 15:54 UTC, samdark commented
https://en.wikipedia.org/wiki/Pivot_table

2017-03-18 17:48 UTC, samdark commented on framework/widgets/Menu.php
> +                    if (!is_array($options['class'])) {
It's OK.

2017-03-18 17:50 UTC, samdark approved these changes

2017-03-30 10:46 UTC, cebe commented on framework/widgets/Menu.php
> -                    $options['class'] = implode(' ', $class);
there is `Html::addCssClass()` which could be used here as far as I see.

2017-03-30 19:53 UTC, dynasource approved these changes

2017-03-31 11:10 UTC, Kolyunya commented on framework/widgets/Menu.php
> -                    $options['class'] = implode(' ', $class);
Thank. That simplifies things up. Also altered resulting class order in tests.

2017-03-31 17:26 UTC, SilverFire approved these changes

2017-04-01 13:57 UTC, merged

2017-04-01 13:57 UTC, samdark commented
Merged. Thanks!

2017-04-01 14:07 UTC, Kolyunya commented
Glad to help!