Enhance web response
yiisoft/yii2 pull request #13815
Opened 2017-03-21 12:48 UTC by Kolyunya

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13813

2017-03-21 14:16 UTC, samdark requested changes

2017-03-21 14:16 UTC, samdark commented on framework/web/Response.php
> +    public function setStatusCodeByException(\Throwable $e)
Type hint needs to be removed since `\Throwable` is PHP 7 only.

2017-03-21 14:19 UTC, Kolyunya commented on framework/web/Response.php
> +    public function setStatusCodeByException(\Throwable $e)
Fixed that. Do we revert docs fixes?

2017-03-21 14:23 UTC, Kolyunya commented on framework/web/Response.php
> +    public function setStatusCodeByException(\Throwable $e)
Updated docs.

2017-03-21 15:00 UTC, samdark approved these changes

2017-03-22 21:56 UTC, dynasource approved these changes

2017-03-22 22:20 UTC, merged

2017-03-22 22:20 UTC, samdark commented
Merged. Thanks!

2017-03-22 22:27 UTC, Kolyunya commented
Don't you think that the changelog is a bit misleading? This seems like a new feature to me, not a compatibility fix according to the docs.

2017-03-22 22:29 UTC, samdark commented
@Kolyunya you mean `UPGRADE`?

2017-03-22 22:36 UTC, Kolyunya commented
I mean that according to the docs only `Exception` was supposed to be accepted by that method. Passing `Error` was not even documented. And now we added new functionality. This seems to be a new feature not a compatibility fix. I'm not sure if this is correct though.

2017-03-22 22:56 UTC, samdark commented
Right. https://github.com/yiisoft/yii2/commit/da3bb5aa429f3f75af88694b25bb1e5b1ed97878

2017-03-22 23:09 UTC, Kolyunya commented
I don't want to be annoying or anything but the signature of the existing method changed (without breaking the BC) and a new type of parameter is now accepted. It seems to me that the original changelog line is quite precise. Never mind anyway.

2017-03-22 23:26 UTC, rob006 commented
Tests are broken on PHP 5 - `Error` was introduced in PHP 7: https://travis-ci.org/yiisoft/yii2/jobs/214033905#L524

2017-03-23 06:31 UTC, Kolyunya commented
Thanks! I made a patch https://github.com/yiisoft/yii2/pull/13834.