Add `yii\web\Request::getOrigin()` method that returns HTTP_ORIGIN of current CORS request
yiisoft/yii2 pull request #13835
Opened 2017-03-23 06:36 UTC by yyxx9988

>The Origin request header indicates where a fetch originates from. It doesn't include any path information, but only the server name. It is sent with CORS requests, as well as with POST requests. It is similar to the Referer header, but, unlike this header, it doesn't disclose the whole path.

From https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

### Working code samples
```php
<?php

// We'll be granting access to only the arunranga.com domain 
// which we think is safe to access this resource as application/xml

if($_SERVER['HTTP_ORIGIN'] == "http://arunranga.com") {
    header('Access-Control-Allow-Origin: http://arunranga.com');
    header('Content-type: application/xml');
    readfile('arunerDotNetResource.xml');
} else {    
  header('Content-Type: text/html');
  echo "<html>";
  echo "<head>";
  echo "   <title>Another Resource</title>";
  echo "</head>";
  echo "<body>",
       "<p>This resource behaves two-fold:";
  echo "<ul>",
         "<li>If accessed from <code>http://arunranga.com</code> it returns an XML document</li>";
  echo   "<li>If accessed from any other origin including from simply typing in the URL into the browser's address bar,";
  echo   "you get this HTML document</li>", 
       "</ul>",
     "</body>",
   "</html>";
}
?>
```
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Server-Side_Access_Control for more info.

2017-03-29 12:06 UTC, SamMousa commented
This will break when / if  #13780 gets merged.
Could you use the header collection instead?

2017-03-30 02:36 UTC, yyxx9988 commented
Of course. Close this pr if it break other :）

2017-03-30 10:06 UTC, SamMousa commented
@yyxx9988 This PR doesn't break anything, but it will be broken by the other PR.
Could you refactor it to use the header collection that is available in the request object?

2017-03-30 13:18 UTC, yyxx9988 commented
> Could you refactor it to use the header collection that is available in the request object?

@SamMousa ...I'm sorry. But did you mean this:
```php
public function getOrigin()
{
    return $this->getHeaders()->get('HTTP_REFERER');
}
```

2017-03-30 14:00 UTC, SamMousa commented
Almost:
````
 return $this->getHeaders()->get('referer');
 return $this->getHeaders()->get('origin');

````
etc..

2017-03-31 02:02 UTC, yyxx9988 commented
@SamMousa Call me Newbie, please...😅😅😅

2017-04-01 14:12 UTC, samdark commented
https://travis-ci.org/yiisoft/yii2/jobs/217006172

2017-07-11 13:01 UTC, cebe requested changes
also a CHANGELOG entry is missing

2017-07-11 13:01 UTC, cebe commented on framework/web/Request.php
> +     * Returns the URL origin.
should explain that it is taken from CORS related header.

2017-07-11 13:01 UTC, cebe commented on framework/web/Request.php
> +     * @return string|null URL origin, null if not available
`@since` PHPdoc annotation is needed here.

2017-07-11 16:22 UTC, yyxx9988 commented
commits added 😀

2017-07-11 19:48 UTC, samdark approved these changes

2017-07-12 09:05 UTC, cebe approved these changes

2017-07-12 09:10 UTC, cebe commented
Merged, thank you!

2017-07-12 09:10 UTC, closed without merging