Php Inspections (EA Extended): minor tweaks
yiisoft/yii2 pull request #13845
Opened 2017-03-23 18:11 UTC by kalessil

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | n/a

Substr calls check adjustments: https://3v4l.org/FC1qY
`$_cookies` re-written in the class constructor, so implicit default value is redundant

2017-03-23 21:53 UTC, samdark requested changes
Overall good changes but there are some things to adjust.

2017-03-23 21:53 UTC, samdark commented on framework/helpers/BaseHtml.php
> +                    if (!in_array($line, $lines)) {
Wouldn't plugin require strict parameter to be set?

2017-03-23 21:53 UTC, samdark commented on framework/web/CookieCollection.php
> +    private $_cookies;
That's wrong change. See:

```php
public function getCount()
{
    return count($this->_cookies);
}
```

2017-03-24 05:05 UTC, kalessil commented on framework/helpers/BaseHtml.php
> +                    if (!in_array($line, $lines)) {
Yes, will add

2017-03-24 05:07 UTC, kalessil commented on framework/web/CookieCollection.php
> +    private $_cookies;
The property is immediately overridden when constructing an object:
```php
    public function __construct($cookies = [], $config = [])
    {
        $this->_cookies = $cookies;
        parent::__construct($config);
    }
```

2017-03-24 09:00 UTC, samdark approved these changes

2017-03-24 09:00 UTC, samdark commented on framework/web/CookieCollection.php
> +    private $_cookies;
OK.

2017-03-24 10:50 UTC, closed without merging

2017-03-24 10:51 UTC, samdark commented
Merged. Thank you!