Fixed yii\db\QueryBuilder to inherit ‘INSERT INTO ... SELECT’ SELECT’s params (fixes #13807)
yiisoft/yii2 pull request #13843
Opened 2017-03-23 16:46 UTC by sergeymakinen

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #13807 

This PR fixes `QueryBuilder` did not account params in a subquery when building `INSERT INTO … SELECT` introduced in #9420. I didn’t mention a small BC break in `UPGRADE.md` yet.

2017-03-23 23:41 UTC, samdark requested changes
Overall looks OK. Method signature change affect SQL query builders only. That should be mentioned in UPGRADE.

2017-03-23 23:41 UTC, samdark commented on framework/db/QueryBuilder.php
> +     * @throws InvalidParamException if query's select does not contain only named parameters.
only named parameters → named parameters only

2017-03-24 19:31 UTC, samdark approved these changes

2017-04-13 15:36 UTC, arogachev commented on framework/db/QueryBuilder.php
> +     * @param \yii\db\Schema $schema Schema object to qoute column name.
`qoute` - `quote`.

2017-04-13 15:39 UTC, arogachev approved these changes

2017-04-15 07:30 UTC, SilverFire approved these changes

2017-04-17 00:31 UTC, merged

2017-04-17 00:31 UTC, samdark commented
Merged. Thank you!