QueryScalar fix for #13846
yiisoft/yii2 pull request #13872
Opened 2017-03-29 10:35 UTC by Alex-Code

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13846

2017-03-29 11:03 UTC, samdark approved these changes

2017-05-10 10:00 UTC, samdark requested changes

2017-05-10 10:00 UTC, samdark commented on tests/framework/db/QueryTest.php
> +        $count = (new Query)->from('customer')->orderBy('id')->limit(1)->count('*', $db);
Is `limit(1)` necessary here?

2017-05-25 21:36 UTC, samdark commented on tests/framework/db/QueryTest.php
> +        $count = (new Query)->from('customer')->orderBy('id')->limit(1)->count('*', $db);
@Alex-Code ?

2017-05-26 15:50 UTC, Alex-Code commented on tests/framework/db/QueryTest.php
> +        $count = (new Query)->from('customer')->orderBy('id')->limit(1)->count('*', $db);
`LIMIT` gets ignored on `COUNT` for MySQL so it was to test if a limit was set it still returned 3.
Not sure if this behaviour is different on MSSQL.

2017-05-28 12:27 UTC, closed without merging

2017-05-28 12:28 UTC, samdark commented
Merged https://github.com/yiisoft/yii2/commit/7c6620a65f65f8e7dd151d09c1918001e4e46712. Thanks!