Moved serialization of `Cookie` to `Cookie`. Added unit test for seri…
yiisoft/yii2 pull request #13889
Opened 2017-03-30 12:06 UTC by SamMousa

…alization / deserialization.

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
Breaks BC?    | yes/no
| Tests pass?   | yes
| Fixed issues  | #13135

2017-03-30 12:08 UTC, SamMousa commented
Note that this also adds support for non-string values in cookies (when validation is enabled).

Should this be expanded so that cookies can contain any kind of data in all cases?
(Basically always serialize / unserialize regardless of validation?)

2017-04-01 23:29 UTC, samdark commented
I think an exception for scalar values is made for cookies which are meant to be used via JavaScript.

2017-04-03 08:09 UTC, SamMousa commented
> I think an exception for scalar values is made for cookies which are meant to be used via JavaScript.

What do you mean?

2017-04-03 08:35 UTC, samdark commented
If the value is not an array, it's not encoded in any special way. That is for using it without decoding.

2017-04-03 08:44 UTC, SamMousa commented
Are you sure?
https://github.com/yiisoft/yii2/blob/master/framework/web/Response.php#L397

I don't see that happening anywhere; as far as I can tell if cookie validation is enabled cookies get encoded.

2017-04-03 22:17 UTC, samdark commented
You're right.

2017-04-05 08:26 UTC, SamMousa commented
@samdark This one could be ready for merge, maybe. 8-)

2017-04-05 08:29 UTC, samdark commented
I wonder how would that work with existing cookies set with data which was passed through old `serialize()/unserialize()`?

2017-04-05 08:29 UTC, samdark commented
That's the main reason I was suggesting it for 2.1.x

2017-04-05 08:34 UTC, SamMousa commented
Well those cookies would be come "invalid", meaning users lose whatever data is stored in there.
I don't feel it's a big issue, since users sessions tend to get remove whenever you do an upgrade anyway (that's what I do at least). And logging in again is not a big hassle.
Other than that, cookies that are used for preferences (like grid view settings) tend not to be validated anyway since they are changed via client side code.

Up to you which one you prefer, I'm in no rush to get this merged, just want it to be finished so it no longer needs a spot on my todo list.

2017-04-05 08:46 UTC, samdark commented
Cookies may hold more than sessions.

2017-04-05 08:48 UTC, samdark requested changes

2017-04-05 08:48 UTC, samdark commented on framework/web/Cookie.php
> +            $result = new self();
How about `Yii::createObject()` so container settings are applies?

2017-04-05 08:48 UTC, samdark commented on framework/web/Cookie.php
> +        if (($unserialized = json_decode($data, true)) !== false) {
I'd use `Json` helper since it produces much better errors.

2017-04-05 08:48 UTC, samdark commented on framework/web/Cookie.php
> +        return json_encode([
I'd use `Json` helper since it produces much better errors.

2017-04-05 14:09 UTC, SamMousa commented on framework/web/Cookie.php
> +        if (($unserialized = json_decode($data, true)) !== false) {
What should the behavior be regarding errors?
If I pass an invalid cookie, should the request object just crash (ie bubble up the exception) or should it silently ignore the cookie?

2017-04-05 14:38 UTC, samdark approved these changes

2017-04-10 07:58 UTC, klimov-paul commented
Changing Cookie serialization from PHP `serialize()` to JSON can not be done at `2.0.x` as it causes a BC break: all existing Cookies in particular Yii-based will stop function after such update.

2017-04-10 08:04 UTC, klimov-paul requested changes

2017-04-10 08:04 UTC, klimov-paul commented on framework/web/Cookie.php
> +            'value' => $unserialized[1],
Keys `0` or `1` can be absent in unserialized data.
Such code may produce E_NOTICE.
It is better to perform `isset()` before like it was at original implementation.

2017-04-10 08:06 UTC, klimov-paul commented
I do not like the idea: processing of the Cookie value is still depends on `Request` and `Response` since they  use `Security` to process the hash. 
It would be more consistent to keep all fucntionality related to hash composition at single place rather then extend it to the extra class.

2017-04-10 08:07 UTC, SamMousa commented on framework/web/Cookie.php
> +            'value' => $unserialized[1],
The data is validated first, you shouldn't pass unvalidated data into any function.

2017-04-10 08:08 UTC, SamMousa commented
Well validation of user data is part of the request object, so that makes sense in my opinion.
Just like formatting the response is part of the response object.

2017-04-10 08:08 UTC, klimov-paul commented
Note that all this 'cookie data string' support exists only because of necessity of cookie value protection, which is introduced and configured(!) at `Request`/`Response` level. Changes proposed here looks like encapsulation break to me.

2017-04-10 08:09 UTC, klimov-paul commented
I can see absolutely no benefit in proposes changes - just a redundant overcomplication of code.

2017-04-10 08:28 UTC, SamMousa commented
The serialization is not only for cookie protection, it also enables use of complex cookie values.

2017-04-10 08:32 UTC, klimov-paul commented
> The serialization is not only for cookie protection, it also enables use of complex cookie values.

I can not see any complex valu handling in your PR. Besides what prevent us to simply use `Json` methods instead of PHP `serialize()`/`unserialize()` and `Request` and `Response`? Why there is a necessity of instroduction of extra methods at `Cookie` class?

2017-04-10 08:37 UTC, SamMousa commented
Because it should be the cookies'  responsibility to handle its serialization / deserialization.
Discuss this with the team make a decision, I've got no more arguments to add.

2017-04-10 08:57 UTC, klimov-paul commented
> Because it should be the cookies' responsibility to handle its serialization / deserialization.

It would be so in case I can use single `Cookie` class to get/set complex cookie value, like following:

```php
$cookie = Cookie::parse($_COOKIES['someComplexValue']);
var_dump($cookie->value);
```

but this code can not function since cookie value may contain security hash, which handled and configured at `Request` class.

In case there is no way to provide clear interface for cookie serialization/unserializion and single `Cookie` class value - why should we create a half-solution methods at `Cookie` class? Those will just confuse the developer, which expects it handles it all - while it does not take security hash into account.

Creating those methods just because 'it seems they should be there' does not seem right.
Either entire Cookie value processing including security hash should be moved inside the `Cookie` class - or it should remain intact.

2017-04-10 09:00 UTC, SamMousa commented
Look at the tests..

It will work just fine like this:
````
$cookie = new Cookie();
$cookie->value = ['abc', 'def'];
$cookie->name = test;
````

This cookie can be serialized and unserialized by the request / response object, or other code.

2017-04-10 09:02 UTC, klimov-paul commented
The raw value, which includes security hash, can not be parsed.

2017-04-10 09:04 UTC, SamMousa commented
It only includes the security hash if it was signed by the Response. If you add it manually as you propose then it'll work without.

Your argument does not make sense. I could use it for any encryption / signing library, arguing that when encrypting data it does not work unless decrypted....
Of course if you sign the data and thus change it you have to undo that change, which is what the Request and Response objects do.

If you bypass them, the cookie serialization part will work just fine without it.

2017-04-10 09:11 UTC, klimov-paul commented
>Your argument does not make sense. I could use it for any encryption / signing library, arguing that when encrypting data it does not work unless decrypted....

Cookies, which submitted per request are built and processed by `Request` class, which handles thier unserialization and decryption.
Standalone unserialization without decryption of the Cookie value make a little sence.
The only use case, in which I may want to unserialize some Cookie value on my own is getting this value from raw request, but in this case this value will contain the security hash in it.

Can you describe the use case, in which you get some random Cookie string value and want to unserialize it, but can be sure its value is secure and decrypted?

2017-04-10 10:00 UTC, SamMousa commented
> Can you describe the use case, in which you get some random Cookie string value and want to unserialize it, but can be sure its value is secure and already decrypted?

When I use any other implementation than the default `Request` / `Response` class.

Note that "being sure" is not really relevant here. Can you be sure no developer will subclass `Response` but not `Request` and guarantee that they still use the same scheme for validation? (No you can not)

2017-04-10 10:19 UTC, klimov-paul commented
> When I use any other implementation than the default Request / Response class. 

This is exactly the case - if you wish the Cookie ecryption/serialization change - you need to override `Request`/`Response` classes pair - this is the only consistent solution I see for such task. During such implementation another way for cookie serialization can be used as well. 

> Can you be sure no developer will subclass Response but not Request and guarantee that they still use the same scheme for validation? 

When it comes to override existing core functionality developer is responsible for its results. I can not see how new methods in `Cookie` class ensures anything in this field - who can garantee developer will use those methods, while creating its own Cookie protection solution?

Yii is not a Symfony and it does not follow SOLID methodology - we do not introduce a new abstraction layer just because we have found a potential place for it.

2017-04-10 18:02 UTC, sergeymakinen commented
I think it’s useful to extract a `Cookie` serialization completely, so it can be swapped without the need to touch `Request`/`Response` (like using JWT for signing/validation).

2017-04-10 23:11 UTC, samdark commented
I think in this case serialization should be extracted as @sergeymakinen suggested.

2017-04-11 08:41 UTC, SamMousa commented
Signing and validation will require configuration though.
Currently that is set in the `Request` component (`cookieValidationKey`).

I think serialization (transformation from complex to string) is a separate step from signing (transformation from string to protected string).
I agree that signing should be removed from `Request` / `Response`, but it should not be in `Cookie`; since cookies are not the only thing you can / could sign, you could sign any piece of data that you want to send to the client and get back in a later request. (For example, hidden form field).

That said, this is a first step to separate the serialization part, feel free to make the next step and make a PR for it...

This PR does what I want it to do, if you don't want that in the framework that's fine, close this issue. If you do want it but see improvements for the future I suggest we create a separate issue for that and mark this as "ready to merge into 2.1".

2017-04-11 13:13 UTC, samdark commented
As @klimov-paul noted, that's significant enough to go to 2.1. I like these changes overall so would not vote for not accepting the pull request.

2019-04-23 21:00 UTC, closed without merging

2019-04-23 21:00 UTC, samdark commented
Won't be merged into 2.0.