Apply `Indexby` after loading relations
yiisoft/yii2 pull request #13891
Opened 2017-03-30 14:04 UTC by SamMousa

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | maybe
| Fixed issues  | #9342

2017-03-31 15:42 UTC, samdark requested changes

2017-03-31 15:42 UTC, samdark commented on framework/web/Cookie.php
> +    public static function fromDataString($data)
Doesn't look like it belongs to this pull request.

2017-03-31 15:42 UTC, samdark commented on framework/web/Request.php
> +                if (($cookie = Cookie::fromDataString($data)) !== null && $cookie->name === $name) {
Same here.

2017-03-31 16:20 UTC, SamMousa commented
Hmm based it off the wrong branch.

On Mar 31, 2017 5:42 PM, "Alexander Makarov" <notifications@github.com>
wrote:

> *@samdark* requested changes on this pull request.
> ------------------------------
>
> In framework/web/Cookie.php
> <https://github.com/yiisoft/yii2/pull/13891#discussion_r109189283>:
>
> > @@ -65,4 +67,35 @@ public function __toString()
>      {
>          return (string) $this->value;
>      }
> +
> +    /**
> +     * Unserializes a cookie received by the client.
> +     * @param string $data
> +     * @return self|null
> +     */
> +    public static function fromDataString($data)
>
> Doesn't look like it belongs to this pull request.
> ------------------------------
>
> In framework/web/Request.php
> <https://github.com/yiisoft/yii2/pull/13891#discussion_r109189332>:
>
> > @@ -1286,13 +1286,9 @@ protected function loadCookies()
>                  if ($data === false) {
>                      continue;
>                  }
> -                $data = @unserialize($data);
> -                if (is_array($data) && isset($data[0], $data[1]) && $data[0] === $name) {
> -                    $cookies[$name] = new Cookie([
> -                        'name' => $name,
> -                        'value' => $data[1],
> -                        'expire' => null,
> -                    ]);
> +
> +                if (($cookie = Cookie::fromDataString($data)) !== null && $cookie->name === $name) {
>
> Same here.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yiisoft/yii2/pull/13891#pullrequestreview-30278936>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAhYzbnT6s5Ocvlh-LIsTFo1XxUkMxIzks5rrR7tgaJpZM4MuaEM>
> .
>

2017-03-31 17:10 UTC, SilverFire requested changes

2017-03-31 17:10 UTC, SilverFire commented on framework/db/ActiveQueryTrait.php
> +            $models = [];
No need for `else` above

2017-03-31 17:34 UTC, SamMousa commented on framework/db/ActiveQueryTrait.php
> +            $models = [];
I know there's no need but I find it more readable, early return statements tend to make your code less readable; is it in violation of the coding  standard?

2017-03-31 17:37 UTC, SilverFire commented on framework/db/ActiveQueryTrait.php
> +            $models = [];
Hm, personally for me early return statements are more readable :)

2017-04-01 12:09 UTC, samdark commented
@SamMousa would you please fix the branching?

2017-04-01 12:44 UTC, arogachev commented on framework/db/ActiveQueryTrait.php
> +            $models = [];
It's documented in Core code style guide, [Control statements section](https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md#54-control-statements):

> Prefer avoiding `else` after `return` where it makes sense. Use [guard conditions](http://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html).
> 
> ```php
> $result = $this->getResult();
> if (empty($result)) {
>     return true;
> } else {
>     // process result
> }
> ```
> 
> is better as
> 
> ```php
> $result = $this->getResult();
> if (empty($result)) {
>    return true;
> }
> 
> // process result
> ```

2017-04-01 12:52 UTC, SamMousa commented
Yes, it's on my list

On Apr 1, 2017 2:09 PM, "Alexander Makarov" <notifications@github.com>
wrote:

> @SamMousa <https://github.com/SamMousa> would you please fix the
> branching?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/yiisoft/yii2/pull/13891#issuecomment-290916269>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAhYzTyA_6X6xWs7NRcNQEY06nNbdwgKks5rrj6RgaJpZM4MuaEM>
> .
>

2017-04-03 08:11 UTC, SamMousa commented
@samdark I've reverted the erroneous commit.

2017-04-18 05:06 UTC, Faryshta commented on tests/framework/db/ActiveRecordTest.php
> +            return isset($order->product->id) ? $order->product->id : null;
this is where you should call the `assertNotEmpty()` method.

2017-04-18 05:07 UTC, Faryshta commented on tests/framework/db/ActiveRecordTest.php
> +        $this->assertNotEmpty($orderClass::find()->with('customer')->indexBy(function($order) {
why does the `with()` statement calls the customer relation and the index uses the product relation?

2017-04-18 05:09 UTC, Faryshta commented on tests/framework/db/ActiveRecordTest.php
> +        $this->assertNotEmpty($orderClass::find()->with('customer')->indexBy('product.id')->all());
maybe here you should call https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertArrayHasKey

2017-10-08 00:07 UTC, samdark commented
Seems tests are failing...

2018-02-15 22:27 UTC, merged

2018-02-15 22:27 UTC, SilverFire commented
Thank you!

2018-02-16 03:21 UTC, cebe reviewed
Looks good to me!

2018-03-01 22:36 UTC, klimov-paul commented
This PR is BC break: NOSQL ActiveQuery classes are broken because of it:

- [mongodb](https://github.com/yiisoft/yii2-mongodb/issues/251)
- [filedb](https://github.com/yii2tech/filedb/issues/10)

I suspect the same problem at `yii2-elasticsearch` repository too. Someone should check it out and apply a fix if necessary.

2018-03-02 11:00 UTC, klimov-paul commented
`yii2-redis` should be checked as well.

2018-03-12 09:56 UTC, cebe commented
yes, yii2-redis is broken too: https://github.com/yiisoft/yii2-redis/issues/141

2018-03-12 14:56 UTC, cebe commented
elasticsearch seems not affected