WIP SqlProvider total count
yiisoft/yii2 pull request #13895
Opened 2017-03-31 08:18 UTC by SamMousa

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #13883 

I'd like some feedback on the test.
- Does it have the right group
- Is it in the right folder
- Should it use sqlite (I assumed that's the most lightweight way of testing the database without mocking).

2017-03-31 17:23 UTC, SilverFire commented
I think it should be done in a manner RBAC Manager tests: https://github.com/SamMousa/yii2/tree/master/tests/framework/rbac

2017-03-31 17:23 UTC, SilverFire approved these changes
Looks good

2017-03-31 17:34 UTC, SamMousa commented
@SilverFire Isn't one db test enough considering the query itself is trivial? No use making tests slower?

2017-03-31 17:36 UTC, SilverFire commented
Yeah, I think you are right as well

2017-03-31 17:39 UTC, arogachev requested changes

2017-03-31 17:39 UTC, arogachev commented on tests/framework/data/SqlDataProviderTest.php
> +
Unnecessary linebreaks.

2017-04-01 11:36 UTC, samdark approved these changes

2017-04-01 12:19 UTC, arogachev approved these changes

2017-04-01 13:38 UTC, closed without merging

2017-04-01 13:38 UTC, samdark commented
Merged https://github.com/yiisoft/yii2/commit/79f16b149239c0d1314102999a2fc8353ee8cb0b. Thank you!