Test write for `yii\filters\AccessControl` and refactoring
yiisoft/yii2 pull request #13946
Opened 2017-04-09 03:12 UTC by vladis84

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  |no
| Breaks BC?    | yes/no
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2017-04-30 19:50 UTC, samdark requested changes

2017-04-30 19:50 UTC, samdark commented on framework/CHANGELOG.md
> +- Enh #13963: Added tests for yii\behaviors\TimestampBehavior (vladis84)
Seems it's not related.

2017-04-30 19:50 UTC, samdark commented on framework/filters/AccessControl.php
> +                return $this->execDenyCallback($user, $rule, $action);
I'd rename exec to execute.

2017-04-30 19:50 UTC, samdark commented on framework/filters/AccessControl.php
> +    private function execDenyCallback($user, $rule, $action)
There should be phpdoc.

2017-06-10 15:37 UTC, vladis84 commented on framework/filters/AccessControl.php
> +                return $this->execDenyCallback($user, $rule, $action);
Fix it

2017-06-10 15:37 UTC, vladis84 commented on framework/filters/AccessControl.php
> +    private function execDenyCallback($user, $rule, $action)
Fix it

2017-06-11 15:11 UTC, samdark requested changes
Overall it looks good to me but some adjustments are needed.

2017-06-11 15:11 UTC, samdark commented on framework/filters/AccessControl.php
> +            throw new InvalidConfigException('AccessControl property denyCallback is not function');
`AccessControl::$denyCallback should be callable` sounds better.

2017-06-11 15:11 UTC, samdark commented on framework/CHANGELOG.md
> +- Enh #13963: Refactored for yii\behaviors\TimestampBehavior. Added tests (vladis84)
`Enh #13946: Refactored yii\filters\AccessControl, added tests (vladis84)`

2017-06-11 15:11 UTC, samdark commented on framework/filters/AccessControl.php
>              } elseif ($allow === false) {
Could be just `if ($allow === false) {` since previously we're returning immediately.

2017-06-11 15:11 UTC, samdark commented on framework/filters/AccessControl.php
> +     * @return false
I don't think returning false belongs to this method.

2017-06-11 15:11 UTC, samdark commented on framework/filters/AccessControl.php
> -                return false;
Return false should be kept here.

2017-06-11 15:11 UTC, samdark commented on framework/filters/AccessControl.php
> +     * @param Action $action the action to be executed
Need `@since 2.0.13`.

2017-06-11 15:11 UTC, samdark commented on framework/filters/AccessControl.php
> +     * If not set denyCallback, [[denyAccess()]] will be called.
`If [[denyCallback]] is not set, [[denyAccess()]] will be called.`

2017-06-11 15:11 UTC, samdark commented on framework/filters/AccessControl.php
> +     * DenyCallback that will be called if the access should be denied to the current user.
Executes deny callback when access should be denied to the current user.

2017-06-11 15:12 UTC, samdark commented
@dynasource would you please take a look at tests?

2017-06-14 09:59 UTC, cebe requested changes

2017-06-14 09:59 UTC, cebe commented on framework/filters/AccessControl.php
>              } elseif ($allow === false) {
its fine this way.

2017-06-14 09:59 UTC, cebe commented on framework/filters/AccessControl.php
> -                    call_user_func($rule->denyCallback, $rule, $action);
where has this code been moved to?

2017-06-21 15:58 UTC, vladis84 commented on framework/filters/AccessControl.php
> -                    call_user_func($rule->denyCallback, $rule, $action);
fixed

2017-06-21 22:36 UTC, samdark approved these changes

2017-06-26 12:59 UTC, dynasource requested changes
reviewed in depth

2017-06-26 12:59 UTC, dynasource commented on framework/filters/AccessControl.php
> +            $allow = $rule->allows($action, $user, $request);
it was fine as it is?

2017-06-26 12:59 UTC, dynasource commented on framework/filters/AccessControl.php
> +            $filter = $this;
$filter should be called $accessControl

2017-06-26 12:59 UTC, dynasource commented on tests/framework/filters/AccessControlTest.php
> +        $this->assertEquals($expectedFilters, $filter->rules);
this test is too complex for what you are testing. Just verifying $filter->rules[0] with assertInstanceOf is enough

2017-06-26 12:59 UTC, dynasource commented on tests/framework/filters/AccessControlTest.php
> +    }
this test is not necessary

2017-06-26 12:59 UTC, dynasource commented on tests/framework/filters/AccessControlTest.php
> +        $filter = new AccessControl();
please keep it consistent and name the variable like its Classname

2017-06-26 12:59 UTC, dynasource commented on tests/framework/filters/AccessControlTest.php
> +        $this->assertInstanceOf('\Closure', $filter->denyCallback);
this test is error prone. Without the specified config, the assertion still applies.

2017-06-26 12:59 UTC, dynasource commented on tests/framework/filters/AccessControlTest.php
> +
the previous methods should ideally be merged into a dataProvider in which the logic is easier to understand and verified. Now the tests are bit hard to read & to compare.

2017-07-03 09:48 UTC, cebe requested changes

2017-07-03 09:48 UTC, cebe commented on framework/filters/AccessControl.php
> +            $this->denyCallback = function () use ($filter) {
first parameter to denyCallback is the AccessRule, not the filter.

2017-08-07 10:32 UTC, samdark commented
@vladis84 do you plan to work on it further?

2017-08-08 17:39 UTC, vladis84 commented
No

2017-08-08 18:03 UTC, samdark commented
OK. Will see what I can do with the pull request after current release. Thanks for contributing.

2017-08-09 07:25 UTC, vladis84 commented
I  finished pull request

2018-02-03 16:02 UTC, samdark commented
Can't be merged with current code :(

2018-02-03 16:02 UTC, closed without merging