Add new param  for Yii::setAlias() enh #13957
yiisoft/yii2 pull request #13988
Opened 2017-04-13 20:09 UTC by ejsoft

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13957

2017-04-14 21:31 UTC, Kolyunya commented on framework/BaseYii.php
> +     * @param boolean $overwrite the overwrite allow to overwrite the alliance if it is set, or skip if the alias is already set
> overwrite the alliance

`alias`?

2017-04-14 21:43 UTC, ejsoft commented on framework/BaseYii.php
> +     * @param boolean $overwrite the overwrite allow to overwrite the alliance if it is set, or skip if the alias is already set
yeap, thanks

2017-04-15 21:50 UTC, samdark requested changes

2017-04-15 21:50 UTC, samdark commented on framework/BaseYii.php
> +    public static function setAlias($alias, $path, $overwrite = true)
Public method signature change is a backwards compatibility break.

2017-04-15 21:50 UTC, samdark commented on framework/BaseYii.php
> +    public static function setAlias($alias, $path, $overwrite = true)
I don't think we need it as option. It should be default behavior not to overwrite it.

2018-01-21 19:59 UTC, closed without merging