Rate limiter refactor test
yiisoft/yii2 pull request #13994
Opened 2017-04-15 04:25 UTC by vladis84

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  |no
| Breaks BC?    |no
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2017-04-15 07:27 UTC, SilverFire requested changes
The tests seems to be broken: https://travis-ci.org/yiisoft/yii2/jobs/222293533

2017-04-15 07:27 UTC, SilverFire commented on framework/filters/RateLimiter.php
> +        if (!$this->user && Yii::$app->getUser()) {
I think `!$this->user` could be replaced to `$this->user === null`

2017-04-15 07:46 UTC, vladis84 commented
I correct tests

2017-04-15 08:44 UTC, vladis84 commented
I corrected tests

2017-04-15 15:26 UTC, samdark requested changes

2017-04-15 15:26 UTC, samdark commented on framework/CHANGELOG.md
> +- Enh: Test write for yii\filters\RateLimiter and refactoring (vladis84)
`Enh #13994: Refactored yii\filters\RateLimiter. Added tests (vladis84)`

2017-04-15 15:26 UTC, samdark commented on framework/filters/RateLimiter.php
> +    public function init()
phpdoc missing

2017-04-15 15:26 UTC, samdark commented on framework/filters/RateLimiter.php
> +        if (!$this->request) {
What are these initializations for?

2017-04-15 15:26 UTC, samdark commented on tests/framework/filters/stubs/UserIdentity.php
> +    public function getRateLimit($request, $action)
Doesn't look like a good idea to me. Interface should return an array in this case but it does not. Implementing methods like that isn't right. Better to leave default user implementation w/o this interface at all.

2017-04-15 15:26 UTC, samdark commented on tests/framework/filters/stubs/UserIdentity.php
> +class UserIdentity extends Component implements IdentityInterface, RateLimitInterface
Doesn't look right.

2017-04-16 02:44 UTC, vladis84 commented on tests/framework/filters/stubs/UserIdentity.php
> +    public function getRateLimit($request, $action)
In this case, the api will be broken.
The programmer must implement the RatLimitInterface for the use of RateLimiter.
The structure is reliable than the array.

2017-04-16 02:48 UTC, vladis84 commented on framework/filters/RateLimiter.php
> +        if (!$this->request) {
https://github.com/yiisoft/yii2/blob/master/framework/filters/RateLimiter.php#L75
It is difficult to say why in the filter these properties

2017-04-17 00:26 UTC, samdark commented on tests/framework/filters/stubs/UserIdentity.php
> +    public function getRateLimit($request, $action)
Won't it be broken in case of returning nulls as well?

2017-04-17 16:54 UTC, vladis84 commented on tests/framework/filters/stubs/UserIdentity.php
> +    public function getRateLimit($request, $action)
no https://github.com/yiisoft/yii2/pull/13994/files#diff-f4d94127b38f18704a417ac109ef0af7R113

2017-04-17 17:42 UTC, vladis84 commented on framework/filters/RateLimiter.php
> +    public function init()
i corrected

2017-04-17 17:42 UTC, vladis84 commented on tests/framework/filters/stubs/UserIdentity.php
> +class UserIdentity extends Component implements IdentityInterface, RateLimitInterface
I corrected

2017-04-17 17:42 UTC, vladis84 commented on tests/framework/filters/stubs/UserIdentity.php
> +    public function getRateLimit($request, $action)
I corrected

2017-04-18 21:47 UTC, cebe requested changes

2017-04-18 21:47 UTC, cebe commented on framework/filters/RateLimiter.php
> +        if (!$this->request) {
test for `===` null instead of `!`.

2017-04-18 21:47 UTC, cebe commented on framework/filters/RateLimiter.php
> +        if (!$this->response) {
test for `===` null instead of `!`.

2017-04-19 23:19 UTC, samdark approved these changes

2017-04-20 14:26 UTC, cebe approved these changes

2017-04-24 19:19 UTC, SilverFire approved these changes

2017-04-24 19:20 UTC, merged

2017-04-24 19:21 UTC, SilverFire commented
Thank you!