Allow AccessControl filter to work without User component
yiisoft/yii2 pull request #14066
Opened 2017-04-27 10:40 UTC by bizley

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | a bit
| Tests pass?   | yes
| Fixed issues  | #4793

This allows `AccessControl` filter to work without `user` component since only matching role mechanism depends on it.

- `yii\filters\AccessControl::user` can be set to `false` to explicitly switch this component support off for the filter,
- `yii\filters\AccessControl::denyAccess()` throws `yii\web\ForbiddenHttpException` if the user is already logged in **or in case of detached User component**,
- `yii\filters\AccessRule::matchRole()` throws `yii\base\InvalidConfigException` if User component is detached and `yii\filters\AccessRule::roles` are not empty.

With default configuration behavior is the same as before.

Also `yiiunit\framework\filters\AccessRuleTest` methods don't require mocking User component anymore.

2017-04-27 16:30 UTC, SilverFire requested changes
Generally good

2017-04-27 16:30 UTC, SilverFire commented on tests/framework/filters/AccessRuleTest.php
> +        $this->setExpectedException('yii\base\InvalidConfigException');
Should be replaced with `expectException()`

https://github.com/yiisoft/yii2/blob/master/tests/compatibility.php#L18

2017-04-27 17:53 UTC, SilverFire approved these changes

2017-04-30 19:44 UTC, samdark approved these changes

2017-05-01 09:23 UTC, cebe requested changes

2017-05-01 09:23 UTC, cebe commented on framework/filters/AccessRule.php
> +            throw new InvalidConfigException('The required component is not specified.');
this error message could be improved:

> "The user application component must be available to specify roles in AccessRule."

2017-05-01 10:06 UTC, cebe approved these changes

2017-05-01 12:53 UTC, SilverFire approved these changes

2017-05-02 22:18 UTC, merged

2017-05-02 22:18 UTC, samdark commented
Merged. Thank you!