Added assignments cache to check access on request
yiisoft/yii2 pull request #14061
Opened 2017-04-26 17:47 UTC by leandrogehlen

| Q             | A
| ------------- | ---
| Is bugfix?    |  no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

On request the method checkAccess load assingments from database every invocation.
Example: 

```php
$access = [
  'person',
  'category,
  'product'
];

foreach ($access as $permission)  {
  if (Yii:$app->user->can($permission)) { // this will be executed the same SQL 3 times
   ...
  }
}

```

2017-04-26 20:26 UTC, SilverFire requested changes

2017-04-26 20:26 UTC, SilverFire commented on framework/rbac/DbManager.php
> +        $assignments = ArrayHelper::getValue($this->assignments, $userId);
I think it is better to do caching in `getAssignments()` method

2017-04-26 20:38 UTC, leandrogehlen commented on framework/rbac/DbManager.php
> +        $assignments = ArrayHelper::getValue($this->assignments, $userId);
i think that is not possible, because it generate  conflict with `defaultRules`

2017-04-27 08:19 UTC, MysteryDragon commented
Was this idea already rejected, or am I mistaken? #12902

2017-04-27 14:46 UTC, leandrogehlen commented
I think so, but in i disagree with @samdark, because his justification is that the assignments could be removed during the request. 

The same could be happens with anoters access resources, that currently has cache

2017-04-27 16:27 UTC, SilverFire commented
This PR implements per-request caching, that should not lead to problems, mentioned by @samdark

2017-04-27 16:31 UTC, leandrogehlen commented
Sorry @samdark, @SilverFire  i hadn't understood it

2017-04-28 05:30 UTC, MysteryDragon commented
https://github.com/yiisoft/yii2/issues/12902#issuecomment-258111421
> Кешировать (даже в пределах запроса) назначенные юзеру роли не безопасно в общем случае.
I doubt that... All right, it's up to you anyway)

2017-04-28 08:24 UTC, SilverFire commented
> Кешировать (даже в пределах запроса) назначенные юзеру роли не безопасно в общем случае.

Translation:

> Roles caching (even per-request) is not save in general

Calling for @yiisoft/core-developers thoughts

2017-04-28 10:12 UTC, klimov-paul commented
If such enhancement to be applied, it should be made optional. Caching assignments per user will lead to memory overflow in case of checking permissions over several different users during same request (for example inside console command).

2017-04-28 11:50 UTC, leandrogehlen commented
@klimov-paul, Could be used cache system per-request, to avoid memory overflow?

2017-04-28 12:13 UTC, klimov-paul commented
> Could be used cache system per-request, to avoid memory overflow?

I do not understand this: for console command there is only one request.
If you chck access for several users during same program flow - it will cause memory leak.

For example: I may want to check if user have permission to access 'gifts' section before sending an email with 'new gifts are availbale' content during mass mail cron.

2017-04-28 16:45 UTC, leandrogehlen commented
@klimov-paul, sorry my stupid question

2017-08-02 07:38 UTC, Alex-Code commented
In my `DbManager` extension I cached them like below.

```php
class DbManager extends \yii\rbac\DbManager
{
    /**
     * Store the result of getAssignments for the current request to negate multiple queries.
     * @var array
     */
    private $_assignments = [];

    /**
     * @inheritdoc
     */
    public function getAssignments($userId)
    {
        if (isset($this->_assignments[$userId])) {
            return $this->_assignments[$userId];
        }
        $this->_assignments = [];
        
        return $this->_assignments[$userId] = parent::getAssignments($userId);
    }
}
```

This way it'll query the db again if the user id changes.

2017-08-02 11:28 UTC, leandrogehlen commented
@Alex-Code, It seems that do the same think, but i don't agree to use cache for this method.
I think better to use only to check access

2017-09-01 08:50 UTC, closed without merging

2017-09-01 08:52 UTC, cebe commented
merged with adjustments in  #14696, thanks!