Refactored `yii\base\Theme`. Added tests
yiisoft/yii2 pull request #14089
Opened 2017-04-30 10:23 UTC by vladis84

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes

| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2017-05-09 07:29 UTC, dynasource requested changes
Im happy with the added tests. The rest is not 'refactoring' in which the framework will be improved.

2017-05-09 07:29 UTC, dynasource commented on framework/base/Theme.php
> +        $this->_baseUrl = $baseUrl;
these 6 lines should be compressed to one line as it will still be understandable.

2017-05-09 07:29 UTC, dynasource commented on framework/base/Theme.php
> +
$pathMap isnt required at this line anymore

2017-05-09 07:29 UTC, dynasource commented on framework/base/Theme.php
> +            if (strpos($normalizedPath, $basePath) !== 0) {
$pathMap is looped for the second time? This is not optimal and adds complexity

2017-05-11 15:57 UTC, vladis84 commented on framework/base/Theme.php
> +        $this->_baseUrl = $baseUrl;
Fix it

2017-05-11 15:58 UTC, vladis84 commented on framework/base/Theme.php
> +
Fix it

2017-05-11 15:58 UTC, vladis84 commented on framework/base/Theme.php
> +            if (strpos($normalizedPath, $basePath) !== 0) {
Fix it

2017-06-11 14:39 UTC, closed without merging

2017-06-11 14:39 UTC, samdark commented
Merged with adjustments.