Refactored yii\base\Module. Added tests
yiisoft/yii2 pull request #14085
Opened 2017-04-29 03:48 UTC by vladis84

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes/no
| Tests pass?   | yes

2017-04-29 04:24 UTC, anton-pribora approved these changes

2017-04-29 04:24 UTC, anton-pribora commented on framework/base/Module.php
> +    private function findLayout()
A little bit better I think
```php
private function findLayout()
{
    $module  = $this;

    do {
        if (is_string($module->layout)) {
            return [$module, $module->layout];
        }
    } while (($module = $module->module) !== null);

    return [null, null];
}
```

2017-04-29 04:24 UTC, anton-pribora commented on framework/base/Module.php
> +            $file = $module->getLayoutPath() . DIRECTORY_SEPARATOR . ltrim($layout, '/');
I think it should be one of `DIRECTORY_SEPARATOR . ltrim($layout, DIRECTORY_SEPARATOR);` or `'/' . ltrim($layout, '/')`

2017-04-30 20:09 UTC, samdark commented on framework/base/Controller.php
> +    public function findLayoutFile(View $view)
Method signature can't be changed in Yii 2.0.x because of backwards compatibility.

2017-05-01 04:41 UTC, vladis84 commented on framework/base/Controller.php
> +    public function findLayoutFile(View $view)
ok

2017-05-01 09:32 UTC, cebe reviewed
can you explain a bit why you made these changes? i.e. move the logic from controller to module.

2017-05-01 09:32 UTC, cebe commented on framework/BaseYii.php
> +        if (!self::isAlias($alias)) {
wrapping a function call in an extra method is unnecessary.

2017-05-01 09:32 UTC, cebe commented on framework/BaseYii.php
> +    public static function isAlias($alias)
what is the use case for this method? There should not be a need to check for this.

2017-05-01 11:08 UTC, vladis84 commented on framework/BaseYii.php
> +    public static function isAlias($alias)
https://github.com/yiisoft/yii2/pull/14085/files#diff-d24221cf7f251030273dc9f1c436ba75R747
Code reuse

2017-05-01 11:09 UTC, vladis84 commented
I think it is the duty of the module

2017-05-07 04:07 UTC, vladis84 commented on framework/BaseYii.php
> +        if (!self::isAlias($alias)) {
Public api will be broken

2017-05-07 21:58 UTC, cebe commented on framework/BaseYii.php
> +        if (!self::isAlias($alias)) {
how exactly? This adds unnecessary overhead.

2017-05-08 03:32 UTC, vladis84 commented on framework/BaseYii.php
> +        if (!self::isAlias($alias)) {
This method return 3 value.
First original parameter.
To alias path.
Three value of of alias not found false

2017-05-09 08:16 UTC, dynasource requested changes

2017-05-09 08:16 UTC, dynasource commented on framework/base/Module.php
> +        $module = $this;
$module is confusing here. This should be in the next `else` statement

2017-05-09 08:16 UTC, dynasource commented on framework/base/Module.php
> +     * @param string $layout    Layout name
this should be called $controllerLayout or $defaultLayout for a better understanding

2017-05-09 08:16 UTC, dynasource commented on framework/base/Module.php
> +    private function findLayout()
this method feels awkward. Why not simply use
```php
private function findLayout()
{
    $module = $this;
    while(module = $module->module){
        if (is_string($module->layout)) {
            return [$module, $module->layout];
        }
    }
    return false;
}
```

2017-05-09 08:16 UTC, dynasource commented on framework/base/Module.php
> +    private function findLayout()
additionally, it returns the $module + $layout, so the method should match this return result

2017-06-11 14:23 UTC, samdark commented
@vladis84 are you going to work more on it?

2018-02-03 15:11 UTC, closed without merging

2018-02-03 15:12 UTC, samdark commented
Won't be able to merge this into 2.0 and for 2.1 it doesn't make sense. Sorry.