Make FileHelper::normalizeOptions() protected
yiisoft/yii2 pull request #14098
Opened 2017-05-01 22:07 UTC by brandonkelly

We have a need to call `normalizeOptions()` in an extension of FileHelper in Craft (preceding some calls to `filterPath()`). Assume there’s no harm in making it protected, so we don’t have to copy the function over to our class, just to work around the private visibility.

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes

2017-05-01 22:44 UTC, brandonkelly commented
For context, here’s why we need this: https://github.com/craftcms/cms/commit/e66b5a288fc56ba582ecf7ffebee84e942923357

Lines 426 - 518 could be deleted if `normalizeOptions()` were protected.

2017-05-02 21:51 UTC, samdark requested changes

2017-05-02 21:51 UTC, samdark commented on framework/helpers/BaseFileHelper.php
>       * @return array normalized options
Need `@since` because it's now a part of accessible interface.

2017-05-02 22:36 UTC, brandonkelly commented on framework/helpers/BaseFileHelper.php
>       * @return array normalized options
@samdark Done

2017-05-02 22:53 UTC, merged

2017-05-02 22:53 UTC, samdark commented
Merged. Thank you!

2017-05-02 23:03 UTC, brandonkelly commented
Awesome, thanks!