How to use Yii as Microframewok
yiisoft/yii2 pull request #14154
Opened 2017-05-12 14:31 UTC by mtangoo

PR adds documentation on how to use Yii framework as "micro-framework"
As much as I tried to be accurate with the information, I didn't had enough time to test things out.

So any correction, factual or otherwise is welcome!

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | N/A
| Fixed issues  | 12500,14095

2017-07-29 15:35 UTC, dynasource approved these changes
looks ok

2017-07-29 18:06 UTC, SilverFire commented
Changed a lot. Re-review please.

2017-07-29 18:06 UTC, SilverFire approved these changes
Great job

2017-07-29 22:06 UTC, samdark approved these changes

2017-07-30 23:26 UTC, cebe requested changes
Good addition! Needs some adjustments. Also a link should be added to the guide README.

2017-07-30 23:26 UTC, cebe commented on docs/guide/tutorial-yii-as-micro-framework.md
> +Save the file and run the `composer install` command. This will install the framework with all its dependencies. Alternatively you can skip the manual creation of the `composer.json` file and just ru
"alternative" will not work because of bower dependencies.

2017-07-30 23:26 UTC, cebe commented on docs/guide/tutorial-yii-as-micro-framework.md
> +    'basePath' => __DIR__,
this will make point `@app` to the web folder. does not really make sense.

2017-07-30 23:26 UTC, cebe commented on docs/guide/tutorial-yii-as-micro-framework.md
> +> Note: In our example, we have changed default application namespace `app` to a `micro` to demonstrate that you are not tied to that name (in case you thought you were), then adjusted [controllers n
"controllers namespace" link should be a code link: `[[yii\base\Application::$controllerNamespace|controllers namespace]]

2017-07-30 23:26 UTC, cebe commented on docs/guide/tutorial-yii-as-micro-framework.md
> +namespace micro\resources;
controller namespace above does not match with this:

```
'controllerNamespace' => 'micro\controllers'
```

2017-07-30 23:26 UTC, cebe commented on docs/guide/tutorial-yii-as-micro-framework.md
> +Now you can use the application on REST API calls just like you would for any application made with Yii.
add some links to REST guide and note that setting up URL rule would be helpful to get REST URLs.

2017-07-31 10:07 UTC, mtangoo commented on docs/guide/tutorial-yii-as-micro-framework.md
> +Save the file and run the `composer install` command. This will install the framework with all its dependencies. Alternatively you can skip the manual creation of the `composer.json` file and just ru
Thanks I will remove it

2017-07-31 10:08 UTC, mtangoo commented on docs/guide/tutorial-yii-as-micro-framework.md
> +    'basePath' => __DIR__,
should I put a note or you have better idea where should it point to?

2017-07-31 10:09 UTC, mtangoo commented on docs/guide/tutorial-yii-as-micro-framework.md
> +> Note: In our example, we have changed default application namespace `app` to a `micro` to demonstrate that you are not tied to that name (in case you thought you were), then adjusted [controllers n
noted

2017-07-31 10:09 UTC, mtangoo commented on docs/guide/tutorial-yii-as-micro-framework.md
> +namespace micro\resources;
noted

2017-07-31 10:11 UTC, cebe commented on docs/guide/tutorial-yii-as-micro-framework.md
> +    'basePath' => __DIR__,
better point it to `dirname(__DIR__)` so it points to the same place as in other applications, this way example code from other places would work out of the box.

2017-07-31 10:11 UTC, cebe commented on docs/guide/tutorial-yii-as-micro-framework.md
> +Now you can use the application on REST API calls just like you would for any application made with Yii.
I can do that.

2017-07-31 10:13 UTC, mtangoo commented on docs/guide/tutorial-yii-as-micro-framework.md
> +Now you can use the application on REST API calls just like you would for any application made with Yii.
thanks

2017-07-31 10:14 UTC, mtangoo commented on docs/guide/tutorial-yii-as-micro-framework.md
> +    'basePath' => __DIR__,
noted. I will try to update them this night in case no one gets time to fix all the suggestions

2017-08-23 11:32 UTC, cebe commented
Merged and edited a bit, thank you!

2017-08-23 11:32 UTC, closed without merging