Create AttributesBehavior.php
yiisoft/yii2 pull request #14151
Opened 2017-05-12 10:25 UTC by bscheshirwork

Propose new behavior like "AttributeBehavior", but can accept multiply values

I think for multiply attributes 
we need use 
invert ([attribute => event]) syntax:
```
[
    'class' => AttributesBehavior::className(),
    'attributes' => [
        'attribute1' => [
            ActiveRecord::EVENT_BEFORE_INSERT => new Expression('NOW()'),
            ActiveRecord::EVENT_BEFORE_UPDATE => \Yii::$app->formatter->asDatetime('0000-00-00'),
        ],
        'attribute2' => [
            ActiveRecord::EVENT_BEFORE_VALIDATE => [$this, 'storeAttributes'],
            ActiveRecord::EVENT_AFTER_VALIDATE => [$this, 'restoreAttributes'],
        ],
        'attribute3' => [
            ActiveRecord::EVENT_BEFORE_VALIDATE => $fn2 = [$this, 'getAttribute2'],
            ActiveRecord::EVENT_AFTER_VALIDATE => $fn2,
        ],
        'attribute4' => [
            ActiveRecord::EVENT_BEFORE_DELETE => function($event) {static::disabled() || $event->isValid = false;},
        ],
    ],
],
```

Let's discuss!

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Links  | #14101, #9921

2017-07-13 18:23 UTC, samdark commented
@yiisoft/core-developers thoughts?

2017-07-13 18:46 UTC, SilverFire commented
Good idea, I'm voting for

2017-07-13 18:55 UTC, dynasource commented
Im positive based on https://github.com/yiisoft/yii2/pull/14101#issuecomment-300434317

2017-07-13 19:15 UTC, blacksmoke26 commented
+1 for this

2017-08-13 18:43 UTC, SilverFire approved these changes

2017-08-13 21:58 UTC, samdark requested changes

2017-08-13 21:58 UTC, samdark commented on framework/behaviors/AttributesBehavior.php
> + * AttributeBehavior automatically assigns a specified values to one or multiple attributes of an ActiveRecord
`AttributeBehavior` → `AttributesBehavior`.

2017-08-13 21:58 UTC, samdark commented on framework/behaviors/AttributesBehavior.php
> + * AttributeBehavior automatically assigns a specified values to one or multiple attributes of an ActiveRecord
a specified values → values specified

2017-08-13 21:59 UTC, samdark approved these changes

2017-08-13 22:03 UTC, merged

2017-08-13 22:03 UTC, samdark commented
Merged. Thank you!