Removed non-default call of `$app-get()` in favor of using `$app->has()`
yiisoft/yii2 pull request #14185
Opened 2017-05-22 08:59 UTC by SamMousa

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes

This is a small code quality improvement. Related to #14184

2017-05-22 09:05 UTC, lynicidn commented on framework/behaviors/BlameableBehavior.php
> +            return !$user->isGuest ? $user->id : null;
this equal:
return $user->getId();
https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L338

2017-05-22 09:15 UTC, SamMousa commented on framework/behaviors/BlameableBehavior.php
> +            return !$user->isGuest ? $user->id : null;
Nice, even better :)

2017-06-15 10:44 UTC, SamMousa commented
I think this can be merged.

2017-06-20 23:17 UTC, samdark commented on framework/behaviors/BlameableBehavior.php
> +        if ($this->value === null && Yii::$app->has('user')) {
`!$user->isGuest` check is missing. Because of that behavior is not the same as it was.

2017-06-20 23:17 UTC, samdark requested changes
Changed code doesn't look like equivalent of the previous code.

2017-07-03 11:49 UTC, cebe commented
why do you think it is better to call two methods instead of one? Or what exactly is the improvement? I see no reason to change it.

2017-07-03 11:52 UTC, SamMousa commented
@cebe Depending on the implementation there could be large differences.

If the API offers a `has` and a `get` then for checking it makes sense to use `has`. There could be an implementation where checking is a lot cheaper than actually retrieving.

Why even offer `has` if it is better to just check the result of `get`?

2017-07-03 12:13 UTC, samdark commented
`has()` is there for cases when you don't need the value but actually need to check if there's something or not.

2017-07-03 12:13 UTC, samdark commented
@SamMousa how about https://github.com/yiisoft/yii2/pull/14185#discussion_r123120165?

2017-07-03 12:18 UTC, SamMousa commented on framework/behaviors/BlameableBehavior.php
> +        if ($this->value === null && Yii::$app->has('user')) {
Actually this is already part of the getter:
````
    public function getId()
    {
        $identity = $this->getIdentity();

        return $identity !== null ? $identity->getId() : null;
    }

    public function getIsGuest()
    {
        return $this->getIdentity() === null;
    }
````

2017-07-03 12:20 UTC, samdark approved these changes

2017-07-03 12:21 UTC, SamMousa commented
@samdark See the comment I just added.
@cebe Using `$app->has` does not instantiate the component; `$app->get()` does.

If your code does this:
````
if ($app->get('test', false) === null) {
    // Some stuff here.
    $app->get('test')->someFunc();
    $app->get('someOtherComponent')->test();
}
````
It doesn't matter what you use. But if then, 2 years later you don't need the 3rd line and you remove it:
````
if ($app->get('test', false) === null) {
    // Some stuff here.
    $app->get('someOtherComponent')->test();
}
````

Now you're instantiating a component you no longer need; you just need to know it exists.

2017-07-03 13:39 UTC, cebe commented
> But if then, 2 years later you don't need the 3rd line

I am fine with changing it to `has()` two years later then ;)

2017-07-03 13:44 UTC, SamMousa commented
But who says it is actually @cebe making the change? The point I was trying to make is that the code is not descriptive.
You're not getting a component you're checking if the application knows about a component.
It doesn't matter if you get it or not 2 lines later, in the guard of the if statement you are just checking existence.

2017-07-03 17:54 UTC, dynasource approved these changes
it's better readable, although it is less obvious that guests return null

2017-07-04 09:41 UTC, cebe approved these changes

2017-07-04 10:52 UTC, merged

2017-07-04 10:52 UTC, samdark commented
Merged. Thanks!