Optimization complexity and test coverage of \yii\helpers\BaseArrayHelper::merge()
yiisoft/yii2 pull request #14197
Opened 2017-05-24 08:48 UTC by ilyar

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  |

2017-05-24 10:55 UTC, samdark requested changes

2017-05-24 10:55 UTC, samdark commented on framework/helpers/BaseArrayHelper.php
> +    public static function merge(array $a, array $b = [])
I don't think we can adjust signature like that in 2.0.x. Would break backwards compatibility.

2017-05-24 10:55 UTC, samdark commented on framework/helpers/BaseArrayHelper.php
> +        $merge = function (array $res, array $b) use (&$merge) {
I think new implementation could be significantly slower. Worth making performance benchmarks on small, mid-size and large arrays.

2017-05-24 12:22 UTC, ilyar commented on framework/helpers/BaseArrayHelper.php
> +        $merge = function (array $res, array $b) use (&$merge) {
Good. I will think about this. I will be happy your advice (link to doc or tools).

2017-05-24 12:25 UTC, ilyar commented on framework/helpers/BaseArrayHelper.php
> +    public static function merge(array $a, array $b = [])
I understand, I'll correct it.
Are yor sure that BC breaks, please specify exactly how?

2017-05-24 13:51 UTC, samdark commented on framework/helpers/BaseArrayHelper.php
> +        $merge = function (array $res, array $b) use (&$merge) {
https://github.com/phpbench/phpbench

2017-05-24 13:53 UTC, samdark commented on framework/helpers/BaseArrayHelper.php
> +    public static function merge(array $a, array $b = [])
https://3v4l.org/hGLUF

2018-02-03 15:27 UTC, samdark commented
Sorry it took that long to run benchmarks. They've confirmed what I was worried about:

```php
+-------------------+------------------------+--------+--------+------+------+------------+----------+--------------+----------------+
| benchmark         | subject                | groups | params | revs | iter | mem_peak   | time_rev | comp_z_value | comp_deviation |
+-------------------+------------------------+--------+--------+------+------+------------+----------+--------------+----------------+
| TimeConsumerBench | benchMergeTooArray     |        | []     | 1000 | 0    | 1,965,984b | 4.997μs  | +1.68σ       | +1.54%         |
| TimeConsumerBench | benchMergeTooArray     |        | []     | 1000 | 1    | 1,965,984b | 4.938μs  | +0.38σ       | +0.35%         |
| TimeConsumerBench | benchMergeTooArray     |        | []     | 1000 | 2    | 1,965,984b | 4.883μs  | -0.84σ       | -0.77%         |
| TimeConsumerBench | benchMergeTooArray     |        | []     | 1000 | 3    | 1,965,984b | 4.918μs  | -0.07σ       | -0.06%         |
| TimeConsumerBench | benchMergeTooArray     |        | []     | 1000 | 4    | 1,965,984b | 4.869μs  | -1.15σ       | -1.06%         |
| TimeConsumerBench | benchMergeTooArrayOld  |        | []     | 1000 | 0    | 1,473,912b | 4.145μs  | -1.39σ       | -2.8%          |
| TimeConsumerBench | benchMergeTooArrayOld  |        | []     | 1000 | 1    | 1,473,912b | 4.407μs  | +1.67σ       | +3.35%         |
| TimeConsumerBench | benchMergeTooArrayOld  |        | []     | 1000 | 2    | 1,473,912b | 4.263μs  | -0.01σ       | -0.03%         |
| TimeConsumerBench | benchMergeTooArrayOld  |        | []     | 1000 | 3    | 1,473,912b | 4.224μs  | -0.47σ       | -0.94%         |
| TimeConsumerBench | benchMergeTooArrayOld  |        | []     | 1000 | 4    | 1,473,912b | 4.282μs  | +0.21σ       | +0.42%         |
| TimeConsumerBench | benchMergeMoreArray    |        | []     | 1000 | 0    | 3,455,920b | 14.679μs | -1.16σ       | -0.49%         |
| TimeConsumerBench | benchMergeMoreArray    |        | []     | 1000 | 1    | 3,455,920b | 14.717μs | -0.55σ       | -0.23%         |
| TimeConsumerBench | benchMergeMoreArray    |        | []     | 1000 | 2    | 3,455,920b | 14.855μs | +1.65σ       | +0.70%         |
| TimeConsumerBench | benchMergeMoreArray    |        | []     | 1000 | 3    | 3,455,920b | 14.789μs | +0.60σ       | +0.25%         |
| TimeConsumerBench | benchMergeMoreArray    |        | []     | 1000 | 4    | 3,455,920b | 14.718μs | -0.54σ       | -0.23%         |
| TimeConsumerBench | benchMergeMoreArrayOld |        | []     | 1000 | 0    | 2,951,016b | 13.522μs | -0.84σ       | -0.74%         |
| TimeConsumerBench | benchMergeMoreArrayOld |        | []     | 1000 | 1    | 2,951,016b | 13.544μs | -0.65σ       | -0.58%         |
| TimeConsumerBench | benchMergeMoreArrayOld |        | []     | 1000 | 2    | 2,951,016b | 13.579μs | -0.36σ       | -0.32%         |
| TimeConsumerBench | benchMergeMoreArrayOld |        | []     | 1000 | 3    | 2,951,016b | 13.613μs | -0.08σ       | -0.07%         |
| TimeConsumerBench | benchMergeMoreArrayOld |        | []     | 1000 | 4    | 2,951,016b | 13.856μs | +1.93σ       | +1.71%         |
+-------------------+------------------------+--------+--------+------+------+------------+----------+--------------+----------------+
```

Based on test results I don't think it's a good idea to merge PR.

2018-02-03 15:27 UTC, closed without merging