Add test coverage of yii\helpers\BaseArrayHelper
yiisoft/yii2 pull request #14205
Opened 2017-05-24 20:19 UTC by ilyar

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Test coverage?   | up 
| Fixed issues  |

2017-05-24 22:24 UTC, cebe requested changes

2017-05-24 22:24 UTC, cebe commented on tests/framework/helpers/ArrayHelperTest.php
> +        $this->assertEquals([], ArrayHelper::toArray($dataArrayable));
what are you testing here? converting empty object to an empty array? if so, `new stdClass` would be more intuitive than calling getMock() for it.

2017-05-25 06:16 UTC, ilyar commented on tests/framework/helpers/ArrayHelperTest.php
> +        $this->assertEquals([], ArrayHelper::toArray($dataArrayable));
This is test line https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseArrayHelper.php#L87 I made a mistake in the name of the class should be interface `yii\base\Arrayable`.

2017-05-25 06:46 UTC, ilyar commented on tests/framework/helpers/ArrayHelperTest.php
> +        $this->assertEquals([], ArrayHelper::toArray($dataArrayable));
done

2017-05-25 09:11 UTC, cebe approved these changes

2017-05-25 09:12 UTC, merged

2017-05-25 09:12 UTC, samdark commented
Merged. Thank you!