[WiP] Add test coverage of yii\helpers\Html
yiisoft/yii2 pull request #14220
Opened 2017-05-27 11:37 UTC by ilyar

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | up
| Fixed issues  |

2017-05-27 12:05 UTC, ilyar commented on tests/framework/helpers/HtmlTest.php
> +    public function testBeginFormSimulateViaPost()
Perhaps it https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L336 should be so `if (strcasecmp($method, 'get') or strcasecmp($method, 'post')) {`

2017-05-27 18:51 UTC, ilyar reviewed
:shipit:  ready

2017-05-27 22:39 UTC, samdark requested changes

2017-05-27 22:39 UTC, samdark commented on tests/framework/helpers/HtmlTest.php
> +        $this->assertEquals('', Html::csrfMetaTags());
It's not clear what is tested here. Empty string is returned because we're in console environment, not because CSRF validation is disabled.

2017-05-27 22:39 UTC, samdark commented on tests/framework/helpers/HtmlTest.php
> +    public function testBeginFormSimulateViaPost($expected, $method)
Method name `SimulateViaPost` doesn't match data from data provider since there are other methods as well.

2017-05-28 06:36 UTC, ilyar commented on tests/framework/helpers/HtmlTest.php
> +        $this->assertEquals('', Html::csrfMetaTags());
This is test coverage for framework/helpers/BaseHtml.php:305 result if Disable Csrf Validation:

https://scrutinizer-ci.com/g/yiisoft/yii2/code-structure/master/code-coverage/framework/helpers/BaseHtml.php

2017-05-28 06:49 UTC, ilyar commented on tests/framework/helpers/HtmlTest.php
> +    public function testBeginFormSimulateViaPost($expected, $method)
Method `testBeginFormSimulateViaPost` and data `providerBeginFormSimulateViaPost` testing conition `framework/helpers/BaseHtml.php:336` neme for method i based on comment from `framework/helpers/BaseHtml.php:337`:

> simulate PUT, DELETE, etc. via POST

2017-05-28 07:36 UTC, ilyar commented on tests/framework/helpers/HtmlTest.php
> +        $this->assertEquals('', Html::csrfMetaTags());
It is unclear what exactly needs to be corrected. Maybe I need to rename the method `providerBeginFormSimulateViaPost` to `dataProviderBeginFormSimulateViaPost` for consistency?

2017-05-28 07:36 UTC, ilyar commented on tests/framework/helpers/HtmlTest.php
> +    public function testBeginFormSimulateViaPost($expected, $method)
It is unclear what exactly needs to be corrected.

2017-05-28 12:30 UTC, samdark commented on tests/framework/helpers/HtmlTest.php
> +        $this->assertEquals('', Html::csrfMetaTags());
Empty string will be returned even if validation is enabled since you're under CLI environment.

2017-05-28 12:30 UTC, samdark commented on tests/framework/helpers/HtmlTest.php
> +    public function testBeginFormSimulateViaPost($expected, $method)
Method name.

2017-05-28 12:47 UTC, ilyar reviewed
fix done

2017-05-28 12:57 UTC, samdark approved these changes

2017-05-28 13:03 UTC, merged

2017-05-28 13:03 UTC, samdark commented
Merged. Thank you!