[WIP] ActiveRecordInterface improvements
yiisoft/yii2 pull request #14295
Opened 2017-06-15 11:41 UTC by SamMousa

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes/no
| Related issues  | #9745

This is a work in progress.

2017-06-15 12:17 UTC, SamMousa commented
The failing tests seem to not be originating in any code but in the test environment.

2017-06-17 11:23 UTC, samdark requested changes

2017-06-17 11:23 UTC, samdark commented on framework/db/ActiveRecordInterface.php
> +    public function afterFind();
Doesn't look like it belongs here. Even if it does, there are other alike methods such as `afterSave()`.

2017-06-17 11:35 UTC, cebe commented
Thank you for the proposal.

> populateRecord ActiveQueryTrait#134
> instantiateActiveQueryTrait#134

while they are called within the trait, adding them to the interface it would limit the possibilities of implementing ARInterface in different ways that use different ways of instantiating records.
I do not think there is a good practical reason to add these to the interface, even if it would be theoretically more correct solution.

> afterFind ActiveQuery#223

This is the implementation bound to a concrete relalisation of ActiveRecordInterface for DB, its fine to expect a db\ActiveRecord here.

2017-06-19 07:40 UTC, SamMousa commented on framework/db/ActiveRecordInterface.php
> +    public function afterFind();
@samdark, I've listed my "proofs" in the post. This is the exempt is from `ActiveQuery` line 221:
````
        if (!$this->asArray) {
            foreach ($models as $model) {
                $model->afterFind();
            }
````
If you call it without checking if it exists you're assuming it is there. Which means it should be in the interface.

2017-06-19 07:44 UTC, klimov-paul commented on framework/db/ActiveRecordInterface.php
> +    public function afterFind();
ActiveRecordTrait has been design for the `BaseActiveRecord` in order to reuse the code for common inplementations. It does not sticts to `ActiveRecordInterface` anyhow.

2017-06-19 07:44 UTC, SamMousa commented
I feel the querying should be separate from the models. If the query related classes do something it should be part of the AR interface otherwise I cannot implement my own AR models that work with the query part.

2017-06-19 07:46 UTC, SamMousa commented on framework/db/ActiveRecordInterface.php
> +    public function afterFind();
I'm not talking about `ActiveRecordTrait`?

2017-06-19 07:48 UTC, klimov-paul commented
> I feel the querying should be separate from the models. If the query related classes do something it should be part of the AR interface otherwise I cannot implement my own AR models that work with the query part.

There are `ActiveRecordInterface` and `ActiveQueryInterface` thier method lists are consistent. If you create your own implementation you need to satisfy those interfaces.
`ActiveQueryTrait` is a particular implementation, to be precise - a shared part of particular implementation, which is bound to `BaseActiveRecord` class, which is a shared part of particular implementation.
If you wish to use `ActiveQueryTrait` you should either extend your `ActiveRecord` from `BaseActiveRecord` or implement it compatible way.
if you wish to create pure ActiveRecord/ActiveQuery implementation you should use nothing but `ActiveRecordInterface` and `ActiveQueryInterface`.

2017-06-19 07:50 UTC, SamMousa commented
They are not consistent separately. If I implement `ActiveRecordInterface` in my model class. And try to retrieve instances of it via Yii's `ActiveQuery` concrete implementation, it will break because the `ActiveRecordInterface` is incomplete.

2017-06-19 07:54 UTC, klimov-paul commented
> They are not consistent separately. If I implement ActiveRecordInterface in my model class. And try to retrieve instances of it via Yii's ActiveQuery concrete implementation, it will break because the ActiveRecordInterface is incomplete.

???
What are you actually trying to do? Are you attempt to use `yii\db\ActiveQuery` for `yii\mongodb\ActiveRecord` or something?

Particular ActiveRecord and ActiveQuery is **always** a pair. If while creating such a pair you can reuse code from `BaseActiveRecord` or `ActiveQueryTrait` it is fine, but if it does not fit - you should avoid them and craete implementation from scratch.

2017-06-19 07:57 UTC, klimov-paul commented on framework/db/ActiveRecordInterface.php
> +    public function afterFind();
Here are **your** links from the PR description:

- populateRecord [ActiveQueryTrait#134](https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQueryTrait.php#L134)
- instantiate[ActiveQueryTrait#134](https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQueryTrait.php#L132)
- afterFind [ActiveQuery#223](https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQuery.php#L223)

2 are pointing to `ActiveQureyTrait` and 1 to `ActiveQuery` (the one specific for `yii\db\ActiveRecord` and **not shared** for `yii\mongodb\ActiveRecord` for instance).

2017-06-19 07:57 UTC, SamMousa commented
> Particular ActiveRecord and ActiveQuery is always a pair. If while creating such a pair you can reuse code from BaseActiveRecord or ActiveQueryTrait it is fine, but if it does not fit - you should avoid them and craete implementation from scratch.

Why? There is no argument for this, just the fact that your interface is incomplete forces them to be a pair...
If the interface is complete, then by definition concrete implementations are exchangeable.

2017-06-19 07:59 UTC, klimov-paul commented
> Why? There is no argument for this, just the fact that your interface is incomplete forces them to be a pair...
If the interface is complete, then by definition concrete implementations are exchangeable.

Very well, lets start from beginning then: can you please open a famous book by Martin Fowler named " Patterns of Enterprise Application Architecture" and draw a class diagram for 'ActiveRecord' pattern? How does it look like?

2017-06-19 08:10 UTC, SamMousa commented
That's a non-argument. You've split the query logic away from the `ActiveRecord` class. There is no argument to then couple the interface when there's no need to.

Anyway, I don't feel like there is a point to try and change your mind, it hasn't ever happened before. Instead I'll try to convince the team members who take the time to think for themselves instead of blindly quoting Martin Fowler like he wrote the bible.

2017-06-19 08:37 UTC, klimov-paul commented
> That's a non-argument.

I can say just the same for yours: as I have already said [here](https://github.com/yiisoft/yii2/pull/14295#issuecomment-309365717) at the present state you are talking that `yii\mongodb\ActiveRecord` should be actually able to use `yii\db\ActiveQuery` for the models search. This can not happen anyhow

> You've split the query logic away from the ActiveRecord class. There is no argument to then couple the interface when there's no need to.

This is a common practice and used in other places too. For example, see:
https://github.com/yiisoft/yii2/blob/master/framework/db/mssql/TableSchema.php#L22
https://github.com/yiisoft/yii2/blob/master/framework/db/mssql/Schema.php#L160

Here we can also tell, that `$catalogName` should belong to `\yii\db\TableSchema` to produce consistent `TableSchema` class interface, even if it not used anywhere besides MSSQL.
Here we can say your argument: why I can not take plain `yii/db/TableSchema` an use it with `yii/db/mssql/Schema`?
Should we change this and other places as well to make you feel better?

> Anyway, I don't feel like there is a point to try and change your mind, it hasn't ever happened before. Instead I'll try to convince the team members who take the time to think for themselves instead of blindly quoting Martin Fowler like he wrote the bible.

It is a pity you do not want to re-think the issue from beginning with me.
The point is an ActiveRecord is a monolith: it incapsulates BOTH finding and saving the data. It can not function otherwise - that is why it is called ACTIVE record actually. Creating a separated ActiveQuery was a design choice, which simplifies and structures the implementation. And even still ActiveRecord actually hides ActiveQuery behind the scenes: developer uses `ActiveRecord::find()` to instatiate an ActiveQuery instead of `new ActiveQuery()`.

Here you wish to extend `ActiveQueryInterface` with extra methods, which puts a restriction on the possible particular implementation. You enforce `afterFind` method, which according to its specification should trigger a Yii event, while particular ActiveRecord library may be built on non-Yii classes an use its own event managenemt or do not use events at all. You are converting a necessity into a requirement/restriction here.

Your argument is there should not be any `such method does not exist` error during using any combination of ActiveRecord and ActiveQuery, while random combnation of thoses will definetely produce other fatal errors.

2017-06-20 16:16 UTC, cebe commented
@SamMousa I agree with @klimov-paul in the point that there is not reason in separating ActiveRecord and ActiveQuery implementations. AR and AQ are a set of classes that play together, i.e. highly depend on each other. There is a balance to take between perfect interface completeness (formal correctness) and practical usage. Yii is mostly following the practical path. Unless you have a concrete implementation that would show up a problem with the current interface I would prefer to not make any changes to the interface.

2017-06-20 22:43 UTC, samdark commented
I agree with @cebe and @klimov-paul. In this particular case initial proof seem to be incorrect.

2017-06-20 22:43 UTC, closed without merging