Add method ArrayHelper::setValue() Writes a value to the array at the specified path.
yiisoft/yii2 pull request #14351
Opened 2017-06-26 19:47 UTC by LAV45

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #6644

Writes a value to the array at the specified path.
If the array key specified path is missing, then it will be created and it is assigned an appropriate value.
If the key exists, then it will be overwritten.

2017-06-27 15:15 UTC, samdark requested changes

2017-06-27 15:15 UTC, samdark commented on framework/helpers/BaseArrayHelper.php
> +     * @param array $array
Need descriptions.

2017-06-27 15:15 UTC, samdark commented on framework/helpers/BaseArrayHelper.php
> +            if (isset($array[$left_key])) {
Variables should be named in camelCase such as `$leftKey`.

2017-07-03 17:03 UTC, samdark requested changes
I think it should behave similar to ArrayHelper::getValue() i.e. support specifying path as an array.

2017-07-03 18:12 UTC, LAV45 commented
you can add support for both options

2017-07-03 18:16 UTC, samdark commented
Please do.

2017-07-04 09:47 UTC, cebe commented
Looks good to me in general. Have you considered passing the array by reference?
Using it like this might be more useful:

```php
$array = [ ... ];
ArrayHelper::setValue($array, 'components.db', [ ... ]);
ArrayHelper::setValue($array, 'components.cache', [ ... ]);
// ...
```

compared to:

```php
$array = [ ... ];
$array = ArrayHelper::setValue($array, 'components.db', [ ... ]);
$array = ArrayHelper::setValue($array, 'components.cache', [ ... ]);
// ...
```

or are there good reasons/use cases where you'd want to keep the original array?

2017-07-07 08:03 UTC, LAV45 commented
Check description on the `docs/guide-ru/helper-array.md` if everything is OK then I translate it in English

2017-07-11 21:34 UTC, samdark requested changes
Wording should be fixed but overall info in the guide is good. Please translate into English.

2017-07-11 21:34 UTC, samdark commented on docs/guide-ru/helper-array.md
> +В результате исходное значение `$array['key']['in']` будет перезаписано но новое
но новое → новым

2017-07-11 21:34 UTC, samdark commented on docs/guide-ru/helper-array.md
> +// путь можно по которому записано новое значение в `$array` может указать как массив
путь можно по которому записано новое значение → путь для записи значения

2017-07-12 09:25 UTC, cebe requested changes

2017-07-12 09:25 UTC, cebe commented on framework/helpers/BaseArrayHelper.php
> +        if (is_null($path)) {
`is_null($path)` -> `$path === null`

2017-07-12 09:25 UTC, cebe commented on framework/helpers/BaseArrayHelper.php
> +     * @return array a new array with the value written
there is no need to return the array if it is passed by reference.

2017-07-12 19:23 UTC, dynasource approved these changes
nice work

2017-07-12 19:26 UTC, samdark commented on docs/guide-ru/helper-array.md
> +// путь можно по которому записано новое значение в `$array` может указать как массив
может → можно

2017-07-15 21:23 UTC, samdark approved these changes

2017-07-15 21:25 UTC, samdark commented
Merging since @cebe comments were addressed.

2017-07-15 21:25 UTC, merged

2017-07-15 21:25 UTC, samdark commented
Merged. Thank you!

2017-11-03 17:12 UTC, mattether commented
Do you think this should work for objects, as `getValue` does?

I've put in a dirty fix, which works on ActiveRecords, checking whether the `$array` has an attribute for the first `$keys`

```php
//...
if (is_object($array) && $array instanceof \yii\db\ActiveRecord && $array->hasAttribute($keys[0]))
//...
```

Obviously could be a lot better, just wondering whether you think the core should handle it?

2017-11-03 18:04 UTC, samdark commented
Not sure about it. What's use case?

2017-11-03 18:04 UTC, samdark commented
Don't know. Let's wait till it's asked for i.e. when it's really required for a project.