issue #13674 fix
yiisoft/yii2 pull request #14372
Opened 2017-06-30 15:49 UTC by dabkhazi

framework/db/mssql/QueryBuilder.php

Before (normalizeColumns):

             foreach ($columns as $name => $value) {
                 // @see https://github.com/yiisoft/yii2/issues/12599
                if (isset($columnSchemas[$name]) && $columnSchemas[$name]->type === Schema::TYPE_BINARY && $columnSchemas[$name]->dbType === 'varbinary' && is_string($value)) {
                     $phName = self::PARAM_PREFIX . count($params);
                    $columns[$name] = new Expression("CONVERT(VARBINARY, $phName)", [$phName => $value]);
                 }
             }

After:

             foreach ($columns as $name => $value) {
                 // @see https://github.com/yiisoft/yii2/issues/12599
                if (isset($columnSchemas[$name]) && $columnSchemas[$name]->type === Schema::TYPE_BINARY && $columnSchemas[$name]->dbType === 'varbinary' && (is_string($value) || is_null($value))) {
                     $phName = self::PARAM_PREFIX . count($params);
                    $params[$phName] = $value;
                    $columns[$name] = new Expression("CONVERT(VARBINARY(MAX), $phName)", [$phName => $value]);
                 }
             }

Comments: 
+is_null($value) - this fix inserting null values into varbinary field
+$params[$phName] = $value; - this fix params counter

framework/rbac/DBManager.php

Before (getRule):

        $row = (new Query())->select(['data'])
             ->from($this->ruleTable)
             ->where(['name' => $name])
             ->one($this->db);

After:

    /**
     * Convert binary column to string
     * @param string $column the name of column to be converted
     */       
    protected function toStringBinaryColumn($column) {  
        if ($this->db->getDriverName() == 'sqlsrv') {
            $toType = $this->db->charset == 'utf8' ? 'NVARCHAR(MAX)' : 'VARCHAR(MAX)';
            return new Expression("CONVERT($toType,$column) $column");  
        }
        return $column;
    }
    
    /**
     * Check if the columns of type binary and convert it to string
     * @param string $table the name of table
     * @param array $columns the column names
     */    
    protected function normalizeColumns($table,$columns) {
        if (($tableSchema = $this->db->getSchema()->getTableSchema($table)) !== null) {
            $result = [];
            $columnSchemas = $tableSchema->columns;
            foreach ($columns as $column) {
                if (isset($columnSchemas[$column]) && $columnSchemas[$column]->type === \yii\db\Schema::TYPE_BINARY) {
                    $result[] = $this->toStringBinaryColumn($column);
                } else {
                    $result[] = $column;
                }   
            }
            return $result;
        }
        return $columns;
    }

getRule:

        $row = (new Query)->select($this->normalizeColumns($this->ruleTable,['data']))        
             ->from($this->ruleTable)
             ->where(['name' => $name])
             ->one($this->db);

Comments: Rule lives in column with name - data, for mssql DB it has type Varbinary and before unserialize the value of this column we need to convert value into string.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2017-09-13 09:26 UTC, achretien commented
Have the same issue.

I add to convert back the data part in all those lines:

https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L241
https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L425
https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L471
https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L519
https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L554
https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L590
https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L643
https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L667
https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L810
https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L1006

2017-09-28 08:49 UTC, sergeymakinen requested changes
I got some questions.
Also: shouldn't all queries in `DbManager` be wrapped with `normlizeColumns`?

And it has to be covered with tests as I feel a possibility of unintentional half-fixes.

2017-09-28 08:49 UTC, sergeymakinen commented on framework/db/mssql/QueryBuilder.php
> +                if (isset($columnSchemas[$name]) && $columnSchemas[$name]->type === Schema::TYPE_BINARY && $columnSchemas[$name]->dbType === 'varbinary' && (is_string($value) || is_null($value))) {
I don't exactly understand why casting `NULL` to `VARBINARY` is necessary here. Nulls seem to work fine.

2017-09-28 08:49 UTC, sergeymakinen commented on framework/rbac/DbManager.php
> +    protected function toStringBinaryColumn($column) {
Should this be null aware?

2017-09-28 09:03 UTC, dabkhazi commented on framework/db/mssql/QueryBuilder.php
> +                if (isset($columnSchemas[$name]) && $columnSchemas[$name]->type === Schema::TYPE_BINARY && $columnSchemas[$name]->dbType === 'varbinary' && (is_string($value) || is_null($value))) {
Сергей,  без is_null($value) падает с ошибкой. (SQL Server 11.0,3)

2019-03-09 10:48 UTC, samdark commented
Doesn't seem to be apply-able.

2019-03-09 10:48 UTC, closed without merging