calling getAttributeNames() only once
yiisoft/yii2 pull request #14389
Opened 2017-07-04 16:54 UTC by nicdnepr

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    |  yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2017-07-04 17:37 UTC, samdark approved these changes

2017-07-05 10:17 UTC, cebe requested changes

2017-07-05 10:17 UTC, cebe commented on framework/validators/Validator.php
> +            $cleanAttributes = $this->getAttributeNames();
a better variable name would be `$attributeNames`

2017-07-05 10:21 UTC, cebe commented
merged with variable name adjustment. Thank you!

2017-07-05 10:21 UTC, closed without merging