Logfile compression
yiisoft/yii2 pull request #14433
Opened 2017-07-11 12:45 UTC by cebe

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13854

best to be reviewed in two steps: 7b89162 + 3fa3ba6

2017-07-11 12:48 UTC, klimov-paul commented
Why `*.gz` only?
if you wish to support archiving of the files there should be option to use any archive format `*.tar`, `*.zip`, `*.rar` etc.
Hardcoding single `*.gz` can not satisfy all needs.

2017-07-11 12:55 UTC, klimov-paul commented
Would't it be better to simply introduce an event or callback, which should be triggered after particular file has been rotated, so developer may choose, what to do with it?
For example, besides compression, some people tranfer log file to separated file storage server.

2017-07-11 13:54 UTC, cebe commented
> Why *.gz only?

because it is directly supported by PHP, other methods would need more complex implementation or external tools.



> Hardcoding single *.gz can not satisfy all needs.

this is a start for supporting compression, `.gz` is the most common one for logs. it can be extended later.



> Would't it be better to simply introduce an event or callback, which should be triggered after particular file has been rotated, so developer may choose, what to do with it?

you can override `compressFile()` method if you want to customize behavior



> For example, besides compression, some people tranfer log file to separated file storage server.

There are tons of different ways to do this. and dependent on the case a spearate log target should be created for that.

2017-07-11 13:59 UTC, klimov-paul commented
> There are tons of different ways to do this. and dependent on the case a spearate log target should be created for that.

I can say just the same thing for compression feature.

2017-07-11 14:01 UTC, klimov-paul commented
> this is a start for supporting compression, .gz is the most common one for logs. it can be extended later.

That is the point: it is a start, but where it will lead? Starting support of compression log files we can end in countless request for its expansion for many purposes.
Framework either should provide sophisticated level for file archiving or do not provide it at all.

2017-07-11 15:53 UTC, dynasource commented
based on the fact that the framework already covers log rotation, it makes sense to include compression.  It also makes sense to provide such standard GZ compression as a default.

2017-07-11 16:52 UTC, rob006 commented
We could extract compressor to separate component - basic implementation (gzip) will be provided by framework, other options may be provided by extensions.

2017-07-11 19:39 UTC, samdark requested changes

2017-07-11 19:39 UTC, samdark commented on framework/log/FileTarget.php
> +     * @param string $target the target file name.
Need `@since`.

2017-07-11 19:39 UTC, samdark commented on framework/log/FileTarget.php
> +        $gz = gzopen($gzFilename, 'wb9');
How about making compression rate and filtration flags configurable?

2017-07-11 19:39 UTC, samdark commented on framework/log/FileTarget.php
> +        while(!feof($f)) {
Formatting...

2017-07-11 19:39 UTC, samdark commented on framework/log/FileTarget.php
> +            gzwrite($gz, fread($f, 8192));
What is 8192?

2017-07-11 19:39 UTC, samdark commented on framework/log/FileTarget.php
> +    protected function compressFile($filename)
Is it possible that multiple processes call `compressFile` for the same file concurrently?

2017-07-11 23:30 UTC, cebe commented on framework/log/FileTarget.php
> +            gzwrite($gz, fread($f, 8192));
default chunk size from the fread docs.

2017-07-11 23:31 UTC, cebe commented on framework/log/FileTarget.php
> +            if (!is_file($rotateFile)) {
there is no else on this one :) only if the file does not exist, something needs to be done.

2017-07-11 23:34 UTC, cebe commented on framework/log/FileTarget.php
> +    protected function compressFile($filename)
yes, same as `rotateFile()`. As far as I see they would do the compression twice. needs to be checked.

2017-07-12 09:26 UTC, samdark commented on framework/log/FileTarget.php
> +            if (!is_file($rotateFile)) {
OK. I've missed extra condition inside looking at `continue` statement. Everything's fine.

2018-02-03 15:04 UTC, samdark commented
Does not seem we can fix it in time to get into 2.0.

2019-04-18 23:38 UTC, closed without merging