Fixes #14423, wrong checking existing keys in ArrayHelper::merge with…
yiisoft/yii2 pull request #14444
Opened 2017-07-12 15:06 UTC by dmirogin

Wrong checking existing keys in ArrayHelper::merge with null values for integer-keyed elements

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #14423

2017-07-12 17:01 UTC, dynasource requested changes
thanks for improving the merge function. Could you limit the size of the test in which your usecase is still covered correctly?

2017-07-12 19:25 UTC, samdark approved these changes

2017-07-12 20:31 UTC, dmirogin commented
Yeah, sure, made shorter, but still covered.

2017-07-13 07:06 UTC, dynasource approved these changes

2017-07-13 07:37 UTC, merged

2017-07-13 07:37 UTC, samdark commented
Thanks!