Fixes 14366 upgrade php 72alpha
yiisoft/yii2 pull request #14449
Opened 2017-07-13 12:05 UTC by dynasource

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #14366

2017-07-13 13:58 UTC, samdark approved these changes
Formatting should be fixed and changelog should be added. Other than that looks good.

2017-07-13 14:07 UTC, dynasource commented
> Formatting should be fixed and changelog should be added. Other than that looks good.

Which is formatting?

This is mainly a compatibility patch to make it work with 7.2. Do we need a changelog for that?

2017-07-13 16:49 UTC, samdark requested changes

2017-07-13 16:49 UTC, samdark commented on framework/base/Application.php
> +            if($mixed instanceof \Closure){
Formatting.

2017-07-13 16:49 UTC, samdark commented on framework/base/Application.php
> +                if(!$component = call_user_func($mixed, $this)){
Formatting.

2017-07-13 16:49 UTC, samdark commented on framework/base/Application.php
> +            }else if (is_string($mixed)) {
Formatting.

2017-07-13 16:56 UTC, samdark commented on framework/base/Application.php
> +                if (is_string($mixed)) {
This could be `elseif`.

2017-07-13 17:06 UTC, samdark approved these changes

2017-07-13 23:36 UTC, cebe reviewed
`Application::$bootstrap` docs need to be updated to list Closure as possible input.

2017-07-13 23:41 UTC, cebe requested changes
CHANGELOG is also missing.

2017-07-13 23:41 UTC, cebe commented on framework/base/Application.php
> +                }
in the closure case there should also be a log like in other cases below.
e.g. `Yii::trace('Bootstrap with Closure', __METHOD__);`

2017-07-14 09:15 UTC, cebe approved these changes

2017-07-14 09:23 UTC, merged

2017-07-14 09:23 UTC, samdark commented
Merged. Thanks!