Add `InputWidget::createInputField()`
yiisoft/yii2 pull request #14441
Opened 2017-07-12 11:03 UTC by cebe

to implement behavior described in class docs directly in the class
itself instead of relying on subclasses to respect the description.

fixes #14294

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #14294

2017-07-12 11:06 UTC, samdark approved these changes

2017-07-12 18:50 UTC, dynasource requested changes

2017-07-12 18:50 UTC, dynasource commented on framework/widgets/InputWidget.php
> +    protected function createInputField($type)
isnt this ambigious as it renders a HTML tag and not actually creating a Field? Perhabs a better name is `renderInput()`

2017-07-12 19:01 UTC, samdark commented on framework/widgets/InputWidget.php
> +    protected function createInputField($type)
Good suggestion.

2017-07-13 10:15 UTC, cebe commented on framework/widgets/InputWidget.php
> +    protected function createInputField($type)
done.

2017-07-13 13:51 UTC, dynasource approved these changes

2017-07-13 14:04 UTC, merged

2017-07-13 14:04 UTC, samdark commented
Merged. Good one.

2017-07-13 16:16 UTC, SilverFire commented
Introducing `InputWidget::renderInput()` with `$type` as a required parameter causes declaration compatibility exceptions in PHP 7+

In my projects this change affected at least three widgets:

https://github.com/hiqdev/yii2-combo/commit/af68b1577b830c52048903fe7d02abc4215b0677
https://github.com/kartik-v/yii2-widget-datepicker/blob/master/DatePicker.php#L297
https://github.com/omnilight/yii2-bootstrap-daterangepicker/blob/master/DateRangePicker.php#L114

2017-07-13 16:39 UTC, cebe commented
Ooops ... @SilverFire can you open an issue?

2017-07-13 17:20 UTC, cebe commented
reopened https://github.com/yiisoft/yii2/issues/14294#issuecomment-315144541