Fixed caching rules in  with different ruleConfig configuration that …
yiisoft/yii2 pull request #14479
Opened 2017-07-18 15:00 UTC by dmirogin

Fixed caching rules in `yii\web\UrlManager` with different ruleConfig configuration

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #14406

2017-07-18 20:21 UTC, rob006 commented on tests/framework/web/UrlManagerCreateUrlTest.php
> +                'cache' => ArrayCache::class
You can not use `::class` - it will now work on PHP 5.4.

2017-07-18 20:27 UTC, dmirogin commented on tests/framework/web/UrlManagerCreateUrlTest.php
> +                'cache' => ArrayCache::class
@rob006 Thanks!

2017-07-18 21:16 UTC, samdark approved these changes

2017-07-18 22:16 UTC, cebe approved these changes

2017-07-19 07:08 UTC, dynasource requested changes

2017-07-19 07:08 UTC, dynasource commented on tests/framework/web/UrlManagerCreateUrlTest.php
> +        $urlManager = $this->getUrlManager([
$urlManager does not seem to be used and is therefore hard to understand. Perhabs can you add an assertion similar to what you  do for $cachedUrlManager

2017-07-19 07:08 UTC, dynasource commented on tests/framework/web/UrlManagerCreateUrlTest.php
> +        $this->assertInstanceOf(CachedUrlRule::className(), $cachedUrlManager->rules[0]);
it would be more logical to verify that this $rule is not similar to that of $urlManager

2017-07-19 11:18 UTC, dmirogin commented
Made tests clearer.

2017-07-19 12:25 UTC, dynasource approved these changes
thx

2017-07-19 20:45 UTC, merged

2017-07-19 20:45 UTC, samdark commented
Merged. Thank you!