Fixed DbException not displaying error info
yiisoft/yii2 pull request #14492
Opened 2017-07-19 20:02 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | -
| Fixed issues  | -

2017-07-20 20:37 UTC, cebe approved these changes

2017-07-20 20:39 UTC, cebe commented
> Seems it's like that since 2014: 7511de6

that code is fine, seems someone changed it to use php tag later and did not see the second parameter.

2017-07-20 21:06 UTC, samdark commented
Right. I've pointed out wrong commit. It's the last time it was right...

2017-07-20 23:07 UTC, cebe commented
Seems to be a bug in PHP-CS-Fixer :-/ https://github.com/yiisoft/yii2/commit/ba0ab403b52124c941dbeb46fbd9efdc12252a5d#diff-23a5ef85354dc67ddeec3bb5782a94a2L19

cc @rob006 

@samdark same issue exists in `framework/views/errorHandler/previousException.php`

2017-07-20 23:08 UTC, cebe requested changes
@samdark same issue exists in `framework/views/errorHandler/previousException.php`

2017-07-21 09:48 UTC, samdark commented
Updated.

2017-07-21 09:49 UTC, merged