Fixed creating built-in validator in model with same function name
yiisoft/yii2 pull request #14499
Opened 2017-07-20 22:25 UTC by dmirogin

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #14370

2017-07-21 08:06 UTC, dynasource requested changes

2017-07-21 08:06 UTC, dynasource commented on tests/data/validators/models/FakedValidationModel.php
> +    private function number()
shouldnt this be mapped to a configured rule `Rules()`?

2017-07-21 08:22 UTC, dmirogin commented on tests/data/validators/models/FakedValidationModel.php
> +    private function number()
This bug happen when you have function in model class with name that same to one of built-in validators. And Validator::createValidator create InlineValidator instead NumberValidator in this case. I can make separate model class and test for getting this more clear.

2017-07-21 09:54 UTC, dynasource commented on tests/data/validators/models/FakedValidationModel.php
> +    private function number()
true. It's a bit magical in the current form

2017-07-22 10:06 UTC, dynasource approved these changes
looks more verbose now

2017-07-22 21:53 UTC, cebe approved these changes

2017-07-23 14:16 UTC, samdark approved these changes

2017-07-23 14:17 UTC, merged

2017-07-23 14:17 UTC, samdark commented
Merged. Thanks!