Update AttributeTypecastBehavior.php
yiisoft/yii2 pull request #14538
Opened 2017-07-26 14:39 UTC by littlefuntik

Line `Handles owner 'beforeInsert' and 'beforeUpdate' events, ensuring attribute typecasting.` required for change (hotfix php docs.)

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2017-07-29 11:13 UTC, dynasource approved these changes

2017-08-03 21:20 UTC, dynasource requested changes
why would one want to type cast after a save?

2017-08-03 21:24 UTC, samdark commented
@littlefuntik would you please elaborate about the purpose of code changes in this pull request?

2017-08-04 08:56 UTC, littlefuntik commented
@samdark 

en:
The goal is that before saving and after saving, it was necessary to store attribute types. If you can convert attribute types before the save event, you can not do this after successfully saving it. Accordingly, after a successful save, the model contains the values that are stored in the database. For example: after saving, I need the "hasTrial" attribute, which would be of type "\ddd\HasTrialType".

ru:
Цель такова: до сохранения и **ПОСЛЕ** сохранения нужно было тайпкастить атрибуты.
Если перед событием сохранения можно преобразовать типы атрибутов, то после успешного сохранения этого сделать нельзя. Соответственно после успешного сохранения в модели AR будут типы полей, которые нужны были для сохранения в БД, а я например работаю с типами "\ddd\HasTrialType".
Например: после сохранения мне нужно атрибут "hasTrial" что бы был типа "\ddd\HasTrialType".

2018-02-05 21:03 UTC, samdark commented
@littlefuntik are you willing to add unit tests?

2018-02-06 07:28 UTC, littlefuntik commented
@samdark Thank you for reminding me. I will try to add tests today or tomorrow.

2018-02-14 22:21 UTC, SilverFire commented
Merged in 798947af29726d488cfb98c88df6fcf825313113
Added tests in 41cf14e515ea0fdbe1009d1e516ddfcd722b16d6

Thank you

2018-02-14 22:21 UTC, closed without merging