Added `dataFolder` property into `BaseActiveFixture`
yiisoft/yii2 pull request #14546
Opened 2017-07-27 16:41 UTC by leandrogehlen

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

With this property it's possible to define folder to data file fixtures.
This allow  to change `tests/_data` as default folder i Yii2 module in Codepection

2017-07-28 22:43 UTC, samdark requested changes

2017-07-28 22:43 UTC, samdark commented on framework/test/BaseActiveFixture.php
> +            $dataFile = $this->dataFolder . '/' . basename($dataFile);
This way file path is ignored so it's not possible to use subdirs.

2017-07-28 22:43 UTC, samdark commented on framework/CHANGELOG.md
> +- Enh #14546: Added `dataFolder` property into `BaseActiveFixture` (leandrogehlen)
What's the use case?

2017-07-28 22:43 UTC, samdark commented on framework/test/BaseActiveFixture.php
> +    public $dataFolder;
dataDirectory?

2017-07-29 11:41 UTC, leandrogehlen commented on framework/test/BaseActiveFixture.php
> +            $dataFile = $this->dataFolder . '/' . basename($dataFile);
it's possible, but it's necessary to set subdir in `dataFolder`. Ex:

```php
$this->dataFolder = '@app/subdir1/subdir2
```

2017-07-29 11:49 UTC, leandrogehlen commented on framework/CHANGELOG.md
> +- Enh #14546: Added `dataFolder` property into `BaseActiveFixture` (leandrogehlen)
Currently, the fixtures directory is `@tests/fixtures/data`. The default directory for it in codeception is `@tests/_data` with this implementation it's possitble to change Yii2 module to use `@tests/_data` as default directory

2017-07-29 21:52 UTC, samdark commented on framework/test/BaseActiveFixture.php
> +            $dataFile = $this->dataFolder . '/' . basename($dataFile);
Why not using datafile w/o `basename`?

2017-07-30 18:01 UTC, pana1990 commented on framework/CHANGELOG.md
> +- Enh #14546: Added `dataFolder` property into `BaseActiveFixture` (leandrogehlen)
@samdark maybe we could change path by default here as well : 

https://github.com/yiisoft/yii2/blob/master/framework/test/ActiveFixture.php#L99

2017-07-30 19:27 UTC, leandrogehlen commented on framework/test/BaseActiveFixture.php
> +            $dataFile = $this->dataFolder . '/' . basename($dataFile);
To avoid conflicts like:

```php
$this->dataDirectory = '@app\tests\_data';

$this->dataFile = '@app\tests\fixutres\data\cutomer.php'
```

2017-07-30 19:33 UTC, samdark commented on framework/test/BaseActiveFixture.php
> +            $dataFile = $this->dataFolder . '/' . basename($dataFile);
If data file is specified with absolute path then it's meant to be loaded from where it's specified, isn't it?

2017-07-30 19:55 UTC, leandrogehlen commented on framework/test/BaseActiveFixture.php
> +            $dataFile = $this->dataFolder . '/' . basename($dataFile);
Could be, but currently it's different, the `dataDirectory` is mandatory

2017-07-30 20:10 UTC, samdark commented on framework/test/BaseActiveFixture.php
> +            $dataFile = $this->dataFolder . '/' . basename($dataFile);
Yes.

2017-07-31 23:12 UTC, leandrogehlen commented
@samdark, Probably it's necessary docs improve

2018-02-03 12:11 UTC, samdark commented
Merged. Thank you!

2018-02-03 12:11 UTC, merged

2018-03-01 12:24 UTC, mikk150 commented
I think there is a regression here..
Before when you did not have file it `yii\test\ActiveFixture::getData()` returned `yii\test\ActiveFixture::$data` which was empty array, now since it always tries to load a file, it always throws `yii\base\InvalidConfigException`

2018-03-01 12:27 UTC, samdark commented
@mikk150 please create separate issue. Will be lost here.

2018-03-01 12:29 UTC, leandrogehlen commented
@mikk150, you need to set 

```php
class MyFixture extends ActiveFixtrue {
   public $dataFile = false;
}
```

2018-03-01 12:32 UTC, mikk150 commented
leandrogehlen

Breaks BC? | no
-- | --

tells me that I should not change any code

2018-03-01 12:41 UTC, mikk150 commented
https://github.com/yiisoft/yii2/blob/master/framework/test/BaseActiveFixture.php#L33