Added `dataExtra` to `ActiveFixture`
yiisoft/yii2 pull request #14602
Opened 2017-08-05 17:47 UTC by leandrogehlen

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

With this property it's possible to load fixture for relation `hasMany viaTable`

2017-08-07 10:28 UTC, samdark requested changes
Overall looks good but documentation is mandatory in this case.

2017-08-07 12:44 UTC, leandrogehlen commented
I have tried to write something, but sorry my english, i hope to solve the request

2017-08-07 13:53 UTC, samdark requested changes

2017-08-07 13:53 UTC, samdark commented on docs/guide/test-fixtures.md
> +    public $dataExtra = [
Since we're defining fixtures for relations here, it's better to name it `$relationFixtures` instead of general `$dataExtra`. Do you agree?

2017-08-07 13:56 UTC, leandrogehlen commented on docs/guide/test-fixtures.md
> +    public $dataExtra = [
i'm not sure, because it's possible to load any data

2017-08-07 13:59 UTC, samdark commented on docs/guide/test-fixtures.md
> +    public $dataExtra = [
Indeed. Not **any** data but data for any database table...

2017-08-07 14:16 UTC, samdark approved these changes

2017-08-08 12:25 UTC, githubjeka commented
Hmmm, Why you don't use depends?

2017-08-08 13:32 UTC, samdark commented
@githubjeka that's actually a good question :) @leandrogehlen what do you think?

2017-08-08 16:56 UTC, leandrogehlen commented
Because is not same thing. This classes are not mapped

2017-08-08 18:42 UTC, githubjeka commented
Controversially. 

```php
class OrderItemFixture extends ActiveFixture 
{   
    public $tableName = 'order_item';

      public $depends = [
         'app\tests\fixtures\OrderFixture'
    ];
}
```

Not problem for me. IMHO more flexible

And what about user depend by user_id ? 

```
class OrderItemFixture extends ActiveFixture 
{   
    public $tableName = 'order_item';

      public $depends = [
         'app\tests\fixtures\OrderFixture',
         'app\tests\fixtures\UserFixture',
    ];
}
```

How it should look via `dataExtra` and how order for cleanup in this case?

2017-08-08 18:47 UTC, leandrogehlen commented
@githubjeka, how can you get model fixture for `User` or `Order` in your case?

```php
class OrderItemFixture extends ActiveFixture 
{   
    public $tableName = 'order_item';

      public $depends = [
         'app\tests\fixtures\OrderFixture',
         'app\tests\fixtures\UserFixture',
    ];
}

class OrderTest extends \Codeception\Test\Unit
{

   public function _fixtures()
   {
         return [
            'items' => OrderItemFixture::className(), 
         ];
   }

   public function testSomething()
   {
       // how to get order fixture
        $order1 = $this->grabFixtures('what use here', 'order1' );
   }
}
```

Can you explain me?

2017-08-08 18:58 UTC, githubjeka commented
```php
$order1 = $this->grabRecord(Order::class, ['name'=>'order1'] );
```

or I expect that this should work if you dont like `grabRecord`
```php
class OrderItemFixture extends ActiveFixture 
{   
    public $tableName = 'order_item';

      public $depends = [
         'app\tests\fixtures\OrderFixture',
         'app\tests\fixtures\UserFixture',
    ];
}

class OrderTest extends \Codeception\Test\Unit
{

   public function _fixtures()
   {
         return [
            'order'=> OrderFixture::className(),
            'items' => OrderItemFixture::className(),            
         ];
   }

   public function testSomething()
   {
        $order1 = $this->grabFixtures('order')[0];
   }
}
```

2017-08-08 19:10 UTC, leandrogehlen commented
> or I expect that this should work if you dont like grabRecord

Thanks, for your answer. 
I think my PR it`s easier, but the decision is from yii team

2017-08-08 19:38 UTC, githubjeka commented on docs/guide/test-fixtures.md
> +        'user_id' => 1,
It requires check off for foreign key.
If UserFixture calls through implicit dependence on another fixture with same `dateExtra`? How does it merge?

2017-08-09 15:47 UTC, samdark commented
Looks like dependencies are much cleaner and better way to achieve the goal rather than filling up tables directly. Thanks for the pull request but won't merge it.

2017-08-09 15:47 UTC, closed without merging

2017-08-09 17:31 UTC, githubjeka commented
Anycase you can use it code in your projects ;)

2017-08-10 14:28 UTC, leandrogehlen commented
@samdark, no problem