fix #14604 CompareValidator compareAttribute does not work if `compar…
yiisoft/yii2 pull request #14605
Opened 2017-08-06 16:29 UTC by mikk150

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | frontend has no tests?
| Fixed issues  | #14604

2017-08-08 08:32 UTC, samdark requested changes
Overall makes sense.

2017-08-08 08:32 UTC, samdark commented on framework/assets/yii.validation.js
> +                    if (attributes[i].id == options.compareAttribute) {
`===` could be used.

2017-08-08 08:36 UTC, mikk150 commented on framework/assets/yii.validation.js
> +                    if (attributes[i].id == options.compareAttribute) {
yep, that is true

2017-08-08 08:37 UTC, mikk150 commented on framework/assets/yii.validation.js
> +                for (var i = attributes.length - 1; i >= 0; i--) {
1st speed (do not need to count every time, just simple substraction)
2nd compatible with current version, which takes first element's value

2017-08-08 08:42 UTC, samdark approved these changes

2017-11-14 21:43 UTC, merged

2017-11-14 21:43 UTC, samdark commented
Merged. Thank you!