#14643 Easy change layout for error action
yiisoft/yii2 pull request #14644
Opened 2017-08-14 10:54 UTC by swods

Sometimes when we use ErrorAction, we need use different layout, but now it's little bit difficult to do it easily, so this small new feature help to solve problem

```
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
                'layout' => 'error'
            ],
        ];
    }
```

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #14643

2017-08-14 11:06 UTC, arogachev requested changes

2017-08-14 11:06 UTC, arogachev commented on framework/web/ErrorAction.php
> +        if ($this->layout) $this->controller->layout = $this->layout;
Code style must be PSR-2 compatible:

- [Yii 2 Core Framework Code Style](https://github.com/yiisoft/yii2/blob/master/docs/internals/core-code-style.md)
- [PSR-2 - if, elseif, else](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#51-if-elseif-else)

2017-08-14 11:06 UTC, arogachev commented on framework/web/ErrorAction.php
> +     * @since 2.0.~
It's better to specify exact version.

2017-08-14 11:08 UTC, swods commented on framework/web/ErrorAction.php
> +     * @since 2.0.~
when i pull requisting it, i didn't know version

2017-08-14 11:15 UTC, cebe requested changes
the behavior of `$layout` property of the action should be:

- if `null`, do not change the value in controller
- if anything else (including `false`) set the value on controller.

2017-08-14 11:17 UTC, cebe commented on framework/web/ErrorAction.php
> +     * @see [[yii\base\Component::$layout]]
should refer to controller, not component ;) also brackets are not needed.

```
@see \yii\web\Controller::$layout
```

2017-08-14 11:23 UTC, swods commented on framework/web/ErrorAction.php
> +     * @see [[yii\base\Component::$layout]]
ohh miss copy

2017-08-14 11:27 UTC, cebe commented
I've applied some changes in formatting and changed the check to compare with `null` explicitly.

2017-08-14 11:28 UTC, swods commented
heh u was faster, but i wanted to do it like this - !is_null($this->layout), bad?

2017-08-14 11:33 UTC, cebe commented
` === null` matches the style we use throughout the framework.

2017-08-14 11:37 UTC, klimov-paul commented
https://github.com/yiisoft/yii2/issues/14643#issuecomment-322167870

2017-08-14 11:42 UTC, swods commented
© The removal of the tonsils through the anus - best

2018-02-03 18:19 UTC, closed without merging

2018-02-03 18:19 UTC, samdark commented
https://github.com/yiisoft/yii2/commit/61b47014a2f68ccb9ed000265a8c413dc4d41af3

Merged. Thank you!