[2.1] use `random_int()` instead of `mt_rand()` to generate cryptographically secure pseudo-random integers
yiisoft/yii2 pull request #14671
Opened 2017-08-19 11:37 UTC by yyxx9988

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | no

like `random_bytes()`, PHP 7.0 introduces `random_int()` as a core function, consider migrating.

refs:
- offical site: https://secure.php.net/manual/en/function.random-int.php
- a userland implementation for php5.2 to 5.6 https://github.com/paragonie/random_compat
- benchmark (random_int vs mt_rand) https://gist.github.com/masakielastic/0f71d119911225b708bc

2017-08-19 13:42 UTC, FabrizioCaldarelli commented
Why don't create a method  (for example, randomInt) in yii\base\Security that wraps both implementations ( below php 7 and over php 7 versions)? So this method could be used in other part of framework and applications.

2017-08-19 14:06 UTC, Renkas commented
@FabrizioCaldarelli Yii 2.1 has minimum requirenment of php 7.1 so there is no need for that.

2017-08-19 14:16 UTC, FabrizioCaldarelli commented
It could be useful also to prevent other future changes.

2017-08-19 22:05 UTC, samdark approved these changes

2017-08-20 07:14 UTC, dynasource approved these changes

2017-08-20 10:32 UTC, klimov-paul requested changes

2017-08-20 10:32 UTC, klimov-paul commented on framework/caching/DbCache.php
> +        if ($force || random_int(0, 1000000) < $this->gcProbability) {
I am unsure it make sense to change `gc`. It has nothing to do with security or cryptographics.
Replacing `mt_rand` with `random_int` will degrade performance without purpose here.

2017-08-20 10:32 UTC, klimov-paul commented on framework/caching/FileCache.php
> +        if ($force || random_int(0, 1000000) < $this->gcProbability) {
Same here.

2017-08-20 10:32 UTC, klimov-paul commented on framework/mail/BaseMailer.php
> +        return date('Ymd-His-', $time) . sprintf('%04d', (int) (($time - (int) $time) * 10000)) . '-' . sprintf('%04d', random_int(0, 10000)) . '.eml';
Here change also make a little sense. Email message file is meant to be created for debugging purposes and does not affect security anyhow.

2017-08-20 12:42 UTC, yyxx9988 commented on framework/caching/DbCache.php
> +        if ($force || random_int(0, 1000000) < $this->gcProbability) {
agreed.

2017-08-20 17:36 UTC, samdark commented on framework/caching/DbCache.php
> +        if ($force || random_int(0, 1000000) < $this->gcProbability) {
@yyxx9988 could you change this one back then? And the one below.

2017-08-21 01:40 UTC, yyxx9988 commented on framework/caching/DbCache.php
> +        if ($force || random_int(0, 1000000) < $this->gcProbability) {
@samdark updated and changed one more file `UploadedFileTest.php`
```php
    private function generateFakeFileData()
    {
        return [
            'name' => md5(random_int()),
            'tmp_name' => md5(random_int()),
            'type' => 'image/jpeg',
            'size' => random_int(1000, 10000),
            'error' => 0,
        ];
    }
```

2017-08-21 11:11 UTC, klimov-paul approved these changes

2017-08-21 11:52 UTC, yyxx9988 commented
closed after #14632

2017-08-21 12:03 UTC, klimov-paul commented
If you are unable to perform a merge - open a new PR.

2017-08-21 15:15 UTC, merged

2017-08-21 15:15 UTC, samdark commented
Merged. Thanks!