Fix \yii\data\Sort
yiisoft/yii2 pull request #14703
Opened 2017-08-22 14:18 UTC by LAV45

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #13260

Tested this functionality on a production project

2017-08-22 16:29 UTC, samdark commented
What issue is it fixing? The one referenced was taken care of by @klimov-paul already, wasn't it?

2017-08-22 19:02 UTC, cebe requested changes

2017-08-22 19:02 UTC, cebe commented on framework/data/Sort.php
> +                $orders = $columns;
in this case `columns` is not an array. The return type of this method is `array`, so assigning columns to orders does not make sense.

2017-08-23 06:29 UTC, LAV45 commented on framework/data/Sort.php
> +                $orders = $columns;
@cebe, updated

2017-08-23 07:21 UTC, cebe commented on framework/data/Sort.php
> +                $orders = $columns;
changing the return type may break code that relies on current behavior. SqlDataProvider does expect an array for example: https://github.com/yiisoft/yii2/blob/4081a4b20349974ea9f37957b166fa4398cf3a8b/framework/data/SqlDataProvider.php#L121-L126

please elaborate on why you think this change should be made. It looks wrong to me.

2017-08-23 10:58 UTC, samdark commented on framework/data/Sort.php
> +                $orders = $columns;
Same here. I don't see the reason for the change...

2017-09-06 11:58 UTC, closed without merging