ensure backwards compatibiliy with migration without $compact
yiisoft/yii2 pull request #14745
Opened 2017-09-01 09:09 UTC by cebe

See https://github.com/yiisoft/yii2/pull/14474#discussion_r135237472

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | https://github.com/yiisoft/yii2/pull/14474#discussion_r135237472

2017-09-01 09:23 UTC, klimov-paul requested changes

2017-09-01 09:23 UTC, klimov-paul commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
Such fix makes a little sense. It is better to simply avoid passing `compact` to constructor here.
In case particular migration implementation supports `compact` it can overridde `createMigration` just in the way `MigrateController` for regular DB does.

2017-09-01 10:33 UTC, cebe commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
if it does not hurt, why not try to set it?

2017-09-01 10:35 UTC, klimov-paul commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
In case there is no such field in target class - it will cause `UnknownPropertyException`.

2017-09-01 10:37 UTC, klimov-paul commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
We can not rely that **any** custom implementation overrides the `createMigration()` method.
It may do so, and it may do not.

2017-09-01 10:38 UTC, samdark commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
@klimov-paul if we won't pass it then it won't be settable from command line.

2017-09-01 10:40 UTC, cebe commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
My fix will only set it, if `canSetProperty` returns true.

2017-09-01 10:41 UTC, samdark approved these changes

2017-09-01 10:43 UTC, klimov-paul commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
> if we won't pass it then it won't be settable from command line.

If migration class does not suport - it will not be settiable from command line anyway.
That was a mistake at the first place - this option should not belong to migration object, but should belong to some 'view' layer which performs the output. I have told you about this [here](https://github.com/yiisoft/yii2/pull/14474#issuecomment-317697935).

In current state this option may be inconsistent at some cases, but there is nothing we can do.

2017-09-01 10:46 UTC, klimov-paul commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
> My fix will only set it, if canSetProperty returns true.

How does it changes anything? If particular `Migration` class have no property `$compact` you can not set it from command line. Unless you add it somehow to `MigrationInterface` you can not rely on it.
At the present state only `yii\db\Migration` can accept this property. Any externla library is not aware of it.

2017-09-01 10:47 UTC, klimov-paul commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
Also what will happen in case particualr Migration class does not extend `BaseObject` but has `$compact` field?

2017-09-01 10:58 UTC, cebe commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
> At the present state only yii\db\Migration can accept this property. Any externla library is not aware of it.

but is can be added by just adding the property, instead of the need to extend this method.



> Also what will happen in case particualr Migration class does not extend BaseObject but has $compact field?

nothing.

2017-09-01 11:00 UTC, klimov-paul commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
> nothing

So it is inconsistent anyway.

2017-09-01 11:01 UTC, klimov-paul commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
> but is can be added by just adding the property ... nothing

So, in case I have NOT extended my migration class from `BaseObject` and add a property `$compact` as you suggets - it will not applied.

2017-09-01 11:29 UTC, cebe commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
in the Yii eco system it is very uncommon to not extend from BaseObject, so I do not think this is a problem. This addition is made for convenience when implementing Migration, its not meant to cover any extra special use case that may not even exist.

2017-09-01 11:52 UTC, klimov-paul commented on framework/console/controllers/BaseMigrateController.php
> +        return $migration;
>  I do not think this is a problem

I can not see any problem to have `BaseMigrateController::createMigration()` without `$compact` either. So?
Why do we need to exploit usage of `canSetProperty()` at this method, creating a bad example for the developers? It only justifies solutions like #12929.

At the present state `canSetProperty()` method used only around the behavior mechanism and can be considered as internal one. Its usage is unnatural for the PHP as uses `isset()` or `property_exists()` for such cases. I would prefer do not expose it anywhere besides setter/getter realted to behaviors.

2017-09-12 20:35 UTC, SilverFire approved these changes

2017-09-12 20:53 UTC, schmunk42 approved these changes
LGTM

2017-09-12 21:10 UTC, merged