Fixes #14929: Add support of semicolon-less JS to asset/compress comm…
yiisoft/yii2 pull request #14930
Opened 2017-10-05 13:15 UTC by tanakahisateru

Idea to fix #14929 by wrapping function scope block.

…and.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes (maybe)
| Tests pass?   | yes
| Fixed issues  | #14929

2017-10-05 13:46 UTC, shirase commented
Global variable will be undefined beyond wrapper function context.
```
var test =""; // is global, but
(function() {
var test =""; // is not global
})();
```

2017-10-05 14:23 UTC, tanakahisateru commented
To insert a ";" doesn't break BC. Should I change?

2017-10-05 14:37 UTC, tanakahisateru commented
I'm sure that wrapping was too aggressive. I will change this PR to avoid function.

2017-10-05 20:37 UTC, samdark commented
Isn't https://github.com/yiisoft/jquery-pjax/commit/0d4cc3f479d4b7b800aefca1275a852c8d3dd3c6 fixing the problem?

2017-10-05 22:10 UTC, samdark requested changes

2017-10-05 22:10 UTC, samdark commented on framework/console/controllers/AssetController.php
>                  . file_get_contents($file)
It's better to check if trimmed contents end with `;` and add it if it's not there.

2017-10-06 01:39 UTC, tanakahisateru commented
@samdark I've modified the commit.

2017-10-06 07:53 UTC, rob006 approved these changes
Changelog entry is missing.

2017-10-06 20:25 UTC, samdark approved these changes

2017-10-06 20:31 UTC, merged