Added StringHelper::ensurePrefix
yiisoft/yii2 pull request #14963
Opened 2017-10-14 09:03 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | none

2017-10-14 12:24 UTC, rob006 commented on framework/helpers/BaseStringHelper.php
> +        if (!self::startsWith($string, $prefix, $caseSensitive)) {
`self` -> `static` ?

2017-10-14 12:33 UTC, samdark commented on framework/helpers/BaseStringHelper.php
> +        if (!self::startsWith($string, $prefix, $caseSensitive)) {
Yes.

2017-10-14 13:01 UTC, dmirogin approved these changes

2017-10-14 23:19 UTC, cebe requested changes

2017-10-14 23:19 UTC, cebe commented on framework/helpers/BaseStringHelper.php
> +     * Useful for adding "http://" to user entered website addresses, twitter handles etc.
how about http vs. https?

2017-10-14 23:19 UTC, cebe commented on framework/helpers/BaseStringHelper.php
> +            $string = $prefix . $string;
no need to modify the string, you can just return the result.

2017-10-14 23:19 UTC, cebe commented on framework/helpers/BaseStringHelper.php
> +     * Useful for adding "http://" to user entered website addresses, twitter handles etc.
so its not really useful for user content, what are other use cases?

2017-12-17 20:57 UTC, samdark commented
Closing for the reason @cebe described. Proper handling is more complex than that...

2017-12-17 20:57 UTC, closed without merging