Only truncate the original log file for rotation
yiisoft/yii2 pull request #15173
Opened 2017-11-17 06:01 UTC by developeruz

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #8983

2017-11-17 07:27 UTC, samdark requested changes

2017-11-17 07:27 UTC, samdark commented on framework/log/FileTarget.php
> +    private function clearLogFile($rotateFile)
phpdoc needed.

2017-11-17 07:27 UTC, samdark commented on framework/log/FileTarget.php
> +    private function rotateByCopy($rotateFile, $file, $i)
phpdoc needed.

2017-11-17 07:27 UTC, samdark commented on framework/log/FileTarget.php
> +    private function rotateByRename($rotateFile, $file, $i)
phpdoc needed.

2017-11-18 12:37 UTC, developeruz commented
@samdark  у меня нет идей, как можно протестировать данный PR, т.к изменение больше по производительности и поведение никак не меняется. Тесты на этот метод [уже есть](https://github.com/yiisoft/yii2/blob/75dbdb008363b90d4ffc8f502022763aedd6998a/tests/framework/log/FileTargetTest.php#L102). Они как бы подтверждают, что ничего в плане функциональности не поменялось. Файлы логов сдвигаются на 1, т.е log.2 становится log.3 и тп. Нет смысла очищать log.2 после копирования в log.3 тк log.2 и так перезатрется файлом log.1.

2017-11-18 23:27 UTC, samdark commented on framework/log/FileTarget.php
> +     * @param $rotateFile
`@since 2.0.14`

2017-11-18 23:28 UTC, samdark approved these changes
All good except phpdoc for private methods.

2017-11-30 20:23 UTC, merged

2017-11-30 20:23 UTC, samdark commented
Merged. Thank you!