Add clearErrors parameter to ValidateMultiple
yiisoft/yii2 pull request #15314
Opened 2017-12-08 08:09 UTC by developeruz

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | probably yes, because method signature is changed
| Tests pass?   | yes
| Fixed issues  | #9727

2017-12-08 08:28 UTC, samdark commented
Should be pull requested against 2.1 since it's method signature change.

2017-12-08 08:50 UTC, developeruz commented
Changed to be against 2.1

2017-12-08 10:08 UTC, samdark approved these changes

2017-12-08 10:12 UTC, MysteryDragon requested changes

2017-12-08 10:12 UTC, MysteryDragon commented on framework/base/Model.php
> +     * @param bool $clearErrors whether to call [[clearErrors()]] before performing validation. Default true
This line must be moved after full `$attributeNames` description.

2017-12-08 12:22 UTC, MysteryDragon approved these changes

2017-12-09 22:20 UTC, merged

2017-12-09 22:20 UTC, samdark commented
Merged. Thank you!