"ezyang/htmlpurifier" package has been made optional
yiisoft/yii2 pull request #15448
Opened 2018-01-03 12:59 UTC by klimov-paul

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #8452 (patrially)

"html" data format is not mandatory to be used inside every application - it is necessary only in case web user is allowed to enter an HTML code, which should be shown as HTML code.
It is much more common to simply secure any web user input passing it to `htmlspecialchars()`, e.g. `Html::encode()` instead.

"ezyang/htmlpurifier" package has been made optional.
`HtmlPurifier` unlikely to be moved into a separated package since it produces tight coupling with `Formatter::asHtml()`, which can not be simply removed or dropped as developer may extend `Formatter` class providing his own implementation.

2018-01-04 15:27 UTC, sergeymakinen requested changes
LGTM, but some strings have to be corrected.

2018-01-04 15:27 UTC, sergeymakinen commented on framework/CHANGELOG.md
> +- Chg: Package "ezyang/htmlpurifier" has been made optional and does installed via Composer by default (klimov-paul)
```diff
- and does installed via Composer by default
+ and it's not installed by default
```

2018-01-04 15:27 UTC, sergeymakinen commented on framework/UPGRADE.md
> +* Package "ezyang/htmlpurifier" has been made optional and does installed via Composer by default. If you need
Same as in the changelog.

2018-01-04 15:27 UTC, sergeymakinen commented on framework/composer.json
> +        "ezyang/htmlpurifier": "required at `yii\\helpers\\HtmlPurifier` for 'html' data format support (e.g. `yii\\i18n\\Formatter:asHtml()`)"
Does Symfony's Console under Composer support/highlight grave accents? If it doesn't, there's no need to use it in the description.

2018-01-05 17:56 UTC, sergeymakinen approved these changes

2018-01-05 18:50 UTC, rob006 commented
`BaseStringHelper` also uses `HTMLPurifier_*` classes. 

Also note that using `suggest` section gives not real constraints for this dependency. User can install `htmlpurifier` with wrong version and then only runtime bugs will let him know about it.

2018-01-07 21:38 UTC, samdark approved these changes

2018-01-07 21:38 UTC, samdark commented on framework/CHANGELOG.md
> +- Chg: Package "ezyang/htmlpurifier" has been made optional and is not installed by default (klimov-paul)
Need issue number.

2018-01-09 15:27 UTC, SilverFire commented
Will review this evening

2018-01-09 20:18 UTC, SilverFire approved these changes

2018-01-09 20:18 UTC, merged