Fixed inconsistency in use of new InvalidArgumentException #15727.
yiisoft/yii2 pull request #15729
Opened 2018-02-21 15:46 UTC by Offout

Replaced PHPDoc @throw InvalidParamException tags with InvalidArgumentException.
Replaced catch InvalidParamException with catch InvalidArgumentException.
Removed @throw InvalidParamException in CheckAccessInterface because it never thrown in framework realizations, reworked PHPDoc return comment.
Replaced expectException InvalidParamException in tests with expectException InvalidArgumentException.

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #15727

2018-02-21 16:18 UTC, SilverFire approved these changes

2018-02-21 17:42 UTC, Offout commented on framework/rbac/CheckAccessInterface.php
> -     * @throws \yii\base\InvalidParamException if $permissionName does not refer to an existing permission
Yes, I wrote about this in issue https://github.com/yiisoft/yii2/issues/15727

2018-02-21 17:43 UTC, samdark approved these changes

2018-02-21 17:44 UTC, samdark commented
Looks good. Please add a line for changelog.

2018-02-21 17:48 UTC, Offout commented
I added line in changelog 
[https://github.com/yiisoft/yii2/pull/15729/files#diff-6ed25333dcd29100ab12768833283a45R9](url)
In [https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md](url) mentioned that in CHANGELOG I must add new line 'you should insert this at the top of the file under the first heading' but also ' The changelog should be grouped by type (Bug,Enh) and ordered by issue number.' So I added line at the bottom.

2018-02-21 17:49 UTC, rob006 requested changes
Some of these changes are intentionally omitted in #15633. See https://github.com/yiisoft/yii2/issues/15727#issuecomment-367410682

2018-02-21 17:51 UTC, SilverFire commented
@rob006 is right

2018-02-22 13:52 UTC, Offout commented
Replied https://github.com/yiisoft/yii2/issues/15727#issuecomment-367416285

2018-02-23 22:44 UTC, samdark commented
Re-checked once again. Sorry but won't merge it into 2.0. Initial set of changes was just right.

2018-02-23 22:44 UTC, closed without merging