Fix ExistValidator is broken for NOSQL (#15726)
yiisoft/yii2 pull request #15738
Opened 2018-02-22 03:54 UTC by developeruz

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2018-02-22 08:19 UTC, samdark approved these changes

2018-02-22 13:09 UTC, klimov-paul commented
This is not enough: same fix should be applied to `valueExists()`.
https://github.com/yiisoft/yii2/blob/master/framework/validators/ExistValidator.php#L256-L262

2018-02-22 13:10 UTC, klimov-paul requested changes

2018-02-22 14:27 UTC, developeruz commented on framework/validators/ExistValidator.php
> +        if ($this->forceMasterDb && method_exists($model::getDb(), 'useMaster')) {
Changed

2018-02-22 14:43 UTC, klimov-paul commented
CHANGELOG entry should be added as well.

2018-02-23 21:40 UTC, SilverFire approved these changes

2018-02-23 21:43 UTC, merged

2018-02-23 21:43 UTC, SilverFire commented
Thank you