Fixed has-error class to ActiveField div container when attribute nam…
yiisoft/yii2 pull request #15805
Opened 2018-02-28 09:27 UTC by FabrizioCaldarelli

Fixed has-error class to ActiveField div container when attribute name is tabular

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | https://github.com/yiisoft/yii2/issues/15801

2018-02-28 14:20 UTC, FabrizioCaldarelli commented
Is there a test script to check when a model has errors?

2018-02-28 15:20 UTC, samdark commented
https://github.com/yiisoft/yii2/blob/master/tests/framework/widgets/ActiveFieldTest.php

2018-02-28 23:26 UTC, samdark approved these changes

2018-03-01 06:13 UTC, SilverFire requested changes

2018-03-01 06:13 UTC, SilverFire commented on framework/widgets/ActiveField.php
> +        $attributeName = yii\helpers\BaseHtml::getAttributeName($this->attribute);
We do not rely directly on `Base%` helpers. Use `Html::getAttributeName()`, as it is done above in this file `https://github.com/yiisoft/yii2/pull/15805/files#diff-afe28192283fbfadaf6145620191c339R904`

2018-03-01 07:56 UTC, SilverFire approved these changes

2018-03-01 07:58 UTC, merged

2018-03-01 07:59 UTC, SilverFire commented
Thank you