fix #15798 (yii\grid\CheckboxColumn, yii\grid\RadioButtonColumn conte…
yiisoft/yii2 pull request #16021
Opened 2018-04-01 18:07 UTC by lesha724

…nt option has no effect)

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #15798

2018-04-09 07:28 UTC, cebe requested changes

2018-04-09 07:28 UTC, cebe commented on framework/grid/CheckboxColumn.php
> +            return call_user_func($this->content, $model, $key, $index, $this);
better call the parent implementation instead.

2018-04-09 07:28 UTC, cebe commented on framework/grid/RadioButtonColumn.php
> +            return call_user_func($this->content, $model, $key, $index, $this);
better call the parent implementation instead.

2018-04-28 07:36 UTC, SilverFire commented
@lesha724 could you add unit tests, please?

There are already tests for [CheckboxColumn](https://github.com/yiisoft/yii2/blob/master/tests/framework/grid/CheckboxColumnTest.php) and [RadioButtonColumn](https://github.com/yiisoft/yii2/blob/master/tests/framework/grid/RadiobuttonColumnTest.php)

2018-04-28 20:49 UTC, SilverFire commented
Great! The last thing to do is to add a line in a CHANGELOG.md. Could you do it, please?

2018-04-29 07:47 UTC, merged

2018-04-29 07:47 UTC, SilverFire commented
Thank you!