[ENH] introduce yii\behaviors\OptimisticLockBehavior to avoid #9133 bug
yiisoft/yii2 pull request #16206
Opened 2018-05-02 13:16 UTC by tunecino

| Q             | A
| ------------- | ---
| Is bugfix?    | yes/no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #9133

This is more of an enhancement than bug fix as the mentioned bug in #9133 really depends on how devloppers did implement optimistic lock and may still have it do to the way it was designed. A quick example is this code in ActiveRecord::deleteInternal() : 

```php
    $lock = $this->optimisticLock();
    if ($lock !== null) {
        $condition[$lock] = $this->$lock;
    }
    $result = static::deleteAll($condition);
    if ($lock !== null && !$result) {
        throw new StaleObjectException('The object being deleted is outdated.');
    }
```
That code assumes user have loaded a version number to model's optimistic lock attribute but it is rare to perform `$model->load()` on delete actions, either does the generated code for controllers by gii or built-in REST controllers, so the code is just getting it from database and upgrading without checking if there is a version attribute in user inputs. And there is no easy way to perform a "dirty attribute but equal to what we already have in db" check within ActiveController.

That said, this PR is an enhancement introducing a behavior that when implemented, ensure Optimistic Lock works properly. It parses the version value directly from `Yii::$app->request` as it is usually done with headers.

2018-05-02 17:49 UTC, tunecino commented
A way to actually fix #9133 bug is to first update `yii/base/Model::setAttributes()` and add a private `$_touched` array to track attributes edits. Then in `BaseActiveRecord` this code:

```php
$lock = $this->optimisticLock();
if ($lock !== null) {
    $condition[$lock] = $this->$lock;
}
```
 could become:

```php
$lock = $this->optimisticLock();
if ($lock !== null) {
    $lockValue = $this->isDirtyAndTouched($lock) ? $lock : 0;
    $values[$lock] = $lockValue + 1;
    $condition[$lock] = $lockValue;
}
```
That should fix it but not sure if it is too much for Model class to track those changes as almost everything is built on top of it.

2018-05-02 22:17 UTC, samdark commented
Since it is an enhancement, we can have it in 2.1.

2018-05-04 05:44 UTC, rustamwin reviewed
method `className` deprecated

2018-05-05 14:48 UTC, tunecino commented
Good catch. For 2.1 `className` should be removed. I'll fix that later, but for now, I'd wait and see if there is a better fix for #9133, if not then I think we should re-consider merging this to 2.0.x, otherwise optimistic lock won't work as expected in versions prior to 2.1.

2018-05-08 15:39 UTC, SamMousa commented
@tunecino "as expected" is subjective here. What if other implementations assume the locking is cooperative and optional (meaning you can omit the version if you don't care what you're overwriting)?

This would be a backwards compatibility break.

2018-05-08 16:46 UTC, tunecino commented
@SamMousa this PR changes nothing in current code. Current Optimistic lock implementations will continue to upgrade the the lock version as retrieved from database when the lock version isn't sent like if there is no Optimistic Lock implemented. That bug isn't fixed as I didn't find a non BC way to fix it.

This PR introduces a behavior that you can optionally add to your model class to ensure optimistic lock work properly and changes documentation to recommend using it as the recommended way in old documentation doesn't work as it says it does (the **"as expected"** part).

2018-05-08 17:03 UTC, SamMousa commented
Oh, ignore my comment then :)

2018-05-08 23:13 UTC, samdark commented
Thinking about it more, I think it can be merged into 2.0.x since it's half-bug half-enhancement...

2018-05-08 23:13 UTC, samdark commented on framework/behaviors/OptimisticLockBehavior.php
> +     * @throws InvalidCallException if [[\yii\db\BaseActiveRecord::optimisticLock()|optimisticLock()]] is not properly configured.
`@since 2.0.16`

2018-05-08 23:14 UTC, samdark commented on framework/behaviors/OptimisticLockBehavior.php
> +    public function upgrade()
`@since 2.0.16`

2018-05-08 23:14 UTC, samdark requested changes
Changelog needed.

2018-05-09 00:13 UTC, tunecino commented
done 👍 (Changelog is [there](https://github.com/yiisoft/yii2/pull/16206/files#diff-6ed25333dcd29100ab12768833283a45))

2018-05-12 11:43 UTC, merged

2018-05-12 11:43 UTC, samdark commented
Merged. Thank you!