Fix define command::executeResetSequence() to work with Oracle
yiisoft/yii2 pull request #16362
Opened 2018-06-04 15:02 UTC by CedricYii

Introduce command::executeResetSequence() to handle OCI need for several
queries to reset a sequence.
Preserve backward compatibility with other databases.
Check if resetSequence() should be written as deprecated.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | we'll see
| Fixed issues  | #5442

2018-06-18 12:34 UTC, sergeymakinen approved these changes
LGTM. `@since` should be added.

2018-06-18 12:44 UTC, samdark commented
@sergeymakinen should there be tests?

2018-06-18 12:49 UTC, sergeymakinen commented
@samdark Oh. I have noticed there's an existing test but forgot it should be altered. Good catch!

I will run tests as soon as they are ready.

2018-06-18 12:49 UTC, sergeymakinen requested changes
Need updated tests for Oracle.

2018-06-27 19:29 UTC, merged

2018-06-27 19:29 UTC, samdark commented
Merged. Thank you!