Auto filter switch(#16365)
yiisoft/yii2 pull request #16370
Opened 2018-06-07 07:49 UTC by s1lver

| Q             | A
| ------------- | ---
| Is bugfix?    |no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #16365

2018-06-07 09:10 UTC, yura-shutkin commented
Looks like feature that can be switched on and off via flag

2018-06-07 12:27 UTC, samdark commented on framework/grid/GridView.php
> +    public $filterAutoApply = true;
filterOnFocusOut?

2018-06-07 12:44 UTC, s1lver commented on framework/grid/GridView.php
> +    public $filterAutoApply = true;
Хорошо, так будет лучше

2018-06-16 00:00 UTC, samdark requested changes

2018-06-16 00:00 UTC, samdark commented on framework/grid/GridView.php
> +     * Allows you to disable the automatic application of filters, while leaving the ability to manage filters using yiiGridView in JS
Need `@since`.

2018-06-16 00:00 UTC, samdark commented on framework/grid/GridView.php
> +        if ($this->filterOnFocusOut) {
It doesn't look correct not to register any JS in this case.

2018-06-17 14:59 UTC, samdark commented
I think we were talking about not automatically applying filter only. There are events and row selection that you turn off by not registering any JS.

2018-06-26 08:12 UTC, s1lver commented
Совершенно верно.
Добавляемая опция не позволяет фильтру применяться автоматически. Т.к не будет происходить событие, но, при этом, остается возможность повесить применение фильтра на кнопку.

Собственно это и есть реализация моего вопроса #16365.
- По умолчанию **filterOnFocusOut** всегда true чтобы не сломать фильтры у других пользователей
- Если **filterOnFocusOut** установить в false, то мы отключаем  
```php 
$view->registerJs("jQuery('#$id').yiiGridView($options);");
```
- yii.gridView.js всегда должен подключаться


При этом это решает вопрос с виджетами которые основаны на GridView (например виджет картика). Сейчас чтобы получить тот же эффект, необходимо написать очень много кода.

2018-06-26 08:58 UTC, samdark commented
Так там не только фильтры в `yiiGridView()`

2018-06-26 09:31 UTC, s1lver commented
Проверил.

**setSelectionColumn** и **getSelectedRows** для CheckboxColumn в нем есть

```php
$this->grid->getView()->registerJs("jQuery('#$id').yiiGridView('setSelectionColumn', $options);");
```

2018-06-26 09:44 UTC, s1lver commented
Придумал еще вариант, сейчас проверю его

2018-06-26 10:40 UTC, s1lver commented
@samdark 
Вот другой вариант.

**GridView**
Передаем filterOnFocusOut в качестве второго параметра (предварительно приведем к числу)
```php
$filterOnFocusOut = (int)$this->filterOnFocusOut;
$view->registerJs("jQuery('#$id').yiiGridView($options, $filterOnFocusOut);");
```

**yii.GridView.js**
Поскольку функция init используется только для фильтрации, то и оперировать будем с ней. Дополнительная проверка внутри typeof method === 'object' || !method для предотвращения генерации ошибки(т.к в этом случае сторонний JS становится не работоспособным). 
```js
$.fn.yiiGridView = function (method, filterOnFocusOut) {
        if (methods[method]) {
            return methods[method].apply(this, Array.prototype.slice.call(arguments, 1));
        } else if (typeof method === 'object' || !method) {
            if (filterOnFocusOut === 1) {
				return methods.init.apply(this, arguments);
			}
			return;
        } else {
            $.error('Method ' + method + ' does not exist in jQuery.yiiGridView');
            return false;
        }
    };
```

В этом варианте мы никак не затрагиваем CheckboxColumn.

2018-06-27 20:16 UTC, samdark commented
https://travis-ci.org/yiisoft/yii2/jobs/396857068

2018-07-04 18:42 UTC, merged

2018-07-04 18:42 UTC, samdark commented
Merged. Thank you!