Added method call support in DI and Yii::configure
yiisoft/yii2 pull request #16495
Opened 2018-07-06 17:16 UTC by hiqsol

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

Cannot leave `Yii::configure()` untouched to have consistent behavior for all objects.

2018-07-06 19:09 UTC, samdark approved these changes
Looks good. I think we need to update docs.

2018-07-06 19:31 UTC, SilverFire requested changes
It will be good to add test for calling not existing or private method

2018-07-06 19:31 UTC, SilverFire commented on framework/BaseYii.php
> +            if (substr($name, -2) === '()') {
mb_substr should be used

2018-07-06 19:31 UTC, SilverFire commented on framework/di/Container.php
> +            if (substr($name, -2) === '()') {
mb_substr should be used

2018-07-08 22:12 UTC, merged

2018-07-08 22:12 UTC, samdark commented
Merged. Thank you very much!