Update start-installation.md
yiisoft/yii2 pull request #16605
Opened 2018-08-03 23:21 UTC by jiuly256

Propongo mejorar la redacción en español

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #16605 propongo estos cambios

2018-08-04 21:36 UTC, samdark commented on docs/guide-es/start-installation.md
> +> Nota: Durante la instalación, Composer puede preguntar por tus credenciales de acceso de Github. Esto es normal ya que Composer
These should not be translated.

2018-08-04 21:36 UTC, samdark requested changes
Please revert changes to note blocks.

2018-08-06 15:30 UTC, jiuly256 reviewed
nota to note again

2018-08-06 20:12 UTC, samdark commented on docs/guide-es/start-installation.md
> +> Información: Puedes saltear esta sección por ahora si sólo estás probando Yii sin intención
Same here. Should be `Info` as it was.

2018-08-08 20:53 UTC, jiuly256 reviewed
Instalando only

2018-08-08 22:56 UTC, merged

2018-08-08 22:56 UTC, samdark commented
Merged. Thanks!