Ignore console commands that have no actions
yiisoft/yii2 pull request #16954
Opened 2018-12-09 12:24 UTC by alexeevdv

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #16855 

Changes summary:

- Add filter to `HelpController::getCommands` in order to ensure that command exist and it has actions. It allows to remove these checks from other places.
- `UnknownCommandException::getSuggestedAlternatives` ensure that command has default action before adding it to the suggested list.
- [Replace Nested Conditional with Guard Clauses](https://refactoring.guru/replace-nested-conditional-with-guard-clauses)

2018-12-17 22:56 UTC, alexeevdv commented
Tests added

2018-12-30 22:15 UTC, samdark requested changes

2018-12-30 22:15 UTC, samdark commented on tests/framework/console/controllers/HelpControllerTest.php
> +        $this->assertContains("fake\n", $result);
There's no need to test for it. We're checking that action list doesn't contain empty controllers and nothing more.

2018-12-30 22:15 UTC, samdark commented on tests/framework/console/controllers/HelpControllerTest.php
> +    public function testCommandsFilterOnActionList()
`testActionListContainsNoEmptyCommands`

2018-12-30 22:15 UTC, samdark commented on tests/framework/console/controllers/HelpControllerTest.php
> +    public function testCommandsFilterOnActionIndex()
testActionIndexContainsNoEmptyCommands

2018-12-30 22:15 UTC, samdark commented on tests/framework/console/controllers/HelpControllerTest.php
> +        $this->assertContains("- fake", $result);
There's no need to test for it. We're checking that action list doesn't contain empty controllers and nothing more.

2019-09-10 16:01 UTC, closed without merging

2019-09-10 16:01 UTC, samdark commented
Merged with adjustments https://github.com/yiisoft/yii2/commit/6e2b1782e52f8122302b84c331b30deec8972041. Thanks for contributing.