throw exception
yiisoft/yii2 pull request #17066
Opened 2019-01-23 21:11 UTC by GHopperMSK

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #16626

2019-01-23 22:22 UTC, GHopperMSK commented
Why do we have both blocks of code:

https://github.com/GHopperMSK/yii2/blob/c59df914c1f544889eafc4d8aa64132ae1337102/framework/db/QueryBuilder.php#L462-L478

https://github.com/GHopperMSK/yii2/blob/c59df914c1f544889eafc4d8aa64132ae1337102/framework/db/pgsql/QueryBuilder.php#L460-L478

Can't we use only one of them?

2019-03-09 12:33 UTC, samdark requested changes

2019-03-09 12:33 UTC, samdark commented on framework/db/QueryBuilder.php
> +     * @param $tableName
Types should be specified, descriptions should be added. `@since` tag needs to be added.

2019-03-09 12:33 UTC, samdark commented on framework/db/sqlite/QueryBuilder.php
> +        foreach($values as $i => $value) {
```suggestion
        foreach ($values as $i => $value) {
```

2019-03-09 17:00 UTC, rob006 commented
This will break existing applications for no valid reason. So far keys were ignored, so you could pass associative array and as long order was correct (and you're not relying on typecasting), everything was fine. After this PR, old code (which works correctly) will start throwing exception - IMO it is pointless BC break and annoying limitation. If typecasting was a problem, then fix typecasting, there is no need to break existing code.

2019-03-09 18:51 UTC, samdark commented
@rob006 were there any valid reasons for using associative arrays?

2019-03-09 18:57 UTC, rob006 commented
1. Readability (especially if you use `array_keys(current($values))` to get column names).
2. You may already have associative array from external source (API, SQL query) and there is no valid reason to iterate trough whole array and call `array_values()` to remove keys.

2019-03-09 19:00 UTC, samdark commented
Right. Indeed, that could break things and isn't clearly fixing a bug. @GHopperMSK thank you for preparing the pull request and starting discussion but it seems we won't merge it.

2019-03-09 19:00 UTC, closed without merging

2019-03-09 19:01 UTC, samdark commented
@SamMousa would like to get your opinion as well.

2019-03-10 11:37 UTC, SamMousa commented
It's a bit unclear to me, my original issue is about the fact that associative arrays will result in unexpected behavior. I suggest there we throw an exception for associative arrays to make execution more explicit.
Obviously this will always break BC and break code that is currently working.

Seeing as we're no longer doing new features in Yii2 I'd suggest we move this to 3.0 instead, where we can freely break BC. We could simply implement 2 functions there:
`batchInsertAssociative`
`batchInsertIndexed`

That way it's clear and since it's 3.0 we don't break existing code.

2019-03-10 12:23 UTC, rob006 commented
In Yii 3 we could just support associative arrays and don't ignore keys. For non-associative arrays it will work as before, but for associative arrays you would need also define column-value map in `$columns`.

```php
$x->batchInsert('table1', ['a' => 'a', 'b' => 'somecolumn'], [['b' => 123, 'a' => 345]]);
```

result:

```sql
insert into `table1` (`a`, `somecolumn`) values (345, 123);
```

But this will return error (since there is no `0` and `1` keys in `$rows` items):

```php
$x->batchInsert('table1', ['a', 'b'], [['b' => 123, 'a' => 345]]);
```

which is basically the same as:

```php
$x->batchInsert('table1', [0 => 'a', 1 => 'b'], [['b' => 123, 'a' => 345]]);
```

It should fix #16626 and provide some flexibility to support also associative arrays (without introducing additional methods). It should also fail early if number of columns in `$rows` does not match number of columns in `$columns` (AFAIK now it just generates and executes incorrect query).

2019-03-10 22:39 UTC, SamMousa commented
I don't think we should do both in  one function. 2 functions means easier to use, easier to test easier to comprehend.