Translate runtime requests
yiisoft/yii2 pull request #17247
Opened 2019-04-02 09:00 UTC by s1lver

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | no

2019-04-02 09:25 UTC, samdark requested changes

2019-04-02 09:25 UTC, samdark commented on docs/guide-ru/runtime-requests.md
> +Однако если ваше Yii-приложение  работает за обратным прокси-сервером, вам нужно добавить дополнительную конфигурацию для получения этой информации, поскольку прямой клиент теперь является прокси-сер
```suggestion
Однако если ваше приложение работает за обратным прокси-сервером, вам нужно дополнить конфигурацию, поскольку клиентом теперь является прокси-сервер, а IP-адрес пользователя передаётся приложению с помощью заголовка, установленного им.
```

2019-04-02 09:25 UTC, samdark commented on docs/guide-ru/runtime-requests.md
> +Начиная с 2.0.13, Yii поддерживает настройку доверенных прокси через
```suggestion
Начиная с 2.0.13, Yii поддерживает настройку доверенных прокси через следующие свойства компонента `request`:
```

2019-04-02 09:25 UTC, samdark commented on docs/guide-ru/runtime-requests.md
> +свойства компонента `request`.
```suggestion

```

2019-04-02 09:25 UTC, samdark commented on docs/guide-ru/runtime-requests.md
> +Ниже приведена конфигурация компонента `request` для приложения, которое работает за массивом обратных прокси, которые расположены в IP-сети `10.0.2.0/24`:
```suggestion
Ниже приведена конфигурация компонента `request` для приложения, которое работает за рядом обратных прокси, которые расположены в IP-сети `10.0.2.0/24`:
```

2019-04-02 09:25 UTC, samdark commented on docs/guide-ru/runtime-requests.md
> +Если ваши прокси используют разные заголовки, вы можете использовать конфигурацию компонента `request` для их настройки, например:
```suggestion
Если ваши прокси используют другие заголовки, вы можете использовать конфигурацию компонента `request` для их настройки, например:
```

2019-04-04 09:33 UTC, s1lver commented on docs/guide-ru/runtime-requests.md
> +Если ваши прокси используют разные заголовки, вы можете использовать конфигурацию компонента `request` для их настройки, например:
@samdark   внес исправления по замечаниям

2019-04-04 12:25 UTC, merged

2019-04-04 12:25 UTC, samdark commented
Merged. Thank you!