Translate output client scripts into russian
yiisoft/yii2 pull request #17272
Opened 2019-04-15 18:45 UTC by s1lver

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | no

2019-04-16 17:01 UTC, samdark requested changes

2019-04-16 17:01 UTC, samdark commented on docs/guide-ru/output-client-scripts.md
> +Один из способов достичь этого-использовать [интернационализацию](tutorial-i18n.md#message-translation), предоставляемую Yii и передающий результат в код JavaScript.
```suggestion
Один из способов достичь этого — использовать [интернационализацию](tutorial-i18n.md#message-translation), предоставляемую Yii и передавать результат в код JavaScript.
```

2019-04-16 17:01 UTC, samdark commented on docs/guide-ru/output-client-scripts.md
> +Приведенный выше пример кода использует PHP [синтаксис Heredoc](https://secure.php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc) для лучшей читаемости. Это также обесп
```suggestion
Приведенный выше пример кода использует PHP [синтаксис Heredoc](https://secure.php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc) для лучшей читаемости. Это также обеспечивает лучшую подсветку синтаксиса в большинстве IDE, поэтому это предпочтительный способ написания встроенного JavaScript, особенно полезный для кода, более длинного чем однострочный. Переменная `$message` создается PHP и благодаря [[yii\helpers\Json::htmlEncode|Json::htmlEncode]] содержит строку в допустимом синтаксисе JS, которую можно вставить в JavaScript код, чтобы поместить динамическую строку в вызов функции `alert()`.
```

2019-04-23 11:26 UTC, samdark commented
@s1lver please address additional comments I've left: https://github.com/yiisoft/yii2/pull/17272/files

2019-05-14 19:42 UTC, samdark commented
@s1lver do you have time to finish it?

2019-05-15 12:17 UTC, s1lver commented
> @s1lver do you have time to finish it?
Я вроде бы внес последние замечания по тексту? Или что-то пропустил?

2019-05-15 14:19 UTC, samdark commented
Пропустил: https://github.com/yiisoft/yii2/pull/17272/files

2019-05-15 14:22 UTC, s1lver commented
Хорошо, доработаю

2019-05-28 07:06 UTC, samdark approved these changes

2019-05-28 07:07 UTC, merged

2019-05-28 07:07 UTC, samdark commented
Merged. Thank you!