Fix for PostgreSQL alter column
yiisoft/yii2 pull request #17285
Opened 2019-04-23 20:09 UTC by bizley

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | will see
| Fixed issues  | #17263 #12135

2019-04-24 05:21 UTC, bizley commented
Well, I was hoping for Travis to run on this WIP PR but apparently it's not :)

2019-04-24 10:18 UTC, samdark commented
I wonder why... Can you make additional commit?

2019-04-24 15:18 UTC, bizley commented
Looks like tests are passed. Also this issue is related to #12077 as well.

2019-04-24 15:22 UTC, bizley commented
If you guys could take a look at the regex work here... It should be fine with default strings generated by `ColumnSchemaBuilder` but I'm not sure about user provided ones. In general I think most of the users are choosing CSB anyway because it's simply easier and faster.

2019-04-24 22:02 UTC, samdark requested changes

2019-04-24 22:02 UTC, samdark commented on framework/db/pgsql/QueryBuilder.php
> +            $type = preg_replace('/\s+NOT\s+NULL/i', '', $type);
`preg_replace` `$count` argument could be used to avoid matching regexp twice.

2019-04-24 22:02 UTC, samdark commented on framework/db/pgsql/QueryBuilder.php
> +        if (preg_match('/\s+(CHECK|check)\s+\((.+)\)/', $type, $matches)) {
```suggestion
        if (preg_match('/\s+CHECK\s+\((.+)\)/i', $type, $matches)) {
```

2019-04-24 22:02 UTC, samdark commented on framework/db/pgsql/QueryBuilder.php
> +            $multiAlterStatement[] = "ADD CONSTRAINT {$constraintPrefix}_check CHECK ({$matches[2]})";
```suggestion
            $multiAlterStatement[] = "ADD CONSTRAINT {$constraintPrefix}_check CHECK ({$matches[1]})";
```

2019-04-24 22:02 UTC, samdark commented on framework/db/pgsql/QueryBuilder.php
> +            $type = preg_replace('/\s+UNIQUE/i', '', $type);
`preg_replace` `$count` argument could be used to avoid matching regexp twice.

2019-04-25 07:17 UTC, bizley commented on framework/db/pgsql/QueryBuilder.php
> +        $constraintPrefix = preg_replace('[^a-zA-Z0-9_]', '', $table . '_' . $column);
Oh, wow, how this passed the tests :grin:

2019-04-30 17:07 UTC, samdark approved these changes

2019-04-30 17:08 UTC, merged

2019-04-30 17:08 UTC, samdark commented
Merged. Thank you!