Closes #17325. Add view detection for MySQL.
yiisoft/yii2 pull request #17402
Opened 2019-06-28 17:20 UTC by alexkart

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #17325

2019-06-28 18:15 UTC, samdark requested changes

2019-06-28 18:15 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +     * Determines whether the error message related to deleting a view or not
```suggestion
     * Determines whether the error message is related to deleting a view or not
```

2019-06-28 18:15 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +    private function isView($errorMessage)
```suggestion
    private function isViewRelated($errorMessage)
```

2019-06-28 18:15 UTC, samdark commented on framework/console/controllers/MigrateController.php
> +                if ($this->isView($e->getMessage())) {
```suggestion
                if ($this->isViewRelated($e->getMessage())) {
```

2019-06-28 19:08 UTC, alexkart commented
> Thank you for putting effort in the improvement of the Yii framework.
> We have reviewed your pull request.
> 
> In order for the framework and your solution to remain stable in the future, we have a unit test requirement in place. Therefore we can only accept your pull request if it is covered by unit tests.
> 
> Could you add these please?
> 
> Thanks!
> 
> P.S. If you have any questions about the creation of unit tests? Don't hesitate to ask for support. [More information about unit tests](http://www.yiiframework.com/doc-2.0/guide-test-unit.html)
> 
> _This is an automated comment, triggered by adding the label `pr:request for unit tests`._

Is it possible to run tests for MySQL?

2019-06-28 20:00 UTC, alexkart commented
Have I done it correctly?

2019-06-28 21:11 UTC, samdark commented
Yes, it is possible to run MySQL. You did it but there are connection configs and it is better to use these and not hardcoding credentials.

2019-06-30 16:53 UTC, samdark approved these changes

2019-06-30 16:53 UTC, merged

2019-06-30 16:53 UTC, samdark commented
Merged. Thank you!