Update ExistValidator.php
yiisoft/yii2 pull request #17561
Opened 2019-09-16 17:01 UTC by DrDeath72

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Tests pass?   | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2019-09-16 20:04 UTC, samdark requested changes
Please add a line for changelog.

2019-09-16 20:04 UTC, samdark commented on framework/validators/ExistValidator.php
> +     * @var string|array|\Closure|callable additional filter to be applied to the DB query used to check the existence of the attribute value.
```suggestion
     * @var string|array|callable additional filter to be applied to the DB query used to check the existence of the attribute value.
```

2019-09-16 20:04 UTC, samdark commented on framework/validators/ExistValidator.php
>       * on the format of query condition), or an anonymous function with the signature `function ($query)`, where `$query`
```suggestion
      * on the format of query condition), or an callable with the signature `function ($query)`, where `$query`
```

2019-09-16 20:04 UTC, samdark commented on framework/validators/RangeValidator.php
> +     * @var array|\Traversable|\Closure|callable a list of valid values that the attribute value should be among or an anonymous function that returns
```suggestion
     * @var array|\Traversable|callable a list of valid values that the attribute value should be among or a callable that returns
```

2019-09-16 20:04 UTC, samdark commented on framework/validators/UniqueValidator.php
> +     * @var string|array|\Closure|callable additional filter to be applied to the DB query used to check the uniqueness of the attribute value.
```suggestion
     * @var string|array|callable additional filter to be applied to the DB query used to check the uniqueness of the attribute value.
```

2019-09-16 20:04 UTC, samdark commented on framework/validators/UniqueValidator.php
>       * on the format of query condition), or an anonymous function with the signature `function ($query)`, where `$query`
```suggestion
     * on the format of query condition), or a callable with the signature `function ($query)`, where `$query`
```

2019-09-17 08:04 UTC, alex-code commented
Is
```php
$this->filter instanceof \Closure
```
still needed with `is_callable`?
Could this be simplified to 
```php
if (is_callable($this->filter)) {
```

2019-09-17 08:13 UTC, DrDeath72 commented
i think no, do it like in other place :)

2019-09-17 09:48 UTC, samdark approved these changes

2019-09-17 10:02 UTC, rob006 commented
:-1: from me. This will create ambiguous where array could be interpreted either as callable or value - this may lead to really weird bugs and even security issues. For example `['Foo', 'bar']` in `RangeValidator::$range` may be interpreted as list of allowed values. But if you add `Foo` class with `bar` method, it will magically call this method and use result as list of allowed values.

2019-09-17 10:39 UTC, kamarton commented
>  from me. This will create ambiguous where array could be interpreted either as callable or value - this may lead to really weird bugs and even security issues. For example `['Foo', 'bar']` in `RangeValidator::$range` may be interpreted as list of allowed values. But if you add `Foo` class with `bar` method, it will magically call this method and use result as list of allowed values.

I completely agree.

2019-09-17 11:01 UTC, rob006 commented
Just for the record - the use case seems to be valid, but implementation is plain wrong. I would personally disallow `is_callable` in every place where non-callables are also allowed - this is just asking for troubles and it is really easy to shoot yourself in the foot by simple mistake. #17560 probably could be fixed by introducing some kind of `CallableExpression` which will wrap callable array/string, so they will never be confused with plain array/string.

2019-09-17 15:35 UTC, alex-code commented
If you're able to use PHP7.1+ there's https://www.php.net/manual/en/closure.fromcallable.php
e.g.
```php
class foo {
    public static function bar() {
        return 'foo-bar';
    }
}

$closure = Closure::fromCallable(['foo', 'bar']);
echo call_user_func($closure);
```

Should work with the existing checks then.

2019-09-17 16:10 UTC, DrDeath72 commented
Closure not cacheable

2019-09-17 17:32 UTC, kamarton commented
Create your own validators and implement the necessary logic in them. Caching validators object is wrong idea.

2026-06-04 14:37 UTC, terabytesoftw commented
Thank you for the contribution.

After reviewing the discussion again, I am closing this PR because the proposed approach is not safe to merge. These validator properties already accept arrays as values or query conditions, so interpreting callable arrays specially would make behavior ambiguous and may introduce backward compatibility issues.

The use case described in #17560 may still be valid as a feature request, but it needs a different explicit design rather than changing existing array semantics implicitly.

Closing this PR as outdated and not acceptable in its current form.

2026-06-04 14:37 UTC, closed without merging