InConditionBuilder proper null handling
yiisoft/yii2 pull request #17697
Opened 2019-11-29 15:13 UTC by strychu

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ❌
| Fixed issues  | #17661

2019-11-30 00:02 UTC, samdark commented
Seems to fail tests: https://travis-ci.org/yiisoft/yii2/jobs/618641372

2019-12-05 18:55 UTC, strychu commented
I've fixed tests and added some test cases to condition provider

2019-12-05 22:25 UTC, strychu commented
Although i see that build fails for php 7.4

2019-12-05 22:30 UTC, samdark commented
That's OK. Same in master.

2019-12-11 23:17 UTC, samdark requested changes

2019-12-11 23:17 UTC, samdark commented on tests/framework/db/QueryBuilderTest.php
> +            [['in', 'id', new TraversableObject([1, null])], '[[id]]=:qp0 AND [[id]] IS NULL', [':qp0' => 1]],
That doesn't look right. `in` is about the value is being in the list. "in X [1,2,3]" transforms into `X IN [1,2,3]` that is equal to `X = 1 OR X = 2 OR X = 3`. Here we have `AND` and I think it should be `OR`.

2019-12-11 23:17 UTC, samdark commented on tests/framework/db/QueryBuilderTest.php
> +            [['in', 'id', new TraversableObject([1, 2, null])], '[[id]] IN (:qp0, :qp1) AND [[id]] IS NULL', [':qp0' => 1, ':qp1' => 2]],
Same here. Looks like it should generate `OR`.

2019-12-11 23:17 UTC, samdark commented on tests/framework/db/QueryBuilderTest.php
> +            [['not in', 'id', new TraversableObject([1, null])], '[[id]]<>:qp0 AND [[id]] IS NOT NULL', [':qp0' => 1]],
These ones are correct.

2019-12-11 23:17 UTC, samdark commented on tests/framework/db/QueryBuilderTest.php
> +            [['in', 'id', new TraversableObject([null])], '[[id]] IS NULL', []],
These ones are correct as well.

2019-12-12 18:56 UTC, samdark approved these changes

2019-12-17 10:58 UTC, merged

2019-12-17 10:58 UTC, samdark commented
Merged. Thank you!