Fix non-HTTP POST upload file
yiisoft/yii2 pull request #17729
Opened 2019-12-12 03:58 UTC by sup-ham

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #17037, #7280, #multipa

2019-12-12 04:08 UTC, sup-ham commented
Also the docs need to be adjusted.

2019-12-12 10:31 UTC, samdark commented
@sup-ham which docs?

2019-12-12 10:31 UTC, samdark commented
There seems to be trouble with the changes under Windows.

2019-12-12 10:42 UTC, My6UoT9 commented
Would this work if my filename is "@webroot.jpg" ? Looks like trouble?

2019-12-16 21:11 UTC, samdark requested changes

2019-12-16 21:11 UTC, samdark commented on framework/web/UploadedFile.php
> +            return is_file($this->tempName) && copy($this->tempName, $file);
That looks suspicious to me. Previously there was `is_uploaded_file` check that ensured that file moved is what came via POST. Now, resource is empty only when the method is POST but the check is missing.

2020-01-14 13:09 UTC, samdark approved these changes

2020-01-14 21:57 UTC, merged

2020-01-14 21:57 UTC, samdark commented
Thank you!