Update the translating
yiisoft/yii2 pull request #17945
Opened 2020-03-30 10:37 UTC by VikingBO

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ❌
| Fixed issues  | ❌

Just translating

2020-03-30 16:23 UTC, samdark requested changes

2020-03-30 16:23 UTC, samdark commented on docs/guide-ru/security-authorization.md
> +> Примечание: Если вы используете версию yii2-basic-app, кроме конфигурации веб приложения `config/web.php` подключение компонента
```suggestion
> Примечание: Если вы используете шаблон проекта basic, компонент `authManager` необходимо настроить как в `config/web.php`, так и в
```

2020-03-30 16:23 UTC, samdark commented on docs/guide-ru/security-authorization.md
> +> `authManager` нужно также указать в [конфигурации консольного приложения](tutorial-console.md#configuration) `config/console.php`.
```suggestion
> [конфигурации консольного приложения](tutorial-console.md#configuration) `config/console.php`.
```

2020-03-30 16:23 UTC, samdark commented on docs/guide-ru/security-authorization.md
> +> В версии yii2-advanced-app класс `authManager` нужно подключить один раз в `common/config/main.php`.
```suggestion
> При использовании шаблона проекта advanced `authManager` достаточно настроить единожды в `common/config/main.php`.
```

2020-04-03 15:01 UTC, VikingBO commented
I don't understand what I should do next to accept the request

2020-04-03 15:29 UTC, samdark commented
Take suggestions into account, not just close them.

2020-04-03 15:56 UTC, VikingBO reviewed
upd changes

2020-04-03 16:35 UTC, VikingBO commented
And how i can restart tests?

2020-04-03 23:21 UTC, samdark approved these changes

2020-04-03 23:22 UTC, merged

2020-04-03 23:22 UTC, samdark commented
👍