Fix #18096: Fix InlineValidator with anonymous inline function not wo…
yiisoft/yii2 pull request #18097
Opened 2020-06-11 09:39 UTC by trombipeti

…rking well from EachValidator

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18096

2020-06-11 11:07 UTC, samdark commented
Seems to break tests on pre PHP 7.4.

2020-06-11 12:09 UTC, trombipeti commented
Sorry, fixed.

2020-06-14 07:43 UTC, bizley requested changes
Some code style changes only. The rest looks good

2020-06-14 07:43 UTC, bizley commented on framework/validators/InlineValidator.php
> +            } else if ($method instanceof \Closure) {
```suggestion
            } elseif ($method instanceof \Closure) {
```

2020-06-14 07:43 UTC, bizley commented on tests/data/validators/models/ValidatorTestEachAndInlineMethodModel.php
> +            ['arrayProperty', 'each', 'rule' => [function($attribute, $params, $validator) {
```suggestion
            ['arrayProperty', 'each', 'rule' => [function ($attribute, $params, $validator) {
```

2020-06-14 07:43 UTC, bizley commented on tests/data/validators/models/ValidatorTestEachAndInlineMethodModel.php
> +                if(is_array($this->$attribute)) {
```suggestion
                if (is_array($this->$attribute)) {
```

2020-06-15 07:14 UTC, samdark approved these changes

2020-06-15 07:14 UTC, merged

2020-06-15 07:15 UTC, samdark commented
Thank you!

2020-07-14 17:59 UTC, brandonkelly commented
This change introduced a change in behavior that should be documented: #18175