Db expression
yiisoft/yii2 pull request #18142
Opened 2020-06-29 18:32 UTC by darkdef

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️/❌
| Tests pass?   | ✔️
| Fixed issues  | #18134 

 Expression is not will be quoted

2020-06-29 23:40 UTC, samdark requested changes
Overall it's fine. Need some minor things fixed and a line for CHANGELOG.md

2020-06-29 23:40 UTC, samdark commented on framework/db/Connection.php
> +     * If the column name is Exresion - return as is
```suggestion
     * If the column name is an instance of `ExpressionInterface` it is returned as is.
```

2020-06-29 23:40 UTC, samdark commented on framework/db/Connection.php
> +        // Expression is not will be quoted (https://github.com/yiisoft/yii2/issues/18134)
```suggestion
```

2020-06-29 23:40 UTC, samdark commented on framework/db/Connection.php
>       * @param string $name column name
```suggestion
     * @param string $name|ExpressionInterface column name
```

2020-06-29 23:40 UTC, samdark commented on tests/framework/db/QueryBuilderTest.php
> +    public function testIssue18134()
```suggestion
    public function testExpressionIsNotQuotedInColumnName()
```

2020-06-30 14:58 UTC, samdark approved these changes

2020-06-30 14:59 UTC, merged

2020-06-30 14:59 UTC, samdark commented
Thanks!

2020-06-30 18:01 UTC, rob006 reviewed
I don't think that this is right place to fix it. Expressions should be handled at `LikeConditionBuilder::build()` level, there is no need to add special conditions in `Connection::quoteColumnName()`.

See https://github.com/yiisoft/yii2/pull/17490

2020-06-30 18:06 UTC, darkdef commented
But what about the case when the Expression will be used instead of the column name in other cases?
This issue (for example): https://github.com/yiisoft/yii2/issues/17473

2020-06-30 18:32 UTC, samdark commented on framework/db/Connection.php
> +     * @param string $name|ExpressionInterface column name
Why?

2020-06-30 18:35 UTC, darkdef commented on framework/db/Connection.php
> +     * @param string $name|ExpressionInterface column name
@param $name string|ExpressionInterface column name

2020-06-30 18:36 UTC, rob006 commented
@darkdef What cases? #17473 is already fixed by #17490 in a way I proposed (by fixing `SimpleConditionBuilder::build()`). It just does not make sense to pass non-string to `Connection::quoteTableName()`, so code should be adjusted to not do that. This PR makes `Connection::quoteTableName()` interface more twisted only to silently handle bugs in other places.

2020-06-30 18:38 UTC, samdark commented
Yes, makes sense. Reverted. Should be fixed another way.

2020-06-30 18:42 UTC, darkdef commented
ok. I understood

2020-06-30 18:50 UTC, rob006 commented on framework/db/Connection.php
> +     * @param string $name|ExpressionInterface column name
Valid syntax is:

```
@param string|ExpressionInterface $name column name
```

But this should not be changed in the first place.