Fix for OUTPUT INSERTED and computed columns
yiisoft/yii2 pull request #18307
Opened 2020-09-24 18:48 UTC by darkdef

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18287 
Added key to computed column in table schema and usage for generate query (OUTPUT INSERTED without computed columns)

2020-09-25 08:37 UTC, bizley requested changes

2020-09-25 08:37 UTC, bizley commented on framework/db/mssql/QueryBuilder.php
> +                    continue;
```suggestion
                if ($column->isComputed) {
                    continue;
                }
```

2020-09-25 08:37 UTC, bizley commented on framework/db/mssql/QueryBuilder.php
> +            . (($version2005orLater and count($columns)) ? ' OUTPUT ' . implode(',', $columns) . ' INTO @temporary_inserted' : '')
```suggestion
            . (($version2005orLater && count($columns)) ? ' OUTPUT ' . implode(',', $columns) . ' INTO @temporary_inserted' : '')
```

2020-09-25 08:37 UTC, bizley commented on framework/db/mssql/QueryBuilder.php
> +            . (($version2005orLater and count($columns)) ? ' OUTPUT ' . implode(',', $columns) . ' INTO @temporary_inserted' : '')
Also `count($columns)` is used more than once, it's worth to make it a variable.

2020-09-25 08:37 UTC, bizley commented on framework/db/mssql/QueryBuilder.php
> +        if ($version2005orLater and count($columns)) {
```suggestion
        if ($version2005orLater && count($columns)) {
```

2020-09-25 08:37 UTC, bizley commented on framework/db/mssql/QueryBuilder.php
> +            $sql = "SET NOCOUNT ON;DECLARE @temporary_inserted TABLE (" . implode(", ", $cols) . ");" . $sql .
```suggestion
            $sql = 'SET NOCOUNT ON;DECLARE @temporary_inserted TABLE (' . implode(', ', $cols) . ');' . $sql .
```

2020-09-25 08:37 UTC, bizley commented on framework/db/mssql/QueryBuilder.php
> +                ";SELECT * FROM @temporary_inserted";
```suggestion
                ';SELECT * FROM @temporary_inserted';
```

2020-09-25 08:37 UTC, bizley commented on framework/db/mssql/ColumnSchema.php
> +     * @var bool whether this column is a computed column
Requires `@since`

2020-09-25 11:00 UTC, bizley approved these changes

2020-09-29 23:28 UTC, samdark approved these changes
Looks good 👍 Please add a line for CHANGELOG.md. Thanks.

2020-10-04 18:44 UTC, merged

2020-10-04 18:44 UTC, samdark commented
👍