Fix creating migration with defaultValue
yiisoft/yii2 pull request #18311
Opened 2020-09-29 21:00 UTC by wsaid

Fix creating migration issue for column methods used after defaultValues

2020-09-30 03:56 UTC, bizley commented
#18303

2020-10-04 09:58 UTC, bizley requested changes

2020-10-04 09:58 UTC, bizley commented on tests/framework/console/controllers/MigrateControllerTest.php
> +            'create_fields_withc_col_method_after_default_value' => [
```suggestion
            'create_fields_with_col_method_after_default_value' => [
```

2020-10-04 09:58 UTC, bizley commented on tests/framework/console/controllers/MigrateControllerTest.php
> +
Remove empty line

2020-10-04 09:58 UTC, bizley commented on tests/framework/console/controllers/MigrateControllerTest.php
> +            ['create_fields_withc_col_method_after_default_value', 'create_test_table', 'test', $params['create_fields_withc_col_method_after_default_value']],
```suggestion
            ['create_fields_with_col_method_after_default_value', 'create_test_table', 'test', $params['create_fields_with_col_method_after_default_value']],
```

2020-10-04 10:36 UTC, bizley approved these changes

2020-10-04 22:02 UTC, samdark approved these changes

2020-10-04 22:02 UTC, merged

2020-10-04 22:02 UTC, samdark commented
Thank you!