Connection class for ActiveDataProvider
yiisoft/yii2 pull request #18560
Opened 2021-03-11 10:06 UTC by bizley

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18557 

This fixes regression introduced in #18476 - at the same time to not lose the advantage of using `ensure` for the connection configuration I propose adding new property `connectionClass` that providers extending `ActiveDataProvider` can set to their appropriate connection.

Changes in the following packages are required as well:
- `yii2-elasticsearch`
- `yii2-sphinx`
- `yii2-redis` (only tests)
- `yii2-mongodb` (only tests)

I will add the required changes if this PR is merged.

2021-03-12 20:53 UTC, samdark approved these changes

2021-03-12 20:53 UTC, samdark commented
Looks good to me. Will be merged after PRs for extensions are ready.

2021-03-13 11:51 UTC, bizley commented
Ready.

2021-03-13 20:05 UTC, samdark requested changes

2021-03-13 20:05 UTC, samdark commented on framework/data/ActiveDataProvider.php
> +    public $connectionClass = 'yii\db\Connection';
That's big BC break in case of non-default DB connections.

2021-03-13 20:05 UTC, samdark commented on framework/data/ActiveDataProvider.php
> +            $this->db = Instance::ensure($this->db, $this->connectionClass);
How about just removing the check? That would both pass the test *and* won't cause BC break.

```suggestion
            $this->db = Instance::ensure($this->db);
```

2021-03-14 10:15 UTC, bizley commented
Changes in the related packages removed except the ones made to the tests setup.

2021-03-14 15:43 UTC, merged

2021-03-14 15:43 UTC, samdark commented
👍