Added 'software' and 'hardware' string to BaseInflector $specials.
yiisoft/yii2 pull request #18628
Opened 2021-05-03 06:43 UTC by kjusupov

Added following 4 lines to `$specials` to use in `Inflector::pluralize($category->name)` and it should return correct plural form.
```
'software' => 'software',
'Software' => 'Software',
'hardware' => 'hardware',
'Hardware' => 'Hardware',`
```

2021-05-03 07:55 UTC, schmunk42 commented
How about *Vaporware* and other "...wares"?

2021-05-03 08:16 UTC, kjusupov commented
> How about _Vaporware_ and other "...wares"?

@schmunk42 `$specials` uses the keys (special words) in singular form, unlike regular expression keys in`$singulars` and `$plurals`, so I have just added what I needed.

2021-05-03 08:35 UTC, bizley commented
Apparently all `-ware` words (except for `houseware` and maybe `homeware`) don't have distinct plural forms. Do we want to add all of them? There should be a smarter way of doing this. Anyway, this small amendment is fine although I don't think we should have separate keys for capitalized versions. All other specials don't have them.

2021-05-07 08:17 UTC, bizley requested changes

2021-05-07 08:17 UTC, bizley commented on framework/helpers/BaseInflector.php
> +        'Software' => 'Software',
Please remove capitalized versions

2021-05-07 14:07 UTC, bizley approved these changes

2021-05-08 21:59 UTC, samdark approved these changes

2021-05-08 21:59 UTC, samdark commented
Please add a line for CHANGELOG.

2021-05-10 08:54 UTC, merged