Normalize test classes
yiisoft/yii2 pull request #18811
Opened 2021-08-06 14:57 UTC by WinterSilence

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  |

2021-08-06 15:53 UTC, machour requested changes
Please provide a description for this PR, explaining the change of exceptions.

2021-08-06 15:57 UTC, machour commented
And are these the only test models files that could benefit from this PR ?
If there are other, please include them in this PR as well.

2021-08-06 16:01 UTC, WinterSilence commented
@machour 
> And are these the only test models files that could benefit from this PR ?

just review test code

2021-08-16 10:00 UTC, WinterSilence commented
@samdark @bizley please review and merge - I'm can't send other PRs will uses this changes.

2021-08-16 12:25 UTC, bizley commented
I don't see here anything justifying the PR tbh. @samdark ?

2021-09-03 09:41 UTC, merged

2021-09-03 09:41 UTC, samdark commented
Won't hurt overall.