Update ActiveRelationTrait.php
yiisoft/yii2 pull request #19585
Opened 2022-09-19 03:17 UTC by spo0okie

fix #19507

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | 19507

2022-10-03 15:13 UTC, bizley requested changes
Also please add Changelog line, thanks.

2022-10-03 15:13 UTC, bizley commented on framework/db/ActiveRelationTrait.php
> +            $resultMap[$key]=[];
```suggestion
            $resultMap[$key] = [];
```

2022-10-03 15:13 UTC, bizley commented on tests/data/ar/Customer.php
> +    public function getOrderItems2()
```suggestion
    public function getOrderItems2()
```

2022-10-03 15:13 UTC, bizley commented on tests/data/ar/Customer.php
> +    public function getItems()
```suggestion
    public function getItems()
```

2022-10-03 15:13 UTC, bizley commented on tests/framework/db/ActiveRecordTest.php
> +            ->all();
```suggestion
        $eagerCustomers = Customer::find()->joinWith(['items'])->all();
```

2022-10-03 15:13 UTC, bizley commented on tests/framework/db/ActiveRecordTest.php
> +        $eagerItemsCount=0;
```suggestion
        $eagerItemsCount = 0;
```

2022-10-03 15:13 UTC, bizley commented on tests/framework/db/ActiveRecordTest.php
> +        foreach ($eagerCustomers as $customer) $eagerItemsCount+=count($customer->items);
```suggestion
        foreach ($eagerCustomers as $customer) {
            $eagerItemsCount += count($customer->items);
        }
```

2022-10-03 15:13 UTC, bizley commented on tests/framework/db/ActiveRecordTest.php
> +            ->all();
```suggestion
        $lazyCustomers = Customer::find()->all();
```

2022-10-03 15:13 UTC, bizley commented on tests/framework/db/ActiveRecordTest.php
> +        $lazyItemsCount=0;
```suggestion
        $lazyItemsCount = 0;
```

2022-10-03 15:13 UTC, bizley commented on tests/framework/db/ActiveRecordTest.php
> +        foreach ($lazyCustomers as $customer) $lazyItemsCount+=count($customer->items);
```suggestion
        foreach ($lazyCustomers as $customer) {
            $lazyItemsCount += count($customer->items);
        }
```

2022-10-03 15:13 UTC, bizley commented on tests/framework/db/ActiveRecordTest.php
> +        $this->assertEquals($eagerItemsCount, $lazyItemsCount);
```suggestion
        $this->assertEquals($eagerItemsCount, $lazyItemsCount);
```

2022-10-03 16:55 UTC, spo0okie reviewed
ok

2022-10-03 16:57 UTC, spo0okie reviewed
sry, cant find how to approve changes =/

2022-10-04 06:22 UTC, bizley approved these changes

2022-10-04 06:23 UTC, bizley commented
Just waiting for some other team member to approve it and we are good to go.

2022-10-04 09:45 UTC, samdark approved these changes

2022-10-04 09:49 UTC, arogachev approved these changes

2022-10-04 09:55 UTC, merged

2022-10-31 09:14 UTC, sigaryov commented
В db/ActiveRelationTrait.php, по-моему, есть баг.

Делаю запрос:

```
->joinWith([
    'dayRealTime',
    'user.usersWorkRoles.workRole.predictionType',
])
```
Получаю ошибку:

> Undefined index: date

в функции filterByModels($models). date - это поле для связи по свойству dayRealTime.


![847dd835b0](https://user-images.githubusercontent.com/59250170/198972616-7c83163e-1a7a-4341-a91b-7b460242fa65.jpg)

Если добавить проверку на наличие элемента в массиве, то ошибка уходит:

```
foreach ($prefixedLink as $attribute => $link) {
    $value = isset($model[$attribute]) || (is_object($model) && property_exists($model, $attribute)) ? $model[$attribute] : null;
    if ($value !== null) {
        $v[$attribute] = $model[$link];
    }
}
```

2022-11-07 06:33 UTC, samdark commented
@sigaryov it's better to create a separate issue for it. @arogachev would you please take a look?

2022-11-07 07:05 UTC, arogachev commented
@samdark. OK. I'll check it.

@sigaryov Thanks for reporting. Could you share the relevant data structure (you can remove sensitive data)?