Added skiping `FileTarget::class` with message its `empty` array.
yiisoft/yii2 pull request #19897
Opened 2023-07-17 23:06 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | https://github.com/yiisoft/yii2/pull/16208

2023-07-18 14:57 UTC, samdark approved these changes
Looks 👍 Need a line for CHANGELOG.

2023-07-18 14:58 UTC, samdark commented
Also, is it the same in Yii3 log package?

2023-07-18 15:29 UTC, bizley requested changes

2023-07-18 15:29 UTC, bizley commented on framework/CHANGELOG.md
> +- Bug #16208: Added skiping `FileTarget::class` with message its empty array (terabytesoftw)
```suggestion
- Bug #16208: Fix `yii\log\FileTarget` to not export empty messages (terabytesoftw)
```

2023-07-18 15:29 UTC, bizley commented on framework/log/FileTarget.php
> +        if (empty($trimmedText)) {
Can we move this whole check to the first line? To not create directories if there is nothing to export anyway.
Also - why not use `$trimmedText` later on when actually saving to the file?

2023-07-18 15:44 UTC, bizley approved these changes

2023-07-19 00:08 UTC, Arhell approved these changes

2023-07-24 07:01 UTC, merged

2023-07-24 07:01 UTC, samdark commented
Thanks!