Added support for string as Cookie::$expire
yiisoft/yii2 pull request #19920
Opened 2023-07-29 17:52 UTC by rhertogh

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | -
| Fixed issues  | #19917

The `\yii\httpclient\Response::parseCookie()` function sets the `Cookie::$expire` as string.
This PR broadens the accepted types for `Cookie::$expire` from `int` to `int|string|null`.

2023-07-30 10:43 UTC, bizley commented
Ok, let's keep it as it seems that it's common thing to be prepared for other types than int. BUT since we are doing this let's allow DateTimeInterface as well.

2023-08-04 08:23 UTC, bizley requested changes

2023-08-04 08:23 UTC, bizley commented on framework/web/Cookie.php
> +     * @var int|string|null the timestamp or date at which the cookie expires. This is the server timestamp.
Let's allow DateTimeInterface as well.

2023-08-04 09:17 UTC, rhertogh commented on framework/web/Cookie.php
> +     * @var int|string|null the timestamp or date at which the cookie expires. This is the server timestamp.
I'll add it 👍

2023-08-04 14:34 UTC, bizley approved these changes

2023-08-05 07:09 UTC, Arhell approved these changes

2023-08-15 16:38 UTC, merged

2023-08-15 16:38 UTC, bizley commented
👍🏻