Add support for index / query hints in query builder
yiisoft/yii2 pull request #19946
Opened 2023-09-02 06:41 UTC by uaoleg

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | 9119

2023-09-03 09:39 UTC, rob006 commented
Note that this syntax is planned to be deprecated in MySQL:

> As of MySQL 8.0.20, the server supports the index-level optimizer hints [JOIN_INDEX](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html#optimizer-hints-index-level), [GROUP_INDEX](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html#optimizer-hints-index-level), [ORDER_INDEX](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html#optimizer-hints-index-level), and [INDEX](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html#optimizer-hints-index-level), which are equivalent to and intended to supersede FORCE INDEX index hints, as well as the [NO_JOIN_INDEX](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html#optimizer-hints-index-level), [NO_GROUP_INDEX](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html#optimizer-hints-index-level), [NO_ORDER_INDEX](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html#optimizer-hints-index-level), and [NO_INDEX](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html#optimizer-hints-index-level) optimizer hints, which are equivalent to and intended to supersede IGNORE INDEX index hints. Thus, you should expect USE INDEX, FORCE INDEX, and IGNORE INDEX to be deprecated in a future release of MySQL, and at some time thereafter to be removed altogether.
> 
> These index-level optimizer hints are supported with both single-table and multi-table [DELETE](https://dev.mysql.com/doc/refman/8.0/en/delete.html) statements.
> 
> For more information, see [Index-Level Optimizer Hints](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html#optimizer-hints-index-level).

https://dev.mysql.com/doc/refman/8.0/en/index-hints.html

And new syntax can already be handled by `$option` parameter in `select()`.

2023-09-03 09:48 UTC, bizley approved these changes

2023-09-03 10:43 UTC, rhertogh commented
@uaoleg Looks good. Please also add unit tests and a line in the changelog.md

2023-09-04 00:32 UTC, Arhell approved these changes

2023-09-04 12:48 UTC, rob006 requested changes
This is definitely not finished:
1. There are no tests that would verify that generated queries actually work.
2. Implementation uses MySQL specific syntax, so it would fail for the rest of DBMS.
3. This MySQL syntax is planned to be removed, so the only part of this PR that works, is already soft-deprecated.

IMO instead of providing API for `FORCE INDEX` clause, we should just provide API for adding something after table name (including table name for JOIN) - it should be easier to maintain and more flexible for users (even index hints for MySQL are more complicated than just `FORCE INDEX`). If you need index hints, you're probably targeting very specific DBMS with specific version, so having abstraction at framework level does not bring much benefit.

2025-05-08 05:40 UTC, xicond commented
> This is definitely not finished:
> 
> 1. There are no tests that would verify that generated queries actually work.
> 2. Implementation uses MySQL specific syntax, so it would fail for the rest of DBMS.
> 3. This MySQL syntax is planned to be removed, so the only part of this PR that works, is already soft-deprecated.
> 
> IMO instead of providing API for `FORCE INDEX` clause, we should just provide API for adding something after table name (including table name for JOIN) - it should be easier to maintain and more flexible for users (even index hints for MySQL are more complicated than just `FORCE INDEX`). If you need index hints, you're probably targeting very specific DBMS with specific version, so having abstraction at framework level does not bring much benefit.

agree, it's same syntax in postgre sqlserver etc

2026-03-25 19:21 UTC, terabytesoftw commented
Index hint syntax is incompatible across supported database engines:

Engine       | Syntax                       | Type       | Behavior
------------ | ---------------------------- | ---------- | ------------------------------------
MySQL        | table USE INDEX (idx)         | Advisory   | Silent fallback. Deprecated in 8.0.20+
PostgreSQL   | No native support             | N/A        | Requires third-party pg_hint_plan extension
SQL Server   | table WITH(INDEX(idx))        | Advisory   | Silent fallback
SQLite       | table INDEXED BY idx          | Constraint | Errors if the index cannot be used
Oracle       | /*+ INDEX(t idx) */           | Advisory   | Silently ignored
  
Problems:

1. PostgreSQL has no native support a cross-database abstraction is impossible.
2. SQLite uses INDEXED BY as a hard constraint (fails with error), not an advisory hint fundamentally different semantics.
3. MySQL deprecated FORCE INDEX/USE INDEX/IGNORE INDEX in 8.0.20 in favor of comment-based optimizer hints.
4. SQL syntax placement differs across engines (FROM clause, comment block, WITH clause), making a unified API impractical.

Existing workaround: users can already achieve this without framework changes using Expression:

```php
// MySQL
$query->from([new Expression('{{%user}} USE INDEX (idx_name)')]);

// SQL Server
$query->from([new Expression('{{%user}} WITH(INDEX(idx_name))')]);

// SQLite
$query->from([new Expression('{{%user}} INDEXED BY idx_name')]);
```

This approach is explicit, engine-specific (appropriate for advanced DBA optimization), and requires zero framework changes.

2026-03-25 19:40 UTC, samdark commented
@terabytesoftw so should we close the pull request then or?

2026-03-25 19:41 UTC, terabytesoftw commented
> @terabytesoftw so should we close the pull request then or?

yes, the syntax is deprecated and not supported by all drivers.

2026-03-25 20:15 UTC, closed without merging