Bug #18469: fix Link::serialize method
yiisoft/yii2 pull request #20020
Opened 2023-10-20 10:42 UTC by ggh2e3

| Q             | A
| ------------- | ---
| Is bugfix?  ✔️
| New feature? ❌
| Breaks BC? ❌
| Fixed issues  | #18469 

Hi, I applied the fix proposed above with some unit tests. Hope it helps

2023-10-25 10:19 UTC, ggh2e3 commented on framework/web/Link.php
> +            if ($link instanceof self) {
something like this?
`        foreach ($links as $rel => $link) {
            if (is_array($link)) {
                $link = self::serialize($link); // refactored snippet
                $links[$rel] = $link;
            }
            if ($link instanceof self) {
                $l = array_filter((array)$link);
                $links[$rel] = $l;
            } else {
                $links[$rel] = ['href' => $link];
            }
        }`

2023-10-25 10:22 UTC, ggh2e3 commented on framework/web/Link.php
> +            if ($link instanceof self) {
Are you referring to line 66(or maybe the whole method)?
I'd replace line 66 with this recursive call` $link = self::serialize($link);` in order to remove the second loop

2023-10-25 11:41 UTC, rob006 commented
It is only me, or these test do not have sense at all? :P

2023-10-25 11:49 UTC, bizley commented
Heh, yes, this is what I thought as well, so I had to go through the code again.
@ggh2e3 could you refactor the tests to not confuse? For example [this](https://github.com/yiisoft/yii2/pull/20020/files#diff-649b7c9c42053caeda40e96fad0d665907b4b281093f719df437f138c532698bR29) looks like a config for a single object so the expected result is weird.

2023-10-29 17:27 UTC, ggh2e3 commented
Yep, I can refactor the tests to avoid confusion.

2023-11-12 17:52 UTC, ggh2e3 commented
@bizley is it fine now?

2023-11-13 10:05 UTC, bizley requested changes

2023-11-13 10:05 UTC, bizley commented on framework/web/Link.php
>                  $links[$rel] = $link;
```suggestion
                $links[$rel] = self::serialize($link);
```

2023-11-13 10:05 UTC, bizley commented on framework/web/Link.php
> +                $links[$rel] = $l;
```suggestion
            } elseif ($link instanceof self) {
                $links[$rel] = array_filter((array)$link);
```

2023-11-18 10:31 UTC, bizley approved these changes

2023-11-19 02:02 UTC, Arhell approved these changes

2023-11-23 15:09 UTC, merged

2023-11-23 15:09 UTC, samdark commented
👍