Raise version min `PHP 7.3`.
yiisoft/yii2 pull request #20134
Opened 2024-03-20 20:29 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2024-03-20 20:52 UTC, rob006 commented on composer.json
> +        "phpunit/phpunit": "9.6",
```suggestion
        "phpunit/phpunit": "^9.6",
```

2024-03-21 10:42 UTC, bizley approved these changes

2024-03-21 11:00 UTC, samdark requested changes

2024-03-21 11:08 UTC, terabytesoftw commented on tests/data/validators/models/ValidatorTestTypedPropModel.php
> +    public $arrayTypedProperty = [true, false];
done.

2024-03-21 11:18 UTC, terabytesoftw commented on tests/IsOneOfAssert.php
> +    public function __construct($allowedValues)
done.

2024-03-21 11:18 UTC, terabytesoftw commented on tests/IsOneOfAssert.php
> +        return in_array($other, $this->allowedValues);
done.

2024-03-21 11:31 UTC, terabytesoftw commented on tests/framework/helpers/ArrayHelperTest.php
> -            $this->markTestSkipped('Using floats as array key is deprecated.');
done.

2024-03-21 11:31 UTC, terabytesoftw commented on tests/framework/helpers/ArrayHelperTest.php
> -            $this->markTestSkipped('Using floats as array key is deprecated.');
done.

2024-03-21 11:31 UTC, terabytesoftw commented on tests/framework/helpers/ArrayHelperTest.php
> -            $this->markTestSkipped('Using floats as array key is deprecated.');
done.

2024-03-21 11:40 UTC, terabytesoftw commented on tests/framework/db/ActiveRecordTest.php
> -    public function testCastValues()
done.

2024-03-21 12:36 UTC, terabytesoftw commented on tests/framework/di/ContainerTest.php
> -    public function testVariadicConstructor()
done.

2024-03-21 12:36 UTC, terabytesoftw commented on tests/framework/di/ContainerTest.php
> -    public function testVariadicCallable()
done.

2024-03-21 17:49 UTC, terabytesoftw commented
![image](https://github.com/yiisoft/yii2/assets/42547589/a085c633-0fa9-4eb2-b39c-52a0b600745f)

@rob006 You still think 7.3 will be useful here.

2024-03-21 17:59 UTC, rob006 commented
@terabytesoftw What would be practical benefit of raising requirements to PHP 7.4? Yii 2.0 is in maintenance mode, we won't add new features and we can't refactor existing code using types because it would be a BC break (and probably a massive waste of time - such changes make more sense for Yii 2.2). So what features of PHP 7.4 would be so useful that it would be worth to cut \~5% of userbase?

2024-03-22 09:49 UTC, terabytesoftw commented
I think we should then:

- Release of `2.0.49.4` with the current `master` and (remove the 8.4 tests) to leave the tests green, and leave the last update green, for `PHP 5.4 - 8.3`.
- merge php `7.3` in the master with `php 8.4 tests`.
- merge null implicit fixes.

With this we must have all the tests in green, review more PR, merge and release `2.0.50`.

@samdark @bizley @rob006 @mtangoo @schmunk42

2024-03-22 10:14 UTC, rob006 commented
I think we could skip `2.0.49.4`, we specially released `2.0.49.3` so all changes in master would go to 2.0.50.

2024-03-22 10:34 UTC, bizley commented
Yes, let's go to 2.0.50 finally.

2024-03-22 10:37 UTC, terabytesoftw commented
> Yes, let's go to 2.0.50 finally.

Ok then merge this PR, and the implicit null, to finish removing the PHP 8.4 deprecations.

2024-03-22 10:43 UTC, bizley commented
@samdark please approve

2024-03-22 18:23 UTC, mtangoo commented
Let's go :)

2024-03-23 16:41 UTC, rhertogh approved these changes

2024-03-24 21:09 UTC, samdark approved these changes

2024-03-25 00:05 UTC, Arhell approved these changes

2024-03-25 05:12 UTC, mtangoo commented
Since we all approve this am merging it!
Thanks to @terabytesoftw for taking your time to prepare this, and everyone for making it reach thus far.
Cheers!

2024-03-25 05:13 UTC, merged