add CSRF validation by custom HTTP header
yiisoft/yii2 pull request #20280
Opened 2024-11-23 11:59 UTC by olegbaturin

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #20279

2024-11-23 13:06 UTC, samdark commented
This is backport from Yii3. Good one.

2024-11-24 15:07 UTC, samdark approved these changes

2024-11-25 00:32 UTC, Arhell approved these changes

2024-11-27 13:06 UTC, bizley requested changes

2024-11-27 13:06 UTC, bizley commented on framework/web/Request.php
> +            return in_array($method, $this->csrfHeaderUnafeMethods, true)
```suggestion
            return in_array($method, $this->csrfHeaderUnsafeMethods, true)
```

2024-11-27 14:56 UTC, mtangoo commented
I think this PR is good with exception of typos as pointed out by @bizley 
@olegbaturin would you please address them?

2024-11-28 08:00 UTC, bizley approved these changes

2024-11-28 08:27 UTC, mtangoo commented
@olegbaturin thanks for your time and efforts

2024-11-28 08:27 UTC, merged