7593 at least one field core validator
yiisoft/yii2 pull request #7664
Opened 2015-03-11 04:33 UTC by slinstj

2015-03-11 04:48 UTC, slinstj commented
Have these tests fails to do with some unavailability of the Travis CI?

2015-03-11 04:48 UTC, slinstj commented
#7593

2015-03-11 05:19 UTC, unclead commented
I found that you have invalid name of test class "BooleanValidatorTest" instead  of AtLeastOneValidatorTest

2015-03-11 05:31 UTC, slinstj commented
Thank you. I will fix! I used that one as base.

2015-03-21 22:42 UTC, slinstj commented
`AtLeastOne` >> `AtLeast`
`validateWith` >> `with`
`errorAttributes` >> `errorIn`
Added `min` param

2016-05-14 04:58 UTC, Faryshta commented
How about adding a new parameter `RequiredValidator::targetAttribute`?

2016-05-15 14:14 UTC, SilverFire commented
@Faryshta instead of this PR?

2016-05-15 17:24 UTC, slinstj commented
I think a `targetAttribute` in RequiredValidator would be messy. The attributes are *not* required, they are *alternative* between them.

2016-05-15 20:45 UTC, Faryshta commented
@SilverFire could be an option, i see this PR has been inactive for sometime. I am cool with a new vaildator or adding functionality to an existing one.

@slinstj well to me it sounds like one of them is required. Again, its just an alternative since this PR seems inactive.

2016-05-15 21:35 UTC, SilverFire commented
@Faryshta I think it's better to create a new validator instead of overcomplicating existing one

2016-05-16 06:11 UTC, Faryshta commented
ok cool, what does this need to be accepted?

2017-07-10 22:51 UTC, cebe requested changes

2017-07-10 22:51 UTC, cebe commented on framework/validators/AtLeastValidator.php
> +class AtLeastValidator extends Validator
I'm not really happy with the name, "at least" is missing something. at least... what? Alternatives:

- RequireFrom
- RequireOne
- RequireAny
- Alternative
- AtLeastOne
- ...

2017-07-10 22:51 UTC, cebe commented on framework/validators/AtLeastValidator.php
> +    public $with;
also naming: `alternativeAttributes`, `targetAttributes`, ...

2017-07-10 22:51 UTC, cebe commented on framework/validators/AtLeastValidator.php
> +    public $errorIn;
naming: `errorAttributes`

2017-07-10 22:51 UTC, cebe commented on framework/validators/AtLeastValidator.php
> +            $this->message = Yii::t('yii', 'Please, fill {attributesList}.');
`Please fill at least {min} of {attributesList}.`

2017-07-10 22:51 UTC, cebe commented on framework/validators/AtLeastValidator.php
> +            $filled += !empty($value) ? 1 : 0;
better use the `isEmpty()` method of Validator.

2017-07-10 22:51 UTC, cebe commented on framework/validators/AtLeastValidator.php
> +        if (!$filled) {
should compare to `$this->min` here

2017-07-10 22:51 UTC, cebe commented on framework/validators/AtLeastValidator.php
> + * @since 2.0.4
update to 2.0.13

2017-07-26 06:12 UTC, MaXL-ru commented
I vote for `RequireAny` validator name.

@slinstj can you make changes ? I'll be very glad to see this feature in nearest Yii2 version.

2017-08-09 23:36 UTC, slinstj commented
@MaXL-ru Please, go ahead and make the changes (if it is ok to you). I can't do it for now (no time). Sorry.

2017-11-04 23:51 UTC, slinstj commented
@developeruz sorry, not sure what you need. I did not lock anything and I can't see any place to 'allow' your changes. Please, explain it better sothat I can help.

2017-11-05 03:11 UTC, developeruz commented
@slinstj on the left sidebar of this page, you should see "Allow edits from maintainers" checkbox (please look at the attached image in the previous comment). You and only you, as an owner of PR,  can mark this checkbox. Without that permission, no one except you can modify files in your branch.

2017-11-15 09:59 UTC, samdark commented
Replaced by https://github.com/yiisoft/yii2/pull/15157

2017-11-15 09:59 UTC, closed without merging