symlink() windows OS
yiisoft/yii2 pull request #7931
Opened 2015-03-31 16:07 UTC by msajko

avoid problems with symlink() on windows systems

2015-03-31 22:26 UTC, cebe commented
What is the problem this code is solving? please describe the issue in detail.

2015-04-01 08:37 UTC, msajko commented
symlink(): Cannot create symlink, error code(1314)
This is a Windows error message indicating that the current user does not have permission to create symbolic links. By default, this privilege is granted to administrators only. On core Win 8 edition and Win 7 Home Basic you can't add privileges!

tested on platform: Windows 7 and 8.1 :: PHP v5.4.28 / v5.4.3 / 5.5.12 / 5.5.15

There are many posts around the web about it!

2015-04-01 08:55 UTC, samdark commented
Do you have access to mklink in this case?

2015-04-01 10:51 UTC, msajko commented
Yes, you dont have to warry about mklink path. And NTFS has supported symlinks for a while.

2015-04-04 16:02 UTC, cebe commented
The fix does not really make sense with the changes now. you could set linkAssets to false to solve this problem in your environment...

2015-04-07 07:51 UTC, msajko commented
For files maybe not, but for folders it's still active...

2015-10-10 23:02 UTC, samdark commented
@msajko how to reproduce it?

2015-10-16 19:10 UTC, msajko commented
@samdark on Windows platform common/config/main.php set components=>assetManager->linkAssets=>true;
in backend/web/assets/ and frontend/web/assets/ Yii will create Junction(symbolic links) instead of true folders

2016-11-27 01:48 UTC, cebe commented
I do not really get the problem and how the solution solves it. Why don't you just disable `linkAssets` if your system does not support links?

2016-11-27 12:52 UTC, samdark commented
@cebe Windows supports symlinks but there are weird requirements about permissions often.

2016-11-28 15:30 UTC, samdark requested changes

2016-11-28 15:30 UTC, samdark commented on framework/web/AssetManager.php
> +                        exec('mklink /J '.$dstDir.' '.$src);
It is preferred to use `/D` i.e. directory symlinks instead of outdated junctions.

2016-11-28 15:30 UTC, samdark commented on framework/web/AssetManager.php
> +                        symlink($src, $dstDir);
Why repeating?

2016-11-28 15:30 UTC, samdark commented on framework/web/AssetManager.php
> +                        symlink($src, $dstFile);
Why repeating?

2016-11-28 15:30 UTC, samdark commented on framework/web/AssetManager.php
> +                        copy($src, $dstFile);
I'm not sure it's proper fallback. Why not using `mklink`?

2017-03-14 09:23 UTC, SamMousa commented
I don't think calling `exec('mklink')` is something you should do, especially with a relative path.
If anyone manages to upload something called `mklink` and get it in the search path somehow (for example by changing the currrent directory) it is a remote code execution risk.

2017-04-20 18:49 UTC, samdark commented
Won't merge it in its current state.

2017-04-20 18:49 UTC, closed without merging

2017-04-20 18:56 UTC, SamMousa commented
Side note, from http://php.net/manual/en/function.symlink.php
> Note: Windows users should note that this function will only work if the system you run PHP from is Windows Vista/Windows Server 2008 or newer. Windows versions prior to that do not support symbolic links.