Added cookie validation whitelist
yiisoft/yii2 pull request #9357
Opened 2015-08-08 20:33 UTC by kidol

Fixes #9158

I don't understand the reasoning for doing the `cookieValidationKey`-check in 2 different methods. So I added this check to `Request::init()` instead.

2017-03-14 10:50 UTC, SamMousa commented on framework/web/Response.php
> +            if ($cookie->expire != 1 && $request->enableCookieValidation && !in_array((string)$cookie->name, $request->cookieValidationWhitelist, true)) {
What is the use of strict check combined with a manual type cast?
This is effecitvely the same as using a non-strict check.

2017-03-14 11:06 UTC, samdark commented on framework/web/Response.php
> +            if ($cookie->expire != 1 && $request->enableCookieValidation && !in_array((string)$cookie->name, $request->cookieValidationWhitelist, true)) {
It is.

2017-06-24 20:05 UTC, cebe requested changes
> I don't understand the reasoning for doing the cookieValidationKey-check in 2 different methods. So I added this check to Request::init() instead.

If both methods are never called, there is no reason to configure cookie validation key.

2017-07-13 10:41 UTC, cebe commented
@kidol are you willing to work on this further?

2018-02-03 18:34 UTC, samdark commented
Closing since it seems @kidol isn't going to pick it up again.

2018-02-03 18:34 UTC, closed without merging