Basic syntax of 'INSERT INTO ... SELECT' statement was added (#8293).
yiisoft/yii2 pull request #9420
Opened 2015-08-14 17:41 UTC by voroks

Method "insert()" accepts instance of \yii\db\Query for second parameter as well as array.
Column names (or aliases, if exists) of SELECT statement became column names for INSERT statement. So, support of basic usage of "INSERT INTO ... SELECT" statement (as in issue #8293) was added.

2015-08-14 17:52 UTC, samdark commented
How about non-MySQL?

2015-08-14 18:14 UTC, voroks commented
PostgreSQL - OK
SQLite - OK
Unfortunately, I can't perform test with using other DBs.

2016-11-26 23:34 UTC, cebe requested changes
test seems to pass on travis so this looks good to me. A CHANGELOG is needed and it should be rebased on current master.

2016-11-26 23:34 UTC, cebe commented on framework/db/Command.php
> +     * of \yii\db\Query to perform INSERT INTO ... SELECT SQL statement.
Need a note that the `Query` can be passed since version 2.0.11.

2016-11-26 23:34 UTC, cebe commented on framework/db/QueryBuilder.php
> +     * of \yii\db\Query to perform INSERT INTO ... SELECT SQL statement.
Need a note that the Query can be passed since version 2.0.11.

2016-11-26 23:34 UTC, cebe commented
@voroks are you willing to work on this further?

2016-11-28 10:25 UTC, cebe requested changes

2016-11-28 10:25 UTC, cebe commented on framework/db/mysql/QueryBuilder.php
> -            $names[] = $schema->quoteColumnName($name);
no need to check `=== true`. Change this to:

```php
if ($columns instanceof \yii\db\Query) {
```

2016-11-28 10:25 UTC, cebe commented on framework/db/oci/QueryBuilder.php
> -            $names[] = $schema->quoteColumnName($name);
no need to check `=== true`. Change this to:

```php
if ($columns instanceof \yii\db\Query) {
```

2016-11-28 10:25 UTC, cebe commented on framework/db/pgsql/QueryBuilder.php
> -        if (($tableSchema = $this->db->getSchema()->getTableSchema($table)) !== null) {
no need to check `=== false`. Also better not wrap the whole function in the if but return early, so change this to:

```php
if ($columns instanceof \yii\db\Query) {
    return $columns;
}
```

2016-11-28 11:12 UTC, cebe requested changes

2016-11-28 11:12 UTC, cebe commented on tests/framework/db/CommandTest.php
> +                'address',
could you add the alias syntax `'alias' => 'column'`. Seems this is not supported by your implementation right now.

> When the columns are specified as an array, you may also use array keys as the column aliases (if a column
>  does not need alias, do not use a string key).
> http://www.yiiframework.com/doc-2.0/yii-db-query.html#select%28%29-detail

sorry, have not noticed this earlier.

2016-12-19 15:35 UTC, samdark commented on framework/db/QueryBuilder.php
> +     * @return array
Need `@since 2.0.11`

2016-12-26 16:14 UTC, samdark approved these changes

2016-12-30 18:45 UTC, SilverFire commented on framework/db/QueryBuilder.php
> +            foreach ($columns as $name => $value) {
@yiisoft/core-developers how about moving this part into a separate method to make `insert` simpler to read?

2016-12-31 11:31 UTC, samdark commented on framework/db/QueryBuilder.php
> +            foreach ($columns as $name => $value) {
I'm OK with that.

2016-12-31 12:29 UTC, dynasource requested changes

2016-12-31 12:29 UTC, dynasource commented on framework/db/QueryBuilder.php
> +            foreach ($columns as $name => $value) {
agree. Placeholders are not always defined. 
I would expect a separate method for the creation of an "insert" statement with all the relevant arguments.

2016-12-31 12:29 UTC, dynasource commented on framework/db/QueryBuilder.php
> +    }
the creation of the insert statement could be done a lot cleaner in a separate method returning a <<<SQL block

2016-12-31 12:29 UTC, dynasource commented on framework/db/oci/QueryBuilder.php
> +            . (!empty($placeholders) ? ' VALUES (' . implode(', ', $placeholders) . ')' : $values);
this should be refactored to a solution in which with https://github.com/yiisoft/yii2/pull/9420/files#diff-e2271b5ca7ffbb33d4f2bfa5ed2e94f4R181 is reused

2016-12-31 12:29 UTC, dynasource commented on tests/framework/db/CommandTest.php
> +    {
please split these tests into separate selfcontained methods

2017-01-28 20:48 UTC, closed without merging

2017-01-28 20:48 UTC, samdark commented
Merged https://github.com/yiisoft/yii2/commit/25f08afc96035b517d6a7be13b28bb09514bfc39. Thank you!